### ISSUE TITLE
Add throttling combinators to ZStream

### ISSUE THREAD

**Issue by iravid** [zio/zio#1027]
A token bucket implementation.

Variants:
- [x] `ZStream#throttleEnforce, ZStream#throttleEnforceM` - a version that drops elements that exceed the available bandwidth
- [x] `ZStream#throttleShape, ZStream#throttleShapeM` - a version that delays elements until sufficient bandwidth is available
- [ ] Accomodate bursts by allowing the token bucket to go into a (configurable) negative amount or by accumulating tokens over the available bandwidth up to a configurable amount

**Comment by NeQuissimus** [comment]
It would be cool if there was an implementation of this that has some sort of `f: Token => UIO[Unit]`, which can be used to persist the tokens (think storing the token in a Kafka `KTable`)

**Comment by iravid** [comment]
@NeQuissimus I think we could implement the token bucket as a `ZSink`, then its internal state can be persisted.

**Comment by vasilmkd** [comment]
I would like to try my hand at this.

**Comment by vasilmkd** [comment]
I would like to get some clarification on the requirements. Should there be a way to express how many tokens each stream element is worth (with the possibility of different elements requiring different number of tokens), or should I assume that they are all equal, e.g. one token? Thanks.

**Comment by vasilmkd** [comment]
Also, would the ZSink's state extending Serializable make it persistable or am I looking for something else here?

**Comment by vasilmkd** [comment]
I guess that each element can have a certain token cost by passing it through a costFn: A => Long or something equivalent.

**Comment by iravid** [comment]
Hi @vasilmkd, thanks for looking into this. Indeed a cost function is required to compute the weight of each element. `A => Long` is ok, but `A => ZIO[R, E, Long]` is better :-)

Don't worry about making ZSink's state serializable. We can deal with that concern later.

**Comment by vasilmkd** [comment]
Already on it.

**Comment by vasilmkd** [comment]
Regarding the throttling combinator that accounts for burst.

In the currently merged `throttleEnforce` implementation, the bandwidth that can be achieved is at best the specified bandwidth in the arguments, meaning, the bucket at any time can contain at most `units` worth of tokens.

Could the burst combinator be implemented in such a way that would allow the bucket to accumulate `n` cycles worth of `units` tokens, such that in the case of delayed production of elements followed by a burst of elements all elements would go through if sufficient tokens are present?

Or is this proposal less user friendly than having a configurable negative threshold?

I believe that having the bucket accumulate tokens over time will also provide an `average` bandwidth use case, instead of the rigid, `at most` bandwith already implemented by `throttleEnforce`.

Or was the original implementation of `throttleEnforce` wrong and does it need addressing?

Hopefully this is clear. Thanks.

**Comment by iravid** [comment]
You know, I'm not sure- I'm not that knowledgeable about possible implementations. Both approaches sound good to me but if you have the time to do some research on the tradeoffs between the two, that'd be great.

**Comment by iravid** [comment]
I know that (for example) EBS volumes in AWS work the way you've described, by accumulating "burst tokens".

**Comment by vasilmkd** [comment]
Already working on a burst implementation.

**Comment by vasilmkd** [comment]
I would love a quick explanation on type parameters.

Since I have stumbled on the interesting case where I have to return the throttling sinks as managed resources, after some thinking I have come to the following conclusion.

Given an effectful cost function `A => ZIO[R, E, Long]` which is only ever invoked inside the Sink's internal methods and _never_ in the creation of the `ZManaged`, I would think that we get a `ZManaged[Clock, Nothing, ZSink[R with Clock, E, A0, A, A]]` as a resulting type.

The reason why I believe this is the correct type is because when the `ZManaged` is created, none of the steps can fail (i.e. they all have `Nothing` as the error type), and none of the `R` from the effectful function is used, except for the Clock, which is also used in the sink internally, which of course widens the environment for the Sink, but only for the Sink.

Of course, this managed sink is then used in `ZStream#transduceManaged`, which has an interesting type signature. It accepts a `ZManaged[R, E, ZSink[R, E, A0, A, B]]`, which to my understanding, means that both the `ZManaged` _and_ the `ZSink` it contains must _both_ fail with the same `E` and use the same `R`. I personally have no problems with this, and I don't propose any changes here.

What I would like to know is why does passing a `ZManaged[Clock, Nothing, ZSink[R with Clock, E, A0, A, B]]` to `transduceManaged` even compiles in the first place, when clearly, the `ZManaged` and the `ZSink` have _different_ error and environment types.

I'm planning to introduce a commit which makes error types clearer for the throttling sinks, and this got my attention.

**Comment by iravid** [comment]
@vasilmkd

Right, so your understanding of `transduceManaged`'s signature is correct, but with one important nuance: because both `ZManaged` and `ZSink` are *covariant* in the `E` parameter, we should read `transduceManaged`'s signature as if it said, "the Sink and Managed must both fail with an error type that can be *unified* to the same type".

Now since `Nothing` is the subtype of all types, it can be upcasted safely to any other type; including the `E` in your sink.

**Comment by vasilmkd** [comment]
Clearly, I still have lots to learn about variance. I have never thought about it in this way.

Thanks, I appreciate this very much.
