### ISSUE TITLE
Introduce real companion objects for Stream, Schedule, Sink, Managed, Queue

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1111]
Currently the type aliases only have "virtual companion objects". We should introduce real companion objects that delegate to the methods in the most polymorphic object, but use restricted type parameter lists. This will provide the best possible user experience.

 - [x] Stream
 - [x] Schedule
 - [x] Sink
 - [ ] Managed
 - [x] Queue

**Comment by ghostdogpr** [comment]
+ `Queue` as well

**Comment by jdegoes** [comment]
This could use a better write-up of all the details involved, if anyone has time / interest.

**Comment by andreamarcolin** [comment]
Hi @jdegoes! I would love to help there, so I am interested in having some more details on how I should deal with this one. Thank you

**Comment by ghostdogpr** [comment]
@andreamarcolin the idea is to create a dedicated companion object for each type so that it simplifies the signatures as much as possible. If I want a `ZManaged` I would use `ZManaged.make` but if I need only a `Managed`, I would use `Managed.make` which won’t require any R parameter. Currently you have to provide R = Any even when you just want a `Managed`. 

You can check this comment from John that describes similar work for the ZIO type: https://github.com/zio/zio/issues/744#issuecomment-485906585
We need the same thing applied to the types listed in this issue.

**Comment by andreamarcolin** [comment]
@ghostdogpr Great! Will start to work on it just now and will come back hopefully in a few days with a PR. Thanks for the explanation

**Comment by iravid** [comment]
@andreamarcolin I strongly suggest to do separate PRs for each object or you'll be fighting endless merges

**Comment by andreamarcolin** [comment]
@iravid Got it. Any suggestion on which to start from or isn't it that important?

**Comment by dorsev** [comment]
hey @andreamarcolin, would love to help out and try taking 'Schedule' if you did not start it yet.

**Comment by dorsev** [comment]
hey @andreamarcolin, I would love to help out with the ```Schedule``` if you haven't started working on it.

**Comment by andreamarcolin** [comment]
@dorsev Sure! I have started working on Managed, and I was planning to work on it this weekend. My idea is to follow @iravid suggestion and do separate PRs, so if you want you can take Schedule and then we will see for the others. Are you ok with this plan? :)

**Comment by dorsev** [comment]
Thanks for the quick response @andreamarcolin! sounds like a plan. 👍

**Comment by geymed** [comment]
@andreamarcolin, @dorsev I would be happy to take `Sink`.

**Comment by dsebban** [comment]
I would be happy to take `Queue`

**Comment by bobrowadam** [comment]
I can take `Stream`
