### ISSUE TITLE
Mention in "Getting Started" that Scala 2.13 is not supported yet

### ISSUE THREAD

**Issue by PiotrJander** [zio/zio#1138]
This will save some pain for newcomers.

**Comment by softinio** [comment]
Personally when ever I want to use a new scala package I take a look at it on scaladex (and maven central if not there) and use that to confirm what versions of scala supported etc before using it: 

https://index.scala-lang.org/zio/zio/zio

Maybe a link to the above scaladex page in the README and/or docs a good option to improve the docs instead of repeating the information  and having to maintain it and making the docs footprint larger in my opinion.

As this is an OSS project volunteers time better spend coding features than remembering to update a version matrix in the docs when it can easily be fetched from scaladex and maven central where it is automatically updated and always accurate.
