### ISSUE TITLE
Add ZStream#onExit, ZStream#onError and variants

### ISSUE THREAD

**Issue by iravid** [zio/zio#1202]
Add the following combinators that allow attaching cleanup actions to a stream:
```scala
trait ZStream[R, E, A] {
  def onExit[R1 <: R](cleanup: Exit[E, A] => ZIO[R1, Nothing, Any]): ZStream[R1, E, A]
  def onExitFirst[R1 <: R](cleanup: Exit[E, A] => ZIO[R1, Nothing, Any]): ZStream[R1, E, A]
  def onError[R1 <: R](cleanup: Cause[E] => ZIO[R1, Nothing, Any]): ZStream[R1, E, A]
  def onErrorFirst[R1 <: R](cleanup: Cause[E] => ZIO[R1, Nothing, Any]): ZStream[R1, E, A]
  def onComplete[R1 <: R](cleanup: A => ZIO[R1, Nothing, Any]): ZStream[R1, E, A]
  def onCompleteFirst[R1 <: R](cleanup: A => ZIO[R1, Nothing, Any]): ZStream[R1, E, A]
}
```

With the same semantics as `ZManaged#onExit/onExitFirst`. The last 4 combinators should be based on the first 2.

**Comment by adamgfraser** [comment]
I can take this one too.

**Comment by adamgfraser** [comment]
After spending some time on this and discussions with @iravid I don't think we can actually implement these combinators due to differences between the semantics of streams and effects.

Effect types like `IO[E, A]` will always produce an `A` or fail with an `E`. In contrast, a `Stream[E, A]` may when run produce zero, one, or many `A` values.  In particular, an empty stream will succeed without producing any `A`. Therefore, it doesn't make sense to implement combinators like `onExit` or `onComplete` that assume a success will generate an `A` value.

In addition to this, a `Stream[E, A]` is something that can be effectually folded over, potentially failing with an error type `E1 >: E`. Since the cleanup action in `OnError` takes a `Cause[E]`, the cleanup action would not know how to handle all the errors potentially arising when running the stream. For example, if `DatabaseError` is a subtype of `AppError`, cleanup knowing how to handle a `DatabaseError` does not imply that `cleanup` knows how to handle an `AppError`.

**Comment by iravid** [comment]
Thank you @adamgfraser! Closing this.
