### ISSUE TITLE
FiberFailure stack trace suggests wrong location

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1218]
Whenever a `FiberFailure` is constructed, it builds a stack trace, which is printed out by some third-party libraries (rather than, say, its `toString` method).

To avoid this, we should probably disable the stack trace, or delegate to the stack trace of the first / primary defect.

/cc @kaishh ???

**Comment by kaishh** [comment]
Makes sense! I can do this if no one else wants to take it first 😉

**Comment by mgibowski** [comment]
I am not sure I understand well the issue.

@jdegoes Do you mean something like that?

```scala
import scala.{ Console => SConsole }

final case class FiberFailure(cause: Cause[Any]) extends Throwable {

  override final def getMessage: String = cause.toString

  override def printStackTrace(): Unit = {
    SConsole.withErr(SConsole.err)(cause.prettyPrint)
    () // because of "discarded non-Unit value"
  }

  override def printStackTrace(s: PrintStream): Unit = {
    SConsole.withErr(s)(cause.prettyPrint)
    ()
  }


  override def printStackTrace(w: PrintWriter): Unit = {
    w.println(cause.prettyPrint)
    ()
  }

}
```

**Comment by jdegoes** [comment]
@mgibowski Yes, and possibly even overriding `getStackTrace` and filling it with execution trace information. It's not a perfect mapping but I can see some frameworks just dump out the stack trace and it's not remotely helpful compared to the `Cause` with tracing.

**Comment by kaishh** [comment]
@mgibowski 
`Throwable` has a constructor parameter to disable stacktrace capture, you may use that instead of overriding methods.

@jdegoes 
Have you encountered frameworks dumping just the trace and ommiting `.getMessage/.printStackTrace` - which should both print ZIO Trace? There's a mapping method `ZTrace.ZTraceElement.toStacktraceElement` that can convert a ZTrace to a Java stacktrace, but it may be unnecessary as long `message` is not omitted by the frameworks.

**Comment by jdegoes** [comment]
@kaishh No, just `.printStackTrace`. Maybe we should just disable the stack trace capture.

**Comment by mgibowski** [comment]
Ok, I opened the PR 👆
