### ISSUE TITLE
Make `testkit` cross-platform (Scala.js)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1227]
Right now, `testkit` is entirely JVM, but it can work on Scala.js as well, possibly without changes.

This ticket is to move source files inside `testkit` from the `jvm` directory to the `shared` directory and fix any issues that arise in the process.

**Comment by vasilmkd** [comment]
I can take this.

**Comment by vasilmkd** [comment]
This issue can be closed probably.

**Comment by mgibowski** [comment]
Hi, while rebasing my branch I have disovered that some specs (`test.mock.*`) are not JS-compatible because of dependency on `TestRuntime`.

It was not visible, as in the current sbt configuration these tests were actaully nevery really compiled or run in JS.

If you want to see how current sbt could be changed to see them failing, I created a [branch](https://github.com/mgibowski/zio/tree/failing-js-test).

This will be also visible in the PR I whill shortly submit. In that case I decided it is best to bring these back to `jvm` folder.

Not sure if this issue should get reopened or not.  It is these 5 tests that are not JS-compatible:
* `ClockSpec.scala` 
* `ConsoleSpec.scala` 
* `RandomSpec.scala` 
* `SchedulerSpec.scala`
* `SystemSpec.scala`

**Comment by jdegoes** [comment]
@mgibowski 

`TestRuntime` will go away soon, so I'd say let's not worry about this. Ultimately we want all these tests running on Scala.js, and that will happen shortly after ZIO Test is completed.

**Comment by vasilmkd** [comment]
Sorry for all the confusion this caused.

**Comment by mgibowski** [comment]
> Sorry for all the confusion this caused.

No worries! 😉
