### ISSUE TITLE
Implement `Pool`

### ISSUE THREAD

**Issue by sinoz** [zio/zio#1236]
We have the `Managed` data type that manages single `A`'s but what about a data type that manages multiple elements of `A`? I think this is useful for the Scalaz NIO project to elegantly and safely reuse resources such as buffers. The buffer pool could be passed on as an environment to effects that write to buffers and output a `Chunk`.

And what about a `Pool` that is fiber local?

**Comment by iravid** [comment]
Sounds interesting! What API did you have in mind?

**Comment by jdegoes** [comment]
```scala
trait Pool[A] {
  def acquire: Managed[Nothing, A]
  def acquireN(n: Int): Managed[Nothing, List[A]]
  def destroy: UIO[Unit]
}
object Pool {
  def make[R, E, A](create: ZIO[R, E, A], destroy: A => UIO[Any]): ZIO[R, E, Pool[A]] = ???
```

**Comment by denisgarci** [comment]
Hi,
I would like to try this one. 
Shouldn't `create` signature be `IO[E,A]` instead of `ZIO[R, E, A]`?
Thanks

**Comment by jdegoes** [comment]
@denisgarci Why not be more polymorphic? It can include `R` without difficulty.

**Comment by jdegoes** [comment]
Here is revision 2:

```scala
trait Pool[A] {
  val acquire: Managed[Nothing, A]
  def acquireN(n: Int): Managed[Nothing, List[A]]
}
object Pool {
  def make[R, E, A](create: ZIO[R, E, A], destroy: A => UIO[Any]): ZManaged[R, E, Pool[A]] = ???
}
```

This one has no `destroy` because it returns the `Pool` inside `ZManaged`.

**Comment by denisgarci** [comment]
Oh I see let me try with the new one. Thank you!

**Comment by pshirshov** [comment]
I'm wondering if there was any update on that. It's a very useful thing :)

**Comment by jdegoes** [comment]
I will do this.

**Comment by adamgfraser** [comment]
One thing that I've run into a couple of times is the need for a resource manager where you can look up a resource and create it if it doesn't exist. I think maybe that is a different concept than this because it implies a concept of shared resources versus this implies exclusive access to multiple resources. Could be a generalization of the `MemoMap`.

**Comment by jdegoes** [comment]
A `Pool` can be generalized for mutually exclusive and shared resources, although "lookup" seems to imply key which seems to imply more cache than pool? I suppose one could generalize a pool further by keying the resource, maybe with a default for the case the key is `Any`.

**Comment by adamgfraser** [comment]
Yes, basically a cache where the lookup effect is resourceful and its finalizer needs to be safely added to the outer scope of the cache so maybe it is something different.

**Comment by adamgfraser** [comment]
Maybe we could just have an operator on `ZManaged` that does this:

```scala
objet ZManaged {
  def memoize[R, E, A, B](f: A => ZManaged[R, E, B]): ZManaged[Any, Nothing, A => ZIO[R, E, B]] =
    ???
}
```

**Comment by jdegoes** [comment]
I like that.

**Comment by adamgfraser** [comment]
Will add.

**Comment by adamgfraser** [comment]
This has been implemented in ZIO 2 with `ZPool`.

**Comment by guizmaii** [comment]
Is it possible to use `ZPool` as a "keyed pool", a bit like https://github.com/typelevel/keypool? 🤔

It seems not possible because the `ZPool::get` method does not take any argument 🤔

I need something like `ZManaged.memoize` but with a pool management system on top of it: 
  - Finalize the resource if not used for `n` seconds
  - Potentially more than one instance allowed per key
  
I wonder if I can't combine `ZPool` and `ZManaged.memoize` to achieve this 🤔
