### ISSUE TITLE
Add a combinator for parallel composition of sinks

### ISSUE THREAD

**Issue by iravid** [zio/zio#1310]

**Comment by iravid** [comment]
cc @simpadjo_gitlab

**Comment by simpadjo** [comment]
Thank you, it would be very useful.

@jdegoes 
>  The reason that probably doesn't exist now is because it's not obvious what to do with leftovers: each sink will, in general, have a different amount of leftover; and the leftovers will overlap. So in their composition, what do you do? Probably emit the shortest. All to say, possible but tricky to do correctly.

I had the same question in my head initially. Now I think that returning the shortest one looks pretty much consistent with respect to `ZIIO#zipPar` behavior. If a Stream is a timeline and Sinks are processes then `ZSink#zipPar` considered done at the latest point. Dual to `ZSink#raceBoth`.

**Comment by jdegoes** [comment]
I do think shortest is the best ("minimal leftover"). 

Albeit there will be some nice laws that it can't satisfy.

It'd be nice if you could take `sink1 -> sink2` and `sink3 -> sink4` and `zipPar` `sink1` and `sink3`, and then `zipPar` `sink2` and `sink4`, and then do `(sink1 zipPar sink3) -> (sink2 zipPar sink4)` and have that give you the same result. But Sink appears not to have the structure required to allow that, because it would require tuple leftovers and tuple inputs.

**Comment by simpadjo** [comment]
I'd like to try to implement it

**Comment by iravid** [comment]
Closed in #1344
