### ISSUE TITLE
Remove explicit delay in ZSchedule

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1348]
ZSchedule has an explicit `Duration` at each step. The original motivation for this was quite simple: it makes testing schedules easier, because there is no need for the schedule itself to sleep; rather, the driver for the schedule can sleep. 

However, at this point, with ZIO Environment, testing schedules is already easy, even if the schedules are sleeping. In fact, the `.jittered` combinator, which uses randomness, is also easy / fast / deterministic to test, when used with `MockRandom`.

Given the original motivation for making schedules explicit with `Duration` no longer applies, and given the potential to simplify #676, it may be worth implementing a formulation of `Schedule` that is responsible for its own "sleeps".

This will have the following effects:

 - Simplify some mechanics inside `Schedule`
 - Remove the `Clock` from `ZIO#repeat` / `ZIO#retry` and friends (only schedules that sleep will "contaminate" the effect with `Clock`)
 - Permit "sleep to fixed point in time" without added machinery
 - Make sleeping schedules responsible for their own sleeping

The most difficult change will be redefining semantics for `&&` and `||` operators.

### Intersection

The intersection operator `&&` repeats as long as _both_ continue, and for the maximum of the delay of the two schedules.

This operator could be replaced by something like `left.zipWith(right)(_ && _)`. 

### Union

The union operator `||` repeats as long as _either_ continue, and for the minimum of the delay of the two schedules.

This operator could be replaced by using `ZIO#raceWith`: if the first one to finish _wants_ to continue, the schedule as a whole continues, with the state of the first one; otherwise, the second one is joined, to get its decision, and continue with its state. Previous states can be reused to feed to the next race (although the loser of a race will have its state ignored—this may cause some meaningful differences that are worth exploring).

### Thoughts

Overall I am positive of this change because it makes schedule simpler and ties the semantics of `||` and `&&` to noted effect composition operators. 

Also stands to solve #1339  as well as #676, but in a fewer lines of code than currently possible.

**Comment by mschuwalow** [comment]
I would like to take this

**Comment by mschuwalow** [comment]
Sorry I got hung up on a few issues for streams and am now going to be busy for a few days :cry: .
Feel free to pick this up in the meantime.

**Comment by alexandredantas** [comment]
My two cents on this: pushing run logic to Schedule will unify behavior related to repeat and retry. Is it possible to model a thing like `ZSchedule.repeat` and `ZSchedule.retry`, return a new `ZSchedule` and simply call `ZSchedule.run`? This model can enable composing different schedule logics i think

**Comment by jdegoes** [comment]
@alexandredantas Ideally `repeat` and `retry` would have symmetrical behaviors: one invoking the schedule on success, the other on failure. Indeed, it would be a big win to have something like `retry = flipWith(_.repeat)` (pseudo-code).

**Comment by adamgfraser** [comment]
@jdegoes One other possibility for `||` is that we keep the `Fiber` of the loser and race it against the next state update for the winner, so `&&` and `||` would be analogous to `zipWith` and `mergeWith` on streams if we conceptualize schedules as describing a stream of events spaced over time. This would be significantly different than the current implementation because if we used `||` on two schedules that each recurred three times we would get a new schedule that would recur six times instead of just a schedule that recurred three times on the minimum of the pairwise recurrence periods.

This to some extent seems more natural to me, but I'm not sure about the practical implications or which one is more consistent with the laws for the various categories that schedule forms. I was surprised that it seems like we're not using the `||` operator much in powering other combinators, so there could be an opportunity to have different behavior, and perhaps that version could be more useful.

What do you think?

**Comment by adamgfraser** [comment]
This has been done.
