### ISSUE TITLE
Revive StreamPure after Stream#process migration

### ISSUE THREAD

**Issue by iravid** [zio/zio#1408]

**Comment by vasilmkd** [comment]
Work already started.

**Comment by jdegoes** [comment]
Here's a sketch of the idea for embedding exceptions:

```scala
trait StreamEffect[+E, +A] {
  private[zio] def processEffect: Managed[E, () => A]

  def process: Managed[E, A => IO[Option[E], A]] = ???
}
object StreamEffect {
  case class StreamEffectFail[E](value: A) extends Throwable(value.toString, null, true, false)
  case object StreamEffectStop extends Throwable("Stream stop", null, true, false)
}
```

Inside `process` implementation, you `try` / `catch` the `() => A`: if it is `StreamEffectStop, you treat it as `InputStream.end`. If it is `StreamEffectFail`, you treat it as `InputStream.fail(e)` (a cast will be necessary; which makes this unsafe to expose to users).

Now the effectful streams can indicate failure or they can stop. Moreover, combinators on `StreamEffect` can use the lower-level representation for more efficient implementations.

Make sense? /cc @vasilmkd @iravid

**Comment by jdegoes** [comment]
Corresponding to the new ZSink being essentially `InputStream[R, E, A] => ZIO[R, E, (A0, B)` (albeit modified because this one will infer horribly), we could also introduce a `ZSinkEffect` (package private) that would be something like `(() => A) => (A0, B)` (_give me an iterator, I'll give you the remainder and a B_). This will allow highly-performant specializations for stream / sink effect variants.

The applications for `ZStreamEffect` / `ZSInkEffect` would be limited to:

 - Pure unfolds
 - Pure "collection-style" data
 - Conversion from synchronous APIs, such as Java's `InputStream`
 - etc.

Probably the `InputStream` is the killer use-case, although the possibility of using `ZStream` as a more efficient collection (for larger data with laziness, interruption, etc.) might be somewhat interesting.

**Comment by iravid** [comment]
@jdegoes the `A => IO[Option[E], A]]` is a typo, right? Should be `IO[Option[E], A]`?

**Comment by vasilmkd** [comment]
Can we make a list of which combinators and constructors fall under `StreamEffect`?

**Comment by vasilmkd** [comment]
@jdegoes can you explain why the cast is necessary for `StreamEffectFail(e: E)`?

**Comment by jdegoes** [comment]
@vasilmkd If we do this right, then we can just use the default implementations in all the tricky cases (they will be required for dynamic, async, and concurrent cases—it's only "simple" operators that have an effect version).
