### ISSUE TITLE
Task(f(x)) != Task(x).map(f)

### ISSUE THREAD

**Issue by cannedprimates** [zio/zio#1503]
val task1 = zio.Task(List()) map (_.head)
val task2 = zio.Task(List().head)
val rt      = new zio.DefaultRuntime{}
rt.unsafeRun(task1.either)
rt.unsafeRun(task2.either)

Moving the function application inside the try/catch when interpreting map/flatMap would make for more consistent semantics? Would be nice to be able to tell from the type whether or not a piece of code can throw...

**Comment by cannedprimates** [comment]
I agree that it's currently expected behaviour, I'm mostly looking to read some opinions on whether it's the correct behaviour :)

In my mind the main arguments against the current behaviour are (in no particular order):
 - less information conveyed in the type (fewer guarantees)
 - subjectively less intuitive (the function handed to map is not pure, but I'm calling it inside a monad that should handle all throwables)
 - Scala is just full of partial functions, so manually wrapping everything in Task adds a lot of noise/allocations when there's already a conveniently placed try/catch in the interpreter :)

**Comment by cannedprimates** [comment]
Thanks for the input! I will nitpick that the typesystem can guarantee that code won't throw, by catching all errors and converting them to values, c.f. Try. 

I'm also going to disagree, at least for the sake of the argument, that catching exceptions in task somehow makes the structure less algebraic. There's a space of Task values, including failed and successful Task values. Operations on Tasks move around in this space.
The laws exhibited by the proposed behaviour, as opposed to the existing behaviour. are if anything more algebraic, since the semantics don't have to include the concept of fiber failure (this applies only to Task of course, since the other IO variants cannot lift all errors into their value space).
Note the title of this issue, a law which one might reasonably (?) expect to hold :) 

I agree on minimizing the use of partial functions of course (I've been scala._ free for many years) just pointing out that I expect users of the standard library would have a safer experience.

**Comment by cannedprimates** [comment]
The first example I totally forgot about :( 
I wonder if one could write a wartremover or similar check to catch that. Try.succeed shouldn't exist of course (exactly because of that example) :)

Yes, but the operation on Task is map, not f. Your way of looking at it (f's type says no effects therefore throwing is a defect) is completely reasonable of course.
I just think my way of looking at it (a value of type IO[E, A] evaluates to a checked error of type E or a result of type A, or fails with an unchecked error of type other than E, hence evaluating it should never fail with E) is also reasonable :)

As for which approach is more pragmatic, if it were possible to follow rules such as "all code needs to be wrapped" I imagine we wouldn't have many bugs to begin with.

**Comment by jdegoes** [comment]
"Auto-catching" in map/flatMap, as it is called, not only violates applicative laws, but is not compatible with a polymorphic error type. The reason is that ZIO has no way to know that `E` _may_ be `Throwable` (indeed, trying to discern that would violate _parametric reasoning_), so it has no way to allow `catchAll` (for example) to catch an `E` that happens to be `Throwable`.

ZIO's behavior is the only lawful behavior and the only behavior compatible with polymorphic error channels. Other behavior will necessarily break laws and demand a monomorphic error channel (`Throwable`). I'd say those are good reasons why ZIO's behavior is "correct" in a mathematical sense, although I understand it causes some frustration.

I wish Scala were total and sound, but that would be a different language, as a result, a library like ZIO can never guarantee you won't lie in your own code, by writing types that say one thing, but do another. It requires discipline, and hopefully, in the future, more streamlined tooling.

Until then, wrap partial code in `Task(...)` if you want to ensure catchability, or sandbox untrusted code with `ZIO#sandbox`.

**Comment by neko-kai** [comment]
Also, sprinkling some `ZIO.absorb` when you're already using `Throwable` errors is easier than using `sandbox`

**Comment by cannedprimates** [comment]
Time to special case task! ;)

**Comment by jdegoes** [comment]
@cannedprimates It would be possible to create a thin wrapper that catches on map/flatMap (for E = Throwable); or even use Cats Effect instances with this behavior. 

Most people seem not to mind the ZIO behavior after they fix a few errant throws.

**Comment by cannedprimates** [comment]
Actually, to provide some context, in the system I spend most of my time in, we have a wrapper around third party effect systems (to enforce safe usage and to add a treelog-style monitoring library). I wrote a shim for ZIO the other day and noticed that some test cases (testing specific failure modes) were failing. It's trivial for me to add try/catch or an extra layer of Task() in our map/flatMap wrappers (plus we're all -no-imports with Scalaz's IList and such so our code doesn't throw much to begin with).

Just curious what peoples thinking around this was these days.

Not sure what using cats effect instances would involve, but doesn't sound good ;)
Thin wrapper would be nice to have I think (for the reason outlined above, i.e. E = Throwable substantially changes/simplifies the design space and consequently what the cleanest/safest possible semantics are)
