### ISSUE TITLE
ZIO Test: Make `failure` TestAspect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1691]
Inspired by @adamgfraser's recent PR to Cats interop, I think two `failure` aspects would be nice:

 - `failure(p: Assertion[Cause[E]])` — Expects a failure that matches the predicate
 - `failure` — Expects a failure (shorthand for `failure(Assertion.anything)`

**Comment by jaliss** [comment]
@jdegoes I’d like to take this.

**Comment by jdegoes** [comment]
@jaliss Awesome, thank you! 🙏

**Comment by adamgfraser** [comment]
I think we may want the signature to be `failure(p: Assertion[TestFailure[E]])`. The reason is that a `ZTest` fails with a `TestFailure[E]` which can be either a `TestFailure.Runtime(cause: Cause[E])` or a `TestFailure.Assertion(result: TestResult)`. So if our predicate can only take a `Cause[E]` as a parameter we can essentially only check for runtime failures, whereas this signature would allow us to check for either runtime failures or assertion failures.

Copying @jdegoes.

**Comment by LGLO** [comment]
My 2 cents after migrating and add some tests recently.
I like matchers, however because E is treated different to A, I used to `.flip` a lot. Expecting defects requires other kind of exercising (sandbox).
Assertion failures can be negated easily.
I think that `failure` of `fails` aspect should take `Assertion[E]` as a parameter
Later we could add `dies` aspect (there is a question about mapping `Traced`) that expects defects.
There is an assertion `dies` but I didn't see any use of it.I also tried and failed.
