### ISSUE TITLE
Checklist: Make sure tests exist for all data types to be serializable

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1739]

**Comment by jakubjanecek** [comment]
I am taking this.

**Comment by jakubjanecek** [comment]
- [x] Cause
- [x] Exit
- [x] FiberFailure
- [x] InterruptStatus
- [x] Promise
- [x] RefM
- [ ] ZSchedule

Tomas Herman is helping me and did others. We'll continue tomorrow.

**Comment by jakubjanecek** [comment]
`RefM` is not serializable because it calls `fork` in `make`. This might be "fixed" in some future version.

**Comment by dkarlinsky** [comment]
I've investigated the issue, where `ZTrace` deserialization fails with `java.lang.ClassNotFoundException: zio.internal.stacktracer.ZTraceElement$NoLocation`. 

The root cause is a class loader issue, which will probably not occur in normal application.
When deserializing, `ObjectInputStream` walks the stack to find the first "user class" (non java standard library class) and uses its class loader to load classes being deserialized.
Scala's `immutable.List` has custom serialization, so when deserializing anything held in a `List`, the first "user" class found down the stack is `scala.collection.immutable.List$SerializationProxy`, which is loaded by an SBT classloader that doesn't know any of the project classes, such as  `ZTraceElement$NoLocation`. Hence the `ClassNotFoundException`.
Not sure how this can be worked around...

**Comment by tomasherman** [comment]
wow, good one

**Comment by ghostdogpr** [comment]
We found a workaround (see the PR) 👏

**Comment by jakubjanecek** [comment]
My jaw dropped 👏

**Comment by LGLO** [comment]
Can we close it?

**Comment by ghostdogpr** [comment]
Closed by #1771
