### ISSUE TITLE
'timeout' aspect stalls test if timeout happens with uninterruptible effect

### ISSUE THREAD

**Issue by LGLO** [zio/zio#1764]
When using `@@nonFlaky` `TestAspect` and test repetitions exceed timeout aspect, I can observe that test doesn't finish, however it stops repeating case execution.

**Comment by adamgfraser** [comment]
I observed the same thing. Will look into this.

**Comment by adamgfraser** [comment]
@LGLO I am having trouble reproducing this locally. Here is the code I am using. It is a test that prints a line to the console, sleeps for one second and then succeeds. I am doing `nonFlaky(10)` on it with a timeout of 5 seconds, so if there was an issue I would expect it to print the line ten times over 10 seconds, but it is actually timing out after 5 seconds which is the right behavior. Do you have an example of where you saw?

```scala
import zio.duration._
import zio.test._
import zio.test.Assertion._
import zio.test.mock._
import zio.test.TestAspect._
import zio.ZIO

object MySpec
    extends ZIOBaseSpec(
      suite("MySpec")(
        testM("test") {
          for {
            _ <- ZIO.effectTotal(println("Running"))
            _ <- live(ZIO.sleep(1.second))
          } yield assert(true, isTrue)
        } @@ nonFlaky(10)
      )
    )

abstract class ZIOBaseSpec(spec: => ZSpec[MockEnvironment, Any, String, Any])
    extends DefaultRunnableSpec(spec, List(TestAspect.timeout(5.seconds)))
```

**Comment by LGLO** [comment]
Yeah, it can be found in ZManagedSpec. It has something to do with uninterruble threads.
I've modified base spec to 10 seconds timeout:
```scala
package zio

import zio.duration._
import zio.test._
import zio.test.Assertion._
import zio.test.mock._

object NonFlakyStall
    extends ZIOBaseSpec(
      suite("ZManaged")(
        testM("The canceler should run uninterruptibly") {
          for {
            ref     <- Ref.make(true)
            latch   <- Promise.make[Nothing, Unit]
            managed = Managed.make(ZIO.unit)(_ => latch.succeed(()) *> ZIO.never.whenM(ref.get)).withEarlyRelease
            result <- managed.use {
                       case (canceler, _) =>
                         for {
                           fiber        <- canceler.fork
                           _            <- latch.await
                           interruption <- withLive(fiber.interrupt)(_.timeout(1.seconds)).either
                           _            <- ref.set(false)
                         } yield interruption
                     }
            _ <- ZIO.effectTotal(println("Running"))
          } yield assert(result, isRight(isNone))
        } @@ TestAspect.nonFlaky(15)
      )
    )
```
I'll try to shrink this example.

**Comment by adamgfraser** [comment]
@LGLO Thanks! That is super helpful. I have a feeling it has to do with `timeout` trying to interrupt the test and waiting for the interruption to complete but that never happening because the test is performing an effect that is uninterruptible and doesn't terminate. Will look into it more. If that is right we could not wait for the interruption to complete but to a certain extent if you have accidentally created a process that doesn't terminate and can't be interrupted there isn't really a clean way for us to handle it.

**Comment by LGLO** [comment]
Shrinked example
```scala
object TestStall
    extends ZIOBaseSpec(
      suite("timeout aspect")(
        testM("doesn't interrupt uninterruptible") {
          for {
            result <- ZIO.never.uninterruptible *> ZIO.unit
          } yield assert(result, equalTo(()))
        }
      )
    )
```

**Comment by adamgfraser** [comment]
Exactly. I think maybe we have a timeout on the interruption completing and if the interruption doesn't complete within that time we fail and log a warning that we were unable to interrupt the test within that time and a resource leak may have occurred.

**Comment by adamgfraser** [comment]
I will take this one.

**Comment by LGLO** [comment]
Hmm, I have something already:
```scala
def timeout(duration: Duration): TestAspect[Nothing, Live[Clock], Nothing, Any, Nothing, Any] =
    new TestAspect.PerTest[Nothing, Live[Clock], Nothing, Any, Nothing, Any] {
      def perTest[R >: Nothing <: Live[Clock], E >: Nothing <: Any, S >: Nothing <: Any](
        test: ZIO[R, TestFailure[E], TestSuccess[S]]
      ): ZIO[R, TestFailure[E], TestSuccess[S]] =
        for {
          p <- Promise.make[TestFailure[E], Either[TestFailure[E], TestSuccess[S]]]
          _ <- test.either.flatMap(r => p.complete(ZIO.succeed(r))).fork
          _ <- Live
                .withLive(ZIO.unit)(_.delay(duration))
                .flatMap(
                  _ =>
                    p.complete(
                      ZIO.fail(
                        TestFailure
                          .Runtime(Cause.die(TestTimeoutException(s"Timeout of ${duration.render} exceeded")))
                      )
                    )
                )
          result <- p.await.absolve
        } yield result
    }
```

**Comment by LGLO** [comment]
OFC if it's fun for you to provide your implementation, go for it!

**Comment by adamgfraser** [comment]
Sorry, if you want it the ticket is all yours!

My main concern with your snippet is that we are silently dropping the fact that we weren't able to successfully interrupt the test. We have returned a failure which is great so we don't hang, but the fiber running that test is still going which may be causing a resource leak, something I have definitely experienced myself!

I think in this case we want to fail loudly by returning a failure that says something like "Timeout of 60 seconds exceeded. ZIO Test was unable to interrupt this test after 5 seconds. This may indicate a resource leak". I think this would mean having `timeout` taking a second parameter for the maximum duration to wait for interruption to complete, and we could provide a default value so that it wouldn't really impact the user unless they wanted to change the default for some reason.

What do you think?

**Comment by LGLO** [comment]
Thanks for letting me complete this!

That is proposed output for 3 cases, only last one is new:
```
[info] - timeout aspect
[info]   + should pass
[info]   - with interruptible
[info] Timeout of 5 s exceeded
[info]   - with uninterruptible
[info] Timeout of 5 s exceeded. Couldn't interrupt test within 10 s, possible resource leak!
```
Implementation I isn't currently terminating in all cases, but I'll get there.
I'll also add tests to TestAspectSpec.

**Comment by adamgfraser** [comment]
That looks fantastic! Thank you!
