### ISSUE TITLE
utf8Decode not working correctly when chunk overlaps character

### ISSUE THREAD

**Issue by msosnicki** [zio/zio#1831]
I've noticed that `utf8Decode` is not working correctly when the buffer size specified is overlapping the character. So as an example, if I have a string of 10 unicode characters, 2 bytes each, and I set a buffer of size 19, it will fail to decode original string. The problem here is, that the `utf8Decode` sink is discarding leftovers. 
I had a look how Sinks are in general implemented, and it looks like they are mostly stateless, the leftovers are being fed to them from the outside (like from `transduce` for example). The `utf8Decode` is implemented using `foldUntil` and I think it should be possible to fix it using a more powerful version of it, `foldWeighted`.

I'm happy to work on it, I would just like to confirm if my reasoning here is correct :)

Broken example:
https://gist.github.com/msosnicki/3ee998d9854583d03d7d462311bbdbd9

**Comment by iravid** [comment]
Oh right, `utf8Decode` is obviously wrong. That's a good catch, not sure how that slipped by. Would be great to get a patch for this!

Does `utf8DecodeChunk` work correctly for you?

**Comment by iravid** [comment]
I'm actually wondering if it's possible to implement this correctly on a stream of bytes, because in general, we've found out that arrow composition of sinks (e.g. `(Byte => Chunk[Byte], Chunk[Byte] => String) => (Byte => String)`) is impossible.

**Comment by msosnicki** [comment]
I haven't noticed any troubles yet with `utf8DecodeChunk`. 
I was wondering if it would be possible to solve using `foldWeighted`, you could then only count bytes that have been fully decoded. So in the broken example above, it would consume more elements on the overlap (to decode the full char) and copy it over to the leftovers. That would of course mean, that this buffer would be aproximate, because instead of 19 bytes it would have to buffer 20 to decode correctly, but I guess that's acceptable.

**Comment by iravid** [comment]
Ok. I -think- the right way to go about this is to just delete `utf8Decode`. Any stream of bytes can be chunked up and fed into `utf8DecodeChunk`.

Alternatively we could re-implement the sink for a stream of bytes, but I don't fancy maintaining the implementation twice.

**Comment by msosnicki** [comment]
Is there any discussion, perhaps on gitter, which touches upon the arrow composition for sinks? It would be a great read :) 
Anyway, I will play with it for a while to see how to implement this sink without duplication, and just remove the method if I fail.

**Comment by iravid** [comment]
@dkarlinsky and I sketched it out on a paper but unfortunately did not document :-) I will try and document this in the issue about `ZSink#andThen`. 

The gist is that say you've got these two sinks - `A => B`, `B => C`. If the first one has leftovers, that's ok - you can push them back to the stream. But if the second sink has leftovers, there's nothing you could do (with the current combinators - transduce/run) because `B` is not the type of the stream.

Now, writing this, I do realize that in this particular case the types DO line up:
- A chunking sink does `Byte => Chunk[Byte]`, with leftover `Byte` returned as `Chunk[Byte]`
- A UTF8 decoding sink does `Chunk[Byte] => String` with leftover `Chunk[Byte]` returned as `Chunk[Chunk[Byte]]` that can be flattened back to `Chunk[Byte]`.
So it may be possible to write this after all, if you do end up working on this :-)
