### ISSUE TITLE
Flaky test in FiberRefSpec

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1833]
See https://circleci.com/gh/zio/zio/28535

```
- the value of the looser is inherited in zipPar
[info]       update1 did not satisfy equalTo(update2)
```

cc @zezutom

**Comment by adamgfraser** [comment]
Copying @mlangc.

This looks like the same issue we thought we had fixed in #1716. Unfortunately at least to date we have not found a way to write that test in a way that is completely deterministic so we rely on "waiting" long enough to make sure we get the expected result, which still leaves some possibility for flakiness that I think we are seeing here. I also wonder if this is exacerbated by the move to ZIO Test where we have more effects executing in parallel and so more potential execution paths that were always possible but just weren't being realized before in tests when each test was run with `unsafeRun` itself.

**Comment by ghostdogpr** [comment]
@adamgfraser wasn't it removed here? https://github.com/zio/zio/pull/1818/files

**Comment by adamgfraser** [comment]
@ghostdogpr Yes that's the problem. It was removed in #1818 but it was actually added in #1716 to prevent flakiness and apparently worked it was removed. So I think we need to revert #1818.

**Comment by adamgfraser** [comment]
It is a tricky test because we are trying make sure one fiber wins the race by having it complete a latch that the other fiber waits on. But there is a step between the "winner"  completing the latch and being joined back, so if we are particularly unlucky the runtime can suspend the winner immediately after completing the latch, in which case the "loser" can begin executing and actually be joined back first, resulting in the flakiness. The eliminated method suspended the loser a bunch of times even after the latch was completed to make this scenario extremely unlikely, so when we removed it we saw the flakiness come back.
