### ISSUE TITLE
ZIO test: Impedence mismatch with && and ||

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#1888]
While it is possible to write
```scala
assert(x, assertionX) && assert(y, assertionY)
```
it is not to write
```scala
assertM(x, assertionX) && assertM(y, assertionY)
```
or indeed any combination of `assert`, `assertM`, `||`, `&&`, etc.

One is forced to write more boilerplate:

```scala
(assertM(x, assertionX) zipWith assertM(y, assertionY))(_ && _)
```
which doesn't scale well with more than two assertions.

**Comment by adamgfraser** [comment]
Yes. You can avoid this by using a for comprehension to get your effectual result and then using `assert` rather than `assertM` but that is not ideal for all use cases. The challenge is that `assertM` returns a `ZIO[R, E, AssertResult]` rather than an `AssertResult`.

I see two ways we could address this. The first is we could add some methods on the BoolAlgebra companion object along the lines of `bothM`, `eitherM`, `forAllM`, and `existsM` that would take two or a collection of `ZIO[R, E, AssertResult]` and smoosh them together into a new `ZIO[R, E, AssertResult]`.  It isn’t infix but it is concrete methods and would be pretty clear.

The second is we could add some implicit syntax methods for `&&`, `||`, etc...

**Comment by jdegoes** [comment]
I almost think we should eliminate `assertM` for this reason. Without gobs of implicits, it will never have the same functionality or same API as `assert`.

**Comment by adamgfraser** [comment]
@jdegoes I'm not opposed to that. The downside is that it isn't quite as nice to write simple effectual assertions (e.g. `assertM(nanoTime, equalTo(0L))`. But I agree with you about consistency and the issues with going down the implicit route.

@regiskuckaertz Do you have an example of where this was inconvenient for you? That could help us think concretely about the best way to address this.

**Comment by regiskuckaertz** [comment]
@adamgfraser yep, sure thing: https://github.com/zio/zio/pull/1887/files#diff-c41f30b496d69f1d24fa935cc79a247dR1352-R1357

I thought it would be possible to change the type to `(ZIO[R, E, A], A) => TestResult` but I didn't think very far 😅

**Comment by adamgfraser** [comment]
It seems like using for comprehensions could help a lot. Like in this case we could go from:

```scala
  assertM(partialParse, succeeds(equalTo(List.empty[Int]))).zipWith(
    assertM(
      fullParse,
      succeeds(equalTo(List(123, 4)))
    )
  )(_ && _)
```

to:

```scala
  for {
    partial <- assertM(partialParse, succeeds(equalTo(List.empty[Int])))
    full    <- assertM(fullParse, succeeds(equalTo(List(123, 4))))
  } yield partial && full
```

Though admittedly we could also write this without using `assertM` at all:

```scala
  for {
    partial <- partialParse
    full    <- fullParse
  } yield assert(partial, succeeds(equalTo(List.empty[Int]))) &&
    assert(full, succeeds(equalTo(List(123, 4))))
```

Thinking about this more I'm a little hesitant to get rid of `assertM` altogether because it would make it more verbose and less clear to write one line effectual assertions. And this seems to be a relatively common pattern. As one data point, `assertM` is used 195 times in our code base today and 145 times in #1887.

Maybe we just need to document more that for comprehensions are the preferred way to combine multiple effectual assertions?

**Comment by regiskuckaertz** [comment]
This is a library for testing effectful code so I'd vote in favour of keeping `assertM`; I'd be surprised if `assert` was used as much as `assertM` in fact.

**Comment by adamgfraser** [comment]
Actually `assert` is used 1,409 times so it is significantly more common, though `assertM` is definitely used as well. The pattern of using a for comprehension to describe an effect and then using `assert` in the yield clause is very common. How do you feel about the solutions proposed above? If we weren't going to use implicits would you want methods on an object somewhere to combine multiple effectual assertions?

**Comment by regiskuckaertz** [comment]
They definitely work and are more concise than my example, so if implicits are out of the equation I'm happy to go with that 👍 

I was wondering if changing `TestResult` to be a `BoolAlgebra[UIO[FailureDetails]]` would lead somewhere though. I can play with the idea on the side, it's just for my own curiosity.

**Comment by adamgfraser** [comment]
That's interesting. I think you would need to keep the `R` parameter so you could take an arbitrary `assertM` and I think you might want to keep the `E` parameter as well but that could definitely work. The advantage is that `assert` and `assertM` both return a type within our control so we can add methods on it. One disadvantage is that `assertM` would no longer return an effect so you couldn't do anything with it that you would do with a normal effect (e.g. use it in for comprehensions, time it out, etc...).

**Comment by jdegoes** [comment]
Ah, so that is interesting. So what if `assert` and `assertM` returned the same type: a wrapper on effectfully produced result, which _would_ have the same set of methods (`||` / `&&` / etc.).

Then maybe add a combinator to work on the underlying effect (`mapEffect`?), and you'd have about the same power as today.
