### ISSUE TITLE
Promise.complete violates Promise "set exactly once" rule

### ISSUE THREAD

**Issue by Alexey8127** [zio/zio#1932]
I suppose that `Promise.complete` method has very special behavior:

```
val promiseTest = 
	for {
	    p      <- Promise.make[Nothing, Int]
	    action =  random.nextInt(10).provide(Random.Live)
	    _      <- p.complete(action)
	    v1     <- p.await
	    v2     <- p.await
	    v3     <- p.await
	  } yield (v1,v2,v3) 
```

As documentation says: `A promise represents an asynchronous variable, of [[zio.IO]] type, that can be set exactly once...`, so I expect the result of `promiseTest` to be three equal values, but actually it's not:
```
run(promiseTest) 
res13: (Int, Int, Int) = (4, 0, 1)
```
And that result violates the `can be set exactly once` rule. Also we have safe method `ZIO.to` to complete promise with effect which internally use `Promise.complete`. And this version works correctly:
```
for {
    p      <- Promise.make[Nothing, Int]
    action =  random.nextInt(10).provide(Random.Live)
    _      <- action.to(p).fork
    v1     <- p.await
    v2     <- p.await
    v3     <- p.await
  } yield (v1,v2,v3) 
```
 Maybe `Promise.complete` should be the part of private API? 
 Because I spent a lot of time to find this subtle bug trying to complete promise with some effect

**Comment by adamgfraser** [comment]
@Alexey8127 Thanks for raising! This has actually come up a couple of times recently in #1866 (raising the issue) and #1877 (adding additional documentation).

The issue here is that the `Promise` in `ZIO` is based on continuations and can contain an effect. So the "set exactly once" guarantee is that the `Promise` can be set exactly once to some, potentially effectual, value. In your example, the `Promise` could be set to `random.nextInt(10)` and each time `Promise.await` was called it would generate a different value. But once the `Promise` had been completed with `random.nextInt(10)` it could never be completed with `random.nextInt(6)`.

That being said, we have heard from you and several others that the current behavior can be unintuitive and are working on ways to address this.

**Comment by Alexey8127** [comment]
@adamgfraser , thanks for detailed answer! As I can see at documentation it says the type of Promise value is `zio.IO`, then it does make sense. But what is the semantic difference between `action.to(promise)` and `promise.complete(action)`? Because I expected the same behavior, but it differ actually.

**Comment by adamgfraser** [comment]
@Alexey8127 No problem!

`action.to(promise)` is the equivalent of `action.run.flatMap(x => p.complete(ZIO.done(x)))`. So conceptually `to` runs the effect and then takes the result of running the effect, wraps it in an effect constructor, and completes the promise with that. Going back to the idea of completing the `Promise` with an effect `to` runs the effect first and then completes the promise with a constant effect, versus `complete` completes the promise with the effect itself.

**Comment by LGLO** [comment]
Looks like documentation update didn't help. Should we reconsider API?

**Comment by jdegoes** [comment]
How about we rename `complete` to `continueWith` or something, and then introduce a new complete that has "expected" semantics?

**Comment by adamgfraser** [comment]
I think that is a good idea. I’ll take this one.
