### ISSUE TITLE
Intermittent Issue running ZIO schedule

### ISSUE THREAD

**Issue by mmuschalik** [zio/zio#2052]
I took on a little project to get familiar with the core library by trying to solve the dining philosophers problem.

I'm experiencing some strange behavior, once I add a repeat schedule for each philosopher. It sometimes works, sometimes doesn't. It could well be the code, but I can't seem to work it out. 

Real quick explanation: I want to model the forks on the table as zio semiphores and have each philosopher repeat the action of trying to grab the forks, eat and think for a bit.

[dining-philosophers.zip](https://github.com/zio/zio/files/3783635/dining-philosophers.zip)

Basically I have the following code:
```
for {
    table <- setTable(List("john", "david", "peter", "max", "joseph", "meg", "cassy"))
    _ <- ZIO.collectAllPar(table.philosophers.map(p => p.eatAndThink().repeat(Schedule.once)))
  } yield ()
```

When I execute with sbt, it seems to occasionally permanently hang with the following shown in the concole:

```
> sbt run
[info] Loading global plugins from /home/maurice/.sbt/1.0/plugins
[info] Loading settings for project dining-philosophers-build from plugins.sbt ...
[info] Loading project definition from /home/maurice/repo/dining-philosophers/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to dotty-simple (in build file:/home/maurice/repo/dining-philosophers/)
[info] Running MyApp

```
Without the repeat schedule 

> .repeat(Schedule.once)

, I don't seem to be able to replicate this hanging issue and should output something like the following:

```max eating...
max done eating...
peter eating...
max thinking...
peter done eating...
```

Disclaimer, I did also want to try to compile it with dotty.

**Comment by regiskuckaertz** [comment]
This is clearly a deadlock and the whole point of the dining philosophers' problem 😄 Acquiring both forks should be an atomic operation, otherwise deadlock is very likely to happen at some point. It is not trivial to express that, even with ZIO, _except_ if you use STM which was created to solve exactly that problem.

I'll close the issue as it doesn't seem like a bug in the library, please feel free to reopen if you disagree --- or, take the discussion to discord where you are likely to get a response much faster.
