### ISSUE TITLE
TestClock use of Duration and Time could be clearer

### ISSUE THREAD

**Issue by TimPigden** [zio/zio#2068]
Time or DateTime is normally a point on a continuum - see java.time for example.
Duration is the difference between two Times (always positive in zio case)
But TestClock uses Duration in setTime when it should be using some sort of DateTime as in:
```scala
    /**
     * Sets the current clock time to the specified time. Any effects that
     * were scheduled to occur on or before the new time will immediately
     * be run.
     */
    final def setTime(duration: Duration): UIO[Unit] =
```
In other cases it adheres to the norm, with TimeZone, ZoneId etc. and a currentDateTime: UIO[OffsetDateTime]

To make it more consistent I would replace with
setTime(OffsetDateTime)

Now anyone who is working in zero based time for arithmetic convenience can happily continue 
to use the default TestClock which initialises to 0 (1/1/70) and if they want to set the time to something using simple units, they can use adjust(Duration)

**Comment by adamgfraser** [comment]
@TimPigden Thanks for raising!

I would suggest we add a new method `setDateTime` to address the use case you suggest and add additional documentation that `setTime` sets the time to the specified duration since the epoch.

I understand your point about consistency with time units but I think there are a couple of other countervailing factors:

1. Using duration is much more convenient for most typical uses of `TestClock`. In almost all use cases I have seen people are doing some effect that delays for some duration, then adjusting the clock or setting the time, and then verifying that the expected result occurred. So it much nicer to be able to do `sleep(1.second) ... setTime(1.second)` and use the existing ZIO implicit syntax for duration rather than go through constructing a `LocalDate`, especially when the time units are typically very small.
2. `adjust` is not a substitute for `setTime` since adjust moves the clock forward from the current clock time whereas `setTime` sets it to an arbitrary value regardless of the previously set time.
3. This would be a breaking change for all code that uses the `TestClock`. `setTime` and `adjust` are used in pretty much all code that uses the `TestClock`. I would prefer not to make our users rewrite their code for this just when they are starting to adopt using the `TestClock` without a compelling reason.

What do other people think?

**Comment by TimPigden** [comment]
I'm happy with that.

**Comment by adamgfraser** [comment]
Okay, I will take the ticket.

**Comment by TimPigden** [comment]
is it too late to point out that there's a
TestClock.timeZone 
but no
TestClock.currentDateTime
so the set of functions on the companion object is a slightly odd subset of the ones on the class

**Comment by adamgfraser** [comment]
It isn't too late to point it out though I don't know if it is actually a problem.

The logic I have tried to apply is that I have only added companion object functions on the test implementations when those functions are not provided by the live implementations. So for example, there is a `TestClock.adjust` but there is no `TestClock.sleep` because that functionality is already available through `clock.sleep`. If you look at the `Clock` trait in ZIO core it actually doesn't expose a `timeZone` method, so I did supply that method on `TestClock`. In contrast, `currentDateTime` is already available through `clock.currentDateTime`.
