### ISSUE TITLE
ZIO Test: Allow inheritance-style specification of spec

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2085]
```scala
object MySpec extends DefaultRunnableSpec {
  def spec = ...
}
```

**Comment by adamgfraser** [comment]
I spent a little time working on this morning and struggled to get this to work. The challenge that I ran into is that existing code uses the pattern

```scala
object MySpec extends DefaultRunnableSpec(...)
```

This means that `DefaultRunnableSpec` has to have a primary constructor with a parameter list for existing code to fill in. But then I don't know how we support the inheritance style because the compiler is going to complain that we're not providing the required parameters.

Maybe we can work through this morning. Agree it would be nice to support this style.

**Comment by jdegoes** [comment]
We could use default argument, but then we need some sort of discriminatory, e.g. `Option` or something to indicate which one to choose (param or field).

I think the `Util` pattern is a bit of a smell, at least it's a non-obvious workaround to the current problem of defining local methods / data.

We could support both with another `RunnableSpec` and deprecate `DefaultRunnableSpec`.
