### ISSUE TITLE
test timeout failure

### ISSUE THREAD

**Issue by unclebob418** [zio/zio#2193]
When refactoring RandomSpec under #2037, I did a stupid thing by mistake :) some very long lists were created with size of Gen.anyInt (i.e. potentially Int.MaxValue long)

Unfortunately the 60s timeout on `ZIOBaseSpec` didn't (or wasn't able to) interrupt the test as expected. Possibly another manifestation of #1882?

Memory usage was stable, CPU was sitting around 80% on all cores. I killed it after a couple of minutes with no change.

```
object RandomSpec
    extends ZIOBaseSpec(
      suite("RandomSpec")(
...
        testM("check nextString") {
          forAllEqualN(_.nextString(_))(_.nextString(_))
        },
        testM("bounded nextInt") {
          forAllEqualN(_.nextInt(_))(_.nextInt(_))
        },
...
  def forAllEqualN[A](
    f: (Test, Int) => UIO[A]
  )(g: (SRandom, Int) => A): ZIO[Random, Nothing, TestResult] =
    checkM(Gen.anyLong, Gen.anyInt) { (seed, size) => //anyInt should be int(1, 100)
      val sRandom = new SRandom(seed)
      for {
        testRandom <- TestRandom.makeTest(DefaultData)
        _          <- testRandom.setSeed(seed)
        actual     <- f(testRandom, size)
        expected   = g(sRandom, size)
      } yield assert(actual, equalTo(expected))
    }
...
```

**Comment by adamgfraser** [comment]
@unclebob418 I think in this case the failure to timeout is due to the ZIO interruption model and the way the test was written.

The important thing to keep in mind about the ZIO interruption model is that it isn't just based on interrupting blocks of code at any given point. That wouldn't be resource safe. Rather, it is based on the runtime checking for interruption at each step in a chain of effects, like when we `flatMap` to compose two effects. Normally we don't notice this because we compose effects so much that it provides plenty of opportunities for interruption. But sometimes it can become relevant. For example, consider the snippet below. `expensiveComputation1` can't be timed out because it is just one giant effect. We're trying to generate this giant string and we're not coming back to the runtime until we are done so there are no opportunities for interruption. In contrast `expensiveComputation2` can be timed out without issue because although the whole effect will take a very long time it is composed of many very small effects.

In this test the issue is the line `expected = g(sRandom, size)`. We're asking `scala.util.Random` to generate a string of potentially up to `Int.MaxValue` size, which is going to be one giant effect. Furthermore, we're using impure code that generate a random number but we're not properly suspending the effect.  So the first step in the right direction would be to wrap the random number generation in an effect constructor like `effectTotal`. Then the next step if we really did want to be able to interrupt that effect would be to treat it as a blocking effect and use `effectBlocking`, which would run the effect on a separate thread pool and actually interrupt the underlying thread to try to stop it in the middle of the computation, though as we have seen with some of our other work that is not entirely reliable yet.

Does that make sense?

```scala
import zio._
import zio.duration._

object TimeoutTest extends App {

  def run(args: List[String]): ZIO[ZEnv, Nothing, Int] =
    expensiveComputation2.timeout(5.seconds).as(0)

  // can't be timed out
  val expensiveComputation =
    random.nextString(Int.MaxValue)

  // Can be timed out
  val expensiveComputation2 =
    random.nextInt.repeat(Schedule.recurs(Int.MaxValue))
}
```

**Comment by unclebob418** [comment]
@adamgfraser yes, that's very helpful thanks. I've updated #2037 to remove the impure code.
