### ISSUE TITLE
Back out Codecov?

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#222]
It's stalling all builds because they never complete. Something about the Travis / Github integration is failing (though if you look at Codecov, it has coverage).

**Comment by NeQuissimus** [comment]
*sigh*... I am starting to be pretty frustrated by the build stuff...
Codecov should only fail if Travis also fails...
I think I am going to grab a fresh repo, figure all this shit out and document how I did it. This is just brutal because I don't want to have you create tags willy-nilly, so we can test the build definition :(

**Comment by NeQuissimus** [comment]
OK, so I want to get #215 merged and then I will clean things up once more if need be :)
I have this now, where I have figured out the entire process: https://github.com/NeQuissimus/test-and-stuff

**Comment by ghostdogpr** [comment]
Closing, it was removed.
