### ISSUE TITLE
Bring back `interruptChildren`? Or make supervision end children on Fiber end regardless of interruption

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#2289]
`interruptChildren` operator still makes sense with the new supervision model when you want forks of the effect to be interrupted _when it completes_, not just when it's interrupted. Currently forks will be interrupted only if parent is _interrupted_

Alternative path would be to bring back the previous semantic of unconditional interruption on completion – this would also align better with [Structured Concurrency](https://wiki.openjdk.java.net/display/loom/Structured+Concurrency)

> The main benefit of structured concurrency is abstraction.  A caller of a method that is invoked to do a task should not care if the method decomposes the task and schedules a million fibers. When the method completes, any fibers scheduled by the method should have terminated.

**Comment by iravid** [comment]
We can do this with `ensuring + ZIO.children` no? I agree on principle in any case.

I have two more thoughts that are not yet fleshed out:
- I think we need a region-based mechanism for tracking children; tracking children only on the fiber level feels a bit too coarse
- I am very bothered by the very nuanced mismatch between lexical scoping and the result of ZIO.children. This is very apparent in ZManaged.

**Comment by neko-kai** [comment]
@iravid 
> We can do this with ensuring + ZIO.children no?

That's the exact implementation of `ZIO#interruptChildren` on RC16 :)

> I think we need a region-based mechanism for tracking children; tracking children only on the fiber level feels a bit too coarse

Aside from ZManaged.fork? on related note [Structured Concurrency](https://wiki.openjdk.java.net/display/loom/Structured+Concurrency) usually uses nursery objects for regions, but we can of course make them ambient in the effect.

**Comment by jdegoes** [comment]
@neko-kai 

I agree to bring this back, we can do it simply. I deleted it originally because in an early incarnation of auto-supervision, it was impossible to write.

@iravid 

> I think we need a region-based mechanism for tracking children; tracking children only on the fiber level feels a bit too coarse

What happens when a region exits? Do you "forget" about the children in that region? Or maybe you "dispose" of them through a UDF specified when you create the region?

> I am very bothered by the very nuanced mismatch between lexical scoping and the result of ZIO.children. This is very apparent in ZManaged.

I agree with this, and it's something that a region operator could solve. In the meantime you can fork/join, of course (although that you have to does tell us something about the course-grained nature of the supervision).

**Comment by jdegoes** [comment]
@neko-kai 

> That's the exact implementation of ZIO#interruptChildren in RC16 :)

The new implementation should do something like this:

```scala
for {
  fiber <- zio.ensuring(ZIO.children.flatMap(Fiber.interruptAll(children))).fork
  v <- fiber.join
} yield v
```

Though see above, I think the need to fork/join is really telling us something about the need for monadic regions for children.

**Comment by neko-kai** [comment]
@jdegoes 
> I agree to bring this back, we can do it simply. I deleted it originally because in an early incarnation of auto-supervision, it was impossible to write.

👍 What do you think about interrupting children on ALL completion, not just interruption?

> The new implementation should do something like this:

Is the fork/join here necessary to get an up-to-date list in ZIO.children?

**Comment by regiskuckaertz** [comment]
> interrupting children on ALL completion

imo that's a more usable behaviour, which would give `daemon` a more sensible meaning too. I feel like users will often have to write variations of `ZIO.children.flatMap(Fiber.interruptAll)` otherwise (see [recently in the stream combinators](https://github.com/zio/zio/pull/2236/files)). I may be biased though.

**Comment by jdegoes** [comment]
I'm not sure this is relevant anymore. Closing for now.
