### ISSUE TITLE
WIP: Explore lens encoding for environment

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2297]
Lenses allow generic reconstruction of an environment of unknown type.

```scala
  type Lens[S, A] = (S => A, A => S => S)

  // All environmental effects extend this trait:
  trait EnvironmentalEffect {
    type Environment
    def modify[A, B](lens: Lens[Environment, A])(f: A => (B, A)): UIO[B]

    final def update[A](lens: Lens[Environment, A])(f: A => A): UIO[Unit] = 
      modify(lens)(a => ((), f(a)))
  }
  object EnvironmentalEffect {
    def modify[R <: EnvironmentalEffect, A, B](lens: Lens[R#Environment, A])(f: A => (B, A)): ZIO[R, Nothing, B] = ZIO.accessM[R](_.modify(lens)(f))

    def modify[R <: EnvironmentalEffect, A, B](lens: Lens[R#Environment, A])(f: A => (B, A)): ZIO[R, Nothing, B] = 
      ZIO.accessM[R](_.modify(lens)(f))

    def update[R <: EnvironmentalEffect, A](lens: Lens[R#Environment, A])(f: A => A): ZIO[R, Nothing, Unit] = 
      ZIO.accessM[R](_.update(lens)(f))
  }
  
  trait Logging extends EnvironmentalEffect {
    def logging: Lens[Environment, Logging.Service]
  }
  object Logging {
    trait Service {
      def log(line: String): UIO[Unit]
    }
  }
```

Using such a mechanism it becomes possible to arbitrarily deconstruct and reconstruct environments of unknown shape.

Needs to be sketched out into a more fully-fleshed prototype.

**Comment by regiskuckaertz** [comment]
Classy optics FTW

**Comment by adamgfraser** [comment]
I could work on trying to flesh out this and #2296. Would that be helpful?

**Comment by mschuwalow** [comment]
I love where this is going!
We still would have pains when incrementally constructing environments, but this could solve a ton of ergonomic issues :)

**Comment by jdegoes** [comment]
@adamgfraser It would indeed be super helpful to compare them. 

I think #2296 might be a "pointfix" we could use to fix the jittered problem without impacting much downstream code, but this would be more a "real fix" that would incidentally address #2296. 

In addition, @ioleo is working on an `HSet` that models the environment as a set of modules, which should be explored alongside these efforts (although may be too ambitious for 1.0, we'll see).

**Comment by adamgfraser** [comment]
@jdegoes Awesome! `HSet` encoding sounds super interesting.

**Comment by jdegoes** [comment]
> We still would have pains when incrementally constructing environments, but this could solve a ton of ergonomic issues :)

Indeed, lens encoding is great at reconstructing, but not so great at incrementally constructing. Albeit I think you could do something quite clever to solve these pains, basically a heterogeneous map, where you add a typed entry to it and get a typed lens.

**Comment by neko-kai** [comment]
I'd rather resurrect/extend [scala-records](https://github.com/scala-records/scala-records/) and use it for Env. I doubt heterogenous collections can properly support variance.

**Comment by mschuwalow** [comment]
@neko-kai I think that at least for dotty it should be quite easy do to using just the new Selectable/selectDynamic, but I have no idea how to provide a 'safe' API on top of that.

**Comment by neko-kai** [comment]
@mschuwalow 
With macros. Another choice is literal types, e.g. it's legal to have:
```scala
trait Rec extends Dynamic {
  def selectDynamic(s: "field1"): Int
  def selectDynamic(s: "field2"): Boolean
}
```

Unfortunately i threw away my snippets with exploring this, because scala-records does almost the same thing.
What scala-records does is exactly the same thing as Selectable, but in Scala 2 – it's easier in Dotty. They inherit `Dynamic` with selectDynamic implemented by a macro, when called it generates a [new class under the call](https://github.com/scala-records/scala-records/blob/master/core/src/main/scala/records/AccessMacros.scala#L31), so the access is not-dynamic. As far as I can see the underlying store is HashMap, but there's a lot of unused flexibility specifically for the case of efficient indexed store (also, fields type index is invariant I guess specifically for this case, for our use case it must be made covariant)

Really, the only problem with scala-records is that it's an abandoned, seemingly maintained, but no longer published EPFL student project.

**Comment by adamgfraser** [comment]
@jdegoes I'm struggling to get the lenses to be generic enough for what we want to do. I can define a `Lens[ZEnv, Clock]` for example but that isn't very helpful because the `set` operation of a `Lens[S, A]` needs an `S`, so we are reintroducing that dependency on the entire `ZEnv` that were were trying to avoid.

I would like to be able to write something like `Lens[R, Clock]` where `R >: ZEnv <: Clock` but to do that I need to be able to provide a function to go from a `Clock` and and an arbitrary subset of `Clock`, `Console`, `Random`, and `System` to the same subset. Conceptually I should be able to do that by taking the new `Clock` and combining that with the old implementations of the other services but I don't know how to do that when we don't know what the concrete type is.

I feel like I'm not fully grasping your idea here. Any help would be much appreciated.

**Comment by jdegoes** [comment]
@adamgfraser The basic idea behind this solution is that the "final" type of environment is in fact `EnvironmentalEffect#Environment`.

This gives you the ability to modify an environment of unknown type, by using the lens.

So we can write a method that modifies the environment to add a prefix to every log line, for example:

```scala
def addPrefix(prefix: String): ZIO[Logging, Nothing, Unit] = ZIO.accessM[Logging] { logging =>
  EnvironmentalEffect.update(service => new Logging.Service { 
    def log(line: String): UIO[Unit] = service.log(prefix + line)
  })
}
```

**Comment by neko-kai** [comment]
> `def modify[R <: EnvironmentalEffect, A, B](lens: Lens[R#Environment, A])(f: A => (B, A)): ZIO[R, Nothing, B] = ZIO.accessM[R](_.modify(lens)(f))`

Considering that type parameter projection is positively [gone](https://dotty.epfl.ch/docs/reference/dropped-features/type-projection.html) in dotty, I'm not sure how viable it is to pursue long-term...
There is no way to manufacture a value of EnvironmentalEffect here to get a "sound" type prefix `envValue.Environment`, because the R value is supposed to appear way later from inside ZIO

**Comment by adamgfraser** [comment]
In Scala 2 the code above is not compiling:

```scala
package zio

object prototype {

  type Lens[S, A] = (S => A, A => S => S)

  // All environmental effects extend this trait:
  trait EnvironmentalEffect {
    type Environment
    def modify[A, B](lens: Lens[Environment, A])(f: A => (B, A)): UIO[B]

    final def update[A](lens: Lens[Environment, A])(f: A => A): UIO[Unit] =
      modify(lens)(a => ((), f(a)))
  }
  object EnvironmentalEffect {
    def modify[R <: EnvironmentalEffect, A, B](lens: Lens[R#Environment, A])(f: A => (B, A)): ZIO[R, Nothing, B] =
      ZIO.accessM[R](_.modify(lens)(f))
      // type mismatch;
      // found: zio.prototype.Lens[R#Environment,A]
      // required: zio.prototype.Lens[x$1.Environment,?]

    def update[R <: EnvironmentalEffect, A](lens: Lens[R#Environment, A])(f: A => A): ZIO[R, Nothing, Unit] =
      ZIO.accessM[R](_.update(lens)(f))
      // type mismatch;
      // found: zio.prototype.Lens[R#Environment,A]
      // required: zio.prototype.Lens[x$1.Environment,?]
  }

  trait Logging extends EnvironmentalEffect {
    def logging: Lens[Environment, Logging.Service]
  }
  object Logging {
    trait Service {
      def log(line: String): UIO[Unit]
    }
  }
}
```

If I am understanding it right, the issue is that the lens is parameterized on the `Environment` type of `R` but there is no guarantee that the specific instance of `R` we have accessed has the same `Environment` type (e.g. `Environment` could be abstract in `R` and be implemented in the specific instance of `R` as an arbitrary type). I'm not sure how to get around this or if this reflects a more fundamental issue with this encoding.

**Comment by jdegoes** [comment]
Not saying it's a good idea, but we can avoid type projection (in Scala 3) and type inference issues possibly by just making everything polymorphic:

```scala
  trait EnvironmentalEffect[Environment] {
    def modify[A, B](lens: Lens[Environment, A])(f: A => (B, A)): UIO[B]

    final def update[A](lens: Lens[Environment, A])(f: A => A): UIO[Unit] =
      modify(lens)(a => ((), f(a)))
  }
```

Then we have `Logging[R]` which becomes polymorphic in the environment type.

If we're going to say lenses can't work, we should be very sure of that. 😄

**Comment by adamgfraser** [comment]
Superseded by #2594.
