### ISSUE TITLE
Retry should be possible for non-effectful code

### ISSUE THREAD

**Issue by nadenf** [zio/zio#2307]
If have a function:

```
refreshToken: IO[Nothing, Unit]
```

It would be nice to be able to do the following:

```
refreshToken.retry(Schedule.spaced(Duration(refreshInterval, TimeUnit.MILLISECONDS)))
```

In latest RC it is not possible due to the following error message:

```
 This operation only makes sense for effects that can fail.
```

**Comment by adamgfraser** [comment]
Why wouldn't you use `repeat` in this situation?

I don't think `retry` is doing what you want to do, since if it succeeds the first time it will never repeat, regardless of the schedule. If it dies it will not repeat, since `retry` will not recover from that. And since the error type is `Nothing` those are the only possibilities.

On the other hand if you do `repeat` then you will get what I think your intended semantics are of refreshing the token every specified interval.

**Comment by regiskuckaertz** [comment]
`zio.cached(duration)` seems like a combination that comes up time and again. I was thinking about it for auth tokens delivered via SSM with rotation.

**Comment by nadenf** [comment]
Closing this as repeat actually makes a lot more sense.
