### ISSUE TITLE
ZIO Stream: Enable Tests on Dotty

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2318]
Now that we have the test suite for ZIO Core running on Dotty we should try to enable the ZIO Stream test suite as well. We already identified one Dotty specific issue with `ZStream` in #2232 so it okay to mark some tests as `scala2Only` but we should identify all tests that are not passing as Dotty and make sure we have tickets to resolve those issues.

**Comment by laurynasl-wix** [comment]
I did some investigations into enabling the tests, and it seems that there are no issues with the tests or code itself, but there are two issues in dotty `0.21.0-RC1` that are blocking from enabling them now: https://github.com/lampepfl/dotty/issues/7843 (zio.stream.StreamEffect#foldWhileManaged doesn't terminate) and https://github.com/lampepfl/dotty/issues/7840 (problems with type inference)

**Comment by laurynasl-wix** [comment]
One thing I haven't figured out yet is why these tests hang when run without forking.

**Comment by laurynasl-wix** [comment]
Turns out forking was a red herring: the actual issue is with running tests in parallel from sbt. It looks like there's a deadlock with static initializers somewhere (see [thread dump](https://gist.github.com/laurynasl-wix/19267b3d43cc99c173581bb2a1b4c343)), but I couldn't pin it down or create a small reproduction to report to dotty. I see two workarounds for this: replace `val`s in `object`s with `lazy val`s (which would have a negative impact on performance) or run tests sequentially in sbt. It would be great to get to the bottom of this and report to dotty, but I don't know how to go about reproducing a smaller case here

**Comment by adamgfraser** [comment]
Closing as this functionality is already in place.
