### ISSUE TITLE
Add ZIO combinators to accumulate errors and successes

### ISSUE THREAD

**Issue by saraiva132** [zio/zio#2432]
There is a need for combinators that, given a list of effects, accumulate the errors and the successes and return them either possibly in two forms:

` final def collectAllWithErrors[R, E, A](in: Iterable[ZIO[R, E, A]]): ZIO[R, List[E], List[A]]`

` final def collectAllWithErrorsTupled[R, E, A](in: Iterable[ZIO[R, E, A]]): UIO[(List[E], List[A])]`

I need suggestions for the naming though. It is not my forte.

**Comment by alexknvl** [comment]
Perhaps:
```
  def validate[R, E, A, B](it: List[A])(f: A => ZIO[R, E, B]): ZIO[R, NonEmptyList[E], List[B]]
  def validateFirst[A, E, B](list: List[A])(f: A => ZIO[R, E, B]): ZIO[R, List[E], B]
  def validateWithIndices[R, E, A, B](it: List[A])(f: (Int, A) => ZIO[R, E, B]): ZIO[R, NonEmptyList[E], List[B]]

  def partition[R, A, E, B](list: List[A])(f: A => ZIO[R, E, B]): ZIO[R, Nothing, (List[E], List[B])]
```

`validate` is a reference to the standard `Validation` applicative, that has the right `Traverse` instance for this particular use-case
`partition` is a reference to the standard combinator in Scala collections library

**Comment by jdegoes** [comment]
- `partition` => `partitionM`
 - `validate` => `validateM`
 - `validateFirst` => `validateFirstM`
 - ~~`validateWithIndices`~~  (I'd delete this because you can do `zipWithIndex` before calling one of these)
 - `NonEmptyList` => `::`

**Comment by regiskuckaertz** [comment]
I have a hard time understanding the meaning of `validate*`. If they either all succeed or all fail, I guess it makes sense, but if you get something in between where only a few succeed then what happens? A ZIO cannot be both successful and failed at the same time, so we are losing information.

**Comment by saraiva132** [comment]
Thanks for input. After thinking about which ones make sense and which do not. Also based on feedback from john, what about:

 Accumulate failures until it succeeds and returns either accumulated errors or produced value.
`def validateFirst[R, A, E, B](list: List[A])(f: A => Either[E,B]): ZIO[R, List[E], B]`
`def validateFirstM[R, A, E, B](list: List[A])(f: A => ZIO[R, E, B]): ZIO[R, List[E], B]`
`def validateFirsParM[R, A, E, B](list: List[A])(f: A => ZIO[R, E, B]): ZIO[R, List[E], B]`

 Accumulate failures and successes and produces them.
`def partition[R, A, E, B](list: List[A])(f: A => Either[E,B])): ZIO[R, Nothing, (List[E], List[B])]`
`def partitionM[R, A, E, B](list: List[A])(f: A => ZIO[R, E, B]): ZIO[R, Nothing, (List[E], List[B])]`
`def partitionParM[R, A, E, B](list: List[A])(f: A => ZIO[R, E, B]): ZIO[R, Nothing, (List[E], List[B])]`

Validate is a bit tricky, because there is loss of information. Does not look very useful, you would either accumulate at least one error OR return 0 or more successes. 

`def validateM[R, E, A, B](it: List[A])(f: A => ZIO[R, E, B]): ZIO[R, ::[E], List[B]]`

WDYT? @regis-leray @jdegoes @alexknvl

**Comment by saraiva132** [comment]
I am starting to work on this

**Comment by alexknvl** [comment]
@regiskuckaertz @saraiva132 `validateM` is a common pattern, let's say you have a list of items and you go through them and check whether they are all "valid". If any one of them is not "valid", you collect all errors for maximally useful error report. So instead of "item N is bad for this reason", you get "items 1, 3, 17 were bad for these reasons". 

I don't know whether this makes as much sense in the context of IO effects, but when dealing with pure validation (say during json deserialization), that's the number one function I use when I have a list of items. 

Having a method that returns `List[Either[E, A]]` would also be useful. But in the majority of the practical use-cases I would need to do `_.map(_.validate(identity))` right after :)

**Comment by saraiva132** [comment]
@alexknvl In the end I think partition. validate and validateFirst cover all required functionality with, of course, their parallel counterparts. Partition seems to offer what you want in return of List[Either[E, A]] by returning tuple with accumulated errors and successes.

**Comment by regiskuckaertz** [comment]
Yeah, this is definitely useful. I have the exact same case with scanamo where dynamodb may apply some updates and fail at others. The thing is, given how ZIO is defined, I can't see a way around surfacing both errors and successes in the value channel, as otherwise you will lose information.

**Comment by fanf** [comment]
Cool!
Can we get at least a type alias for `::`, I have a feeling no new comers know that `::` is also a class and that is means `NonEmptyList` (or `Cons`, but that's hardly clearer). Even `NEL` is cleared than `::` (because you won't know what it means either, but at least for the following time, you can try to thing that you want a non empty list)

**Comment by saraiva132** [comment]
@fanf Do you know if we have a convention for this kind of type aliases? I do not think ZIO would be a good place to have it in.
