### ISSUE TITLE
Weird results with composed sinks

### ISSUE THREAD

**Issue by iravid** [zio/zio#2455]
```scala
  val bytes: Sink[Nothing, String, String, Long]  =
    ZSink.foldWeighted(0L)((el: String) => el.length, 1024)(
      (bytes, el) => bytes + el.length)

val grouping = 
    ZSink
      .collectAllToMap((el: String) => el.head)
      .filter(_.nonEmpty)

@ ZStream("hello").forever.take(5).run(grouping zip bytes).unsafeRun
res7: (Map[Char, String], Long) = (Map('h' -> "hello"), 0L)

@ ZStream("hello").forever.take(1000).transduce(grouping zipPar bytes).runCollect.unsafeRun
res13: List[(Map[Char, String], Long)] = List((Map('h' -> "hello"), 1020L))
```

**Comment by vasilmkd** [comment]
I managed to reproduce this, it happens regardless of `run` or `transduce`, so it looks to be a bug with `zip`. `zipPar` seems to work as expected.

**Comment by iravid** [comment]
`zipPar` is not working as expected either; note that we should have gotten 5 results for `res13`

**Comment by iravid** [comment]
I think the problem for `res7` is that `zip` is implemented with `flatMap`, which is a cartesian product rather than a pointwise product.

**Comment by vasilmkd** [comment]
Documenting thoughts, haven't dug deeper yet. `grouping` is a `foldLeft` sink which is a sink that always continues, therefore, it never finishes so that it can switch to the `bytes` sink (because of the flatMap implementation of `zip`).

Regarding the `zipPar` case, if I remember correctly, it continues if either of the sinks is willing to continue (which again, `grouping` is more than happy to do, ultimately draining the whole stream and zipping with the first (and only) result of `bytes`).

**Comment by vasilmkd** [comment]
The only thing that I can think of right now that would lead to a more intuitive user experience when `always continuing` sinks are concerned if we somehow encode this information (either in the sink type or in the `cont` method (enumeration?)). If we have that information, `zip` will be able to extract the combined sink as soon as the one that shouldn't continue anymore is done (this is only in the case when we are combining an `always continuing` sink with a "finite" sink).
