### ISSUE TITLE
ZIO Test: Fail fast in `checkM`

### ISSUE THREAD

**Issue by octavz** [zio/zio#2579]
Writing code like this:

```
object Spec
    extends DefaultRunnableSpec(
      spec = suite("Spec")(
        testM("generate") {
          checkM(Gen.anyInt) { u =>
            for {      
            _ <- ZIO.effectTotal(println(u))
            _ <- ZIO.fail(new Exception(s"fail for $u"))
            } yield assertCompletes    
          }
        }))
```

Will execute the `println` multiple times after which it will fail.
I am not sure this is by design or is a bug, however, as an user I was expected that the `println` will run only once and fail fast after `ZIO.fail`

If because repetition it is difficult to handle errors then `checkM` perhaps should require an effect with `Nothing` on error channel, forcing the user to handle it, but this is no ideal since we do want to fail the test in case of something goes wrong.

Also I am not sure if is possible to configure how many values it will generate (wasn't obvious for me) .

**Comment by adamgfraser** [comment]
@octavz Multiple values are being printed in your example because the failing test is being shrunk. Here is an example run. You can see that progressively smaller values are being generated as the test framework searches for an optimal shrink. If you use a generator that does not have shrinking, such as `Gen.fromIterable(List(1))` you will see a single value printed.

You can configure how many values are being generated using `checkN` and `checkNM`. For example `checkN(100)(Gen.anyInt)(myProperty)`.

```
-783686018
-391843009
-195921504
-97960752
-48980376
-24490188
-12245094
-6122547
-3061273
-1530636
-765318
-382659
-191329
-95664
-47832
-23916
-11958
-5979
-2989
-1494
-747
-373
-186
-93
-46
-23
-11
-5
-2
-1
0
```

**Comment by octavz** [comment]
Thank you
