### ISSUE TITLE
ZStream - Close inputStream/outputStream

### ISSUE THREAD

**Issue by regis-leray** [zio/zio#2625]
@jdegoes @iravid  It would be nice to have default behavior to close inputstream/outputstream when calling Stream.fromInputStream / ZSink.fromOutputStream, or even to pass a ZManaged.

`Stream.fromInputStream()`
`ZSink.fromOutputStream()`

It was not obvious the function was not closing it by default.

**Comment by regis-leray** [comment]
i would be pleased to add this feature into zio :)

**Comment by ajaychandran** [comment]
IMO, since these methods do not create the `InputStream`, they should not be responsible for closing it.

Resource cleanup should be tied to acquisition. For the usecase in `SecureFtp`, it makes sense to acquire and close the stream since the stream is not available to the caller. 

PS: In fact, the `InputStream` should be obtained as a `ZManaged` resource. I have used this pattern a lot and it always leads to a leaner and safer API.

**Comment by jdegoes** [comment]
How about this:

```scala
ZStream.fromInputStreamM(is: ZIO[R, IOException, InputStream])
ZSink.fromOutputStreamM(os: ZIO[R, IOException, InputStream])
```

These variants could close the stream, because what it being passed is not an input / output stream, but rather, an effect that _creates_ the input / output stream.

Then Scaladoc can be rewritten to push people toward the safer variants.

Possibly we could have:

```scala
ZStream.fromInputStreamManaged(is: ZManaged[R, IOException, InputStream])
ZSink.fromOutputStreamManaged(os: ZManaged[R, IOException, InputStream])
```

**Comment by ajaychandran** [comment]
Always closing the stream would make the methods unusable for cases where the streams should not be closed. For instance, when streaming from/to standard input/output.

This would not be an issue with the safer variants since resource acquisition and release is performed at call site.
The safer variants can in fact replace the existing methods, thereby removing ambiguity and forcing users to acquire resources safely.

**Comment by iravid** [comment]
I'm 👍 on `ZStream.fromInputStreamM` and `ZStream.fromInputStreamManaged`. Arguably the latter is less justified because it'd be defined as `ZStream.managed(managedIS).flatMap(ZStream.fromInputStream)`, but I wouldn't mind the shortcut.

Ditto for the ZSink OutputStream variants.

**Comment by iravid** [comment]
I would suggest for this issue:
- Add a note to `fromInputStream/fromOutputStream` that these constructors do not close the IS/OS
- Add `ZStream.fromInputStreamM`, `fromInputStreamManaged`

**Comment by regis-leray** [comment]
OKi thanks, i will take care today.
