### ISSUE TITLE
Consider making Promise covariant on E

### ISSUE THREAD

**Issue by mtsokol** [zio/zio#2634]
Hi,

Right now I'm working on actors persistence in zio-actors. I'm trying to abstract message processing from current implementation and ended up with `trait Stateful[..., +E, ...]` with some `Promise[E, ...]` inside. 

Would it be acceptable to make Promise covariant on E so `Promise[+E, A]`? Like in the others types e.g. `IO[+E,+A]`.
Or is my approach not the right one?

**Comment by adamgfraser** [comment]
I don't think we can do that because conceptually a promise is something we can put an E or an A into in addition to getting an E or an A out of so it has to be invariant.

To make it covariant we would first have to deal with the fact that the `AtomicReference` inside the promise is invariant for the same reason. We could deal with that by making the `state` `private[this]`.

But then we still have to handle all these methods like `succeed` that let us put an `E` or an `A` into a promise so now they are in contravariant position. We can try to address this by adding new `E1` and `A1` type parameters but now adding the appropriate type bounds `E1 <: E` and `A1` <: A` is going to put `E` and `A` in contravariant position again. The same problem is going to apply if we try to use implement evidence instead.

We could get around this by defining all of these methods as extension methods, but in addition to the lack of discoverability the extension methods won't be able to access the `state` because we had to make it `private[this]`.

I'm not sure about the contract for the proposed `Stateful` type but I think if it was something that you could put an `E` into in addition to get an `E` out of it would have the same issue. If you are just using the promise as an internal implementation detail then possibly you could make it `private[this]` so it doesn't interfere with the variance of the trait.

**Comment by mtsokol** [comment]
@adamgfraser Thank you for comprehensive explanation! 
Yep, now I see that I had it wrong as it needlessly interfered with traits variance.

Thanks for help!
