### ISSUE TITLE
Should We Remove Traverse and Sequence Method Aliases?

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2649]
The `sequence` and `traverse` method aliases feel like a holdover from a time when we had more traditional, less accessible method names (e.g. `redeem` and `absolve`). In other cases we have just gotten rid of the old names but we have kept these around, which creates a bit of an odd inconsistency. It is also not ideal to have two ways to do the exact same thing. And for readers of a codebase using ZIO it could also be confusing if they see `foreach` used in one place and `traverse` used somewhere else and wonder if or how these are different. Finally, it creates a bit of a maintenance version because every different data type that implements `foreach` should ideally implement `traverse` as an alias or users are going to have a less than ideal experience where sometimes this alias is available and sometimes it is not for arbitrary reasons.

I understand the goal is to provide a more familiar interface for users coming from a functional programming background, but these are going to be more sophisticated users anyway so asking them to learn a new name (especially one that is very logical) doesn't seem like too much to ask.

If there is agreement I will take the ticket.

**Comment by iravid** [comment]
Voting to keep them, not because of `Traverse`, but because of `Future.traverse/sequence`. These parallels helped me teach the library to newcomers in the past.

Not strongly attached to the names and see the benefit of having just one version to maintain, though.

**Comment by ghostdogpr** [comment]
Or maybe we keep them as deprecated to “force” the migration while still being discoverable. But unlike other stuff we deprecated, we keep them a while longer (e.g. until 2.0)?

**Comment by sken77** [comment]
I recently used sequence just because i remember thats how it was called before. so i recommend to keep it

**Comment by jdegoes** [comment]
It's confusing to see code in ZIO itself where both `traverse` and `foreach` are used in the same expression (I saw an example the other day). I expect other people will have that reaction, too—in their own code bases (if we can't enforce consistency internally, it's not gonna happen in corporate code bases).

The argument for "learning via Future" is compelling to me. But overall I feel of the 25% of the market that uses Future regularly, not many of them have reached for `traverse` or `sequence` (I have no doubt some of them had the pain but most likely they "solved" it with `Await.result`, if code bases I have worked on are any indication).

My instinct is to say we should not have multiple ways to do the same thing. Just one way, the ZIO way, and focus that on the biggest possible market that could be a fit for the library.

That said, perhaps a few versions with a @deprecated could work well, as per @ghostdogpr's suggestion. That way no one has to update anything right away, but they're incentivized to do the update eventually (maybe by ZIO 1.2 or something).

**Comment by neko-kai** [comment]
We've had this discussion before. We've already had them deprecated before. We've already had them removed before for quite a few versions. They were already added back after being deprecated and removed due to their popularity, so tbh I think the ship has sailed on this. If anything, we might as well remove `foreach` methods, because no other library has them and the name is misleading because in Scala `foreach` discards results – it ought to have been called `map`, but that's obviously taken.

**Comment by jdegoes** [comment]
@neko-kai Fair criticism, but we've had a chance to live with the decision for a long time and see the effects even in ZIO's own code base (which is mixing both versions in the same expression!).

I'd rather not remove `foreach` and from everything I can see, a supermajority of people new to ZIO and FP use `foreach`, which I think speaks to its success among the target market. 

Additionally, teaching FP for some time, people invariably asked me, "Why is this called traverse / sequence?", whereas they currently never ask that about "collectAll / foreach".

**Comment by jdegoes** [comment]
Basically the world is divided into those who like the FP type classes and can already interact with ZIO through them (Scalaz or Cats), and those who couldn't care less about the FP type classes. Among the latter, it's further divided into those who have used Future traverse/sequence, and those who haven't, the latter being much larger.

It's natural vocal people will complain about the loss of familiarity, but that doesn't mean that it's not the right decision. If anything, I regret having too many FP names in the code base, e.g. `fold`, the underscore notation from Haskell, etc. We can't fix all of them but we can at least stop trying to be all things to all people and just do things the "ZIO way", whatever that ends up being.

**Comment by regiskuckaertz** [comment]
It may be a good idea to clearly state on the site that ZIO is a pure FP library whose primary audience is imperative programmer. Indeed the only one. Just to set expectations.

**Comment by fanf** [comment]
I totally missed that question and for records, I'm adding a note - even if it was already dealt with in the yesterday PR. 

From my point of view, FP has a huge, immense, fabulous advantage above all other paradigm we tried before it: it's building a common vocabulary with concept that are almost immediatly transposable from one language to an other. The corresponding vocabulary may be technical, like in any expert domain where the experts need to define new words for their specific concept and models. But it's just some words to learn, and once you know them, you can explore the deepness behind them. New comers don't have any difficulty to learn them, as it was reapeatdly demonstrated by making students / people from other field start programming with Haskell (or other lang). 

Here, `ZIO` is willingly putting barriers for developpers to have access to a huge base of knowledge, decades of article and blog post and research papers, hidding to them, on purpose, because a hands of people found it was better for them, easy access to that knowledge. 
I'm not sure time to market is an OK price for that. `ZIO` could have been a fabulous way to lift thousands of dev to new hights. 

Also, as @jdegoes said, `ZIO` community is a mix of extremelly knowledgeable FP & category programmers and total newbies in FP, people with imperative prog background or no background at all - and the only one targetted by that choice are the third category. Be careful that by focusing on that category *only*, you don't cut `ZIO` roots in FP excellence, the part that make `ZIO` actually work. 

And finaly, @jdegoes, I respect you on a lot of things, and so I can't let you tell things like that:

> I'd rather not remove foreach and from everything I can see, a supermajority of people new to ZIO and FP use foreach

Of course they are! `foreach` was the only choice for most of the RC, `traverse` is not taught and labelled "hard", etc! How can it be otherwise? 

All that being said: if foreach/etc need to stay, I would be OK with a `ZIO` syntax subpackage which can hold these alias (along with `.succeed` and `.fail`), a package conventionnally forbiden in `ZIO` core projects, but that could be used in project which care about FP concepts - the charge to enforce convention on their side, as it is for everything in all case, as always actually. 
(and it would be MUCH better than deprecated, because deprecation warning are a pain to deal with in scala, and deprecation mean "they will be removed" what I would like not to be the case, if it wasn't clear enought)

**Comment by jdegoes** [comment]
I'm 👍 on `ZIO Syntax` to include a host of things like extensions on iterables, alternative names, etc.  But increasingly I do think ZIO core should provide one opinionated way to do things to make scaling in larger teams easier. Example: `ZLayer` is the way you do environments. It's a highly opinionated change that will make it much easier to adopt ZIO at scale (IMO: we will see, of course).

Some of the "FP" names don't make technical sense either, in my opinion. For example, in Scala we have things like `parSequence`, which is absurd: `sequence` comes from `>>=` (sequencing a bunch of effects) but `parSequence` is actually done in parallel; it's literally a contradiction in terms to say, "let's in parallel do these things in sequence".

**Comment by fanf** [comment]
> Some of the "FP" names don't make technical sense either, in my opinion.

Yes, of course, and `Scala` core lib is not exactly the best example for naming... Actually because of exactly the same reason that you are advocating here. If only @odersky knew that ;)

(and for the record: I respect and I totally agree about enforcing consistancy and opiniated way of doings thing - that is not *at all* contradictory to using a common vocabulary and building up on decades of giant shoulder)

**Comment by jedws** [comment]
boo, creating a bespoke set of names for established concepts (especially in this case core combinators) is an alluring but ultimately flawed exercise as it significantly reduces the ability for the learner to see broader patterns and access primary material on the subject.

I gave a whole talk on why if names matter, then why do people insist on changing them to "easier" names? https://www.youtube.com/watch?v=ZSNg6KNzydQ
