### ISSUE TITLE
Subtle inconsistency between ZManaged#onExit and ZManaged.makeExit

### ISSUE THREAD

**Issue by iravid** [zio/zio#2698]
Signatures:
```scala
def makeExit[R, E, A](
  acquire: ZIO[R, E, A]
)(release: (A, Exit[Any, Any]) => ZIO[R, Nothing, Any]): ZManaged[R, E, A]

def onExit[R1 <: R](cleanup: Exit[E, A] => ZIO[R1, Nothing, Any]): ZManaged[R1, E, A]
```

`makeExit` provides the `release` function with the `Exit` value resulting from `ZManaged#use`. `onExit` provides the `cleanup` function with the `Exit` value resulting from the `acquire` function.

Do we need a version of `onExit` that provides access to the `Exit` value from `ZManaged#use` as well?

@vasilmkd @mschuwalow @adamgfraser

**Comment by vasilmkd** [comment]
I just commented something similar to this in #2682. To me, it comes down to whether we get more expressive power with that combinator. Can't the `Exit` value from `ZManaged#use` be handled on the `ZIO` value of `use` itself?

**Comment by vasilmkd** [comment]
We have to be careful not to create an even bigger inconsistency with `onExit` on streams, if we decide that we are going to offer the stream error `E`, which is a _third_ type of error in that case (one being the `Nothing` on the `acquire` of the scope, and the arbitrary `E1` from `ZManaged#use`.

**Comment by iravid** [comment]
> I just commented something similar to this in #2682. To me, it comes down to whether we get more expressive power with that combinator. Can't the Exit value from ZManaged#use be handled on the ZIO value of use itself?

The usecase here is appending a finalizer to an existing `ZManaged` (in the same way `ZManaged#ensuring` does).

**Comment by vasilmkd** [comment]
If we can be more explicit by doing `managed.use().catch` for handling the `use` error, we should do it that way. If we are appending a finalizer to the `managed` we should be handling the `acquire` error. The finalizer on the `managed` should be unaware of the errors of `use`. We have types, we should use them. Thoughts?

**Comment by iravid** [comment]
Disagree :-)

**Comment by vasilmkd** [comment]
Then I guess we have our answer. 😆

**Comment by iravid** [comment]
Hehe, no, I don't know if the additional version of the combinator is required. I was disagreeing with the notion that `managed.use().catchAll` can replace the usecase here.

The entire premise of `ZManaged` is constructing acquire/release pairs in a manner that is decoupled from the use site. If you accept this premise, then being able to append a finalizer that differentiates between failure/success of the use site (like `makeExit` does!) is a different than catching after using the resource.

**Comment by vasilmkd** [comment]
You are right, that cannot be expressed with `use.catch`. So we should have it as a combinator with `Exit[Any, Any]`.

**Comment by vasilmkd** [comment]
Can we even have a combinator that accepts the `ZManaged` `E` error? I thought no finalizers are executed if the `ZManaged` doesn't enter the scope. I remember explicitly writing tests for this in streams.

**Comment by iravid** [comment]
If creating the reservation fails, no finalizer are executed. If acquire fails, the finalizer is still executed.

**Comment by vasilmkd** [comment]
Here are some ideas that were thrown around in a discussion with @iravid, for posterity:

`onExit` is tied to the `ZManaged` itself and should deal with `Exit[E, A]` (but I need someone to convince me that it is _safe_ to use the `A` in this finalizer, and how it ties to the `release: A => ZIO[R, Nothing, Any]`, especially when we factor in `onExitFirst`.

`onUseExit` is tied to `ZManaged#use` and should deal with `Exit[Any, Any]` due to the unconstrained nature of the error and success values of `ZManaged#use`. (Also `onUseExitFirst`).

We need these combinators on `ZStream` too, but naming them is a bit difficult, as we don't want to assume too much knowledge of internal nomenclature for the end user.

We need a combinator that matches `onUseExit` as outlined above, with `Exit[Any, Any]` and a combinator which matches `onExit` with `Exit[E, Unit]` (an unhandled error thrown by the stream or a successful completion) (some more names include `onLastPull`, `onStreamExit`).

Very interested to hear everyone's thoughts.

**Comment by adamgfraser** [comment]
Closing in light of the introduction of scopes and other API changes.
