### ISSUE TITLE
ZIO#timeout terminates too late

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#2714]
Version: master branch on Jan 21

Try to set a timeout to a task. I expect that the task will complete as soon as timeout expires but it doesn't happen: 

```
object Test extends zio.App {
  override def run(args: List[String]): ZIO[zio.ZEnv, Nothing, Int] = {
    val longTask = Task{
      Thread.sleep(5000)
      "x"
    }

    for {
      start <- zio.clock.nanoTime
      res <- longTask.timeout(Duration.apply(100, TimeUnit.MILLISECONDS)).orDie
      end <- zio.clock.nanoTime
      _ <- zio.console.putStrLn(res.toString)
      _  <- zio.console.putStrLn(((end - start) / 1000000).toString)
    } yield 0
  }
}
```

It prints 

> None
> 5203

**Comment by adamgfraser** [comment]
`Thread.sleep` is a blocking call. To handle blocking call you use to use `blocking(Task(???))` or `effectBlocking(???)`, or one of its variants to properly allocate it to the blocking threadpool and allow the ZIO runtime to properly timeout the effect.

**Comment by simpadjo** [comment]
I tried 

```
val longTask = zio.blocking.effectBlocking{
      Thread.sleep(5000)
      "x"
    }
```
and

```
val longTask = zio.blocking.blocking(Task{
      Thread.sleep(5000)
      "x"
    })
```

Same result :(

**Comment by adamgfraser** [comment]
Can you try `effectBlockingInterrupt` please?

**Comment by simpadjo** [comment]
This one worked, thank you!
Shouldn't it be a default behavior for `ZIO#timeout`?

**Comment by adamgfraser** [comment]
It's funny, we recently changed the behavior regarding this. The issue is that `timeout` interrupts the effect if it does not complete within the specified time, but the interruption effect doesn't return until the effect has been successfully interrupted because we don't want to have resource leaks. 

Previously, `effectBlocking` attempted to interrupt the effect by interrupting the underlying runtime thread, but there is significant overhead associated in doing that which was negatively impacting performance of applications that wanted to run on the blocking thread pool to prevent thread starvation but didn't need interruption. So we just changed it to having `effectBlocking` just move to the blocking thread pool with no interruption logic and `effectBlockingInterrupt` or `effectBlockingCancel` be the tools to add interruption logic on top of that.

**Comment by simpadjo** [comment]
Makes sense. But OTOH current semantic is 
1) astonishing (at least for me)
2) doesn't allow local reasoning about it
Maybe this method deserves an additional parameter `InterruptionMode = WAIT | INTERRUPT | YOLO`

**Comment by jdegoes** [comment]
@simpadjo You can use `timeoutFork` to get the behavior you want.

I'm not sure which one is more common. In general code that cannot be interrupted in an anti-pattern; and using `Thread.sleep` in ZIO is also an anti-pattern.

`timeout` gives you the guarantee it will not return until the loser is killed, which allows avoiding resource explosion; OTOH when used with "uninterruptible" effects, it means it doesn't return right away. The `timeoutFork` combinator lets you explicitly opt-in to doing something that may result in too many background fibers running.

Again, I'm not sure what's the right default here...

**Comment by simpadjo** [comment]
Thank you, exactly what I wanted. Missed this method.
