### ISSUE TITLE
ZIO Test: Delete S parameter?

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2791]
I couldn't find `S` parameter being used. It is "washed away" to `Any` in runners. It's possible with test annotations, users who want to extract information from a test execution can now do so through test annotations, rather than needing a separate type parameter.

Needs investigation.

**Comment by adamgfraser** [comment]
Yes I agree we can delete the `S` type parameter. It is not being used anywhere and removing it would make method signatures shorter, particular for test aspects, and would make a couple of the tests aspects more polymorphic. For example `failure`, and `nonTermination` need to constrain `S` to be `Unit` because we need to have a value that we can put in the success channel. With test annotations we should be able to capture the same information. I will take the ticket.
