### ISSUE TITLE
ZIO#absolve from a fallible effect?

### ISSUE THREAD

**Issue by vasilmkd** [zio/zio#2821]
Is there a reason why ZIO#absolve is available on effects with error type `E` instead of `Nothing`? It seems a bit odd to me, because its inverse, `either` creates an infallible effect.

**Comment by adamgfraser** [comment]
I think just because we can unify it. If I have `ZIO[R, E, Either[E, A]` it is perfectly sensible to take any `E` values in the error channel and any any values in the left side of the either and put them both into the error channel. There is some loss of information there if you do have errors from both sources in where the error originally came from but a lot of more specific combinators do that. Of course in many cases the error channel will have a type of `Nothing` but at least initially I don't see a reason to require it.

**Comment by vasilmkd** [comment]
Thanks. Feel free to close this.
