### ISSUE TITLE
ZIO test: java.lang.InternalError: Malformed class name

### ISSUE THREAD

**Issue by Esardes** [zio/zio#2861]
I think this is the same error as [this](https://github.com/mockito/mockito-scala/issues/117).

I have an exception defined in something similar as
```
sealed trait Exception
object Exception {
  case class MyException() extends Exception
}
```

When I try, in a test, to do `fails(isSubtype[Exception.MyException](anything))`,  I get an internal error
```
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at zio.test.Assertion$.isSubtype(Assertion.scala:527)
```

If I redefine my Exception to be
```
sealed trait Exception
case class MyException() extends Exception
```
and my test to use `fails(isSubtype[MyException](anything))`, it works

**Comment by vasilmkd** [comment]
This is a known Scala on JVM pre JDK 9. https://github.com/scala/bug/issues/2034

Not sure that we can do anything about it.

**Comment by dkarlinsky** [comment]
The assertion should probably catch the exception and fall back to the FQCN.
In one of my projects I had the following code to "safely" get simple class name:
```scala
implicit class ClassOps[T](val clazz: Class[T]) extends AnyVal {
    def simpleNameSafe = {
      try clazz.getSimpleName catch {
        case _: Throwable =>
          val name = clazz.getName.split('$').last
          if(name.length >= 3) name
          else clazz.getName
      }
    }
  }
```
@adamgfraser WDYT?

**Comment by vasilmkd** [comment]
I'm not sure we should be doing this. This is relying too much on the way Scala encodes class names on the JVM. In other instances where this bug has been encountered, we worked around by reorganizing the code structure. I'm against this change.

**Comment by adamgfraser** [comment]
Let’s step back for a minute here. My understanding is the the issue arises from calling getSimpleClassName in Assertion.isSubtype. Notice that we’re not using this method to determine whether the assertion is true (we do a subtype check for that) but just to render the assertion result. So it seems a little silly to blow up on just trying to render something when it doesn’t change whether the test passes or fails. So it does seem like it could be good to have a private getClassName method in Assertion that does a fallback string rendering.

@vasilmkd Does that make sense?

**Comment by vasilmkd** [comment]
In the end, I have no power here, so feel free to disregard my opinion. I linked the relevant scala repository issue in my first comment, there should be enough information there to make a decision.

**Comment by adamgfraser** [comment]
@vasilmkd i don’t want to disregard your opinion, I want us to make the best decision together based on all the information available to us. We’ve got this assertion, at least as I understand it we can always tell whether A is a subtype of B. We want to have some way to render that assertion (doesn’t have to be valid code but has to be informative to the user) and we have this wart in the language that doesn’t seem like it is going to get fixed any time soon. How would you suggest we approach this?

**Comment by vasilmkd** [comment]
Sorry for sounding harsh, but I don't have a problem with you disregarding my opinion. 🤣 

It's not going to be fixed, or rather, it's fixed in JDK 9 and upwards by the JVM developers, not by Scala. I see it as a wart of the virtual machine, not the language, and therefore, to me, it is undefined behavior. For as long as we are running on JDK 8, we should treat all code that causes this exception to be thrown as invalid, and write different code, not write code that expects this error, because I think it sets a dangerous precedent. Again, this is just my opinion.

**Comment by adamgfraser** [comment]
What if we just use `getName` instead of `getSimpleName`?

Also, as I am looking at it I wonder if we need a `Manifest` here instead of a `ClassTag`. For example, the following test passes right now:

```scala
test("isSubtype must fail when supplied value is not subtype of specified type") {
  assert(List("A", "B", "C"))(isSubtype[List[Int]](anything))
},
```

**Comment by adamgfraser** [comment]
Just submitted a PR for this. I took the approach of trying to use the `getSimpleName` and if that fails falling back to `getName`.

@dkarlinsky Thank you for the suggestion. I ended up handling the error a slightly different because I didn't like if the class name was quoted splitting on `$` could lead to only returning a fragment of the class name but I incorporated your basic idea of catching and handling the error.

@vasilmkd Please take a look. I tried to address your concerns.
