### ISSUE TITLE
zio-test's provideLayer is broken

### ISSUE THREAD

**Issue by thesamet** [zio/zio#2895]
I have a test suite that uses `provideLayer`. Since 5f99983b, the tests fail without providing any output:

```
[info] No tests were executed
[error] Error during tests:
[error]         scalapb.zio_grpc.TestServiceSpec
````

**Comment by thesamet** [comment]
Added a minimal example of this issue in this commit https://github.com/thesamet/zio/commit/63b332e623260a153a25d128473e402ca8538c79

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look.

**Comment by adamgfraser** [comment]
Looks like some kind of early initialization issue. If I change to `lazy val layer4` it works. Trying to track down.

**Comment by adamgfraser** [comment]
I looked into this and I actually don't think the issue is related to that PR or even `ZLayer`. I was able to minimize to the following:

```scala
package zio.test

import zio.ZIO

object InitializerSpec extends ZIOBaseSpec {
  import zio.NeedsEnv.needsEnv

  val env = ZIO.unit

  def spec =
    suite("InitializerSpec") {
      test("some test")(assertCompletes)
    }.provideM(env)
}

// java.lang.ExceptionInInitializerError
// Caused by: java.lang.NullPointerException
```

I think the problem is actually related to the way we changed `DefaultRunnableSpec` to be a trait and early initialization issues in Scala. If we define a local value within the spec like `env` above it is fine to use in evaluating tests in the spec itself, but it looks like the members of that value are not yet initialized when we call `provide` or its variants on the spec. If we change `val env` to `lazy val env` that solves the problem. Also if we just inline it `provideM(ZIO.unit)` that is fine. And it is also fine to define a separate object like we used to in RC17 and define the value there.

So obviously there are a bunch of easy immediate solutions mentioned above but it is not great for users to have to think about this stuff. To fix we can make all of these methods on spec lazy. For example:

```scala
// Before
final def provideM[E1 >: E](zio: ZIO[Any, E1, R])(implicit ev: NeedsEnv[R]): Spec[Any, E1, T] =
  provideManaged(zio.toManaged_)

// After
final def provideM[E1 >: E](zio: => ZIO[Any, E1, R])(implicit ev: NeedsEnv[R]): Spec[Any, E1, T] =
  provideManaged(ZManaged.suspend(zio.toManaged_))
```

Unfortunately we have to think about this for a lot of the methods on Spec. Possibly we could write a `Spec.suspend` constructor that we could use to wrap a bunch of these but unfortunately I am not seeing a way to more systematically address this where no one ever has to think about this again in the future.

**Comment by adamgfraser** [comment]
@jdegoes Can you think of anything better to do here?

**Comment by jdegoes** [comment]
@adamgfraser 

A quick analysis of the code suggests That `RunnableSpec.run` may be the problem, because it's accessing the `spec` in building a `val`.

I'd make that `def` and any other `val` a `def` too.

**Comment by adamgfraser** [comment]
@jdegoes You are 100% right. That resolves the problem very cleanly. Thank you!
