### ISSUE TITLE
Schedule.elapsed.whileOutput intersection triggers wrongly

### ISSUE THREAD

**Issue by gaelrenoux** [zio/zio#2957]
Using 1.0.0-RC17

Take the following code:
```scala
    import zio._
    import zio.clock._
    import zio.console._
    import zio.duration._

    val z = for {
      time <- ZIO.accessM[Clock](_.clock.nanoTime)
      _ <- ZIO.accessM[Console](_.console.putStrLn((time / 1000 / 1000 / 1000).toString))
      _ <- ZIO.fail(new Exception("Failed again")).as(0)
    } yield ()
    z.retry(Schedule.spaced(10.second) && Schedule.elapsed.whileOutput(_ < 3.seconds))
```
Here's the output:
```
31756
31766
31776
Fiber failed.
…
```
Ideally, it shouldn't trigger a second attempt (because it would be outside the second schedule), but  I can see where that comes from. The second Schedule still being correct at that point, and it takes the longest delay of the two schedules. What I don't get is how it actually attempts a third time. After the second failure, the second schedule is not applicable anymore, so it should stop here.

It's especially problematic if the first schedule is exponential (instead of a fixed delay), as we end up waiting a lot longer than expected.

**Comment by adamgfraser** [comment]
I will take a look at this.

**Comment by adamgfraser** [comment]
@gaelrenoux I think the current behavior is correct. Here is the analysis:

1. The effect is executed once before being retried with the schedule
2. At that point, the effect of `Schedule.spaced` and `Schedule.elapsed` begin executing. `speed` sleeps for 10 seconds and then returns `1` while `elapsed` immediately returns with a close to 0L delay. The `whileOutput` operator processes immediately after the `elapsed` effect returns and indicates to continue since the elapsed time is less than 3 seconds.
3. The intersection waits for both composed effects to complete, which occurs after ten seconds. At this point the schedule attempts to perform the original effect a second time, which fails.
4. The schedule then checks with the two underlying schedules and both of them say continue, as discussed in (2) above, so the `spaced` and `delayed` effects begin executing again, and then when they return after another 10 seconds we attempt the effect for a third time.

That still leaves the question of how you do what you want to do, which as I understand it is putting an overall time limit on how long you are willing to spend repeating this effect. You can do this with something like:

```scala
zio.retry(Schedule.spaced(3.seconds)).timeout(10.seconds)
```

Hope this helps!

**Comment by gaelrenoux** [comment]
I'm not sure I get it here. After the second failure (point 4), Schedule.elapsed should evaluates to roughly 10 seconds, which means Schedule.elapsed.whileOutput(_ < 3.seconds) should decide to halt. Then the intersection should halt as well.

Thanks for the workaround by the way, it's probably better than what I was doing (fails faster). The doc explicitly offer the intersected schedules though (last entry here: https://zio.dev/docs/datatypes/datatypes_schedule#schedule-combinators), a warning there could be useful.

**Comment by adamgfraser** [comment]
@gaelrenoux The problem is that when we combine two schedules the effects of each schedule are evaluated in parallel. `Schedule.elapsed` returns immediately with the elapsed time each time it recurs, it has no way to "wait" for the other schedule to evaluate. So `elapsed` returns roughly 0 seconds and indicated to continue back at point 2, and then at point 4 when we check with both schedules they both so to continue so we continue.

Good point about the documentation. I will submit a PR to update that.

**Comment by jdegoes** [comment]
Documentation fixed!
