### ISSUE TITLE
ZIO.AccessMPartiallyApplied#apply should allow narrowing the environment

### ISSUE THREAD

**Issue by iravid** [zio/zio#2973]
```scala
  final class AccessMPartiallyApplied[R](private val dummy: Boolean = true) extends AnyVal {
    def apply[E, A](f: R => ZIO[R, E, A]): ZIO[R, E, A] =
      new ZIO.Read(f)
  }
```

`apply` here is unnecessarily restricting `R` in the effect returned from `f`. Should be `[R1 <: R, E, A](f: R => ZIO[R1, E, A]): ZIO[R1, E, A]`.

Same probably holds re `AccessPartiallyApplied`.

**Comment by adamgfraser** [comment]
You’re right. I will fix.

**Comment by iravid** [comment]
Thanks ❤️

**Comment by adamgfraser** [comment]
So the disadvantage of this is it makes type inference significantly worse. For example, the code below no longer compiles:

```scala
def property(prop: => String): ZIO[System, Throwable, Option[String]] =
  ZIO.accessM(_.get property prop)
```

Previously when the `R` type was fixed the compiler could infer that since the `R` in the return type is `System`, the `R` in `accessM` is also `System`. With this change it can't do that and complains that the parameter type for the function is missing.

We can add the type annotations internally and conceptually you are right we should be able to narrow it but seems like a significant cost to lose that inference. Not sure what your exact use case is but you can achieve what you want by specifying `R1` instead of `R` in `accessM`.

**Comment by iravid** [comment]
Ah. My usecase is something like this:
```
trait Module {
  val module: Module.Service
}

object Module {
  trait Service {
    def method: URIO[Blocking, Unit]
  }

  def method: ZIO[Module with Blocking, Nothing, Unit] = 
    ZIO.accessM[Module](_.module.method)
}
```

I'd like to write `ZIO.accessM[Module]`, not `ZIO.accessM[Module with Blocking]`.

**Comment by adamgfraser** [comment]
Right. You could always do something like `ZIO.environment[Module].flatMap(_.module.method)` but that is not as nice. Well we can add. A bit of a shame to have to specify types for the simple cases but maybe that is to be expected when accessing the environment. We could potentially have separate methods that give you the flexibility with worse type inference but that seems like too many ways to do things.

**Comment by iravid** [comment]
I actually never thought I could do away with `R` entirely on `accessM`. It's only for very simple cases (like the System accessors) that it works; anything more complex (e.g. accessM followed by another combinator) would break down immediately and require `R`.

I think it's reasonable for `R` to be required there.

**Comment by adamgfraser** [comment]
I agree.

**Comment by iravid** [comment]
In the meantime, I took advantage of this situation and just rewrote my accessors as
```
def method: ZIO[Module with Blocking, Nothing, Unit] = 
    ZIO.accessM(_.module.method)
```

:-)

Maybe we should wait for some other opinions.

For writing accessors, the current situation is probably fine. `ZIO.accessM` as a general utility probably could be better off with allowing narrowing.

**Comment by adamgfraser** [comment]
Nice! Sounds good.

**Comment by iravid** [comment]
Closing this one. I think it's fine as-is.
