### ISSUE TITLE
ZIO Core: ZLayer.fromServicesMany should be removed

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3038]
It is confusing what the difference is between ZLayer.fromServices and ZLayer.fromServicesMany is and when you should use one or the other.

Would be good to consider removing ZLayer.fromServicesMany entirely.

**Comment by adamgfraser** [comment]
I don't think we can remove these methods. The reason for the distinction between these variants and the normal variants is the `fromServices` allows you to build a layer that outputs a single service (e.g. `ZLayer[A, Nothing, B]`). But if you want to build a layer that outputs more than one service (e.g. `ZLayer[A, Nothing, B with C]`) you need the `Many` variant, hence the name. This is not that common because most of the time we can build layers that output single services and then combine them together but sometimes we need this power.

I will think about how we can make this distinction clearer and open to feedback from others.

**Comment by jdegoes** [comment]
Possibly better Scaladoc would help resolve the issue, guiding users toward the "single service" variants unless they know what they are doing.

**Comment by adamgfraser** [comment]
Yes, I will work on it.
