### ISSUE TITLE
Type inference when creating ZLayer from a subtype

### ISSUE THREAD

**Issue by octavz** [zio/zio#3061]
```
import zio._

object Main extends App {
  type Module = Has[Module.Service]
  object Module {
    trait Service {
      def doSomething(): Task[Unit]
    } 
    def doSomething() = ZIO.accessM[Module](_.get.doSomething)
    trait ModuleService extends Module.Service {
      override def doSomething() = Task(println("Something"))
    }
    //val live: ZLayer[Any, Nothing, Module] = ZLayer.succeed(new ModuleService{}) //this works   
    val live = ZLayer.succeed(new ModuleService{}) //this doesn't work needs to be explicit 
  }
  override def run(args: List[String]) = {
    Module.doSomething().orDie.provideLayer(Module.live).as(1)
  }
}
```

looked into it a bit and seems that `Has[A]` can be made `Has[+A]` and if I didn't do it wrong seems to fix the issue, given some `asInstanceOf` are added here and there, I tried it and tests seem to pass. I can show the code in a PR.

**Comment by adamgfraser** [comment]
@octavz `Has` is intentionally invariant. We cannot make `Has` covariant because then composing two effects that require `Has[A]` and `Has[B]` would return a `Has[A with B]` instead of a `Has[A] with Has[B]` and we cannot construct an `A with B` generically given an `A` and a `B` without macros.

In your situation you can just specify the type or use a constructor for your service that returns the super type.

**Comment by octavz** [comment]
seems is not possible
