### ISSUE TITLE
Managed released immediately when Layer is constructed - before tests has run

### ISSUE THREAD

**Issue by xkrillex** [zio/zio#3087]
There seems to be an issue where the Managed is released immediately when the Layer has been constructed, before the tests has started:

```
def makeDbContext: Managed[Throwable, DbContext] = {
  Managed.make[Throwable, Database] {
    // ensures schema, runs db migration and constructs dbContext
  } { db => 
    // drops schema
  }
}

def live: ZLayer[Blocking, Throwable, Database] = {
  ZLayer.fromServiceManyManaged { blocking => 
    for {
      dbContext <- makeDbContext
      repo1 <- Repo1.live(dbContext, blocking)
      repo2 <- Repo2.live(dbContext, blocking)
    } yield Has.allOf[Repo1.Service, Repo2.Service](repo1, repo2)
  }
}
```

Experienced this when providing the ZLayer to a suite with `provideSomeLayerShared`

**Comment by jdegoes** [comment]
Could be related to `zipPar`.

**Comment by dhpiggott** [comment]
I'm seeing the same sort of issue with 1.0.0-RC18-2. Was https://github.com/zio/zio/pull/3101 expected to mitigate this in 1.0.0-RC18-2?

**Comment by adamgfraser** [comment]
@dhpiggott Do you have a small example to reproduce? This seems to be working as expected:

```scala
package zio

import zio.test._
import zio.test.environment.TestEnvironment

object ExampleSpec extends DefaultRunnableSpec {

  val layer = ZLayer.fromAcquireRelease(console.putStrLn("Acquiring"))(_ => console.putStrLn("Releasing"))

  def spec = suite("ExampleSpec")(
    testM("test") {
      for {
        _ <- ZIO.environment[Has[Unit]]
        _ <- console.putStrLn("Testing")
      } yield assertCompletes
    }
  ).provideSomeLayerShared[TestEnvironment](layer)
}
```

**Comment by dhpiggott** [comment]
@adamgfraser I didn't have a small example - just a large one - but had been going to prepare and share one in the next day or so. I see you've now fixed it though. Thank you!

**Comment by adamgfraser** [comment]
@dhpiggott Yes, the issue was only in nested suites which is why it didn't show up in my simple example. Sorry it took us a little while to get this one resolved!

**Comment by dhpiggott** [comment]
No worries - thank you for such a great library! To provide a little more context, we have an integration test suite which is provided with a shared layer. That layer is expensive to create (think multiple Docker containers expensive) - hence making it be shared. The number of tests and the wall-time taken by each is such that running them in parallel is highly desirable (it's the ability to do that so elegantly which initially prompted us to convert them to ZIO Test - where before they were written as a Gatling Functional Spec).

To workaround this we've temporarily switched to using `provideLayer` and `TestAspect.parallelN`(with a parallelisation factor of 2 - such that we approach but don't exceed the CPU and memory available on a single machine) instead of `provideLayer` and `TestAspect.parallel`. The suite now takes ~10 minutes rather than < 2 minutes, but we're going to take the hit in the short term so we can proceed with upgrading to 1.0.0-RC18-2 and avoid the conversion PRs accumulating conflicts.
