### ISSUE TITLE
ZIO Core: Add isError/isSuccess

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3219]
Feel free to close this if it doesn't make sense but I seem to be commonly writing:
```
success <- someMethod().option.map(_.isDefined)
```

Ideally it would be nice to have something like:
```
success <- someMethod().isSuccess
```

**Comment by adamgfraser** [comment]
@nadenf Can you say a little more about your use case? We have found that these use cases are almost always better handled with a combinator such as `foldM` because you want to know if an effect failed or succeeded and then you want to do something with the success or failure. In your example you can determine whether the effect succeeded but you will have to evaluate the effect again (which may return a different result unless it was memoized) to actually do anything with it.

Conceptually you can replace:

```scala
someMethod.isSuccess.flatMap { success =>
  if (success) onSuccess else onFailure
}
```

with:

```scala
someMethod.foldM(onFailure, onSuccess)
````

**Comment by nadenf** [comment]
@adamgfraser .. Not interested in the actual response just whether it returned successful.

For example:

```scala
for {
  userExists <- getUser.isSuccess
} yield userExists
```
