### ISSUE TITLE
Provide envOr*, propertyOr* overloads for zio.system

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio#3312]
These are useful overloads that exist in the standard library's `scala.util.Properties` to provide a fallback value (or a failure). It would be useful to have them in zio.system.

**Comment by adamgfraser** [comment]
I will add these.

**Comment by adamgfraser** [comment]
@hmemcpy It seems like the `OrElse` and `orSome` variants make sense but `orNone` doesn't because the value returned by the ZIO version of these combinators is already an optional value. Does that make sense to you?

These can be implemented very straightforwardly in terms of existing combinators as `env.map(_.orElse(option))` or `env.map(_.getOrElse(fallback))` but I can see the value in having these convenience methods if you are working with system properties.

**Comment by hmemcpy** [comment]
Thanks Adam! Yeah, I agree orNone isn't very helpful. I was just poring over some code to ZIO and wasn't sure how to best provide a fallback value.

**Comment by adamgfraser** [comment]
Yeah, using `map` and the normal `Option` combinators or some of the option combinators on ZIO is the best way to do it right now. Like you could do `env(variable).get.orElseSucceed(fallback)`. And this is in some ways more composition if you want to chain multiple fallbacks. But agree it is nice to have at least the same functionality as the standard library on the interface.

**Comment by hmemcpy** [comment]
😘
