### ISSUE TITLE
`currentDateTime` in tests doesn't change unless you call `sleep`

### ISSUE THREAD

**Issue by davidpdrsn** [zio/zio#3381]
I'm having trouble understanding how to set/change the time in tests. It seems to me that calling `TestClock.adjust` doesn't have any impact on `currentDateTime` _unless_ you call `sleep` first.

In this code the first test passes while the second fails. The only difference is the fact that the first one calls `sleep` whereas the second one doesn't.

```scala
object WhatIsTimeSpec extends DefaultRunnableSpec {
  val spec = suite("time")(
    testM("with calling sleep") {
      for {
        time1 <- currentDateTime
        _ <- adjust(1.millis)
        _ <- sleep(1.millis)
        time2 <- currentDateTime
      } yield {
        assert(time1)(not(equalTo(time2)))
      }
    },
    testM("without calling sleep") {
      for {
        time1 <- currentDateTime
        _ <- adjust(1.millis)
        time2 <- currentDateTime
      } yield {
        assert(time1)(not(equalTo(time2)))
      }
    }
  )
}
```

Is this intentional or a bug of some kind?

I discovered this while working on code that schedules jobs via postgres and therefore relies on `currentDateTime` rather than ZIO's built-in scheduling APIs.

**Comment by adamgfraser** [comment]
@davidpdrsn This is intentional. The issue is that `currentDateTime` needs to reflect the amount of time that sleeps have occurred on that fiber for more complex effects that access the time to work correctly. For example, in a `Schedule`, the schedule may access the current time as part of determining the next interval for the schedule. If we have something like `Schedule.fixed(1.second)` and then to `TestClock.adjust(10.seconds)`, we would expect the schedule to run 10 times. But for that to happen after each adjustment the Schedule needs to see the amount of time that has passed so far (e.g. 1 second, 2 seconds, etc...), not the full ten seconds or it leads to corruption in the internal state of the schedule.

We recently added a combinator `advance` that does the adjustment and the sleep together for this use case and also updated the documentation for this, but unfortunately the documentation only gets published when we do a release.

**Comment by davidpdrsn** [comment]
Alright thanks. I'll give that a shot.

**Comment by mleclercq** [comment]
I faced the same problem following the documentation at https://zio.dev/docs/howto/howto_test_effects#testing-clock

The first example in the documentation doesn't work. I didn't try the others

**Comment by adamgfraser** [comment]
@mleclercq It has been updated here: https://github.com/zio/zio/blob/master/docs/howto/test_effects.md but unfortunately changes don't get published until we do a release.
