### ISSUE TITLE
Bug in nested parallel operations ?

### ISSUE THREAD

**Issue by chikei** [zio/zio#3429]
```scala
val op = random.nextInt.tap(s => console.putStrLn(s"random: $s"))
val col = ZIO.collectAllPar(List(op, op, op)).tap(s => console.putStrLn(s"List: $s"))
val zip = col.zipPar(col).tap(s => console.putStrLn(s"Lists $s"))
val prog = zip.map(t => t._1 == t._2)
Runtime.default.unsafeRun(prog.provideLayer(ZEnv.live))
```

Sometimes it will produce 6 different random values but two lists from zip are identical.

**Comment by adamgfraser** [comment]
Yes, looking into it now.

I don't know if that is necessarily the best example because it could be related to `Random` but I can replicate it even using a `Ref` which should definitely work:

```scala
import zio._

object ReproduceZipParIssue extends App {
  def run(args: List[String]): ZIO[zio.ZEnv, Nothing, Int] = {
    for {
      counter <- Ref.make(0)
      op = counter.getAndUpdate(_ + 1)
      ops3 = ZIO.collectAllPar(List(op, op, op))
      ops6 = ops3.zipPar(ops3)
      res <- ops6
      finalCount <- counter.get
      _ <- console.putStrLn("" + res)
      _ <- console.putStrLn(s"count=$finalCount")
    } yield 0
  }
}
```

At least for me this always produces two identical lists. It appears that the issue can be traced to the race implementation in `FiberContext` [here](https://github.com/zio/zio/blob/428ceb453a543bd3147dea21e5d4e882fc0c904b/core/shared/src/main/scala/zio/internal/FiberContext.scala#L225). We create two different fibers with different fiber IDs and both effects are executed, but debugging statements show that both fibers produce the same result. I think it may not be safe to use `fork` from `FiberContext` here. It is the only place that it is used outside the `Fork` case in the main run loop.

@jdegoes Would appreciate any guidance on this one.
