### ISSUE TITLE
Add ZStream.fromFile

### ISSUE THREAD

**Issue by iravid** [zio/zio#3646]
Signature TBD. Open to suggestions.

This should use Java NIO and support:
- reading complete file
- reading range
- tailing the file

Specifying the desired chunk size for every read operation should also be supported.

The returned stream should be a stream of bytes that opens the file, emits the bytes and closes the file when the stream ends.

**Comment by luis3m** [comment]
@iravid I would like to give this one a try but can't promise a solution as I'm not familiar with NIO. Anyway, I'm wondering how the tailing part would work, tail the file for as long the stream is open? Would that be a separate function?

I would also need clarification about reading range if possible :)

**Comment by iravid** [comment]
@luis3m Could be nice to unify the signatures with a `ReadMode = Complete | Range(Long, Long) | Tail` config

**Comment by mtjon** [comment]
@iravid Are you still working on this since merging the initial 'complete file' version in #3697 ?

I would be interested in picking this up if noone is working on it.

Question: 
I see you use `nio.FileChannel` in your complete file implementation. What's the intent for the partial reader? Should the range refer to a startpoint and length in the stream or a line range in the file?
Should the other variants also work based on FileChannels or would the `Files` class from NIO be OK to use?

**Comment by iravid** [comment]
Hey @mtjon, I'm not working on the other variants currently. If @luis3m doesn't mind it's a great ticket to work on.

For the range option, it's an offset and length. All the variants should re-use the same filechannel for efficiency rather than use `Files` which would open/close the file on every pull.

**Comment by luis3m** [comment]
@mtjon feel free to take this one :)

**Comment by mtjon** [comment]
Hadn't replied yet, but I'm on it (in my off hours).  ✌️

**Comment by ogresto** [comment]
@mtjon is it in progress?

**Comment by mtjon** [comment]
@ogresto got caught up in a project and honestly kind of forgot about it. I'd like to take a look at it properly soon. But if you think you know how to solve it, feel free to take the issue from me.

**Comment by cherkaskyb** [comment]
@iravid @ogresto looking for my first contribution, can I have a crack at this one?

**Comment by adamgfraser** [comment]
Closing as this has already been implemented.
