### ISSUE TITLE
Consider Deleting Type Alias Companion Objects

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3721]
We currently have companion objects for `UIO`, `Task`, `IO`, `URIO`, `RIO`, and `STM` that alias the methods on `ZIO` and `ZSTM` with more specific type signatures. There is a non-trivial amount of work here in duplicating method signatures and risk of incorrect type signatures.

We should consider moving to an encoding similar to what we currently do with Managed:

```scala
type IO[+E, +A]  = ZIO[R, E, A]
val IO: ZIO.type = ZIO
```

This will let us delete a bunch of code and ensure that all methods available on the ZIO companion object are available on the other companion objects. We lose a little here in that now you could do something like `UIO.fail("fail")` so we would be giving up the guarantee that type alias companion object methods always return the more specific type, but this is already something we don't consistently honor when we use partial type application and is easy to lose when we use any combinators with a value. The type would also still correctly reflect the environmental requirements and possible errors and this would make our treatment of various type aliases consistent.

**Comment by iravid** [comment]
Yes please 👍🏻

**Comment by adamgfraser** [comment]
I will do this.

**Comment by adamgfraser** [comment]
So the one area where this doesn't work is with the `apply` methods where `apply` on types that can fail is `effect` whereas on effects that can't fail is `effectTotal`. We could potentially address by moving all the ZIO static methods to a trait that we extended in each companion object and then implementing that methods separately.

**Comment by neko-kai** [comment]
@adamgfraser That's very similar to how it was before companion objects were duplicated out (to allow for less type parameters & avoid the type members that restricted the range of valid R and E parameters for each ZIO type creeping up in type signatures)

**Comment by adamgfraser** [comment]
@neko-kai Yes. Right now I am thinking we would do it without the additional type parameters to restrict the valid range of outputs. What do you think? This seems like an improvement but I know we did something similar in the past so wary about going in circles without taking advantage of the learnings from the past.

**Comment by neko-kai** [comment]
@adamgfraser I'm fairly ambivalent, I think @jdegoes would have an opinion on this since I think he initiated both previous strategies.
One thing I might add is that it may be possible to avoid traits for exclusion of methods, and overload `def` & `val` in package object -
```scala
val RIO: ZIO.type = ZIO
def RIO[A](effect: => A): RIO[Any, A]
```
That's legal

**Comment by jdegoes** [comment]
The real problem is that it forces you to specify types that do not always infer (e.g. `Any` for `R`, etc.). Right now, the companion objects only require the used types, so they have much better inference for the specialized use cases.

A second issue is that you might call `UIO.bracket` or something, expecting to get back something of type `UIO`, and are surprised when you cannot assign the result to `UIO`.

I suppose the pros and cons should be summarized, and also broken down by _library maintainer_ versus _end user_.

**Comment by ghostdogpr** [comment]
Feels pity to remove it, especially after the efforts it took to create it. Didn't we already do the hardest part? It doesn't seem too hard to add it for new methods now. I remember when it landed, I was able to remove a lot of `Any, Nothing` or `Any, Throwable` from my code.

I was actually wishing it would be there on `ZLayer` since I have some calls to `ZLayer.fromServicesM` that are very long and would benefit from it 😄 But I understand the pain it would be to add and maintain it. As John says, depends where we put the focus between maintainer and user experience.

By the way, partial type application is great for inference but not for discoverability, I've seen quite a few people confused by seeing a signature like `ZIO.BracketAcquire_[R1, E1]`

**Comment by adamgfraser** [comment]
Yes, I will put together a list of the pros and cons but I am leaning in that direction as well.

You are right about the partially applied types. Unfortunately in those cases I think there generally isn't a way to have the types correctly infer without it, but it can create an issue in both discoverability and error messages.

**Comment by adamgfraser** [comment]
So I think the advantages and disadvantages are:

**Alias Methods**

Contributors:
(-) Have to add additional aliases when implementing any new method on ZIO companion object (though most of the work already done that this point)
(-) Additional review to make sure type parameters correctly specified in aliases
End Users:
(+) Better type inference
(+) Some static guarantee that type conforms to expected type (e.g. can't do `UIO.fail("fail")`)
(-) Guarantee that type conforms to expected type is not honored with partial application
(-) Inconsistency in when companion object is available (always for ZIO, for STM but not other ZSTM aliases, previously for Managed and Stream but not anymore)

**Alias Objects**

Contributors:
(+) No additional work required

End Users:
(+) Companion object available for types that it does not currently exist for (e.g. `USTM.succeed(1)` works)
(-) No static guarantee that type conforms to expected type
(-) More type parameters to specify if parameters can't be inferred

Overall given the focus on user experience I think we should keep the type alias companion objects. Not sure whether we should bring back the ones we had previously deleted for `Managed`, `Sink`, and `Stream`. One idea is whenever we don't create separate companion objects for type aliases should we at least alias the companion objects (e.g. `val Layer: Layer.type = ZLayer` since I don't think we are going to implement a separate `Layer` object).

**Comment by adamgfraser** [comment]
Closing given that it does seem like on balance the existing approach provides a better use experience.
