### ISSUE TITLE
Add ZSink.toQueue

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3735]
There is `ZStream#into` operator that allows for writing elements of a stream into a queue.
Would be better to have this functionality as a `ZSink` instead because sinks can be composed.

This sink could also take a boolean parameter like `shutdownWhenFinished` to decide if the queue should be terminated after the stream is done.

I also feel that it's possible to remove `Take` from the queue type w/o loss of functionality.

**Comment by arnoldlacko** [comment]
I've been looking into this one and I'm struggling to understand the reasoning behind `shutdownWhenFinished`, as it seems that shutting down a queue will interrupt all fibers that try to take elements from the queue, which if I understand correctly would make it uncertain whether consumers taking from the queue would be able to consume all elements before they get interrupted due to the stream being completed.
Looking into `Stream#into`, it seems that relying on queues of type `Take` does not lead to the same problem, as instead of the queue being shut down, stream completion is signalled by enqueuing `Take.end`.
I've considered using a similar approach to implement this as a sink (restricting the queue type to `Take`), but it seems that the same behaviour as with `ZStream#into` would not be achievable, because `ZStream#into` handles stream failures by enqueuing `Take.halt`, while a sink will not be pushed in case of a failure.
I would be very interested to hear your thoughts @simpadjo and @iravid. It's quite possible that I've missed something obvious here, please correct me if that is the case. 🙂

**Comment by adamgfraser** [comment]
@arnoldlacko I think you can just implement it like this, following the convention from `ZStream` for just having a separate constructor for the `withShutdown` variant.:

```scala
def toQueue[R, E, I](queue: ZQueue[R, Nothing, E, Any, I, Any]): ZSink[R, E, I, Nothing, Unit] =
  foreachChunk(queue.offerAll)

def toQueueWithShutdown[R, E, I](queue: ZQueue[R, Nothing, E, Any, I, Any]): ZSink[R, E, I, Nothing, Unit] =
  ZSink(ZManaged.make(ZIO.succeedNow(queue))(_.shutdown).map(toQueue[R, E, I]).flatMap(_.push))
```

The `withShutdown` variant makes sense because sometimes our whole program is the stream and we want to tell downstream consumers that there is nothing else for them to do when the stream is over.

For example:

```scala
val stream = ZStream(1, 2, 3, 4).tap(_ => ZIO.sleep(1.second))
for {
  queue <- Queue.unbounded[Int]
  _     <- stream.run(ZSink.toQueueWithShutdown(queue)).fork
  fiber <- queue.take.flatMap(value => UIO(println(value))).forever.fork
  _     <- fiber.await
} yield ()
```

The stream uses `toQueueWithShutdown` to signal that it is done. You are right that in general there is a risk that the queue will be interrupted before the downstream consumers have consumed all the queue elements but that may be judged to be okay or handled in other ways. For example in the above the stream waits another second after emitting the last element to terminate, giving the consumer fiber plenty of time to take it from the queue and print it to the console.

**Comment by arnoldlacko** [comment]
@adamgfraser I'm amazed by how cool that implementation is, as (if I understand correctly) it will guarantee shutdown even if the stream fails. I see your point about the consumer interruption being fine in some cases. I will add the relevant tests and submit a PR with the suggested implementation. Thanks @adamgfraser!

**Comment by adamgfraser** [comment]
@arnoldlacko Awesome! Yeah, especially with the ongoing work on refactoring the underlying implementation of the stream the more we can do in terms of existing operators the better and they also handle some potentially complex logic for us.
