### ISSUE TITLE
Hook scalafmt with compile.

### ISSUE THREAD

**Issue by hepin1989** [zio/zio#382]
Make it easier for contribution:)
Currently, need to run scalafmt manually.

**Comment by hepin1989** [comment]
Akka make it default, I think that's ok for code consistency

**Comment by jdegoes** [comment]
I'm Ok for trying it on compile and seeing if users complaint. 😄

**Comment by NeQuissimus** [comment]
We should then have some sort of "verify" that the CI runs and which does not call `scalafmt`.
Otherwise the CI may format upon build and not be able to contribute those changes back. That should not happen.

At work, we have a task that does all kinds of "linting" (incl. scalafmt) and one that is meant for verification by CI.

I would not hook scalafmt into `compile` directly

**Comment by harjitdotsingh** [comment]
Is this fixed ?

**Comment by NeQuissimus** [comment]
Yes
