### ISSUE TITLE
Allow ZManaged finalizer to throw errors

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3938]
ZManaged finalizers are not allowed to throw exceptions:

`def make[R, R1 <: R, E, A](acquire: ZIO[R, E, A])(release: A => ZIO[R1, Nothing, Any]): ZManaged[R1, E, A]`

Alternatively it could allow to throw an error of type `E`:

`def make[R, R1 <: R, E, A](acquire: ZIO[R, E, A])(release: A => ZIO[R1, E, Any]): ZManaged[R1, E, A]`

Motivation of the current behavior: otherwise a user couldn't distinguish between an error from `use` and an error from finalization.

Counterarguments:
1) In real world finalizers usually can throw errors
2) When they do throw, an error is considered a defect. But in fact it's not a defect but rather an expected error.
3) Often proper finalization is a part of business logic.
E.g. when we write to an `OutputStream`, the bytes are written only when `close` succeeded. 
4) I'd say that a user doesn't care about where the error came from. 
If it really cares, it's quite easy to make `use` unexceptional: `ZManaged.make(acquire)(release)(res => myTask(res).either)`. It's much easier than to catch finalization error under the current encoding.
5) Even in zio codebase there is a code that can create defect:

```
ZManaged: 
def fromAutoCloseable[R, E, A <: AutoCloseable](fa: ZIO[R, E, A]): ZManaged[R, E, A] =
    make(fa)(a => UIO(a.close()))
```

**Comment by adrianfilip** [comment]
You raise an interesting point. 
But wouldn't a failed release imply that there is a leak? That would make ZManaged unsafe by itself because you would then have to deal with the failure somehow.
Maybe a better approach is to make sure that what is in release never fails and if it does you kill the fiber so you "force release" the resource anyway.

**Comment by simpadjo** [comment]
There are 2 kinds of leaks: app-level leaks (stale objects) and system-level leaks (e.g. stale database entries). 
Killing the fiber won't help against the second.
If a finalizer doesn't do any IO, it should be unexceptional, I think.  

But yeah, it's nuanced.

**Comment by s4s0l** [comment]
I have like 2 days of experience with zio so sorry if i don't actually understand what I'm talking about. Case which is quite important in my opinion are database commit / rollback operations. If I understand zio correctly, this issue implicitly refers to all `acquireRelease` and `addFinalizer` operations. Here https://github.com/zio/zio-sql/blob/b63708a35fb27eeab7a7edf4e320809fce77b5fc/jdbc/src/main/scala/zio/sql/SqlDriverLiveModule.scala#L133-L133 is an example of problem I'm seeing. I think lack of ability of 'release' to communicate error to caller is introducing quite huge problem. If code that uses such transaction runs fine, but the commit will fail (communication with db, but perhaps there is some combination of isolation levels and database implementations that can fail during commit due to some constraint validation, or simply due to way db actually handles commits), it seems to me that its quite possible to fail to commit and return  something like HTTP 200 from application. And there is nothing that can be done to work around it, other than explicitly calling commit, or am I wrong?

**Comment by adamgfraser** [comment]
@s4s0l Hi! Finalizers can fail but that failure can't be expressed as part of the typed error channel because that represents the error which the use of the resource can fail with. So when you have a finalizer that can fail you have a choice. Either you can run the finalizer on a "best efforts" basis and continue even if the finalizer fails using an operator such as `ignore` or you convert the failure to a defect and propagate it back to the caller using an operator such as `orDie`. So you definitely can propagate finalizer failures you just don't do so through the typed error channel.
