### ISSUE TITLE
Add equalWith combinator to Cause

### ISSUE THREAD

**Issue by jaliss** [zio/zio#4012]
Adding an equalWith combinator on Cause will allow us to properly implement an `Equal` instance on Prelude.

**Comment by jaliss** [comment]
I'll work on this.

**Comment by adamgfraser** [comment]
Great! There is a decent amount of logic in `Cause` to make sure the different laws about how causes are supposed to be equivalent hold (e.g. `Cause.Both(a, b) <-> Cause.both(b, a)`). I think what you are going to want to do is parameterize all those on an equality function and rename them `equalsWith` instead of `equals`, and then the default `equals` method can just call that with default equality as the argument.

**Comment by jaliss** [comment]
@adamgfraser @sideeffffect do we still need this? It seems there was an attempt at implementing it in #4179 but the PR was closed.

**Comment by sideeffffect** [comment]
IIRC, it turned out to be impossible endeavor, because of the use of `Set[Cause[E]]` which uses the `.equals` method anyway.
Maybe it would be possible, if the whole thing was re-architected to not use `Set[Cause[E]]`, but I'm not sure if that would be desirable, let alone viable.

**Comment by adamgfraser** [comment]
Going to close this as I think it is driven by a very specific ZIO Prelude use case that can be implemented at that level if necessary.
