### ISSUE TITLE
ZLayer can't update dependent layers

### ISSUE THREAD

**Issue by leonbur** [zio/zio#4025]
I've noticed that when I have two layers such as `ULayer[Config]` and `RLayer[Config, MyService]` I can't update the `Config` layer and by that recreate the `MyService` layer.

even if I do something like:
```
val baseConfig: ULayer[Config] = ...
val serviceLayer: RLayer[Config, MyService] = ...

val baseLayer: baseConfig >+> serviceLayer      //I'm using >+> instead of >>> because I need Config for other stuff too but it shouldn't matter

val updatedConfig: ULayer[Config] = ...

(baseLayer ++ updatedConfig) >+>  serviceLayer      //this will only update the Config but not MyService
```

here's an example to paste in a REPL (sorry if it's verbose):
```
import zio._

type MyInt = Has[Int]
type MyDouble = Has[Double]

val testMyInt: ZIO[MyInt, Nothing, Unit] =
ZIO.accessM(myService => ZIO.succeed(println(myService.get)))

val testMyDouble: ZIO[MyDouble, Nothing, Unit] =
  ZIO.accessM(myService => ZIO.succeed(println(myService.get)))


val l1: ULayer[MyInt] = ZLayer.succeed(1)
val l2: ULayer[MyInt] = ZLayer.succeed(2)

val dependee: RLayer[MyInt, MyDouble] = ZLayer.fromService(int => int + 0.5)

val dependOnBase = l1 >+> dependee
val updated = l1 ++ l2
val dependOnUpdated = (dependOnBase ++ l2) >+> dependee

val runtime = Runtime.global

runtime.unsafeRun(testMyInt.provideSomeLayer(l1))
runtime.unsafeRun(testMyDouble.provideSomeLayer(dependOnBase))
runtime.unsafeRun(testMyInt.provideSomeLayer(updated))
runtime.unsafeRun(testMyDouble.provideSomeLayer(dependOnUpdated))
```
I would expect the output to be:
```
1
1.5
2
2.5
```
but instead I get:
```
1
1.5
2
1.5   // <- problem here
```

**Comment by adamgfraser** [comment]
@leonbur The issue is that layers are memoized. So in your example the `dependee` layer is constructed in `val dependOnBase = l1 >+> dependee` and constructs a layer that returns 1.5. When you then call `val dependOnUpdated = (dependOnBase ++ l2) >+> dependee`, the previously computed value of the layer is returned. You can get the behavior you want using the `fresh` combinator, which indicates you want a fresh copy of the layer constructed:

```scala
val dependOnUpdated = (dependOnBase ++ l2) >+> dependee.fresh
```

**Comment by leonbur** [comment]
@adamgfraser I'm confused why then isn't `l1` in `dependOnBase` memoized as well? since `>+>` does a `++` behind the scenes shouldn't it perform an update on dependee?

**Comment by adamgfraser** [comment]
I don’t think `l1` is referred to a second time in any of your four programs.

In `dependOnUpdated` you’re saying you ultimately want to return the result of the `dependee` layer, which way already created. Whether we use `++` or `>>>` if a layer has already been constructed we’re just going to return the previously constructed layer if we refer to it again instead of reconstructing it unless we use `fresh` to indicate we want a different behavior.

**Comment by leonbur** [comment]
`dependOnBase` is `MyInt with MyDouble`. (l1 and dependee)
in `dependOnUpdated` the clause `(dependOnBase ++ l2)` updates the `MyInt` value of `l1` to `l2` so I do in fact refer to `l1`, no?

**Comment by adamgfraser** [comment]
If I substitute the definition of `dependOnBase` into `dependOnUpdated` I get:

```scala
((l1 >+> dependee) ++ l2) >+> dependee
```

So it looks like `l1` only appears a single time if I'm not mistaken.
