### ISSUE TITLE
Side-effect in fromOption operator

### ISSUE THREAD

**Issue by politrons** [zio/zio#4076]
Hi all, congratulation for the 1.0 release, we have been waiting a lot for this oficial release.

We just start the migration from scalaz to dev.ZIO and one of the non retro compatible change that we detect, is in the operator ZIO.fromOption where in the scalaz version the IO type that was generated was

`IO[Unit, IndividualInfo]`

Whole program 

```
IO[Unit, IndividualInfo] = {
    ZIO.fromOption {
      if (CacheDisabled) None
      else Option(cache.getIfPresent(profileId.value))
    }
  }
```

And now is

`IO[Option[Unit], IndividualInfo]`

Whole program

```
IO[Option[Unit], IndividualInfo] = {
    ZIO.fromOption {
      if (CacheDisabled) None
      else Option(cache.getIfPresent(profileId.value))
    }
  }
```

And we were wondering why, since before has a side-effect `Unit` in my `catch` it was more logical than now a `Option[Unit]`

Regards

**Comment by adamgfraser** [comment]
@politrons Thanks! `fromOption` actually returns a `IO[Option[Nothing], A]`. We made the change to make `fromOption` work better with use cases where the error channel is used with `Option[E]` to express an optional value and push the possibility of the value not existing into the error channel. The two types are isomorphic since they both have exactly one inhabitant. But the type inference is better because this way if you have an `Option[E]` and `Option[Nothing]` the inferred type is `Option[E]`. You can map the error back to `Unit` with `zio.orElseFail(())`.

**Comment by politrons** [comment]
@adamgfraser Thanks for the answer.

But the logic side effect of Option is Unit, like the Try is failure or the Either is Left. 

Let's said I have Option[String] = None

If I transform that option into ZIO the side effect it must be None, which eventually is pretty much the same than Unit. Why do I need an Option[Unit].

The question is, how can you use the error channel with more than Unit/None in case of Option? 

Maybe an example it would help me to understand better 😄

**Comment by adamgfraser** [comment]
Sure! So let's say I have a couple of effects that represent queries where the query can either return a value from the database, an indication that the value didn't exist in the database, or an error. We can model this using the type `ZIO[R, Option[E], A]`:

```scala
def getFirstName: IO[Option[Throwable], String] = ???
def getLastName: IO[Option[Throwable], String]  = ???
```

This allows use to use ZIO to work with the values while pushing both the possibilities of failure and and the value not existing into the error channel:

```scala
for {
  first <- getFirstName
  last  <- getLastName
} yield User(first, last)
```

However, what happens if I want to compose this with some other value that may or may not exist but is otherwise pure? If `fromOption` returns `IO[Unit, A]` we're going to have a problem:

```scala
val optionAge: Option[Int] = ???

for {
  first <- getFirstName
  last  <- getLastName
  age   <- ZIO.fromOption(optionAge)
} yield User(first, last, age)
// Option[Throwable] and Unit unify to Any so we have lost all type information on the error channel
```

If instead `fromOption` returns `Option[Nothing]` then the least upper bound of `Option[String]` and `Option[Nothing]` is `Option[String]` so we preserve type information in this case.

Stepping back, I would describe the possibility of `Option` being `None` as a side effect, it is just a a data type that represents some data that may or may not exist. When we import that into `ZIO` we have to transform the possible constructors for that data type into ZIO. As you say, for `Either` we have an actual value of type `E` in the `Left` case, so we move that into the error channel. A `Try` can fail for any reason so we move that into the error the channel. An `Option` is essentially a data type that can fail in only one way and that doesn't contain any information in the error channel.

So we can translate that into any type we want that has only a single inhabitant (all all such types are isomorphic). Translating the failure case to `Unit` is conventional because `Unit` is a simple value that only has a single inhabitant, but there is nothing that makes that more correct than another value that has only one instance, and here using `Option[Nothing]` composes significantly better with other values when ZIO is used to express optionality this way.

**Comment by politrons** [comment]
Thanks for the great explanation, so then basically if I understand is because you want to use least upper bound of types in the error channel when you compose, and the only way to perform that is if we force that all types in IO error channel are Options?

Regards.

**Comment by adamgfraser** [comment]
Yes, if we want to compose an effect with other effects that have `Option[E]` for the error type we want the type we return to unify with that. There is a judgment call that that when people are using `fromOption` that they will be working with optional values that they represent with `Option[E]` in the error channel so this will be helpful. That seems to be true on net, but not always the case as your example shows.
