### ISSUE TITLE
Ensure there is a way for users to make a graceful shutdown of RTS

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#412]
See #370 for context. /cc @hepin1989

**Comment by RaasAhsan** [comment]
#305 #356 has additional context as well

**Comment by RaasAhsan** [comment]
@jdegoes Because this topic isn't getting much discussion, I'd like to pose a question: when would users want to shut down the thread pool of the RTS versus just letting the application end? Are there any valuable guarantees they get from doing it, and to what degree can they reason about the effects of shutting down the thread pool?
