### ISSUE TITLE
Memory leak when racing join

### ISSUE THREAD

**Issue by ollyw** [zio/zio#4135]
When racing a join there is a memory leak. The source of the leak seems to be that the ZIO internal FiberState.observers list keeps on growing, which could be because the .join is never being completed/interrupted successfully. 

![Heap when running](https://github.com/ollyw/zio-memleak-reproducer/raw/master/leak.png)

Simple code to reproduce can be found at https://github.com/ollyw/zio-memleak-reproducer

Tested with ZIO 1.0.0-RC21-2, 1.0.0 and 1.0.1

CC @adamgfraser

**Comment by adamgfraser** [comment]
@ollyw I see it. Working on it now.

**Comment by adamgfraser** [comment]
This is an interesting problem. A slightly simpler example can be illustrated here:

```scala
for {
  ref   <- Ref.make(0)
  queue <- Queue.bounded[Promise[Nothing, Unit]](1)
  fiber <- queue.take.flatMap(_.complete(ZIO.unit)).forever.fork
  offer = for {
            n       <- ref.getAndUpdate(_ + 1)
            _       <- UIO(println(n))
            promise <- Promise.make[Nothing, Unit]
            _       <- queue.offer(promise)
            value   <- ZIO.never.race(promise.await)
          } yield value
  _ <- offer.repeatWhileM(_ => ref.get.map(_ <= 1000))
} yield ()
```

`fiber` will eventually have 1,000 observers. Each time we call `race`, we create a new fiber that calls `join`, adding a new observer to `fiber`. Ideally, we might want to remove the observer each time a fiber loses the race. But we can't do that because observers are just callback functions and fibers don't maintain references to the fibers that are observing them, nor do fibers maintain references to the fibers they are observing. So we have no way to remove the observer and keep adding observers until they eventually get garbage collected.

I'm not sure how we address other than adding more information to fiber context which seems to raise issues with maintaining the consistency of information between fibers observing and being observed.

Note that this example will work with a more sophisticated implementation where we use `raceWith` and keep passing forward the same effect that waits on `fiber`, instead of creating a new effect that waits on it each time.
