### ISSUE TITLE
Can't resume interrupted Fiber from join by either function.

### ISSUE THREAD

**Issue by jeffwji** [zio/zio#4151]
Follow by the example from the document of https://zio.dev/docs/datatypes/datatypes_fiber, I tried to resume the interrupted Fiber from join operation by using either, It supposed to have a Left(Failure(...)) be returned with success. 

    val result: ZIO[Any with Clock, Throwable, Either[Throwable, Analysis]] = {
        for {
            fiber1   <- IO(Analysis("Good!")).delay(2.seconds).fork
            fiber2   <- IO(false).fork
            // Do other stuff
            valid    <- fiber2.join
            _        <- if (!valid)  fiber1.interrupt else IO.unit
            analyzed <- fiber1.join
        } yield analyzed
    }.either

    override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
        result.map(println).exitCode
    }

But it failed with stacks:

    Fiber:Id(1598647929785,2) was supposed to continue to:
        a future continuation at zio.ZIO$._IdentityFn(ZIO.scala:3792)
        a future continuation at zio.ZIO.onInterrupt(ZIO.scala:967)
        a future continuation at <unknown>.<unknown>(ZIO.scala:0)
     
    Fiber:Id(1598647929785,2) execution trace:
        at zio.clock.package$Clock$Service$$anon$1.sleep(package.scala:47)
        at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2522)
        at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2522)
        at zio.clock.package$.sleep(package.scala:97)
    
    Fiber:Id(1598647929785,2) was spawned by:
    
    Fiber:Id(1598647929111,1) was supposed to continue to:
        a future continuation at datatypes.ZioFiber$.result(ZioFiber.scala:17)
        a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:3972)
        a future continuation at datatypes.ZioFiber$.run(ZioFiber.scala:29)
        a future continuation at zio.ZIO.exitCode(ZIO.scala:543)
    
    Fiber:Id(1598647929111,1) ZIO Execution trace: <empty trace>
    
    Fiber:Id(1598647929111,1) was spawned by:
    
    Fiber:Id(1598647927746,0) was supposed to continue to:
       a future continuation at zio.App.main(App.scala:57)
       a future continuation at zio.App.main(App.scala:56)
    
    Fiber:Id(1598647927746,0) ZIO Execution trace: <empty trace>
    
    Fiber:Id(1598647927746,0) was spawned by: <empty trace>

The either doesn't handle the exception. is it a bug?

**Comment by adamgfraser** [comment]
@jeffwji `either` recovers from errors, represented by the `E` type parameter in ZIO, but not defects or interruptions. If you want to recover from interruptions you need to use one of the combinators that exposes the full `Cause` of the failure of a computation such as `foldCauseM`, `catchAllCause`, or `run`.

**Comment by jeffwji** [comment]
Thanks Adam, yes, the catchAllCause is able to catch the exception's stack track, but if I move the `either` to front of the `fork`, `IO(Analysis("Good!")).delay(2.seconds).either.fork`, it would return failure without stack information but an interruption id. Is it the designed?

**Comment by adamgfraser** [comment]
@jeffwji Whether a trace is available depends on how quickly the effect is interrupted. If it is interrupted immediately then no tracing information will be available. You can try delaying interrupting the fiber to see the difference.

**Comment by jeffwji** [comment]
I put a delay before catchAllCause, it does catch Traced with stack information, but obveriously it is not a good idea to have an explicit waiting time, is there any way to have anything be injected and raised automatically when it is ready?

**Comment by jeffwji** [comment]
Another question is why the interpretation exception has to be a Cause? because catchAll doesn’t work for it, any consideration behind it?

**Comment by adamgfraser** [comment]
@jeffwji Usually `Promise` is a good way to wait for something to be ready without blocking. In practice we generally don't want to wait for tracing information to be available, we want to interrupt the computation as soon as we can and get whatever tracing information is available at that point. But if you want to you can create a promise at the beginning of your program, complete it in the fiber you are interrupting, and wait on it immediately before interrupting the fiber. That way you will have ensured that the fiber being interrupted has at least gotten to the point of completing the promise by the time it is interrupted and so will have some tracing information.

**Comment by adamgfraser** [comment]
Regarding your second question, yes that is part of the ZIO error model.

There are a couple of reasons for it.

First, in terms of types `catchAll` catches errors of type `E`. But `E` can be anything. It could be a `Throwable` but it could also be a `String` error message or `Nothing` indicating that the effect can't fail at all. But any of these effects could potentially be interrupted and have to have a way to signal that they were interrupted. So we need a data type that is "bigger" than `E`, which is why we have `Cause[E]`, which represents normal types failures of type `E` as well as other ways a computation can fail such as interruption.

From a more practical perspective, we want to be able to handle errors but we don't normally want to recover from interruption unless doing so very explicitly. For example we might be reading some console input from a user and want to retry if there is some kind of exception thrown in reading the input. But normally we wouldn't want to retry if the user were trying to interrupt the whole program.

So having combinators like `catchAll` not recover from interruption is a very explicit consideration and there are other combinators that can be used for doing that when it is really intended.

**Comment by jeffwji** [comment]
Impressive! however, I tried `zip promise.succeed()` and `ensuring promise.succeed()` after `interrupt` or `join`, and then `await` at the end of `for-comprehension`, neither works, but I think both places are not make sense, coz I'm expecting for the stack information dumping finish, not the function call return, so where could be the right place for this waiting?

**Comment by adamgfraser** [comment]
@jeffwji You have to use the `Promise` to make sure that the forked effect has at least begun execution before being interrupted.

For example, in the program below we complete the promise from within the forked effect and then wait on the promise before interrupting the fiber so we know the fiber has begun execution. This results in a failure with a trace when I test locally.

```scala
package zio

object Example extends App {

  def run(args: List[String]): URIO[ZEnv, ExitCode] =
    for {
      promise <- Promise.make[Nothing, Unit]
      effect  =  promise.succeed(()) *> ZIO.never
      fiber   <- effect.fork
      _       <- promise.await
      _       <- fiber.interrupt
      _       <- fiber.join
    } yield ExitCode.success
}
```

**Comment by jeffwji** [comment]
I tried this, it also works:

        for {
            p <- Promise.make[Throwable, Unit]
            fiber1   <- IO{Analysis("Good!")}.delay(2.seconds).either.fork
            fiber2   <- IO(false).fork
            _ <- p.succeed()
            _ <- p.await
            // Do other stuff
            valid    <- fiber2.join
            _        <- if (!valid) {
                             println("Stop running.")
                             fiber1.interrupt
                        } else IO.unit
            analyzed <- fiber1.join
            // _ <- p.await
        } yield analyzed

The difference is to move the `await` to front of `interrupt`(compared with doing it at the end of for comprehension, which doesn't return full stack information), but it looks not very make sense, because I didn't see the relationship between the promise await and stack information dumping from this point, looks like it just so happened that the await action ran long enough for the dumping to get time, it is a lucky thing not a guarantee. is it right? or there's a magic between the Traced and Promise?

**Comment by adamgfraser** [comment]
Yes, if you are completing a promise and then immediately awaiting it, it is essentially a noop. I think it is just taking enough time so that the forked fiber has begun execution and tracing information has been recorded by the time the forked effect is interrupted.

Stepping back, the basic principle here is that the ZIO runtime records tracing information as it executes a computation and reports that tracing information when an unhandled failure occurs. But the tracing information available depends on how much of the computation has executed. In the extreme case, if an effect is interrupted before it begins execution there will be no trace at all.

So when we guarantee that a computation has begun executing before it is interrupted like in my example we get a trace. If we just take up enough time before interrupting an effect like your example we will get a trace but it will probably be subject to some flakiness because we're just relying on enough time passing versus having an actual "happens after" guarantee. If we immediately interrupt without any delay we often won't see tracing information because the effect will be interrupted before it begins execution, though again this will likely be flaky as it depends on the exact order in which the runtime executes concurrent effects.

Happy to continue discussing here but you may also want to check out Discord where we can have more of a real time discussion about this if that would be helpful to you.

**Comment by jeffwji** [comment]
Thank you Adam, my network prevents me to access social media, as well as Discord. I learned a lot from this discussion, by the end, I would like recommend to add a callback handler for all such action raised from the core of runtime in the future release, seriously, I don’t know is it a solo or other similar scenario happens, if so, it is worth to consider. Finally, thank you again and might talk to you again soon(for other question).

**Comment by adamgfraser** [comment]
@jeffwji Definitely. If Discord doesn't work for you feel free to reopen this issue or another one with questions. I think the feature you are looking for already exists through the `Runtime.withReportFailure` combinator, which lets you specify how unhandled failures should be handled. The default is to just print them to the console but you can use that to add arbitrary logic for handling them.
