### ISSUE TITLE
[docs] Intellij will raise error when trying sample program of test.

### ISSUE THREAD

**Issue by counter2015** [zio/zio#4321]
I'm new to zio and trying to write zio test.

When I tried demo in website [here](https://zio.dev/docs/usecases/usecases_testing), the ide gived a error.

![image](https://user-images.githubusercontent.com/13608862/96211381-c50ec780-0fa6-11eb-8572-ed6a527af8f9.png)

However, `sbt test` worked.

Is it a problem of importing , zio, or ide iteself? How to fix the error(or if it's ide bug, can I suppress it by some way)?

## environment

my `build.sbt` file
```scala
name := "zio-demo"

version := "0.1"

scalaVersion := "2.13.3"

val zioVersion = "1.0.3"

libraryDependencies += "dev.zio" %% "zio" % zioVersion
libraryDependencies += "dev.zio" %% "zio-streams" % zioVersion

libraryDependencies ++= Seq(
  "dev.zio" %% "zio-test"          % zioVersion % "test",
  "dev.zio" %% "zio-test-sbt"      % zioVersion % "test",
  "dev.zio" %% "zio-test-magnolia" % zioVersion % "test" // optional
)
testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework")
```

- system: macos big sur 11.0 beta
- ide: intellij idea 2020.2.3
- scala: 2.13.3
- sbt: 1.4.0

**Comment by counter2015** [comment]
One workaround is explicitly declare types, but I don't know the magic behind.

```scala
// these worked
assert(output)(equalTo(Vector("Hello, World!\n"))(Eql.eqlSubtype1)
assert(output)(equalTo(Vector("Hello, World!\n"))(Eql.eqlSubtype2)

// this doesn't work and raise error following
/* 
 type mismatch;
[error]  found   : zio.test.Eql[scala.collection.immutable.Vector[String],Nothing]
[error]  required: zio.test.Eql[scala.collection.immutable.Vector[String],Vector[String]]
[error] Note: Nothing <: Vector[String], but class Eql is invariant in type B.
[error] You may wish to define B as +B instead. (SLS 4.5)
[error]       } yield assert(output)(equalTo(Vector("Hello, World!\n"))(Eql.eqlSubtype2)
[error]                                                                     ^
[error] one error found
*/
assert(output)(equalTo(Vector("Hello, World!\n"))(Eql.eqlSubtype2)
```

**Comment by adamgfraser** [comment]
I would suggest raising this with the Intellij team.

Intellij uses their own version of the Scala compiler which can lead to differences between what Intellij says works and what actually works when you use SBT or actually go to run your program. We generally can't change our code for the Intellij compiler since we have to make sure it works for the actual Scala language and not some variant of it that differs in subtle ways.

Specifically here we're using some type level machinery to try to help the user avoid doing equality comparisons that don't make sense and it looks like that is throwing Intellij off. We have had some issues before with other ZIO features and several of them have been addressed so if you could raise an issue with them would greatly appreciate it. 🙏

**Comment by counter2015** [comment]
Thanks your reply, I have just raised an issue in [Youtrack SCL](https://youtrack.jetbrains.com/issue/SCL-18349).

**Comment by joroKr21** [comment]
It could be worked around. `eqlReflexive` is redundant and Intellij thinks it's ambiguous with the other two.
