### ISSUE TITLE
The intuition for creating a managed fiber

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#4363]
```scala
val managed = program.fork.toManaged(f => f.interrupt)
```

In the above program, the default intuition is that once the usage of the managed is completed, the program will be interrupted.

But actually, the program isn't interrupted because `program.fork` forms the "acquire" part of the `ZManaged` which is "uninterruptible".

**Comment by adamgfraser** [comment]
@tusharmath I understand this can be somewhat counterintuitive but as you say it follows from the fact that the `acquire` action of a `ZManaged` is normally uninterruptible.

There are a couple of ways you can do this. First, there is a specialized `forkManaged` operator that already takes care of this for you. Second, you can do `ZManaged.makeInterruptible(program.fork)(_.interrupt)`, which will allow the fiber to be interrupted since `makeInterruptible` does not perform the resource acquisition uninterruptibly.

Is there something else that would have helped you here?

**Comment by tusharmath** [comment]
IMHO we should keep everything "interruptible" by default (which is true in most cases, except here), and that's why it seems counterintuitive at first.

But I also agree, that there is a case to be made especially for ZManaged, where "acquire" action needs to be uninterruptible in most cases. 

I guess this is more of a "Learning how to use the library" kind of thing.

Also building a better intuition around ZManaged and not just effects and interruptibility.
