### ISSUE TITLE
Providing layer before scheduling recreates layer for each iteration

### ISSUE THREAD

**Issue by shvimas** [zio/zio#4374]
Consider this code:
```
trait Service {
  def doWork(): UIO[Unit] = ZIO.succeed(println("Doing work"))
  def close(): UIO[Unit]  = ZIO.succeed(println("Closing resource"))
}

object Service {
  def make: UIO[Service] = ZIO.succeed {
    println("Creating resource")
    new Service {}
  }
}

object Main extends zio.App {

  val serviceLayer: ZLayer[Console, Throwable, Has[Service]] =
    ZLayer.fromAcquireRelease(Service.make)(_.close())

  val main: ZIO[Has[Service], Nothing, Unit] =
    ZIO.accessM[Has[Service]](_.get.doWork())

  override def run(args: List[String]): URIO[ZEnv, ExitCode] =
    main
      .provideCustomLayer(serviceLayer)
      .repeat(Schedule.recurs(5))
      .exitCode
}

```

If I run it as is I see that `Service` is being created (and released) 5 times which looks rather counterintuitive to me since I expect layers to be shared. Although if I switch `.provideCustomLayer(serviceLayer)` and `.repeat(Schedule.recurs(5))` I get the expected result: `Service` being created, then worked 5 times and finally released.
Or maybe I got something wrong and this is the desired behaviour?

Tested on 1.0.3

**Comment by adamgfraser** [comment]
@shvimas That is the expected behavior. A layer is a "recipe" that describes how to create a set of services. Every time you call `provideLayer` or one of its variants a new set of services will be created, similar to how every time you `use` a `ZManaged` a new resource will be acquired.

Sharing layers applies to layers that are used multiple times within the same definition (e.g. `layer1 ++ (layer1 >>> layer2`), not between different calls to `provide`. In your case you can simply move the `provideCustomLayer` call after the `repeat` call or you can use `ZLayer#memoize`.

**Comment by shvimas** [comment]
Got it, thanks!

**Comment by adamgfraser** [comment]
No problem!
