### ISSUE TITLE
Project loom and ZIO

### ISSUE THREAD

**Issue by brightonk** [zio/zio#4433]
Project loom is on its way to provide unlimited non-blocking threads. How is project loom going to impact ZIO? Do we have a sand box to start testing ZIO with project loom?

**Comment by justf0rfun** [comment]
1. I tried to find out in which state project Loom is and if it is planned to be included in a specific JDK release. Here are my results:

I don't know when or if project Loom's fiber actually land in the JDK, but JDK 18 is now released for general availability (GA). 
https://openjdk.java.net/projects/jdk/18/

And it comes with two JEPs wich are related to project Loom. So at least there is some progress.
https://openjdk.java.net/jeps/416
https://openjdk.java.net/jeps/418

These issues seem to block a release:
https://wiki.openjdk.java.net/display/loom/Blocking+Operations

At the time of writing there is only one unrelated JEP planned for JDK 19, so far.
https://openjdk.java.net/projects/jdk/19/

However there are early-access-builds based on incomplete versions of JDK 19. I guess they are just basing their work on the current development source of the JDK and that does not necessarily mean that Loom will make it into JDK 19.
https://jdk.java.net/loom/

Here is some example code for trying Loom with the early-access-build.
https://wiki.openjdk.java.net/display/loom/Getting+started

2. What do I think about project Loom in relation to ZIO?

Please note that I am neither an expert for the JVM internals nor ZIO. If I understand the situation right, project Loom will implement its fibers partially with continuations **inside the JVM** (although the continuations might become accessible  by an slim API) and ZIO's fibers will be implemented to run as bytecode **on top of the JVM**. Can someone confirm that this is right?
https://cr.openjdk.java.net/~rpressler/loom/Loom-Proposal.html

If this is right, then I would say, this is a major difference. I wonder what this means for performance and capabilities. Can the project Loom fibers do more than ZIO's and can project Loom fibers be optimized more than ZIO's because they are implemented in the JVM?

Would it be beneficial for ZIO to switch to project Loom's fibers?
Would that be possible without major refactoring or breaking user code?

**Comment by adamgfraser** [comment]
I would encourage folks who are interested in this to check out the talk by @jdegoes regarding it:

https://www.youtube.com/watch?v=SJeAb-XEIe8&t=9s

The short version is that Loom is great and will allow ZIO to internally implement things more efficiently, but that using ZIO will actually reduce the number of changes you need to make in your code in the future. With Loom basically everything bad is good. Blocking used to be terrible, now waiting for the value from a virtual thread is great. If you are working with these primitives yourself you have to rewrite all that code. If you are using ZIO then ZIO contributors rewrite the code in the ZIO runtime and you benefit.

Loom also provides a lot of great functionality for people in higher levels of the stack but itself is relatively low level, so you are still going to benefit from ZIO's functionality around tracing, metrics, safe resource management, interruption, and so on.

**Comment by justf0rfun** [comment]
FYI. The plans for JDK 19 have been updated.

JEP 425: Virtual Threads (Preview) 
Targeted for JDK 19. JDK 19 is planned to go into GA on 2022/09/20.

https://openjdk.java.net/jeps/425

**Comment by adamgfraser** [comment]
Thanks! Going to close this as I don't think there is an action item here but will definitely going to be continuing to develop ZIO with an eye towards making it even better with Project Loom.

**Comment by sbuljat** [comment]
Since Loom is out now, are there any more formal plans when ZIO aims to support it?

**Comment by 987Nabil** [comment]
It is not out btw, it is still in preview. Also, I don't think this is a pressing issue. So I would wait for the final release in an LTS JDK, before investing a lot of time. It might end up being a waste. We waited for loom since JDK 9 I guess. We can wait a little longer 🙂

**Comment by ReDestroyDeR** [comment]
Since Loom is not in preview, are there any news regarding Loom Runtime?

I've seen this thread by De Goes https://contributors.scala-lang.org/t/impact-of-loom-on-functional-effects/5821

But didn't find a clear answer regarding Loom's integration into the ZIO Framework. It is [said](https://zio.dev/overview/performance/) that Loom *will* be integrated, but what is currently planned?

Thank you

**Comment by guizmaii** [comment]
@ReDestroyDeR Loom is supported but doesn't provide better performances. See https://blog.pierre-ricadat.com/tuning-zio-for-high-performance#heading-alternative-executors

**Comment by ghostdogpr** [comment]
It was slower in one benchmark, but it doesn't mean it's always worse. You're encouraged to try it (and let us know) in your specific use case. The blog post above shows how to enable it.

**Comment by ReDestroyDeR** [comment]
> It was slower in one benchmark, but it doesn't mean it's always worse. You're encouraged to try it (and let us know) in your specific use case. The blog post above shows how to enable it.

We have a microservice in ZIO which assembles in-memory state reading some Kafka Topics and provides a couple of REST endpoints which are heavily cached.

Having caching enabled (that's an oversight from me) what I found initially transitioning from JDK 17 to JDK 21 and from ZIO 2.0 to ZIO 2.1 was way more impactful (cut down CPU by ~17% and RAM from ~1.5 GiB to ~860 MiB). I haven't done more thorough benchmarks to determine impact of ZIO and JDK switch independently, but will gladly come forward with the info when I'll get my hands on it again :)

I will try other JDKs, 22, 23, and some preview of 24. From what I read there were some improvements regarding loom's performance in these updates.

Thank you
