### ISSUE TITLE
ProxyFactory is not thread safe

### ISSUE THREAD

**Issue by senia-psm** [zio/zio#4472]
Proxy factory can miss successful calls to mocked methods if methods are called in parallel.

This test succeeds (so both methods are called successfully), note `atMost`:
```scala
def method = Srv.mPar("b").zipPar(Srv.mPar("c"))
...
val mockEnv =
  SrvMock.MPar(equalTo("b"), value("bRes")).atMost(1) &&
    SrvMock.MPar(equalTo("c"), value("cRes"))

assertM(method)(equalTo(("bRes", "cRes"))).provideLayer(mockEnv)
```

This one (without `atMost`) fails on expectations check, so one successful call is missed:
```scala
val mockEnv =
  SrvMock.MPar(equalTo("b"), value("bRes")) &&
    SrvMock.MPar(equalTo("c"), value("cRes"))

assertM(method)(equalTo(("bRes", "cRes"))).provideLayer(mockEnv)
```

```
[info]     - unsatisfied expectations
[info]       in any order
[info]         .IssueSpec.SrvMock.MPar with arguments equalTo(b)
```

See [zio-test-issue-4472](https://github.com/senia-psm/zio-test-issue-4472) for reproducible example.

I believe this issue might be caused by [ProxyFactory implementation](https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/mock/internal/ProxyFactory.scala#L273-L277), namely:
```scala
root    <- state.expectationRef.get
...
_       <- state.expectationRef.set(matched.expectation)
```

**Comment by senia-psm** [comment]
Obvious solution is to add a `Semaphore` into `MockState` and execute `get/set` pair with permit, though I'm not sure if it breaks anything else (or even creates a deadlocks).

**Comment by jypma** [comment]
Looking at [`findMatching`](https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/mock/internal/ProxyFactory.scala#L39), I can't seem to see why it returns `UIO[Matched[R, E, A]]` and not just `Matched[R, E, A]`. It might be just for error handling, in which case we could consider using `Either`.

If `findMatching` is indeed a non-IO function, we could just use `.modify` or `.update` on the `Ref`, instead of needing an explicit semaphore. That would eliminate the possibility of deadlocks.
