### ISSUE TITLE
Overcome limitation: one Service type per environment. 

### ISSUE THREAD

**Issue by heaven-born** [zio/zio#4690]
This is a simplified example of the issue:

    class Http4s {
       trait Service {
         def serverName = "testServer"
       }

       val live: ULayer[Http4s] = ZLayer.succeed(new Service{})
       type Http4s = Has[Service]

       def serverName: URIO[Http4s, String] =
         ZIO.access[Http4s](_.get.serverName)
    }

    def run(args: List[String]): URIO[ZEnv, ExitCode] = {
       val ser1 = new Http4s
       val ser2 = new Http4s

       val r = for{
         _ <- ser1.serverName
         _ <- ser2.serverName
       } yield ()

       r.provideCustomLayer(ser1.live ++ ser2.live).exitCode
    }

The code above gives me an error: `java.lang.Error: Defect in zio.Has: Set(ser2::Service) statically known to be contained within the environment are missing`

There is a very [comprehensive explanation](https://discord.com/channels/629491597070827530/630498701860929559/810271761349738597) of why it happens and the potential solutions for this, but the limitation looks very restrictive. I see a lot of potential cases where I would like to put my layer-wrapper-pattern (is there a name for it, btw?) into an external lib and reuse it multiple times in one environment for connecting to multiple systems using different connection settings. 

It would be nice to have a simple solution for such cases. The workaround for this looks not very complex, but it is not straightforward, and it requires some understanding of zio internals.

**Comment by adamgfraser** [comment]
@heaven-born You should use subtyping instead of path dependent types for these situations.

```scala
trait HttpService

trait HttpService1 extends HttpService
trait HttpService2 extends HttpService

ZIO.environment[Has[HttpService1]]
ZIO.environment[Has[HttpService2]]
```

This allows you to define additional methods for each of the specific services if desired as well as have a type to refer to which of these services you are using throughout your application.

**Comment by heaven-born** [comment]
@adamgfraser my initial idea was to keep `class Http4s ...` in external library, and just pass different configurations to this layer for different servers. 

Like this:

    val ser1 = new Http4s
    val ser2 = new Http4s

    val env = config1 >>> ser1.live ++ config2 >> ser2.live
  
Solution with subtyping requires manipulation with the class directly for each http service, so it is not very reusable. 
Solution with Tags is doing pretty much what I need, but it doesn't look obvious.

**Comment by adamgfraser** [comment]
@heaven-born I think you can achieve the same thing with subtyping.

```scala
// in library
trait HttpServervice {
  def config: Config // abstract method defines configuration settings
}

// in application
trait HttpService1 {
  val config = ??? // same configuration information you would pass to constructor argument
}
```

If you really don't want to do this you can use tags as you suggest, but I would agree that is a more advanced use case.

**Comment by heaven-born** [comment]
@adamgfraser yeah, I see what you mean. I should work, but it breaks the unified approach across my application. Now everything includings configs live inside Env., so the entire application is just a composition of many layers except a few lines  that actually starts the process. Solution with Tags looks more organic in my app.

I opened this ticket because solution based on dependent types looks much more readable and intuitive. I'm pretty sure that many developer will try do the same trick one day and get the same error.

**Comment by adamgfraser** [comment]
@heaven-born The issue is you need to avoid "forgetting" type information with path dependent types. For example this works fine:

```scala
import zio._

object Example extends App {

  class Http4s {
    trait Service {
      def serverName = "testServer"
    }

    def live: ULayer[Http4s] = ZLayer.succeed(new Service {})
    type Http4s = Has[Service]

    def serverName: URIO[Http4s, String] =
      ZIO.access[Http4s](_.get.serverName)
  }

  def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    val ser1 = new Http4s
    val ser2 = new Http4s
    val serverName1: URIO[Has[ser1.Service], String] =
      ZIO.access[Has[ser1.Service]](_.get.serverName)
    val serverName2: URIO[Has[ser2.Service], String] =
      ZIO.access[Has[ser2.Service]](_.get.serverName)
    val live1: ULayer[Has[ser1.Service]] =
      ZLayer.succeed(new ser1.Service {})
    val live2: ULayer[Has[ser2.Service]] =
      ZLayer.succeed(new ser2.Service {})

    val r = for {
      _ <- serverName1
      _ <- serverName2
    } yield ()

    r.provideCustomLayer(live1 ++ live2).exitCode
  }
}
```

Partly for this reason I would consider path dependent types an advanced language feature and would not recommend this pattern for working with the environment.

**Comment by heaven-born** [comment]
@adamgfraser thank you. I will use this approach. Defining types explicitly is pretty much a straightforward solution.

**Comment by adamgfraser** [comment]
@heaven-born Great!

**Comment by heaven-born** [comment]
Just in case someone finds this ticket later. The modified approach works even without providing types explicitly:

    class Http4s {
      trait Service {
        def serverName = "testServer"
      }

      def live: ULayer[Http4s] = ZLayer.succeed(new Service {})
      type Http4s = Has[this.Service]

      def serverName: URIO[Http4s, String] =
        ZIO.access[Http4s](_.get.serverName)
    }

    def run(args: List[String]): URIO[ZEnv, ExitCode] = {
       val ser1 = new Http4s
       val ser2 = new Http4s
       val live1 = ser1.live
       val live2 = ser2.live

       val r = for {
         _ <- ser1.serverName
         _ <- ser2.serverName
       } yield ()

       r.provideCustomLayer(live1 ++ live2).exitCode
    }

**Comment by felher** [comment]
> Just in case someone finds this ticket later. The modified approach works even without providing types explicitly:

I think this should crash, right? `def live` is inside the class and still summons `Http4s::Service` while `provideCustomLayer` still gets two layers it sees as `ser1::Service` and `ser2.Service`.

Am I missing something here?

**Comment by heaven-born** [comment]
@felher I posted without proper checking. It compiled only because I did incorrect copy-paste. It does crashes, unfortunately.

**Comment by adamgfraser** [comment]
The version I posted runs correctly.

**Comment by felher** [comment]
FWIW, here is a "compromise":

```scala
import zio._

trait Http4sService {
  def serverName: String
}

final case class Tagged[T](service: Http4sService)

class Http4s[T: Tag]() {
  type Http4s = Has[Tagged[T]]
  def live: URLayer[Has[String], Http4s] =
    ZLayer.fromService[String, Tagged[T]](s =>
      Tagged(new Http4sService {
        def serverName = s
      })
    )

  def serverName: URIO[Http4s, String] =
    ZIO.access[Http4s](_.get.service.serverName)
}

object Ser1 extends Http4s["Ser1"] {}
object Ser2 extends Http4s["Ser2"] {}

object Example extends App {

  def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    val r = for {
      name1 <- Ser1.serverName
      name2 <- Ser2.serverName
      _ <- console.putStrLn(name1)
      _ <- console.putStrLn(name2)
    } yield ()

    r.provideCustomLayer(
      (ZLayer.succeed("porta") >>> Ser1.live) ++
        (ZLayer.succeed("portb") >>> Ser2.live)
    ).exitCode
  }
}
```

There are still setup costs involved, but then new "instances" can be added by adding a single line (the objects extending `Http4s`).

There should not be any tag collisions as long as the user uses different strings as the other types are now top level. But code reuse is high because there is no need to define several `live` oder `serverName`. I think end user ergonomics are a bit better than with wrapping. With wrapping you would have to do `ZIO.accessM[Wrapper](_.get.unwrapped.method)`, now you can just do `SerX.method`. Of course, the provider of the library now has to do the unwrapping.

Whether all this justifies the added complexity remains to be seen. But maybe the code above provides an example for someone on how code reuse of the service methods can be achieved without requiring the user to do the unwrapping.

**Comment by heaven-born** [comment]
@felher Thanks. That may work for me too. 

Both type and tag magic is pretty dark for zio newcomers. It would be nice to have some simple solution built-in zio directly, because this way of reusing code looks like something that many developers would want.

I'm wondering, maybe be PDT can be fixed in izumi-reflect for scala 3. And then, for example, it would be possible to just put implicit tag directly in Http4s class. Like this: `implicit val t = Tag[Service]`

**Comment by neko-kai** [comment]
@heaven-born It wouldn't be possible to implement that, consider that a Tag is generated at compile-time - it requires a macro invocation.  When you have 
```scala
class Http4s {
  trait Service
  implicit val t = Tag[Service]
}
```
The macro is invoked when the line `implicit val t = Tag[Service]`, inside the template of `Http4s`, it is  still a class, not an object, it's not possible to know to what object it will be instantiated in the future at that moment. So the generated tag looks like `Tag[Http4s#Service]`.

When `new Http4s()` is invoked, the body of Http4s is not recompiled (in fact the source code may not even be around anymore, just the bytecode), therefore the tag cannot be regenerated, so
```scala
object xa extends Http4s
xa.t
```
Will contain `Tag[Http4s#Service]`, not `Tag[xa.Service]` and that's not possible to overcome even in Scala 3.

I am actually using a scheme similar to `Http4s` example, with an additional type parameter to signify difference [here](https://github.com/7mind/izumi/blob/5f147fd5547c552398844da97f65df81319edf91/distage/distage-framework-docker/src/main/scala/izumi/distage/docker/ContainerDef.scala#L12) – however by adding an abstract `type Tag` instead of accepting a `[T: Tag]` I am actually adding path dependency that way every `object x extends ContainerDef` makes a new `x.Tag` type that is then used to index its associated data types.

`Http4s` can be reformulated that way as follows to do the same thing and use path-dependency, note that I think this doesn't even need any updates to work on Scala 3 version of izumi-reflect:

```scala
class Http4s {
  type T
  type Http4s = Has[Tagged[T]]

  def live(implicit t: Tag[Tagged[T]]): URLayer[Has[String], Tagged[T]] =
    ZLayer.fromService[String, Tagged[T]](s =>
      Tagged(new Http4sService {
        def serverName = s
      })
    )

  def serverName: URIO[Tagged[T], String] =
    ZIO.access[Tagged[T]](_.get.service.serverName)
}

object Ser1 extends Http4s

Ser1.serverName: URIO[Tagged[Ser1.T], String]
```

Note that the difference from using a `implicit val t = Tag[Service]` is that the tag is generated *after* construction, when the prefix `xa` exists, the macro is called to generate a new tag every time `.live` method is called, so that there is an opportunity to generate a correct prefix instead of `Http4s#`

**Comment by felher** [comment]
> ```scala
>   def live(implicit t: Tag[Tagged[T]]): URLayer[Has[String], Tagged[T]] =
>     ZLayer.fromService[String, Tagged[T]](s =>
>       Tagged(new Http4sService {
>         def serverName = s
>       })
>     )
> 
>   def serverName: URIO[Tagged[T], String] =
>     ZIO.access[Tagged[T]](_.get.service.serverName)
> ```

I think I might be missing something here: Shouldn't both, `live` and `serverName` get the implicit tag?

**Comment by neko-kai** [comment]
Ah, right

**Comment by heaven-born** [comment]
It seems that I've found a relatively elegant solution for this.

    class Http4s{
      trait Service {
        def serverName = "testServer"
      }

      val live: UIO[Service] = UIO.succeed(new Service{})
    }

    def run(args: List[String]): URIO[ZEnv, ExitCode] = {
      val ser1 = (new Http4s).live
      val ser2 = (new Http4s).live

      val r = for{
        _ <- ser1.map(_.serverName)
        _ <- ser2.map(_.serverName)
      } yield ()

      r.provideCustomLayer(ser1.toLayer ++ ser2.toLayer).exitCode
    }
