### ISSUE TITLE
FR: Add a means to `zio.clock` to retrieve a `ScheduledExecutorService` for interop with legacy Java code

### ISSUE THREAD

**Issue by virusdave** [zio/zio#4796]
`zio.clock.PlatformSpecific` has one internally, and sometimes java libraries want one.  

It would be nice to be able to connect those two together, or alternatively have one created that's backed by this module.

**Comment by adamgfraser** [comment]
I will look at adding this.

**Comment by virusdave** [comment]
Thanks.  I notice that the existing on in the module is using a thread pool of size 1, so it's perhaps better to create a new object that is backed by ZIO fibers and `Clock` rather than reuse the existing one.  But you're the expert :)  Meanwhile, I'm doing this latter idea right now to unblock.  Not sure it'll be all that optimal, but could contribute the impl if interested.

**Comment by adamgfraser** [comment]
Yes. The principle with the `ScheduledExecutorService` is that it is not supposed to be used for anything other than scheduling tasks and the actual execution of the task is to be immediately shifted to another executor so that the `ScheduledExecutorService` is free to keep triggering other effects scheduled for the future. So agree the tricky part is giving the user an implementation that is safe and does not pose a risk to the integrity of the ZIO runtime.
