### ISSUE TITLE
Strange Tag/Has Issue with Scala 3.0.0-RC1

### ISSUE THREAD

**Issue by kitlangton** [zio/zio#4802]
Minimal repro on `3.0.0-RC1`:

```scala
val program = ZIO
  .service[Ref[Int]]
  .provideLayerManual(Ref.make(10).toLayer)

Runtime.default.unsafeRunSync(program)
```

This fails with `java.lang.Error: Defect in zio.Has: Could not find ZRef[+Nothing,+Nothing,-Int,+Int] inside Map(package$::Ref[+Int] -> Ref(1))`

And of course it works if I extract the layer out into a variable first 😜 
```scala
val layer = Ref.make(10).toLayer
val program = ZIO
  .service[Ref[Int]]
  .provideLayerManual(layer)

Runtime.default.unsafeRunSync(program)
```

**Comment by adamgfraser** [comment]
We also ran into this when upgrading ZIO to `3.0.0-RC2`. It appears that the issue is that `toLayer` introduces a new type `A1 >: A` to deal with variance and this creates an issue in the `Tag` machinery. In that case we were able to use `ZLayer.fromEffect` instead, though it looks from the above like assigning it to an intermediate variable may work.

@neko-kai Could you take a look at this when you get the chance?

**Comment by neko-kai** [comment]
Needs more `.dealias` 🥷

**Comment by kitlangton** [comment]
This has been fixed :)
