### ISSUE TITLE
Unexpected "An unchecked error was produced" on Task.map

### ISSUE THREAD

**Issue by ALPSMAC** [zio/zio#4814]
I'm coming to ZIO from Monix, so fair warning - this may be simply a gap in my knowledge or understanding...

I seem to have stumbled upon a case where the error handling in ZIO isn't behaving as I would expect it to.  Consider the following simplified case (real production code is gnarlier): 

```scala
val eth1 = Task{ Task(None).map{ _.getOrElse{ throw new Exception("foo") } } }.flatten.either

// This produces an unchecked exception and I'm not sure why... 
zio.Runtime.default.unsafeRun(eth2)

val eth2 = Task{ throw new Exception("bar") }.either

// This does not - it returns: Left(java.lang.Exception: bar)
zio.Runtime.default.unsafeRun(eth2)
```

In Monix the rough equivalent code produces a `Left(Exception)` in both cases:

```scala
val eth1 = Task{ Task(None).map{ _.getOrElse{ throw new Exception("foo") } } }.flatten.attempt

// produces: Left(Exception: foo)
Await.result(eth1.runToFuture, Duration.Inf)

val eth2 = Task{ throw new Exception("bar") }.attempt

// produces: Left(Exception: bar)
Await.result(eth2.runToFuture, Duration.Inf)
```

Is there a reason for the difference in behavior?  Is this a gap in my understanding of how `.either` may differ in its contract from `.attempt`?  Or... is this actually a bug? 

If not a bug, perhaps there's some additional documentation that could be added to clarify this behavior... it's unexpected to me. 

Kind Regards,
Andy

**Comment by adamgfraser** [comment]
Hi Andy! Welcome!

That behavior is correct, though I can understand it is slightly different from Monix.

ZIO is polymorphic in its error type so its has a distinction between failures (errors that occurred that are reflected in the type signature) and defects (errors that occurred that are not reflected in the type signature). In your example above throwing an exception in `map` causes a defect because `map` is not supposed to fail. That exception is still caught by the ZIO runtime and managed but it is treated as a defect rather than a failure.

Monix is able to cheat a little bit in this regard because they always fix their error type to `Throwable` so they can just treat the exception thrown within `map` like any other exception, but that doesn't work if the user has a domain specific error type.

Normal error handling operators like `either` don't recover from defects because normally it doesn't make sense to do so except at the top of your application or module and you don't want to have to deal with the possibility of unanticipated failures in your normal error handling logic.

There are two ways to deal with this. First, there is a `mapEffect` operator that expects the function may fail and returns an effect with an error type of `Throwable`. That can be very useful when working with the `Task` type alias as your effect type. Second, you can use another set of error handling operators like `catchAllCause` and `catchSomeCause` that allow you to catch and recover from all errors.

Hope this helps! Feel free to reach out more here or Discord is a great place to ask questions and get answers in real time. We are also working on adding further documentation as part of ZIO 2.0 and this is definitely on my list of things to make suer we cover.

Have a great day!

**Comment by ALPSMAC** [comment]
Hey @adamgfraser - really appreciate the detailed response.  Looked at your Gitter before posting this here, but always find that to be sort-of hit-or-miss as far as getting answers goes and genuinely wasn't sure if I'd stumbled upon a bug.  Didn't know about the Discord - good to know - thank you. 

I was actually just about to write back and mention that strange enough `mapEffect` seemed to have the desired "effect" (pun intended).  

While I understand the polymorphic error type I guess when the types _match_ - that is - if I'm using the `Task` type alias so that my error channel is `Throwable` to begin with - it's pretty counter-intuitive to have to consider both cases still, and makes the transition path from Monix (and maybe Cats-Effect too?... although there's an interesting bit in their docs here: https://typelevel.org/cats-effect/datatypes/io.html#use-pure-functions-in-map--flatmap that makes me think perhaps not forever...) where `map` is usually "safe" regardless of what underlying functions may be called and how pure/impure they are to ZIO perhaps more painful than it would be otherwise. 

I'm sure such arguments for and against have already been rehashed many times though and I'm just late to the party, so for now I'll :shrug: and move on.  

Thanks again for the detailed clarification and apologies for my ignorance. :smile:

**Comment by adamgfraser** [comment]
Yeah really appreciate the question and no need to apologize. Learning is natural and we're always working to improve

As you say, I think throwing exceptions in code like `map` is not best practice and we do our best to manage it by catching those exceptions and capturing them as defects as well as providing operators like `mapEffect`. If you are doing things that can throw you can always wrap them with a `ZIO` constructor or there are operators that help you manage failures without throwing exception. For example you could use the `some` operator to shift the possibility of failure to the error channel so you could work directly with the value.

```scala
ZIO.succeed(someOptionalValue).some.map(value => ???)
```
