### ISSUE TITLE
with is too long

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#4844]
I suggest defining a type alias `&`, as in `Console & Database`. Works great:

```scala
import zio.console._
import zio.clock._
import zio.random._
import zio.{ App, ExitCode, URIO, ZIO }

object HelloWorld extends App {
  type &[A, B] = A with B

  override def run(args: List[String]): URIO[Console & Random & Clock, ExitCode] =
    myAppLogic.exitCode

  val myAppLogic: ZIO[Console & Random & Clock, IOException, Unit] =
    for {
      _    <- putStrLn("Hello! What is your name?")
      name <- getStrLn
      time <- currentDateTime.orDie
      _    <- putStrLn(s"Hello, $name, $time welcome to ZIO!")
    } yield ()
}
```

**Comment by adamgfraser** [comment]
Very interesting. The watch out and opportunity here is that `&` is already used in Scala 3 for essentially the same thing. But I'm thinking maybe we could put this in a Scala 2.x version specific file so that if users were writing cross-version code they would get our version on Scala 2.x and the Scala 3 version there. That would also get us and libraries using this closer to Scala 3 which would be nice.
