### ISSUE TITLE
MutableSpec: the TestEnvironment layer is shared between tests

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio#4997]
I ran into an issue where I believe the `TestEnvironment` is provided as a shared layer to the `MutableRunnableSpec`, causing the services (`TestClock` in particular) to be shared between the tests.

My simplest repro for this (printing the hashcode of the `TestClock` service) is:
```scala
object MutableSpec extends DefaultMutableRunnableSpec {
  suite("test") {
    testM("a") {
      for {
        t <- ZIO.service[TestClock.Service]
        _ <- putStrLn(t.##.toString)
      } yield assertCompletes
    }

    testM("b") {
      for {
        t <- ZIO.service[TestClock.Service]
        _ <- putStrLn(t.##.toString)
      } yield assertCompletes
    }
  }
}
```

prints:
```
942338196
942338196
```

While doing this with the `DefaultRunnableSpec` prints two different values every time.

I believe this is a bug, or was this behavior intended? /cc @fokot

**Comment by fokot** [comment]
@hmemcpy It looks like a bug `DefaultMutableRunnableSpec` should behave as `DefaultRunnableSpec`. I will take a look on it this week

**Comment by hmemcpy** [comment]
Cheers, appreciate it!

**Comment by adamgfraser** [comment]
@fokot Thanks for working on this!

**Comment by fokot** [comment]
The problem lies here
https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/DefaultMutableRunnableSpec.scala#L38
and here
https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/MutableRunnableSpec.scala#L148

I can change `provideLayerShared` to `provideLayer` and it would work the same as in `DefaultRunnableSpec`.

But problem is what if user wants to use  `MutableSpec extends MutableRunnableSpec(myOwnLayer)` and have custom `R`. Then his layer won't be shared.

I think there are two solutions.

1) Splitting it to two type parameters. The resulting `R` for test would be `TestEnvironment with CustomR` and `CustomR` would be shared.

2) Or ability to provide layers directly on the `tests` and `spec`
```
object MutableSpec extends DefaultMutableRunnableSpec {
  suite("test") {
    testM("a") {
      for {
        t <- ZIO.service[TestClock.Service]
        _ <- putStrLn(t.##.toString)
      } yield assertCompletes
    }.provideLayer(aaa)

    testM("b") {
      for {
        t <- ZIO.service[TestClock.Service]
        _ <- putStrLn(t.##.toString)
      } yield assertCompletes
    }
  }.provideSomeLayer(bbb).provideSomeLayerShared(ccc)
}
```
This is more work but is probably doable.

 WDYT @adamgfraser ?

**Comment by hmemcpy** [comment]
FWIW, I definitely would like a way to share my custom layer, and have the base `TestEnvironment` layer provided unshared. From my perspective, I wouldn't mind the extra type parameter, but I would definitely like to avoid providing the environment to each test/spec.

**Comment by hmemcpy** [comment]
But I don't really understand the nature of this bug. The test layer is defined as `ZLayer[TestEnvironment, Throwable, R]`, so it will provide (shared) just the user-defined R. The `TestRunner.default` itself calls `provideLayer` with the testEnvironment, so supposedly the testEnvironment should not be shared. I wonder where it gets "confused".

**Comment by fokot** [comment]
@hmemcpy The problem was that in `DefaultMutableRunnableSpec` was basically this code (when you combine the two links from my last comment)
```
(stack.head @@ aspect).toSpec.provideLayerShared(ZLayer.identity[TestEnvironment])
```
It gets the provided test layer shares it.

Now I split it to `R` and `TestEnvironment` and I do not share `TestEnvironment` only `R`. In this code there I use `MutableRunnableSpec` with `R`, `intLayer` is shared and created only once. Test layer is not shared tough
```
import zio.{Has, UIO, ZIO, ZLayer}
import zio.console.{Console, putStrLn}
import zio.test.environment.TestClock
import zio.test.environment.TestEnvironment

object layers {
  val intLayer: ZLayer[Console, Nothing, Has[Int]] = ZLayer.fromEffect(putStrLn("intLayer") as 12345)
}

//object MutableSpec extends DefaultMutableRunnableSpec {
object MutableSpec extends MutableRunnableSpec(layers.intLayer) {
  suite("test") {
    testM("a") {
      for {
        t <- ZIO.service[TestClock.Service]
        _ <- putStrLn(t.##.toString)
        i <- ZIO.service[Int]
        _ <- putStrLn(i.toString)
      } yield assertCompletes
    }

    testM("b") {
      for {
        t <- ZIO.service[TestClock.Service]
        _ <- putStrLn(t.##.toString)
      } yield assertCompletes
    }
  }
}
```

**Comment by hmemcpy** [comment]
Amazing, thank you so much!
