### ISSUE TITLE
Enrich ZHub's documentation

### ISSUE THREAD

**Issue by Lando-L** [zio/zio#5047]
I wanted to familiarise myself with the ZHub data type. While there are nice explanations of what the ZHub is and how it works, I couldn't find any usage examples. The only resources I found were the tests in ZHubSpec, which alone do not provide much information.

In specifically I was thinking I could do something like this:

```
for
    hub <- Hub.bounded[String](2)
    stream = ZStream.fromHub(hub)
     _ <- hub.publish("Hello")
     _ <- hub.publish("World")
     collected <- stream.runCollect
     _ <- ZIO.foreach(collected) { msg => console.putStrLn(msg) }
yield
     ()
```

But this program does not terminate.

**Comment by adamgfraser** [comment]
@Lando-L Thanks for checking out `ZHub` and for the feedback!

In your example, you need to be careful to wait to publish values to the hub until you are subscribed to the hub, because subscribers will only receive messaged published to the hub after they are subscribed. Also, remember that `runCollect` will collect values from a stream until the stream is terminated, which never happens here because more values could be published to the hub. So generally in an example like this you want to do something like `take(2).runCollect`.

Here is a version that addresses these issues:

```scala
import zio._
import zio.stream._

object Example extends App {

  def run(args: List[String]): URIO[ZEnv, ExitCode] =
    for {
      promise <- Promise.make[Nothing, Unit]
      hub     <- Hub.bounded[String](2)
      stream = ZStream.managed(hub.subscribe).flatMap { queue =>
                 ZStream.fromEffect(promise.succeed(())) *>
                   ZStream.fromQueue(queue)
               }
      fiber     <- stream.take(2).runCollect.fork
      _         <- promise.await
      _         <- hub.publish("Hello")
      _         <- hub.publish("World")
      collected <- fiber.join
      _         <- ZIO.foreach(collected)(console.putStrLn(_)).orDie
    } yield ExitCode.success
}
```

Notice that in the stream we subscribe to the hub, then signal that we have successfully subscribed by completing the promise, then start publishing values to the hub.

I will add some more examples to the documentation.

**Comment by adamgfraser** [comment]
@Lando-L Definitely! I submitted #5048 to try to make this a little nicer. I will also add some additional examples to the documentation and then we can close this. Thanks again for the feedback. That's how we get better.
