### ISSUE TITLE
Efficiency of shortcutting

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#525]
Follow-up to #508 

Methods such as `IO.map` and `IO.flatMap` currently switch over the IO's `tag`.
There may be more efficient ways of deciding code paths.

@jdegoes mentioned the Visitor Pattern
Subclassing may also be an option.

We should create some benchmarks to compare the different solutions.

**Comment by NeQuissimus** [comment]
It's all yours :) Don't worry about the timeline

**Comment by LGLO** [comment]
I've made first benchmarks. I'll present this after some cleanup and further investigation, but anyway I don't intend such experiment to be merged.

`self.tag @switch match {...` is faster than overriding `map` in subclasses. TBH I don't understand why, because `self.tag` is polymorphic call and then uses quick switch and `asInstanceOf`, when adding `def map` and overriding in subclasses shoul use just one polymorphic call.

I'll try to see how it looks in bytecode and ask colleagues for advice.

**Comment by LGLO** [comment]
@NeQuissimus https://github.com/scalaz/scalaz-zio/pull/530 although I don't think it proves anything.

**Comment by mschuwalow** [comment]
Sorry for butting in.
I think maybe using an explicit if-then-else might be another approach to consider.
Of course it isn't as nice but it might prove to be more performant, expecially if some code paths are taken far more often than others.

If a larger number of cases has to be considered using the numeric values of the tags and essentially doing binary search might be interesting. Something like:
```
    if (tag <= 4) {
      if (tag <= 2) {
        if (tag == 1) {
          ???
        } else {
          ???
        }
      } else {
        if (tag == 3) {
          ???
        } else {
          ???
        }
      }
    } else {
      if (tag <= 6) {
        if (tag == 5) {
          ???
        } else {
          ???
        }
      } else {
        if (tag == 7) {
          ???
        } else {
          ???
        }
      }
    }
```
