### ISSUE TITLE
ZManaged.race combinator is missing

### ISSUE THREAD

**Issue by heaven-born** [zio/zio#5264]
`ZManaged.race` combinator is missing. It would be also nice to have something like `raceLeft` and `raceRight` on both ZIO an ZManaged. It is useful when I have two effects that depend on each other by means of shared `Ref`, and I want to get result only from one of them, because the other one only produces value to shared `Ref`, but doesn't return anything useful.

**Comment by adamgfraser** [comment]
I'm not sure `race` is particularly meaningful to `ZManaged` because `race` implies that we will return the winner immediately and safely interrupt the loser, but in most cases the acquisition of a resource is uninterruptible so this just means we will wait for both resources to be acquired even if one resource is acquired first and then return one resource and finalize the other. Of course this could be different if one of the resources is interruptible or if you were to disconnect the interruption, but I wonder if this is the type of low level concurrency operator that makes sense for `ZIO` but not `ZManaged`.

Could certainly add `raceLeft` and `raceRight` variants.

**Comment by heaven-born** [comment]
I think `race` on `ZManaged` might be useful on "fake" `ZManaged` (.toManaged_). One `ZManaged` in for comprehension might force to convert there rest of the `ZIO` to `ZManaged`.

**Comment by adamgfraser** [comment]
This can now be done using the `race` operator on ZIO with the introduction of scopes.
