### ISSUE TITLE
Should ZIO.runtime be deprecated in favor of ZManaged.runtime?

### ISSUE THREAD

**Issue by andrewhamon** [zio/zio#5305]
So I recently learned that `ZIO.runtime` has some sharp edges. Take the following contrived example:

```scala
import zio._
import zio.console.Console

object MyApp extends App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val acquire = console.putStrLn("Acquiring").as("Hello").orDie
    val release = console.putStrLn("Releasing").orDie
    val managedLayer = ZManaged.make(acquire)(_ => release).toLayer

    for {
      myRuntime <- ZIO.runtime[Has[String] with Console].provideLayer(managedLayer ++ Console.live)

      _ = myRuntime.unsafeRun {
        for {
          myVal <- ZIO.service[String]
          _ <- console.putStrLn(myVal).orDie
        } yield ()
      }
    } yield ()
  }.exitCode
}
```

The console output is as follows:

```
Acquiring
Releasing
Hello
```

Which is bad.

The solution, of course, is `ZManaged.runtime`:

```scala
import zio._
import zio.console.Console

object MyApp extends App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val acquire = console.putStrLn("Acquiring").as("Hello").orDie
    val release = console.putStrLn("Releasing").orDie
    val managedLayer = ZManaged.make(acquire)(_ => release).toLayer
    val managedRuntime = ZManaged.runtime[Has[String] with Console]

    managedRuntime.provideLayer(managedLayer ++ Console.live).use { rt =>
      ZIO.succeed(
        rt.unsafeRun {
          for {
            myVal <- ZIO.service[String]
            _ <- console.putStrLn(myVal).orDie
          } yield ()
        }
      )
    }
  }.exitCode
}
```

Which acquires/releases things in the expected order:

```
Acquiring
Hello
Releasing
```

So, I'm starting to wonder, why not always use `ZManaged.runtime` instead of `ZIO.runtime`? Would it make sense to deprecate ZIO.runtime in ZIO 2.0?

**Comment by adamgfraser** [comment]
@andrewhamon Thanks for raising!

I think the use case for `ZIO.runtime` is actually pretty common.  In many mixed applications you need to create a `Runtime` to unsafely run effects and often the `Runtime` does not have any environmental requirements or only requires the `ZEnv` so there is no `acquire` or `release` action involved and so limiting access to the `Runtime` to being within the context of a `ZManaged` just creates unnecessary friction and implies something is resourceful when it is not.

In addition, the issue here doesn't really relate to the `Runtime` but with calling `provideLayer`. Notice that you aren't calling `provideLayer` on the `Runtime` itself but on a `ZIO` effect, which you could do with any `ZIO` effect and would result in the `acquire` action being done before that effect and the `release` action being done after. I think the right instinct to have is that `provideLayer` is like calling `use` on a `ZManaged` and will result in the resource being acquired around whatever you provide it to.

For this reason, best practice is typically to provide layers as close to the top of your application as possible, so in your example I think the most idiomatic way to write it would be something like the below, which uses `ZIO.runtime` and achieves your intended semantics.

```scala
import zio._
import zio.console.Console

object MyApp extends App {

  val acquire      = console.putStrLn("Acquiring").as("Hello").orDie
  val release      = console.putStrLn("Releasing").orDie
  val managedLayer = ZManaged.make(acquire)(_ => release).toLayer

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {

    for {
      myRuntime <- ZIO.runtime[Has[String] with Console]

      _ = myRuntime.unsafeRun {
            for {
              myVal <- ZIO.service[String]
              _     <- console.putStrLn(myVal).orDie
            } yield ()
          }
    } yield ()
  }.exitCode.provideLayer(managedLayer ++ Console.live)
}
```

**Comment by andrewhamon** [comment]
> I think the use case for ZIO.runtime is actually pretty common. In many mixed applications you need to create a Runtime to unsafely run effects and often the Runtime does not have any environmental requirements, only requires the ZEnv, or uses an environment that is provided at a higher level of the application.

Yeah, to be fair, I didn't actually bump into this issue naturally, I just discovered it as I was digging deeper/trying to increase my own understanding of how ZIO works in mixed applications.

Specifically, I was trying to determine if `ZIO.runtime` behaves at all like `Runtime.unsafeFromLayer`. It does not. The latter acquires any resources and keeps that acquisition until the JVM shuts down.

Still, I find it slightly surprising how easy it is to do the wrong thing. In most other cases that I can think of, where you call `provideLayer` doesn't impact the correctness of your program quite like this. That's part of the great composability of ZIO, the "fearless refactoring". And that composability feels very broken with `ZIO.runtime`.

But, again, I didn't actually bump into this in real-life code so perhaps it's a non-issue.

**Comment by adamgfraser** [comment]
Awesome that you have been digging into things!

Where you provide a layer can indeed be quite important but I don't think that is really related to the `runtime` operator. Any time you have an application the user can call `provideLayer` on any effect that is composed into the application. And that will very often have quite different semantics. Consider `ZIO.foreach(as)(f).provideLayer(layer)` versus `ZIO.foreach(as)(a => f(a).provideLayer)`. That's why we encourage providing layers at the top of your application if possible.

The same thing is true for `ZManaged` where the scope in which you `use` a `ZManaged` can quite significantly change the semantics of the program.

**Comment by andrewhamon** [comment]
The examples you gave don't lead to accessing a resource that has been released, though. Sure, it might be bad to acquire/release a resource in a loop, but that's a whole different class of error than accessing a resource that has been released.

I think `ZIO.service[A].provideLayer(a)` would lead to this exact same class of error as well. But that seems even more contrived than providing a layer to `ZIO.runtime`. And wrapping that in a ZManaged would be quite annoying as well since `ZIO.service` is handy even in pure zio apps, and perhaps even ubiquitous when using service pattern 2.0.

I am satisfied accepting that concessions are made for the sake of ergonomics, but I maintain that it is `ZIO.runtime` that is dangerous, quite unlike typical effects, since it provides a reference to (possibly managed) resources beyond the lifetime of the effect.

**Comment by adamgfraser** [comment]
I think you are right to focus on the concept of using a resource outside of its scope. Calling `provideLayer` on a `ZLayer`, like calling `use` on a `ZManaged`, defines a scope and it is not valid to use, directly or indirectly, a resource outside its scope. But we don't have the ability to enforce at the type level that a resource is not used outside its scope so the user can potentially leak a resource, for example by returning a reference to the resource from `use` or by accessing a service and then providing the layer, as you point out above.

Given that there are a variety of operators that could potentially allow a user to return a reference to a resource (basically any operator that uses a resource and any operator that accesses the environment outside the context of a managed effect) I tend to think this has to be handled at the level of creating the scope and the issue in the original example was providing the layer at that level and then using it rather than the `runtime` operator in particular, since you could just as easily have created the issue with another operator that accessed the environment.

**Comment by andrewhamon** [comment]
It can't be solved with the type system, but which of these do you think is easier to catch in code review?

```scala
runtime <- ZManaged.runtime[A].use { rt =>
  ZIO.succeed(rt)
}.provideLayer(a)
```

vs

```scala
runtime <- ZIO.runtime[A].provideLayer(a)
```

The latter seems much easier to slip through unnoticed, IMO, whereas the former is more obviously wrong. So obvious that I doubt it would even get written and make it to code review, perhaps.

Anyways, I'm splitting hairs here. Thanks for the discussion though! Now I know I should be a bit more suspicious of the placement of any `provideLayer`. (We do try to keep ours as high up in our app as possible).

Cheers 😄
