### ISSUE TITLE
Error handling regression in ZIO 1.0.11

### ISSUE THREAD

**Issue by christian-schlichtherle** [zio/zio#5439]
Hello,

first of all, thanks for this fantastic library. We have shortly migrated our code base from Cats Effect, FS2 Streams and Monix to ZIO and ZIO Streams and it's been an excellent experience so far - please keep up the good work!

The appended code and test work fine with ZIO 1.0.10 on Scala 2.13.6, but unfortunately the test code fails with ZIO 1.0.11. Now we get the error message:

```scala
Array(java.lang.NullPointerException, java.lang.IllegalStateException, zio.Cause$FiberTrace: Fiber failed.
A checked error was not handled.
java.lang.AssertionError
[...]
```

The error message itself looks odd because the opening parenthesis is not closed.

Here's the code (sorry I cannot make it shorter):

```scala
import zio._

final class Command[+A](private val workAndRevert: Task[(Task[A], Seq[Task[Unit]])]) {

  lazy val compile: Task[A] = {
    for {
      work -> revert <- workAndRevert
      result <- work.tapError { t1 =>
        revert.foldRight[Task[Unit]](UIO.unit) { (a, b) =>
          a.catchAll(t2 => UIO(t1.addSuppressed(t2))) *> b
        }
      }
    } yield {
      result
    }
  }

  def map[B](f: A => B): Command[B] = new Command(workAndRevert.map { case work -> revert => work.map(f) -> revert })

  def flatMap[B](f: A => Command[B]): Command[B] = new Command(
    for {
      workA -> revertA <- workAndRevert
      resultA <- workA
      workB -> revertB <- f(resultA).workAndRevert
    } yield {
      workB -> revertB.appendedAll(revertA)
    }
  )
}

object Do {

  def apply[A](work: => A): Command[A] = new Command(Task.succeed(Task.effect(work) -> Seq.empty))
}

object Undo {

  def apply(revert: => Unit): Command[Unit] = new Command(Task.succeed(UIO.unit -> Seq(Task.effect(revert))))
}
```

And here is the test code:

```scala
import org.scalatest.Assertion
import org.scalatest.matchers.should.Matchers._
import org.scalatest.wordspec.AnyWordSpec
import zio.Runtime.{default => rt}

import java.util.concurrent.atomic.AtomicInteger

class CommandSpec extends AnyWordSpec {

  "Incrementing a counter" should {

    val counter: AtomicInteger = new AtomicInteger

    val good: Command[Int] = {
      for {
        _ <- Undo(throw new IllegalStateException)
        i <- Do(counter.incrementAndGet)
        _ <- Undo(counter.decrementAndGet)
        _ <- Undo(throw new NullPointerException)
      } yield {
        i
      }
    }

    val bad: Command[Int] = {
      for {
        i <- good
        _ <- Do(throw new AssertionError)
      } yield {
        i
      }
    }

    def getDone(expected: Int): Assertion = {
      val work = good.compile
      counter.get shouldBe (expected - 1)
      rt.unsafeRunTask(work) shouldBe expected
      counter.get shouldBe expected
    }

    def getReverted(expected: Int): Assertion = {
      val work = bad.compile
      counter.get shouldBe expected
      intercept[AssertionError](rt.unsafeRunTask(work)).getSuppressed should matchPattern {
        case Array(_: NullPointerException, _: IllegalStateException) =>
      }
      counter.get shouldBe expected
    }

    "get done" in {
      getDone(1)
    }

    "get reverted" in {
      getReverted(1)
    }

    "get done again" in {
      getDone(2)
    }

    "get reverted again" in {
      getReverted(2)
    }
  }
}
```

Any help would be greatly appreciated!

**Comment by adamgfraser** [comment]
@christian-schlichtherle Thanks for reporting! Will take a look!

**Comment by adamgfraser** [comment]
@christian-schlichtherle This is related to #5364. Prior to `1.0.11` when we squashed a `Cause` down to a `Throwable` we added the `Cause` as the cause of the underlying root throwable.

So in your example above you have errors being thrown from three places (you are throwing `NullPointerException` and `IllegalStateException` and `AssertionError`), `AssertionError` was the "root error", you manually added `NullPointerException` and `IllegalStateException` as suppressed exceptions, and then ZIO added its `Cause` with information on the full cause of failure as the cause of the `AssertionError`. This is why your test worked when you asserted that the suppressed exceptions had two elements that were a `NullPointerException` and `IllegalStateException`.

Unfortunately, we can't in general add a cause to a `Throwable` because the cause can only be set once and many `Throwable` constructors already set it. We previously worked around that by reflecting accessing the cause and modifying it, but that functionality is being removed in Java 17, which is being released later this year.

To address this, we now instead add ZIO's cause as an additional suppressed exception, which is why in your example above your test is now failing, since there are three suppressed exceptions instead of the original two.

While we don't want to make unnecessary changes this was required so that ZIO can work for users across Java versions. The solution in your case is simply to modify the expectation in your test to assert that one additional suppressed exception exists.

Hope this helps and let me know if there is anything else I can do on this or as you are migrating to ZIO in general!

**Comment by christian-schlichtherle** [comment]
Thank you so much for the quick help! I can confirm everything works if I change my expectation to:

    Array(_: NullPointerException, _: IllegalStateException, _: Throwable)

Unfortunately, `zio.Cause.FiberTrace` is private so I can only match a `Throwable`, but that's OK.

Thanks again, I'm closing this issue.

BTW: If you would be interested to add something like `Command` to ZIO, let me know.

**Comment by adamgfraser** [comment]
No problem! It looks like the saga pattern if I am understanding it correctly. Have you looked at [zio-saga](https://github.com/VladKopanev/zio-saga)?

**Comment by christian-schlichtherle** [comment]
> No problem! It looks like the saga pattern if I am understanding it correctly. Have you looked at [zio-saga](https://github.com/VladKopanev/zio-saga)?

Oh, cool, somebody had the same idea. ;-) Thank again!

**Comment by adamgfraser** [comment]
Definitely! Maybe you can join forces. 😃
