### ISSUE TITLE
Add ReentrantLock

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5807]
This is a wrapper over `zio.stm.TReentrantLock` which forwards calls to it and commits immediately.

```scala
package zio.concurrent

trait ReentrantLock

object ReentrantLock
  val make: UIO[ReentrantLock]
```

**Comment by TobiasPfeifer** [comment]
I'd like to work on this

**Comment by regiskuckaertz** [comment]
@TobiasPfeifer ROCK'N'ROLL 🕺 🎸

**Comment by TobiasPfeifer** [comment]
@regiskuckaertz I'm busy with zio-schema now but want to finish this later. What kind of underlying representation is suitable? `TReentrantLock` uses a `LockState` structure. I think we can use the same construct in zio.concurrent but captured in an `AtomicReference` or a `Ref` (instead of `TRef`). What are your thoughts?

**Comment by regiskuckaertz** [comment]
@TobiasPfeifer Yes, I think it would be a fairly trivial translation as I believe none of the features of STM are really exploited (famous last words 😆 )
