### ISSUE TITLE
Add ConcurrentMap

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5808]
> A Map providing thread safety and atomicity guarantees.

A wapper over `java.util.concurrent.ConcurrentHashMap`:

```
package zio.concurrent

trait ConcurrentMap[K, V]:
  def compute​(key: K, remap: (K, V) => V): UIO[Option[V]]
  def computeIfAbsent​(key: K, map: K => V): UIO[V]
  def computeIfPresent​(key: K, remap: (K, V) => V): UIO[Option[V]]
  def replace​(key: K, value: => V): UIO[Option[V]]
  def replace​(key: K, oldValue: V, newValue: => V): UIO[Boolean]
  // ... and all other underlying methods

object ConcurrentMap:
  def make[K, V](kvs: (K, V)*): UIO[ConcurrentMap[K, V]]
  def make[K, V](size: Int): UIO[ConcurrentMap[K, V]]
```

### What about `TConcurrentMap`?

There is a question of whether a wrapper over the STM flavour would compete with the above in terms of performance... unlikely, but perhaps there are some optimisations that could be made to the code. One thing though, is that Java `Function`s and `Consumer`s are not functionals; they can and often have side-effects. This is really discouraged in ZIO, for obvious reasons, but what if internally we exposed the runtime? Then we could provide methods accepting at least transactional side-effects:

```scala
  def computeSTM​[R, E](key: K, remap: (K, V) => ZSTM[R, E, V]): ZIO[R, E, Option[V]]
  def computeIfAbsentSTM​[R, E](key: K, map: K => ZSTM[R, E, V]): ZIO[R, E, V]
  def computeIfPresentSTM​[R, E](key: K, remap: (K, V) => ZSTM[R, E, V]): ZIO[R, E, Option[V]]
  def replaceSTM[R, E]​(key: K, value: ZSTM[R, E, V]): ZIO[R, E, Option[V]]
  def replaceSTM[R, E]​(key: K, oldValue: V, newValue: ZSTM[R, E, V]): ZIO[R, E, Boolean]
```

**Comment by adamgfraser** [comment]
I think this one could be implemented by wrapping a mutable concurrent map and suspending operations in effect constructors.

**Comment by adamgfraser** [comment]
I think we could definitely do either way and wrapping the `ZSTM` data types does have an advantage that you could potentially expose the additional operators.

However, I think at least in this case the performance difference might be significant since there is a lot of optimization that went into the concurrent map implementation. And this is one you might call many times in your application if you are using it like a cache, for example if you are using it as a cache, relative to some other data structure that would more be used for control flow and called relatively infrequently.

But could definitely benchmark or implement with STM and then consider whether it made sense to do a more direct implementation.
