### ISSUE TITLE
Add scala collection-like methods to ConcurrentMap

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5889]
After #5808 is done, we can start adding operators that will bring the data structure closer to what a collection type looks like in Scala-land. Things like:

- ++, +
- collect, collectFirst, filter
- map, flatMap, fold, groupBy, grouped
- exists, forall
- etc

**Comment by oliveiosello** [comment]
I'll give this a shot!

**Comment by mijicd** [comment]
@oliveiosello Base implementation is in #5898. Hopefully the CI gods will allow me to merge it soon, but anyhow, you should be able to use it :).

**Comment by oliveiosello** [comment]
For similar reasons listed in the comments left on #5890, I've omitted collect, map, and flatMap. Additionally, I've broken the logic of filter into two methods, retainIf and removeIf, to disambiguate from the immutable methods and to be more consistent with `TMap` and `TSet`. Lastly, instead of ++, I'll add putAll shortly.

**Comment by regiskuckaertz** [comment]
@oliveiosello Thanks a lot for picking this up 😍 I think your arguments are valid, let me check your code.
