### ISSUE TITLE
Add Condition for creating waiting queues around locks

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5892]
Once #5807 is done, add
```scala
trait ReentrantLock:
  def newCondition: UIO[Condition]

trait Condition:
  // Wait for the condition to be fulfilled
  def await: UIO[Unit]
  // Wake up first fiber in the queue
  def signal: UIO[Unit]
  // Wake up all waiting fibers
  def signalAll: UIO[Unit]
```

This could be backed by a queue of promises, nice and easy.

**Comment by TobiasPfeifer** [comment]
I give it a try

@regiskuckaertz should this behave the same as the Java implementation of a `Condition`? There are 2 details that need to be considered:
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/ReentrantLock.html#newCondition--
- If this lock is not held when any of the Condition waiting or signalling methods are called, then an IllegalMonitorStateException is thrown.
- When the condition waiting methods are called the lock is released and, before they return, the lock is reacquired and the lock hold count restored to what it was when the method was called.

The first needs a check that the current fiber is holding the lock. That check need to be in place or otherwise releasing it on a waiting call is unsafe.
The part "the lock is reacquired and the lock hold count restored to what it was when the method was called" implies that reacquiring the lock after a signal call has precedence over other fibers trying to acquire the lock. Is that assumption correct?

**Comment by regiskuckaertz** [comment]
@TobiasPfeifer Yes, I think if we reuse the name, we should model the same semantics.

> Is that assumption correct?

I have the same reading yes.

**Comment by regiskuckaertz** [comment]
We should model breaking the invariant other than with an exception though.

**Comment by TobiasPfeifer** [comment]
To keep those guarantees, I'd need to add state to `ReentrantLock` that is already captured in `TReentrantLock.data`. I don't like the idea of tracking this state in `ReentrantLock` redundantly. I would rather keep following the pattern of delegating to `TReentrantLock` and implementing `newCondition` in STM. What do you think?

**Comment by regiskuckaertz** [comment]
Hmm, I don't think we want that. I would defer to @mijicd for any changes to STM: what are your thoughts?

**Comment by mijicd** [comment]
Yeah, we agreed to go without STM in `zio.concurrent` (semaphore is the only planned exception atm).
