### ISSUE TITLE
ZIO 1.0: DI layers closes before dependent fibers

### ISSUE THREAD

**Issue by maxwell912** [zio/zio#6016]
Java 11
Scala 2.13

```
import zio.{App, ExitCode, Has, UIO, URIO, ZIO, ZLayer, ZManaged}

object Main extends App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    for {
      f <- work.onInterrupt(ZIO.succeed(println("worker interrupt"))).fork
      _ <- f.join
    } yield ()
  }
    .exitCode
    .onInterrupt(ZIO.succeed(println("main interrupt")))
    .provideCustomLayer(live)

  trait Worker {
    def work: UIO[Nothing] = ZIO.unit.forever
  }

  def work: URIO[Has[Worker], Nothing] = ZIO.accessM[Has[Worker]](_.get.work)

  def live: ZLayer[Any, Nothing, Has[Worker]] =
    ZLayer.fromManaged(
      ZManaged.make(
        ZIO.succeed {
          println("acquire")
          new Worker {}
        }
      )(_ =>
        ZIO.succeed(println("release"))
      )
    )
}
```
When app closes, managed worker releases before fiber (which depend on worker) interrupt

**Output**

> acquire
main interrupt
release
worker interrupt

**Expected behaviour**
Fiber interrupts before dependency release
> acquire
worker interrupt
release

**Comment by adamgfraser** [comment]
I don't think this guarantee exists. Interruption of the inner fiber here takes place as part of automatic supervision, which occurs when the parent fiber's scope is closed immediately before returning its exit value. This happens after a fiber has completed any finalization logic associated with that fiber, which in this case includes execution of the release action of the layer.

In other words, the acquisition of the layer, execution of the effect, and release of the layer all occur on the main fiber unless something is forked. The main fiber is not "done" and going to interrupt its children until after that.

Not sure exactly what you are doing since I have a feeling you are not just forking a fiber and then immediately joining it but if you want to more explicitly control the finalization order I would suggest treating the fiber as more of a managed resource. Would be happy to help if you can provide an example a little closer to what you are trying to do.

**Comment by maxwell912** [comment]
Thanks for your reply
Your comment helped me to understand the right way of handling this situation, and i made sure this is expected behaviour
