### ISSUE TITLE
Random.Service.nextIntBounded fail on zero value

### ISSUE THREAD

**Issue by udzin** [zio/zio#6042]
Zio random.nextIntBounded do not allow exceptions because of effectTotal

`        def nextIntBounded(n: Int): UIO[Int] =
          ZIO.effectTotal(SRandom.nextInt(n))`

 but java Random throws an exception on zero values

`    public int nextInt(int bound) {
        if (bound <= 0)
            throw new IllegalArgumentException(BadBound);`

It should be not UIO, but Task.

https://github.com/zio/zio/blob/c36312f37bcd9fd682671656f67f842f84eac9e4/core/shared/src/main/scala/zio/random/package.scala#L77

**Comment by adamgfraser** [comment]
I don't think this is a sufficient condition for treating it as a typed error. One common use of the die channel is for the equivalent of an `IllegalArgumentException`, where fault is with the caller for providing an invalid input as opposed to the implementation.

For example, in `foreachParN` requesting a degree of parallelism less than one will result in a defect. In cases like this adding the failure to the error channel has little value in indicating how an application can fail since the failure can always be avoided by passing a value greater than zero.

It also clutters up type signatures since this error should not occur in code that doesn't have a bug. So it just forces everyone else to immediately handle the error, typically by converting it back to a fiber failure.

**Comment by udzin** [comment]
How about UIO[Option[Int]] if it is not total?

**Comment by luis3m** [comment]
I think same argument applies. There's little value in changing the signature to `UIO[Option[Int]]` when this scenario can be easily avoided. 

In my experience I've never been bitten by one of those scenarios where an illegal argument is passed. On the other hand, I've used many times functions like `nextInt` or `foreachParN` and it would be slightly annoying to handle the `None` case knowing I'm passing a valid argument.
