### ISSUE TITLE
Schedule#>>> results max delay instead of add

### ISSUE THREAD

**Issue by chikei** [zio/zio#6058]
While piping section of schedule document describe delay behaviour as `d1 + d2`, printed times from this snippet are about 2 seconds apart instead of 3 seconds:
```scala
val one = Schedule.once.addDelay(_ => 1.seconds)
val two = Schedule.once.addDelay(_ => 2.seconds)
val pt = clock.instant.flatMap(i => console.putStrLn(i.toString))
pt *> (pt.schedule(one >>> two))
```

this might be a doc bug or code bug (with a potential cause using maxOffsetDateTime [here](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Schedule.scala#L175))

**Comment by adamgfraser** [comment]
Hmmm, I'm not sure this is a bug.

Here is the relevant implementation:

```scala
def >>>[Env1 <: Env, Out2](that: Schedule[Env1, Out, Out2]): Schedule[Env1, In, Out2] = {
  def loop(self: StepFunction[Env, In, Out], that: StepFunction[Env1, Out, Out2]): StepFunction[Env1, In, Out2] =
    (now: OffsetDateTime, in: In) =>
      self(now, in).flatMap {
        case Done(out) => that(now, out).map(_.toDone)
        case Continue(out, interval, next1) =>
          that(now, out).map {
            case Done(out2) => Done(out2)
            case Continue(out2, interval2, next2) =>
              val combined = Schedule.maxOffsetDateTime(interval, interval2)

              Continue(out2, combined, loop(next1, next2))
          }
      }

  Schedule(loop(self.step, that.step))
}
```

As you point out right now we combine the intervals by taking the maximum of them. However, I do not think it is well defined in general to just add them. For one thing the intervals represent specific points in time rather than durations so we can't just add them. Potentially we could calculate the difference between those points in time and `now` and add them, but I don't think that is correct in general, for example if the schedules want to recur at a specific point in time instead of just a duration from the current time.

Conceptually what we potentially want to do is instead of feeding `now` to the second schedule feed the `interval` produced by the first schedule. This would correspond to feeding the second schedule a point in time one second in the future so then when it delayed by two seconds we would get the correct result.

However, that causes other tests to fail and I think runs into a conceptual issue that if we do that then I think if the first schedule wants to continue and the second is done we should continue with the delay of the first schedule, but then we have no more out value from the second schedule to emit when we emit done the next time.

**Comment by chikei** [comment]
or perhaps we could think about new combinator focused on additive delay in the sense `>>>` is more about piping input output and `andThen` is about follow first schedule until it done then follow second schedule ? (so description about duration of both on the website are wrong now)

**Comment by adamgfraser** [comment]
We should definitely update the website assuming we agree about this.

I'm not sure the concept of additive delay of the outputs of two schedules makes sense in general. A schedule outputs a point in time that it wants to recur at, say Tuesday April 1st at 10 AM. So we can certainly add a delay to an existing point in time. We can create a schedule at recurs at a point in time that is delayed a certain amount from the current point in time. But we can't "add" two different points in time.

**Comment by chikei** [comment]
Ah, that's fair point :)
