### ISSUE TITLE
TMap: allow to provide default value if key does not exist

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6084]
`TMap` should allow to provide a default value for the `value` parameter if a `key` does not exist. 
Also an (additional?) `get` operator should exist that allows to provide a default value. 

e.g. currently I have to do: 
```scala
myMap = TMap.empty[JobId, List[CalculationId]]
...
myMap.get(key).map(_.getOrElse(List.empty))
```
all the time, as `get` returns an `Option`. 
Additionally, it might be niceto add a `apply` method to `TMap` so I could do

```
 valueThatHasToBeThereOrIsDefaultValue <- myMap(key)
```

**Comment by alycklama** [comment]
This should already work? Could you maybe share more of your code to understand what you are trying to do?

```
val tx =
  for {
    tmap <- TMap.empty[String, Int]
    e    <- tmap.getOrElse("a", 99)
  } yield e

assertM(tx.commit)(equalTo(99))
```

**Comment by adamgfraser** [comment]
The problem is he wants to avoid having to do the `getOrElse` every time there. He wants something like:

```scala
val tx =
  for {
    map <- TMap.withDefault[String, Int](99)
    e   <- map.get("a")
  } yield e

assertM(tx.commit)(isSome(equalTo(99)))
```

However, this still isn't what he really wants because he doesn't want the `Option` there at all, which is why he is asking for an `apply` method that would not return the value optionally. The problem is that we have no static type information to know that it is safe to do this.

Possibly we could have a `WithDefault` subtype of `TMap` that wraps a normal `TMap` with a default value and expose additional operators on that but not sure it is worth the additional complexity.

**Comment by mijicd** [comment]
As mentioned by @alycklama, `TMap` exposes `getOrElse` which should be sufficient. If you're referring to something else, I guess we could add some `withDefault` constructor, and deal with the callsite. `apply` is omitted intentionally, as it's an unsafe method present on existing collection.

**Comment by domdorn** [comment]
hmmm.. looks like IntelliJ used a older version while I already upgraded in sbt.. migrated to `getOrElse`, thx!
