### ISSUE TITLE
ZPipeline has a really impenetrable type-signature and doesn't infer well.

### ISSUE THREAD

**Issue by freskog** [zio/zio#6122]
I recently started exploring the ZIO Streams encoding for ZIO 2. I like the idea of ZPipeline, but I find that working with this encoding to be more cumbersome that just using the ZStreams directly.

1) The types don't infer as well as with streams

The following sliding method composes two ZPipelines. I needed to specify the types everywhere to do this

```scala 
def sliding[R,E,A](n:Int) =
    scan[A, Chunk[A]](Chunk.empty) {
      case (acc, a) => if(acc.size < n) acc.appended(a) else acc.drop(1).appended(a)
    } @@ dropWhile[Chunk[A]](_.size < n)
```

I couldn't get either VS Code nor Intellij to print out the correct method signature (it was abbreviated in VS Code, and intellij shows red squiggles). Contrast this to the implementation directly on a stream

```scala
  def sliding[R,E,A](stream:ZStream[R,E,A], n:Int):ZStream[R,E,Chunk[A]] =
    stream.scan[Chunk[A]](Chunk.empty) {
      case (acc, a) => if(acc.size < n) acc.appended(a) else acc.drop(1).appended(a)
    }.dropWhile(_.size < n)
```

Here I only needed to specify one type for scan (I think that would probably infer correctly in Scala 3). Both intellij and vs code were able to infer the correct method return type.

Currently I'm forced to use ZPipeline, because certain operations are only available as ZPipelines (utf8decode and splitLines for example). 

What I like about this encoding is that I can separate the processing of streams from the source of the stream, but the typesignature of ZPipeline and additional overhead of having to add type ascriptions everywhere negate the benefit for me at least.

**Comment by adamgfraser** [comment]
The issue is with the current `ZPipeline` encoding we are trying to express stream transformations that don't necessarily depend on the specific type of stream elements. So in the case of `sliding` we don't want to really say that for some specific `R`, `E`, and `A` that we can pass a sliding window but rather that for any stream type we can transform it into the same stream type with a chunk of elements.

This is what that would look like:

```scala
  /**
   * Creates a stream that emits a sliding window of elements emitted by this
   * stream.
   */
  def sliding(windowSize: Int, stepSize: Int): ZPipeline.WithOut[
    Nothing,
    Any,
    Nothing,
    Any,
    Nothing,
    Any,
    ({ type OutEnv[Env] = Env })#OutEnv,
    ({ type OutErr[Err] = Err })#OutErr,
    ({ type OutElem[Elem] = Chunk[Elem] })#OutElem
  ] =
    ???
```

The advantage is this lets us express a transformation as a value that really reflects its fully generality and doesn't requires to specify unnecessary type parameters like we sometimes do with `ZSink`.

At the same time I think the level of complexity definitely pushes the border of what is useable. I think the current encoding probably pushes us in the direction of how test aspects are used, where are would say provide a quite good user experience to work with aspects defined for you but most people will not want to implement aspects themselves.

Here the signature above is already being implemented and would to a certain degree be a "better" type signature because it expresses the full generality of this type of stream transformation as a value. At the same time, it does create a situation where I would not expect users to implement pipelines in general due to the complexity of the type signature, which is unfortunate.

One tactical proposal to address is just to say that all pipeline operators should also be stream operators. This reflects the idea that pipelines are not "fundamental". They are just reifications of stream transformations because as you say it is sometimes nice to be able to treat stream transformations as a value. That way there would always be a fallback where you could use the operators on a stream directly.

More aggressively, we could revert `ZPipeline` to the more monomorphic encoding as a function from stream to stream. That would necessitate having separate pipeline and stream aspect data types, or possibly we would rename pipeline back to transducer at that point, but would make these type signatures more approachable.

**Comment by freskog** [comment]
I found that even just composing existing pipelines (without having them attached to a stream) requires me to put type-ascriptions. I think that's a deal breaker for my main use-case which is really just to separate the transformations from the source. 

I also find that VS Code will show ALL inferred types, making the feature useless in combination with ZPipeline compositions for example look at the following

![Screenshot 2021-12-02 at 14 48 51](https://user-images.githubusercontent.com/453251/144445038-6d66d9ba-2fb9-4007-b445-b53fbb63ea0b.png)

If I switch on type inference in VS Code I get the following

![Screenshot 2021-12-02 at 14 49 35](https://user-images.githubusercontent.com/453251/144445170-a88b27a8-ad33-40ab-9693-69b8f2ecec04.png)

With something a little more complicated (even just a little more complicated) like:

```scala
  val part2 =
    sliding[Any, Nothing, Long](3) @@ map[Chunk[Long], Long](_.sum) @@ sliding(2) @@ increasingOnly
```

.. becomes completely unreadable when I switch on type inference:

![Screenshot 2021-12-02 at 14 51 22](https://user-images.githubusercontent.com/453251/144445492-e6b4c452-c8a6-45e3-8b2c-5414b5c38ff3.png)

I would be in favour of a different encoding that allows me to achieve the same thing, or just enforcing that all operators are available on at least ZStream.

**Comment by adamgfraser** [comment]
You actually don't want to implement `sliding` in terms of `scan` because `scan` is specialized to a particular input and output type whereas `sliding` can be general to any input and output. You can implement `sliding` like this:

```scala
  /**
   * Creates a stream that emits a sliding window of elements emitted by this
   * stream.
   */
  def sliding(n: Int): ZPipeline.WithOut[
    Nothing,
    Any,
    Nothing,
    Any,
    Nothing,
    Any,
    ({ type OutEnv[Env] = Env })#OutEnv,
    ({ type OutErr[Err] = Err })#OutErr,
    ({ type OutElem[Elem] = Chunk[Elem] })#OutElem
  ] =
    new ZPipeline[Nothing, Any, Nothing, Any, Nothing, Any] {
      override type OutEnv[Env]   = Env
      override type OutErr[Err]   = Err
      override type OutElem[Elem] = Chunk[Elem]
      override def apply[Env, Err, Elem](
        stream: ZStream[Env, Err, Elem]
      )(implicit trace: ZTraceElement): ZStream[Env, Err, Chunk[Elem]] =
        stream
          .scan[Chunk[Elem]](Chunk.empty) { case (acc, a) => if (acc.size < n) acc.appended(a) else acc.drop(1).appended(a) }
          .dropWhile(_.size < n)
    }
```

Note that `scan` and `dropWhile` are both already defined on `ZStream` so you can define sliding as an operator on `ZStream` or as a function from stream to stream using that today.

That being said, definitely agree that needing to know about that is not ideal.

**Comment by freskog** [comment]
Ah I think I get the idea behind ZPipeline with that example. That's really flexible!

I think don't think we'll use that for our application code, it would be to much overhead to explain. I'm happy to go back to using just ZStream (I think that getting folks new to ZIO to grok streams will be much easier as well if we restrict the usage to ZStream & ZSink, which covers pretty much all of our use-cases).

**Comment by narma** [comment]
I just want to support what @freskog saying here. 
First of all, I love ZIO for its excellent ergonomic of using in implementing real-world stuff, but ZPipeline looks like a step back in this purpose. Just take a look at IDEA type suggesting, it looks terrible
![image](https://user-images.githubusercontent.com/91045/145488593-6d9ab0c8-6c77-415e-9b91-fddd37c9f529.png)

**Comment by adamgfraser** [comment]
@narma Thanks for your feedback! The actual type will infer flawlessly there but agree that IDE message is terrible. Thinking about this.
