### ISSUE TITLE
zio 2.0: provide equivalent of zio-logging `zio.logging.log.trace`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6147]
zio-logging has `zio.logging.log.trace` .. an equivalent for this is missing in zio 2.0-m6-2

**Comment by adamgfraser** [comment]
Higher level logging functionality will continue to be provided by `zio-logging` and will be available when `zio-logging` publishes a release candidate for ZIO 2.0 after we publish a release candidate of ZIO 2.0.

**Comment by adamgfraser** [comment]
Looked into this a little more. We just don't have a concept of a "trace" log level right now. There are obviously different logging frameworks but I think the one we are currently using is relatively common, even though it is not the same as the one `zio-logging` used. A `logTrace` operator would also be a little confusing because it is not clear from the name whether it is referring to the trace log level or to logging a ZIO stack trace.

It is fairly easy to define your own log level if you want to and I imagine some logging libraries will do so but we could certainly add an additional  log level if we wanted.

**Comment by domdorn** [comment]
in other logging libraries (log4j, logback, slf4j) the level that is more fine grained then DEBUG is called TRACE. However, I see that this may cause confusion because we already use the term "trace", so how about we call it `logFine`?

https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm 
http://logback.qos.ch/manual/architecture.html
https://www.baeldung.com/slf4j-with-log4j2-logback#Further

**Comment by adamgfraser** [comment]
We already have a runtime log level so I exposed that.

**Comment by domdorn** [comment]
hmm... I honestly haven't heard of a "runtime loglevel" before.. searching for it also only yields results for "change a loglevel at runtime".. could we use a more fitting name?

**Comment by adamgfraser** [comment]
Yeah that's fine.
