### ISSUE TITLE
One confused Scala dev suggesting better way to evangelise ZIO's `E` to the community

### ISSUE THREAD

**Issue by V-Lamp** [zio/zio#6172]
Hi, I started playing around localy with IO and clearer a big confusion/unknown I had by reading/watching videos about it.
Bit of background: I am a staff engineer at my job, very confortable with FP, effects, typeclasses and so on, but still got confused, so more may be in the same plane.

ZIO, departs more from the "lazy cancellable future" mental model of Cats/Monix by having an explicit error type (the environment is less confusing imo). 
You often describe ZIO as **instead** of having untyped errors, you control the error types and that unhandled exceptions are propagate further up to be handled (how?). The question in my head was then "but how do you then deal with unexpected errors?" That is until I found after quite some time googling the `*Defect` methods and had my aha moment. But setting up a local project with ZIO to get this answered is not ideal, hence this good-willing feedback 🙂 

What if you said that ZIO has typed errors **in addition** to the usual untyped exception handling. In a sense it has **two** error channels! One for business logic, expected errors, and one for unexpected bug-like exceptions. It is not a different way of doing effects (that may be incopatible with one's codebase) but a strict superset of Future/Cats/Monix, effectively `ZIO[R, E, A] ~~> R => Future[Either[E, A]]` (if you squint and forget about cancellation etc..).

Also, I would suggest that `*Defect` methods are more prominent in blogs and videos to make it clear that the untyped error channel is still there, just less used because a lot of use cases are now covered by the typed error channel. 

Hope this helps, and thanks for all the good work!

**Comment by adamgfraser** [comment]
@V-Lamp Thank you for the feedback! That is really helpful.

Yes as you say there are definitely two error channels, the "typed" error channel and the "untyped" one. I think the intention of some of the descriptions around this is to emphasize the typed error channel because that is what is different from some other functional effect systems, but you are right that is in addition to an untyped error channel. I think usually the typed error channel is the "first" and the untyped error channel is the "second" one but this is good feedback.

The other thing that I think goes into this is the philosophy about when you deal with unexpected errors.

If you are using the typed error channel for known failure modes then the untyped failures are by definition unknown and unanticipated, so in general it is hard to handle them in a meaningful way other than something like logging them, which can also be done at the top of the application as part of the unhandled error handler.

Now clearly there are situations where you do want to handle these errors,. Sometimes this is because you want to do something like run a finalizer regardless of what error occurred. Other times it is at the boundary of your application where an error that can't be handled at one level can be handled at a higher level. But I think that is typically why the typed error channel is emphasized more because it should be used more for "everyday" error handling and the untyped error channel used for "exceptional" error handling.

Thanks again for the feedback! It really helps and reflects what other people are thinking and may not be saying. Will think about incorporating this into the way I talk about these concepts.
