### ISSUE TITLE
ZLayer Deprecations Point to Missing `toLayer`

### ISSUE THREAD

**Issue by jamesward** [zio/zio#6206]
ZIO 2.0.0-RC1

A number of methods on ZLayer have a deprecation:
```
@deprecated("use toLayer", "2.0.0")
```

But `toLayer` doesn't seem to exist.

**Comment by adamgfraser** [comment]
@jamesward Hi! It is actually an operator on `ZIO` and `ZManaged`. So you can replace the different ZLayer constructors with this pattern:

```scala
(for {
  a <- ZIO.service[A]
  b <- ZIO.service[B]
} yield CLive(a, b)).toLayer
```

This pattern scales up with you because you can switch to `ZManaged.service` when you need finalization and do any other effects in setting up your service in the for comprehension. Note that now you can also do the following which I think is even nicer and maybe we should point people to that because it is an actual constructor on `ZLayer`.

```scala
ZLayer {
  for {
    a <- ZIO.service[A]
    b <- ZIO.service[B]
  } yield CLive(a, b)
}
```

**Comment by jamesward** [comment]
Thanks Adam.  That is super nice.  I wonder if that deprecated message could provide more details on that.

**Comment by kascakm** [comment]
Browsing the history, seems this was fixed by https://github.com/zio/zio/pull/6522 by removing all the deprecated methods.
