### ISSUE TITLE
Wrong ZLayer Warning

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6208]
While I was working with ZIO Environment I encountered the following issues

1. The following program is assumed to compile without warning:

```scala
import zio._

sealed trait Foo
object bar extends Foo
object baz extends Foo

object Foo {
  val layer =
    ZLayer.fromZIOEnvironment(
      UIO(
        ZEnvironment(
          Map(
            "bar" -> bar,
            "baz" -> baz
          )
        ) 
      )
    )
}

object Main extends ZIOAppDefault {
  def run = ZIO.serviceAt[Foo]("bar").provideCustom(Foo.layer)
}
```

But it prints the following warning message:

```
──── ZLAYER WARNING ──────────────────────────────────────────────────

 You have provided more than is required.
 You may remove the following layer:
   
   1. ZEnv.any

  
──────────────────────────────────────────────────────────────────────


  def run = ZIO.serviceAt[Foo]("dev").provideCustom(Foo.layer)

```

It compiles with `ZIO#provideCustomLayer` version, so I think it relates to the `ZLayer` macro.

2. Rather than stopping the compilation phase, I think it would be better to allow the compiler to continue compilation after a warning to the user.

**Comment by hmemcpy** [comment]
I have an additional example from my attempt to make one of the mdoc snippets to compile:

```scala
import zio._
import zio.test.{test, _}

object Foo {
  val layer: ZLayer[Any, Nothing, Int] = ZLayer.succeed(1)
  val test1: ZSpec[Int, Nothing] = test("my test")(assertTrue(true))
  test1
    .provideCustomShared(layer)
}
```

Compiling this emits a warning:
![image](https://user-images.githubusercontent.com/601206/148539181-208f3649-78de-4ca9-9134-2f563fd6ad9a.png)

Incidentally, this also currently breaks mdoc with the following error:
```
mdoc.internal.cli.FileException: /Users/hmemcpy/git/zio/docs/datatypes/test/index.md
Caused by: java.lang.IllegalArgumentException: Unknown ansi-escape [2m at index 203 inside string cannot be parsed into an fansi.Str
	at fansi.ErrorMode$Throw$.handle(Fansi.scala:419)
	at fansi.ErrorMode$Throw$.handle(Fansi.scala:407)
	at fansi.Str$.apply(Fansi.scala:272)
	at fansi.Str$.implicitApply(Fansi.scala:227)
	at mdoc.internal.io.ConsoleReporter.warning(ConsoleReporter.scala:59)
	at mdoc.internal.io.ConsoleReporter.warning(ConsoleReporter.scala:55)
        ...
```

Despite this snippet (very similar to it) compiling with `mdoc:compile-only`, mdoc's reporter still collects the warnings during compilation, and it seems that fansi (the ANSI rendering library that mdoc uses) doesn't like the escape sequences produced by the ZLayer warning, causing it to crash.
![image](https://user-images.githubusercontent.com/601206/148539590-c81d0fba-359c-4976-9d93-d713799bbe80.png)

Anyway, the issue here is the wrong warning emitted from compiling. Perhaps it's worth having the macro check for ZIO-specific layers and not report them?

**Comment by khajavi** [comment]
Here is another one related to this issue:

```scala
val cakeLayer: ZLayer[Spoon, Nothing, Cake] =
  ZLayer.makeSome[Spoon, Cake](
    Cake.live,
    Chocolate.live,
    Flour.live,
    Spoon.live
  )
```

Current error message:

```
  ZLayer Wiring Error  

❯ Spoon is provided by multiple layers:
❯ — ZLayer.environment(Tracer.autoTrace)
❯ — Spoon.live


    ZLayer.makeSome[Spoon, Cake](
```
I think it would be better to have an error message like this:

```
  ZLayer Wiring Error  

 You have provided more than is required.
 You may remove the following layer:
   
   1. Spoon.live

    ZLayer.makeSome[Spoon, Cake](
```
