### ISSUE TITLE
ZIO 2.0: ZLayer.apply for ordinary values

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6217]
I think it would be better to have a consistent API for using `DataType.apply` instead of `DataType.succeed` for ordinary values. So as a user when I can write `ZIO(3)` instead of `ZIO.succeed(3)`, I would like to do the same for `ZLayer`. 
So, could this be considered reasonable?

**Comment by adamgfraser** [comment]
I think the problem is that we really want `ZLayer.apply` for converting `ZIO` and `ZManaged` values to `ZLayer`:

```scala
ZLayer {
  for {
    a <- ZIO.service[A]
    b <- ZIO.service[B]
  } yield CLive(a, b)
}
```

We could get around this by using path dependent types and a `ZLayer` constructor pattern to support all three uses of `apply`, but personally given the complexity that already exists in this area I would prefer to avoid making these very commonly used method signatures harder to understand.

Note that even with `ZIO` itself `ZIO.apply` is not equivalent to `ZIO.succeed` but to `ZIO.attempt`, though of course we could change that. But I think in general trying to use `apply` for `succeed` is going to cause issues when we want to use `apply` for something else (e.g. `apply` for `ZManaged` converts an effect that returns a value and a finalizer into a `ZManaged`, `apply` on `ZStream` takes a variable arguments list of elements, etc...).

**Comment by khajavi** [comment]
That makes sense to me. Thank you!
