### ISSUE TITLE
TestClock not adjusting with unsafeRun

### ISSUE THREAD

**Issue by codingismy11to7** [zio/zio#6255]
I have some ZIO2 test code that is mocking a blocking interface during unit tests. Everything works fine, but while trying to backport the same code to ZIO 1.0.13 I find that every run hangs and gets the message

> Warning: A test is advancing the test clock, but a fiber is not suspending, which may result in the test hanging. Use TestAspect.diagnose to identity the fiber that is not suspending.

Am I doing something I'm not supposed to? Is there some other way of doing this that is supported on ZIO1?

Here's the ZIO2 test, ZIO1 just involves changing `attemptBlocking` to `effectBlocking` and `test` to `testM`:

```scala
object ClockTest extends DefaultRunnableSpec {

  final case class Thing(rt: Runtime[Clock]) {
    def takesAWhile: Boolean = rt.unsafeRun(ZIO.sleep(5.seconds).as(true))
  }

  final case class Outer(thing: Thing) {

    def finishedWithin10 =
      attemptBlocking(thing.takesAWhile).timeout(10.seconds).someOrElse(false)
  }

  private def createOuter = ZIO.runtime[Clock].map(Thing).map(Outer)

  final val spec = test("clock") {
    for {
      obj <- createOuter
      fib <- obj.finishedWithin10.fork
      _   <- TestClock.adjust(10.seconds)
      res <- fib.join
    } yield assert(res)(isTrue)
  }
}
```

**Comment by adamgfraser** [comment]
@codingismy11to7 The `TestClock` is not going to work if you are unsafely running effects like that.

The issue is that for correctness the `TestClock` needs to wait until all fibers have entered into a suspended state to ensure that it is safe to advance the clock.

However, when we unsafely run an effect there is now something going on that is no longer in the ZIO runtime and can't be tracked in the same way. In this case we have a fiber that is still in a running state synchronously blocking for a result to be available and don't have any way to know if that result will be available momentarily or not at all.

That is what that error message is trying to tell you. At least for me locally this doesn't work on the `series/2.x` branch either.

**Comment by codingismy11to7** [comment]
that's wacky, admittedly I' running a zio2 build from a couple of weeks ago, but this test works fine for me every time (and the original test it's based on that's doing real things).

is there any way to test this scenario? does unsafeRunAsync have the same effect? if not I could hack something together with that...

(also suppose I can just try it)

**Comment by codingismy11to7** [comment]
yeah unsafeRunAsync can't be used either.

**Comment by codingismy11to7** [comment]
should I just close this? is there any way to mock out legacy libraries while staying inside of zio-test boundaries? (this came up while trying to write a test for a `dev.zio` library that is having an old apache commons library do its heavy lifting; I want to override some of its functionality to make sure the zio library's logic around it is sound)

also curious why this code i posted works with 2.0.0-RC1+52-ab11bde7 on my machine and not on your machine with presumably a version that's only slightly newer, did something change wrt this very recently

**Comment by codingismy11to7** [comment]
adam can't think of a way to accomplish this. still confused why it worked on my version of zio2, but oh well
