### ISSUE TITLE
Revert Back to ZIO 1.0 Naming Convention

### ISSUE THREAD

**Issue by RD-100** [zio/zio#6317]
This is just an opinion but the new naming of some of the methods in ZIO 2.0, particularly the ones suffixed with `ZIO`, is ugly to say the least.

E.g.

ZIO.whenCaseM | ZIO.whenCaseZIO
ZIO.whenM | ZIO.whenZIO
ZIO.unlessM | ZIO.unlessZIO
ZIO#unlessM | ZIO#unlessZIO
ZIO#whenM | ZIO#whenZIO
ZIO#repeatUntilM | ZIO#repeatUntilZIO
ZIO#repeatWhileM | ZIO#repeatWhileZIO
ZIO#retryUntilM | ZIO#retryUntilZIO
ZIO#retryWhileM | ZIO#retryWhileZIO
ZIO.replicateM | ZIO.replicateZIO

There is just too much ZIO everywhere i.e. Libraries names are prefixed with `zio` and now these methods have it as well. Can we cut down the zio noise please in the naming of things? I get it, we are using ZIO, and it's a great library :smile: 

Also it seems to me, and again this just opinion, that there is an effort to hide the FP identity of this library e.g. renaming foldM to foldZIO. The naming of methods in ZIO 1.0 was pretty much on the money on most things. 

Can we get a poll to see what the community thinks about reverting back to the zio 1.0 naming conventions at least?

**Comment by adamgfraser** [comment]
Thanks for your feedback! Naming is always hard and not everyone is going to like any name.

ZIO isn't trying to hide functional programming but it is trying to address the needs of a wider set of users than the traditional group of functional programmers. You shouldn't need to know what a monad is to be an extremely productive and happy ZIO user.

The methods with `M` suffixes are a perfect example of this. What does `M` mean? I think something along the lines of "in the context of a monad". But there is no meaningful answer to that question if you don't know what a monad is. So then we have a whole set of important operators in our library that are just suffixed with a random letter as far as new users of our library who don't have a functional programming background are concerned, which is not acceptable. Now these methods mean they return a `ZIO` versus an ordinary value, which is extremely easy to teach.

When we made this change we realized that this was also often causing us to be imprecise. Do these operators use a `ZIO`, a `ZManaged`, a `ZSTM`, or a `ZStream`? We now have a clearer ability to specify with operator names exactly which data type is involved.

While it is great to get feedback on Github issues, these changes have come out of countless conversations, workshops, and discussions in a variety of forums including many people who wouldn't regularly comment on Github so I strongly believe they take us in the right direction. I also tend to think that it does not make sense to make further significant naming changes at this point in the ZIO 2 release cycle.

**Comment by RD-100** [comment]
OK, no worries. Death by a thousand ZIO's in my code it is! :joy:

**Comment by octavz** [comment]
My 2c: 

 With this rule we should rename `fold` because a person should not know about catamorphisms/recursion schemes to use ZIO :). 
Microsoft renamed `map` -> `Select`, `filter` -> `Where` and `flatMap` -> `SelectMany`  or LINQ instead of `do notation` in C# and that kept back a generation of programmers away from FP. 

I think you should not underestimate the drive for knowledge of a FP user, if they got to ZIO you can be sure they already know what a Monad is because otherwise there would be no `for/yield` notation or `flatMap` understanding.  
Even if they don't know perhaps they should start looking into it and `xxxM` might be a good start.

Thanks!

**Comment by adamgfraser** [comment]
We have talked about that! 😃

One thing that I find has been helpful to think about is what is used in the Scala standard library. We could debate whether `flatMap` is the best name for that thing but it is used in the Scala standard library and I actually find it is pretty straightforward with talking about monads at all ("it maps and then flattens the thing"). Likewise `fold` and for comprehensions exists in the Scala standard library. But you won't find any `M` suffixes!

So I think you work with the language you are in and build on the knowledge people have from that.

**Comment by BardurArantsson** [comment]
I'm not seriously suggesting it's worth doing, but I was surprised that the suffix wasn't simply Z:

* forZ
* foldZ
* ...

To me it reads a lot better than the full forZIO, foldZIO, etc. and it's enough of a signpost.

**Comment by adamgfraser** [comment]
I think one motivation here that isn't as obvious from looking at a single name change is the way this interacts with having various different effect types in the ZIO ecosystem. We have `ZIO` but we also have `ZManaged`, `ZStream`, `ZChannel`, `ZSink`, `ZQuery` in ZIO Query, `Http` in ZIO HTTP, and so on. So `mapZ` doesn't really tell you which one of these effect types you are mapping with and doesn't given us a consistent naming convention when we have multiple variants, for example `serviceWithZIO`, `serviceWithManaged`, `serviceWithStream`. By spelling out these names we make it very clear what is going on with these operators and give ourselves the ability to be explicit about which effect type we are using.

**Comment by octavz** [comment]
There is also the option to have both, the current and the ZIO ones and let people choose. 
Is the same with operators vs methods. 

The magic with `xxxM` is that it makes sense for *all* monadic types ZIO, ZManaged, STM... and also is Google-able.

**Comment by adamgfraser** [comment]
I think having two different ways to do the same thing is the opposite of what we are going for. The "makes sense for all monadic types" is actually the problem because it doesn't give us a consistent naming convention to use for operators like `ZStream.serviceWithZIO`, `ZStream.serviceWithManaged`, and `ZStream.serviceWithStream`. They're all monads, so saying we're doing it in a context of a monad doesn't tell us much!

**Comment by regiskuckaertz** [comment]
Respectfully, the notion of "ugly" is not very objective and will not rally around enough people, I suggest you build a valid use case by proving this has underminded learnability for a large group of people.

I don't think the argument has legs to stand to begin with. Even in Haskell this naming convention is not enforced, e.g. [`Array`'s `Foldable` instance](https://hackage.haskell.org/package/base-4.13.0.0/docs/src/Data.Foldable.html#line-369). These `—M` names only make sense when someone is coding using generic types with contraints like `Monad`, because it's only then that the author does not care if it's a ZIO, a ZStream or a ZManaged. Right? If I was writing a program with arrays, I would refer to the Haddock for arrays and discover `foldlElems` et al; is there an issue with that?[1]

So perhaps these aliases don't have a home in this repo but do in cats-interop and zio-prelude.

[1] well, yes, it turns out the scaladoc for zio is the worst I have ever seen because you need to (1) pick the library name from the dropdown (which is indexed with the scala version – try getting zio-test 2.12 🤯) and (2) pick the artifact version then (2) navigate to where you wanted to initially

**Comment by jdegoes** [comment]
It's definitely more typing, but with that more typing comes greater consistency and greater predictability, as well as fewer Haskellisms.

To me, the most compelling point about the new name changes is that we no longer have to pick, e.g. `mapM` to be the ZIO-variant or the STM variant. Rather, we can have multiple methods: `mapZIO`, `mapManaged`, etc., and you know what you're getting with each one, without even looking at the type.

Though somewhat painful to transition (hopefully eased by the Scalafix migration), and though somewhat more characters to type (auto-complete FTW), I think in the long run, the new more consistent naming convention will prove to be the best choice for productivity and adoption.
