### ISSUE TITLE
Enforcing Users to Handle All Expected Errors

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6363]
The current `ZIOApp` has the following run method:

```scala
trait ZIOApp {
  def run: ZIO[Environment with ZEnv with ZIOAppArgs, Any, Any]
}
```

It does not require the user to handle expected errors. I think it's better to prevent compiling applications which can fail. Explicitly instructing users to distinguish between expected and unexpected errors would be a good practice. So, when a user cannot handle a typed error, the user should turn it into an unexpected error by using the `ZIO#orDie` combinator.

**Comment by adamgfraser** [comment]
There is a trade off here between promoting doing the "right" thing and getting users going quickly. What you are proposed is basically a variant of the signature of run `run` method in ZIO 1.0 which returned a `ZIO[ZEnv, Nothing, ExitCode]`.

As you say, the advantage of a signature like this is that it requires the users to handle all expected errors.

However, the disadvantage is that is makes writing simple applications incrementally more difficult. For example, in ZIO 2.0 I can currently do:

```scala
object MyApp extends ZIOAppDefault {
  val run =
    Console.printLine("Hello, ZIO!")
}
```

With this change I would no longer be able to do that. I would have to write something like `Console.printLine("Hello, ZIO!").exitCode` or `Console.printLine("Hello, ZIO!").catchAll(e => ???)`. And I would have to no about those operators at the very beginning of learning about ZIO to get my first applications running instead of being able to add that to my knowledge over time.

I tend to think we are in the right place here. We could certainly revisit but at least in the past getting rid of the need for error handling for applications like this was an explicit design goal.

**Comment by khajavi** [comment]
Adam, thank you for your clarification!
