### ISSUE TITLE
Migrate built in services to Module Pattern 2.0 (Clock, Console, etc.)

### ISSUE THREAD

**Issue by AlexanderNull** [zio/zio#6400]
2.0 documentation appears to be pushing users towards the new flat Module Pattern 2.0 but many core service objects are still implemented in Module Pattern 1.0. Examples of this are Clock, Console, Random, System, TRandom, and possibly others. It would be nice to be able to follow the same pattern for using one of these services while providing layers to our programs as we should be following for all new modules.

Just recently started learning ZIO so I'm not 100% familiar with all of the cases where this migration is needed in the code base in addition to what I listed above so any assistance there would be appreciated. Some of the example code also needs to be updated to the new pattern such as OldLady for instance. Other instances of `val live: ...` which I'm not sure should/would be updated are ZEnv, which doesn't have a Live implementation to begin with so not sure if that would be moved (my guess would be that it wouldn't be moved, just the references within it updated to point to the newly migrated objects).

Proposed migrations:

- [ ] Clock
- [ ] Console
- [ ] Random
- [ ] System
- [ ] TRandom

Do y'all try and keep issues limited in scope to what would be accomplished via a single PR? Let me know if these should be split out by each individual object to be migrated (if we are going to migrate them).

**Comment by AlexanderNull** [comment]
Specifically suggesting the above get moved to the flat 2.0 pattern of `trait Service`, `case class ServiceLive`, `object ServiceLive { val layer... }`. This is assuming we are ok breaking backwards compatibility for 1.0 uses of this code, which I think has been done in a few other locations of 2.0 so far.

Alternatively if we absolutely must maintain backwards compatibility even for import paths of these services and therefor can't pull ConsoleLive out as a sibling of the Console trait as opposed to it currently being a child, then we can alternatively at least move the existing layer construction down into the ConsoleLive object to allow for new code to use `ConsoleLive.layer` and also point the existing `val live` property on Console object to the new layer property on the child ConsoleLive.

Either way I'd be up for helping out with it.

**Comment by adamgfraser** [comment]
These changes have already been made in ZIO 2.0. We need to maintain binary compatibility in ZIO 1.0 and ZIO 2.0 is almost here so I do not see the value in creating a "Frankenstein" API in ZIO 1.0 that is basically the old pattern with minor changes.

**Comment by AlexanderNull** [comment]
Do you mean 2.0 ZIO has already changed these objects? Looking at v2.0.0-RC2 and they appear to still be using the old pattern: https://github.com/zio/zio/blob/v2.0.0-RC2/core/shared/src/main/scala/zio/Clock.scala#L190

**Comment by vigoo** [comment]
I think having the layer definitions in the service trait's companion object provides better discoverability

**Comment by AlexanderNull** [comment]
For me it's more of a consistency issue which was (momentarily) confusing for me as a new person just now learning ZIO at this start of 2.0 phase. The documentation isn't consistent as far as what the pattern should be if some service layers should be found on `Service.live` while some of them should be found on `ServiceLive.layer`. Which ones should be layer, which ones should be live, and why?

If Release Candidate time is all of a sudden too late to introduce breaking changes... well yeah that makes a lot of since. For consistencies sake in documentation and examples though could we add something like `val layer: Layer[Nothing, Console] = live` on the _Service_Live object for now if we're not going to follow the full pattern? This way documentation detailing how to provide layers to an app could show:
```
myApp.provide(
  DatabaseLive.layer,
  AuthorizationLive.layer,
  ConsoleLive.layer
)
```
as opposed to:
```
myApp.provide(
  DatabaseLive.layer,
  AuthorizationLive.layer,
  Console.live
)
```

**Comment by adamgfraser** [comment]
There are a variety of aspects to the recommended idiomatic way of defining layers in ZIO 2.0 versus ZIO 1.0, including the elimination of the use of the separate package object and the `Has` type alias, the definition of service implementations as case classes, and the use of the `ZLayer` constructor with a for comprehension to define layers that build those implementations.

At this point it seems like we are talking about very minor details about what we name the layer (`live` versus `layer`) and whether these should be defined in the companion object of the layer or of the layer definition. I think we are also glossing over some significant differences here.

We normally recommend defining layers in the companion object of the  particular implementation because different implementations may have different dependencies and thus should be defined not only in separate files but likely separate modules to avoid mixing dependencies. For example if we have a `Persistence` service we might have `CassandraPersistence` and `PostgresPersistence` that each bring in entirely different libraries as dependencies. In contrast, in "simple" cases like the built in ZIO services these services typically only have one live implementation and do not bring in any other dependencies so there is no benefit in separating and instead defining them in the service definition companion object provides greater discoverability as pointed out by @vigoo.

Similarly, while `layer` is certainly a fine name for a layer, especially when it is defined in the companion object of a service implementation and thus the nature of the layer is obvious (e.g. `KafkaLive.layer`) there is nothing that says layers have to be called this and in any case where there might be multiple variants a more descriptive name can be used (e.g. `live`).

So while consistency is certainly very important this seems to be taking it a step too far and taking the module pattern from a description of an idiomatic way to define services to something that is overly rigid and formalistic and actually results in a worse user experience.

**Comment by BardurArantsson** [comment]
> Do you mean 2.0 ZIO has already changed these objects? Looking at v2.0.0-RC2 and they appear to still be using the old pattern: https://github.com/zio/zio/blob/v2.0.0-RC2/core/shared/src/main/scala/zio/Clock.scala#L190

You'll probably want to look at the 'series/2.x' branch, i.e. https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/Clock.scala

**Comment by AlexanderNull** [comment]
I think some of this was due to my confusions surrounding the exact form of the patterns and trying to work through the WIP documentation for 2.0. Closing this cause there doesn't seem to be much changes that could be made here. Thank you for the detailed feedback though!
