### ISSUE TITLE
ZIO 2.0: Rename ZIO#validate to ZIO#foreachValidate

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6422]
I was thinking about how to teach `ZIO.validate` and I think we can say that it is a variation of the `ZIO.foreach` that collects all errors in the error channel.

```scala
val foreach         : ZIO[Any, Throwable, List[Int]]     = ZIO.foreach(List(1, 2, 3))(ZIO.attempt)
val foreachValidated: ZIO[Any, ::[Throwable], List[Int]] = ZIO.validate(List(1, 2, 3))(ZIO.attempt)
```

Instead of having a new group of operators `ZIO.validate*` we can group them together with `ZIO.foreach*` operators and call them `ZIO.foreachValidate*`. It is easy to say that they are the same but with a slightly different strategy in error management policy and the second one doesn't fail fast.

**Comment by adamgfraser** [comment]
I think I am negative on this. One of the core similarities between all of the `foreach` variants right now is that they stop on the first failure and, if necessary, interrupt any other running effects. Having variants that don't have this behavior seems to make teaching more difficult rather than easier.

We also have a variety of other "collection" operators that don't have the `foreach` suffix, such as `partition`, so I'm not sure there is a lot of value in just moving this specific set of operators under `foreach`. There is also already the `validate` operator on the `ZIO` trait that fits with the current naming.

Finally, while we have definitely moved to somewhat longer method names in ZIO 2.0 in some cases for clarity, there is some cost to this and I think this would result in quite lengthy method names without a corresponding benefit.

**Comment by khajavi** [comment]
I agree with you. Your first note makes the most sense to me. 
Thank you for your clarification.
