### ISSUE TITLE
Tuple extraction in for comprehensions does not compile for effects that are not zio.Task

### ISSUE THREAD

**Issue by oridag** [zio/zio#6425]
Version: 2.0 RC2

When extracting a tuple in a for comprehension, if the effect error is other than `Throwable`, the expression does not compile with  the error:
`Pattern guards are only supported when the error type is a supertype of NoSuchElementException. However, your effect has String for the error type.`
even though no guards are used:

```
val io: IO[String, (Int, Int)] = IO.succeed((1, 1))
for {
  (n, m) <- io
} yield n

```

**Comment by adamgfraser** [comment]
This is actually not a ZIO issue but a Scala issue. Due to a wart in the Scala compiler destructuring in for comprehensions like this is translated into a `withFilter` call which implies the possibility of failure even though in cases like this we know from the type system that the pattern match cannot fail. This behavior will actually not be supported for any type of `ZIO` in ZIO 2.0 but you can instead do:

```scala
for {
  tuple <- io
  (n, m) = tuple
} yield (n, m)
```

This is obviously not as nice but this problem needs to be solved at the Scala compiler level versus the ZIO level.
```
