### ISSUE TITLE
[Bug] zio-test `checkAll` doesn't traverse all the posible values when using a "non-deterministic" generator

### ISSUE THREAD

**Issue by guizmaii** [zio/zio#6426]
(not tested with ZIO2)

Minimal reproducer:

```scala
import zio.ZIO
import zio.random.Random
import zio.test.*
import zio.test.TestAspect.*
import zio.test.magnolia.DeriveGen
import zio.test.environment.TestEnvironment

object Specs extends DefaultRunnableSpec {

  sealed trait A
  final case object B extends A
  final case object C extends A
  final case object D extends A
  final case object E extends A
  final case object F extends A

  private val deterministicGen: Gen[Any, A]               = Gen.fromIterable(List(B, C, D, E, F))
  private val nondeterministicGen: Gen[Random & Sized, A] = DeriveGen[A]

  override def spec: ZSpec[TestEnvironment, Any] =
    suite("Test")(
      testM("does test all the possible values") {
        checkAllM(deterministicGen)(a => ZIO.debug(s"deterministic: $a").as(assertCompletes))
      },
      testM("only tests one value") {
        checkAllM(nondeterministicGen)(a => ZIO.debug(s"non-deterministic: $a").as(assertCompletes))
      }
    ) @@ sequential
}
```

Current output:
```scala
deterministic: B
deterministic: C
deterministic: D
deterministic: E
deterministic: F
non-deterministic: E
```

Possible expected output:
```scala
deterministic: B
deterministic: C
deterministic: D
deterministic: E
deterministic: F
non-deterministic: B
non-deterministic: C
non-deterministic: D
non-deterministic: E
non-deterministic: F
```

Might be related to https://github.com/zio/zio/issues/5616

**Comment by adamgfraser** [comment]
I think this is expected behavior. The `checkAll` operator essentially just runs the stream underlying the generator to completion. A non-deterministic generator is a stream with a single element consisting of a random effect that potentially produces a different value each time it is evaluated. The `check` operator runs this stream forever and takes a specified number of values from it, but `checkAll` just takes all the values from the original stream.

In this case there is no way for the test framework to know that the non-deterministic generator only has six possible values. It is just a random effect that produces something. So there is no way that it can know that it can stop after producing those six values.

If you want to produce more values you can use `check` instead of `checkAll` but I think `checkAll` is explicitly intended for finite deterministic generators as documented.

**Comment by guizmaii** [comment]
To me, this behaviour is surprising. 
When I'm using a `checkAll` operator with a generator, I don't expect to have to know the nature of the generator to know that `checkAll` will indeed apply my tests with all the possible values that a generator can generate.

It seems that the current behaviour means that I have no way to check that for any value of a sum type, I can test a property of my code, when my sum type generator is automatically derived.

**Comment by adamgfraser** [comment]
Why aren't you just using `check` here? `checkAll` is a specialized `check` variant for when you know that your generator is finite and deterministic, which is not the case here.
