### ISSUE TITLE
ZIO.provideCustomLayer should return a ZIO[ZENV with ZIOAppArgs, E, A] and not ZIO[ZENV, E, A]

### ISSUE THREAD

**Issue by dylandoamaral** [zio/zio#6429]
Since ZIO2.0, we use `ZEnv with ZIOAppArgs` instead of `ZEnv` for our default application R.

However when we provide the layers for our applications, `provideCustomLayer` is returning `ZIO[ZENV, E, A]` maybe we should replace:

```scala
  final def provideCustomLayer[E1 >: E, R1](
    layer: => ZLayer[ZEnv, E1, R1]
  )(implicit
    ev: ZEnv with R1 <:< R,
    tagged: EnvironmentTag[R1],
    trace: ZTraceElement
  ): ZIO[ZEnv, E1, A] =
    provideSomeLayer[ZEnv](layer)
```

by:

```scala
  final def provideCustomLayer[E1 >: E, R1](
    layer: => ZLayer[ZEnv, E1, R1]
  )(implicit
    ev: ZEnv with R1 <:< R,
    tagged: EnvironmentTag[R1],
    trace: ZTraceElement
  ): ZIO[ZEnv, E1, A] =
    provideSomeLayer[ZEnv with ZIOAppArgs](layer)
```

**Comment by adamgfraser** [comment]
I tend to think that `ZIOAppArgs` is particular to a `ZIOApp`, a specific type of program that takes command line arguments, and is not general to any ZIO workflow. So I would tend to think that it should not be part of the environment provided by `provideCustomLayer`.

Also, I don't know if you want any arbitrary part of your program being able to access the command line arguments. That seems like potentially an implementation leak where only the top of your program should know about the command line arguments and should translate it into more domain specific information such as configuration for lower level components.

You can certainly do `provideSomeLayer[ZEnv with ZIOAppArgs]` for this or implement your own `provideDefaultLayer` variant but for the reasons above I would tend to think `ZIOAppArgs` should not be part of the default environment which is why it is also not part of `ZEnv`.

**Comment by dylandoamaral** [comment]
Thanks for your answers, I agree with Vigoo !

Therefore, according to my comprehension, when we override `run` for a `ZIOAppDefault` we have to return a `ZIO[ZEnv with ZIOAppArgs, Any, Any]`meaning that we should provide ourself any layer that doesn't correspond to R. So according to me, in this case, it doesn't make sense that ZIOAppArgs is seen has a custom layer.

**Comment by DaniRey** [comment]
I'm uncertain how much ZIO 2.0 changed after this discussion. But my current understanding is, that @vigoo 's code could now work as follows, thanks to `.provideSome[ZIOAppArgs](clippConfig)`

```
object Test2 extends ZIOApp {
  def run = {
    val paramSpec = for {
      _ <- metadata("zio-test")
      x <- flag("test parameter", 'x')
    } yield x

    val clippConfig = parametersFromArgs(paramSpec).printUsageInfoOnFailure
    val program = for {
        x <- parameters[Boolean]
        _ <- console.putStrLn(s"x was: $x").ignore
    } yield ExitCode.success
    
    program
      .provideSome[ZIOAppArgs](clippConfig)
      .catchAll { _: ParserFailure => ZIO.succeed(ExitCode.failure) 
      }   
  }
```

**Comment by adamgfraser** [comment]
This operator has been deprecated as the default services are no longer in the environment.
