### ISSUE TITLE
ZStream#zip will not terminate if left side is not progressing 

### ISSUE THREAD

**Issue by oridag** [zio/zio#6505]
If left side of a zipped stream is not progressing (but also not terminated), then right stream will not be pulled, even though there are unmatched elements pending on the left side. For example, the following effect will never terminate (while it should terminate because the right side stream should be fully consumed):   

```
val s1 = ZStream(1, 2, 3).rechunk(1)
val e = for {
  q <- ZQueue.bounded[Int](3)
   _ <- q.offerAll(Seq(1, 1, 1))
   _ <- s1.zip(ZStream.fromQueue(q)).runDrain
} yield ()
```  
  (zio 2.0 RC1)

**Comment by adamgfraser** [comment]
@oridag It looks like this works correctly on `series/2.x`.

Note however that I think you have a slightly misunderstanding regarding the way `ZStream.fromQueue` works. In the example above the right hand stream is not done because more values could always be offered to the queue and it has not been shut down. If you want the right hand stream to be shut down you need to shut down the queue with `Queue.shutdown`.

The reason the above example terminates, at least on `series/2.x`, is because the left hand stream is done. If I had another element to it then the example would not terminate, which is expected behavior.

**Comment by oridag** [comment]
@adamgfraser sorry, I mixed up the sides. I meant to write that the **left** hand side should be fully consumed, but it is not because the **right** hand side is not progressing.

**Comment by oridag** [comment]
Here is the edited description of what I see:
If **right** side of a zipped stream is not progressing (but also not terminated), then the **left** stream will not be pulled, even though there are unmatched elements pending on the **right** side. For example, the following effect will never terminate (while it should terminate because the left side stream should be fully consumed):

**Comment by oridag** [comment]
Yep, just verified it works correctly on RC3 so I'll close this. Thanks!

**Comment by adamgfraser** [comment]
Okay great. Thanks for raising!
