### ISSUE TITLE
ZIO 2.0: Develop macro for constructing layer based on constructor parameters

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6560]
```scala
class UserRepoImpl(database: Database, cache: Cache)

val layer: ZLayer[Database & Cache, Nothing, UserRepo] = ZLayer.fromClass[UserRepoImpl]
```

/cc @adamgfraser @kitlangton

**Comment by jdegoes** [comment]
Links to #6518

**Comment by kitlangton** [comment]
I'll look into this. I'm not sure if it will be possible in Scala 2 without the use of whitebox macros, which would require IntelliJ plugin support. (@hmemcpy, do you think the plugin infrastructure could grab such type-information—inspecting the types of the constructor parameters for a class/case class?). Scala 3 should be better with transparent macros, and hopefully it's possible to grab the necessary types from the constructor of a given type. 

If this can work smoothly, that would be great—and I'll try my best to get it to that point. But if it doesn't I do think the old function-to-layer-syntax is worth reconsidering. Though perhaps there are some other ways that wouldn't require the imports. Either way, this will be a fun challenge 😄

**Comment by hmemcpy** [comment]
a) this would be amazing.
b) I believe there's sufficient type information that IntelliJ provides (will have to double-check that, though), so I'd be happy to provide this support, if possible.

I will say, however, that ever since embracing Copilot, I'm happily letting it write my boilerplate and it's often times a) is actually correct and b) something I prefer over excessive "convenience" methods that hide important work.
