### ISSUE TITLE
Double Logging in ZIO 2.0.0-RC5 and ZIO-Logging 2.0.0-RC8

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#6626]
Hi Team,

It looks there is a problem with log duplication while using ZIO "2.0.0-RC5" with ZIO-Logging "2.0.0-RC8"
*The problem was NOT present in ZIO 2.0 RC2.*

Not sure if that is a problem with ZIO-library itself, ZIO-logging OR just the things has changed and I need to modify somehow my code (?).

wanted to log via logback and have the following code in my zio-app (that was working with ZIO 2.0 RC2):

```scala
object Cli extends ZIOAppDefault {

  private val slf4jAspect = SLF4J.slf4j(
    logLevel = LogLevel.All,
    format = LogFormat.line
  ) // wanted to use with logback

  override def hook: RuntimeConfigAspect = slf4jAspect
// ...
// ... and log somewhere below
  ZIO.logInfo("MESSAGE")
```

By looking the source code, ZIO adds a default logger in RC5 (and in RC2 it was empty?) and then `zio-logging` calls `RuntimeConfigAspect.addLogger` and adds a second logger. In this way a log message is being printed twice: first time with the default logger and the second via logback

```
timestamp=2022-04-15T09:56:10.928955670Z level=INFO thread=#zio-fiber-2 message="MESSAGE" location=xxx file=yyy.scala line=17
11:56:11.042 [ZScheduler-1] INFO  zio-slf4j-logger - 'MESSAGE'.
```
^
but here I expected only the second message to be printed by the logger I set with `slf4jAspect` with logback.

--
Library version

```scala
  private val zio             = "dev.zio" %% "zio"               % "2.0.0-RC5"

  private val zioLogging        = "dev.zio" %% "zio-logging"         % "2.0.0-RC8"
  private val zioLoggingSlf4j   = "dev.zio" %% "zio-logging-slf4j"   % "2.0.0-RC8"
  private val logbackClassic    = "ch.qos.logback" % "logback-classic" % "1.2.11"
```

**Comment by adamgfraser** [comment]
@gchudnov Thanks for reporting!

The encoding of this has changed somewhat between ZIO release candidates but the basic idea is that logging should be additive, so in my most recent PR regarding this the loggers are a set and as the name implies `addLogger` adds a logger to the set of loggers. This way if an inner scope adds a logger it doesn't "take away" from the information that the outer scope sees.

So I think if you just add another logger the expectation is that it will log to both places. Now if you are seeing console logs twice instead of console logs once and logs to your backend of choice once then that would indicate that the `slf4j` logging implementation is "doing too much" and it just needs to print to log to the backend versus printing to the console.

We also need a way to remove a logger in some situations,  such as disabling logging in a region.

For now you can do something like:

```scala
ZIO.withRuntimeConfig(RuntimeConfig.default.copy(logger = Logger.none) @@ slf4j)
```

**Comment by gchudnov** [comment]
yes, it works, thank you!
closing the issue.
