### ISSUE TITLE
ZIO 2 Schedule gets compilation warning: a type was inferred to be `Any`

### ISSUE THREAD

**Issue by alphaho** [zio/zio#6645]
With ZIO **2.0.0-RC5** in Scala **2.13.6**, when I define a `Schedule` variable using the `Schedule.&&` (or `zipLeft` / `zipRight`), it would get a compilation warning `a type was inferred to be `Any`; this may indicate a programming error.`  if I haven't specified the type annotation. Besides, if I type it with `Schedule.WithState` instead of `Schedule`, it would get the same warning.

This seems to be a type inference issue.

```scala
  val someSchedule1: Schedule[Any, Any, (Duration, Long)] =
    Schedule.exponential(2.seconds) && Schedule.recurs(5) // this works

  val someSchedule2: Schedule.WithState[(Long, Long), Any, Any, (Duration, Long)] =
    Schedule.exponential(2.seconds) && Schedule.recurs(5) // this doesn't work

  val someSchedule3 =
    Schedule.exponential(2.seconds) && Schedule.recurs(5) // this doesn't work
```

**Comment by adamgfraser** [comment]
The type is correctly being inferred as `Any`. I would recommend removing warnings regarding types being inferred as `Any` from your Scala compiler settings as types can frequently be correctly inferred as `Any`.

**Comment by alphaho** [comment]
Is it because the Aux pattern would make it inferred as `Any`? I was quite surprised that it can't be inferred to `Schedule` or `Schedule.WithState`

**Comment by adamgfraser** [comment]
The Scala compiler infers the type flawlessly:

```scala
val someSchedule3: Int =
  Schedule.exponential(2.seconds) && Schedule.recurs(5)

[error]  found   : zio.Schedule[Any,Any,(java.time.Duration, Long)]{type State = (Long, Long)}
[error]  required: Int
```

As you can see, even when we try to tell it the wrong type Scala knows exactly what the type of the schedule is. However, the Scala compiler correctly infers `Any` for both the environment and input types, since this schedule does not require any services and can accept any input.

Unfortunately this seems to trigger a different logic path in the Scala compiler that leads to it spuriously warning that the type is inferred as `Any`. Indeed the type is inferred as `Any` and that is totally fine and shouldn't be a warning at all.

The solution to this is to remove the `infer-any` compiler warning. We are already doing this in ZIO ecosystem projects as it can also lead to spurious warnings when the environment type is eliminated and there are no further services required so the environment type is `Any`.

**Comment by alphaho** [comment]
Aha, so the warning on `Any` is about the environment and input types, instead of the Schedule itself. 
But it's weird that it also complains about `someSchedule2` when I explicitly typed it as `Schedule.WithState`.

I think I can remove the `infer-any` compiler warning from the project to fix it.

**Comment by adamgfraser** [comment]
Yeah I don't know. Something about that causes the compiler to go down a different logic path that triggers the warning, even though all of the examples actually infer perfectly.

Anyway, yes removing `infer-any` will resolve the issue.
