### ISSUE TITLE
ZChannel#runScoped missing elements

### ISSUE THREAD

**Issue by luis3m** [zio/zio#6726]
Not sure where the issue lies exactly. It seems to be somewhere in ZChannel. I'll probably edit later with a proper title.

Anyway, I was trying to reimplement `toIterator` without `toPull` and locally I ended up with a similar solution as in the following scastie. However, I noticed the test was failing and since I've been trying to figure out what's wrong.

https://scastie.scala-lang.org/v1dRwyUJTQ6IKHIw8UDiZw 

Locally I'm using `ZStream.Handoff` but as you can see in the scastie the issue is reproducible with Queue as well.

Note: this program is basically the same test that already exists for `toIterator`.

**Comment by adamgfraser** [comment]
@luis3m What are you trying to do with this line?

```scala
mapConcatZIO(element => effect.map(newElement => List(element, newElement)))
```

Your test passes if I comment that out.

**Comment by adamgfraser** [comment]
I think this test is making a very specific assertion about the order in which `effect` is run in `fromIterator` versus `mapConcatZIO` that is not being preserved in your new implementation versus `runScoped` missing elements.

**Comment by adamgfraser** [comment]
Basically I think the issue is that your implementation creates two asynchronous regions. The upstream in the implementation of `toIterator` eagerly begins execution and offers the first element to the `Queue` or `Handoff` without a request from the downstream, which violates the contract implied by this test that the upstream shouldn't begin evaluation until pulled from the downstream.

**Comment by luis3m** [comment]
Yeah, that makes sense. In which case, `toIterator` will remain untouched. I'll close this issue.
