### ISSUE TITLE
2.0 logging: allow removing the default logger (bis)

### ISSUE THREAD

**Issue by francisdb** [zio/zio#6767]
zio 2.0.0-RC6
zio-logging 2.0.0-RC9

I could not find a way to remove the default logger. So when using zio-logging you end up with duplicate logs.
This was raised previously in #6626 but the fix provided there no longer is available since RC6.

I found `ZIOAspect.disableLogging` but have not found a way to transform that into a (bootstrap) layer.
And there is `Runtime.addLogger(stringLogger)`
Then zio-logging `zio.logging.console()` layer appends using above `addLogger`

This could be provided with `Runtime.disableLogging` or `Runtime.setLogger(stringLogger)` and/or a layer for `ZIOLayer.disableLogging`?

**Comment by adamgfraser** [comment]
In general we are trying to move to a model where, when possible, customizations to the runtime are always added and never taken away. This allows the customizations to be commutative and thus deterministic in the presence of concurrency. For example, what happens when two programs are combined and each program's runtime configuration wants to set a different logger.

In particular in the domain of logging there is a further idea that inner workflows should not be able to "shield themselves" from observability installed at higher levels of the program.

Possibly we can address this by not having the default value of the `currentLoggers` include the default logger and instead having a layer that installs it in `bootstrap` in `ZIOAppDefault` that you can override.

I will take a look at this.

**Comment by adamgfraser** [comment]
Yes, I actually just submitted a PR to delete it. 😃

**Comment by francisdb** [comment]
see https://github.com/zio/zio/pull/6771

**Comment by fernanluyano** [comment]
I noticed that Runtime.removeDefaultLoggers removes only logger will level >= info, leaving Debug and Trace behind. My app is filling my logs with DEBUG messages. How can I remove the default DEBUG logger as well?

**Comment by adamgfraser** [comment]
@fernanluyano There is no default logger that logs at that level.

**Comment by fernanluyano** [comment]
Any idea what can be writing those? The only logger in my app is created like this
```
  override val bootstrap: ZLayer[Any, Any, Unit] = {
    val consoleJsonLog = consoleJson(LogFormat.default
      + LogFormat.annotation(CustomLogging.appNameAnnotation)
      + LogFormat.annotation(CustomLogging.dbEndpoint))
    Runtime.removeDefaultLoggers >>> consoleJsonLog
  }
Edit. It seems the logback backend is doing that
