### ISSUE TITLE
[2.0] remove `IO`, `UIO`, `RIO`, `Task`, etc. type aliases

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6928]
ZIO offeres a few type aliases that lead to a lot of confusion for people new to ZIO and to bad design choices regarding error handling ( `Task` & `RIO` with `Throwable` as error type ). 
```scala
IO[+E, +A]   = ZIO[Any, E, A]         // Succeed with an `A`, may fail with `E`        , no requirements.
Task[+A]     = ZIO[Any, Throwable, A] // Succeed with an `A`, may fail with `Throwable`, no requirements.
RIO[-R, +A]  = ZIO[R, Throwable, A]   // Succeed with an `A`, may fail with `Throwable`, requires an `R`.
UIO[+A]      = ZIO[Any, Nothing, A]   // Succeed with an `A`, cannot fail              , no requirements.
URIO[-R, +A] = ZIO[R, Nothing, A]     // Succeed with an `A`, cannot fail              , requires an `R`.
```

I'd like to propose the removal of these type aliases before the release of ZIO 2.0 as they are easy to migrate with scalafix or simple find and replace and people wanting such type aliases could easily add them by themselves. If necessary, we could also provide a migration lib like we did for ZManaged.

**Comment by guizmaii** [comment]
Your idea would be that we'd only have `ZIO[R, E, A]`?
```scala
def f: ZIO[Any, Nothing, A] = ...
```
instead of 
```scala
def f: UIO[A] = ...
```
?

If so, I disagree with this idea. 
These aliases are defining a nice common language between the developers. 
When we're talking about an `UIO`, for example, everyone knows what it means. Without these aliases, we lose this ability to talk in terms of `Task`, `UIO`, etc.

**Comment by domdorn** [comment]
@guizmaii yes, if that's not possible, at least lets get rid of `Task` and `RIO` . 

ZIO 2 is/was all about streamlining things, offering ONE way to do things.. 
I personally don't see a lot of benefit in these types except a few characters less typed. 
For people coming to ZIO however they are a mental burden - at least they where for me 2 years ago, making a thing that was already complicated even more complicated.

**Comment by guizmaii** [comment]
> at least lets get rid of Task and RIO

I'd be ok to rename `RIO` to `RTask` or something like this, but not remove them. 
I can agree on the fact that if `ZIO[Any, Throwable, A]` is named `Task` and `ZIO[Any, E, A]` is named `IO` then `RIO` is a poor name for `ZIO[R, Throwable, A]`. It's too close to `IO` and too far from `Task`.

I think the common language they bring to the developers is something to put in the balance before considering removing them.

**Comment by adamgfraser** [comment]
Yes this is one we have definitely discussed in the past. I think there are basically two sets of arguments.

On the one hand the type aliases are "one more thing to learn". If you know that `Any` for the `R` type means "does not need any services" and `Nothing` for the `E` type means "can't fail" you can express everything you want to with just `ZIO` and this can be more accessible because you don't need to remember these different type aliases.

On the other hand, the three type parameters can require more typing when you aren't actually using one of them and can potentially clarify intent in some places (e.g. if you see `UIO` you don't even have to look at the `E` type parameter).

I personally have been moving more towards using `ZIO[Any, Nothing, A]` instead of `UIO[A]` just to minimize the things people need to know and we have taken some steps in that direction with the deletion of the type alias companion objects.

However, my sense is that there are a sizable number of people who like the type aliases and maintaining them lets the people who enjoy them continue using them and others don't have to. That does create some risk that you have to read code someone else has written that uses type aliases but I think deleting them would create unnecessary friction for the people who do like them.

There is the possibility of renaming but I think the saving grace of the type aliases, to the extent there is any, is that they have been around for a long time. So I would be hesitant about changing the name to replace one somewhat arbitrary name with another.

So overall I would be inclined to keep the status quo though I am definitely sympathetic to these concerns.

**Comment by domdorn** [comment]
ok, would such a proposal be an acceptable compromise?:
- remove the usage of the type aliases in the zio-codebase ( so the type aliases still exist, but they are not used in any of the ZIO.* effects and thus don't get visibility to users) 
- move the documentation of them from the normal documentation to something like "advanced topics"

?

**Comment by robmwalsh** [comment]
I think throwing them out altogether is overkill, but I think some more consistency could be achieved. Task and RIO stick out as being remarkably inconsistent. At this point, I think there's little to be gained by wholesale change, and I don't want to see them all removed. As @guizmaii says, they're much easier to say when talking to someone. I find UIO particularly nice as I'm clearly stating, "this will not fail".

I do think renaming `RIO` to `RTask` would be a very nice change at this point, indicating that it could still fail with a `Throwable` like `Task` rather than being an IO that requires an R (which would be ZIO as @domdorn pointed out in Spartan discord), and giving Task a friend, so it's not the only one that uses a word instead of a variant of `IO`.

I don't think these are challenging concepts to grasp myself. However; my intro to ZIO was as a contributor, so I got pretty comfortable using ZIO without aliases before I was formally introduced to them in a course. Perhaps it may have been more confusing jumping straight into a codebase on a new job, but that's the sort of think I like to use a cheat sheet for.

**Comment by adamgfraser** [comment]
@domdorn I think we need to say whether these type aliases are in "good standing" or not. If we really don't think they are then they need to be deleted entirely, but while I think that is your point of view I think there are a substantial number of people with a different point of view. If they are in good standing then they should be in the documentation and I don't think we can prevent them from being used.

@robmwalsh I think there could be a more internally consistent sets of name. `ZTask` and `ZUIO` was proposed in the ZIO Discord so the principles would be "if it fails with a `Throwable` make it a `Task`, if it can't fail at all make it a `UIO`" and "if it needs an environment, but a `Z` in front of it". I don't know if I love the way those read but they are at least internally consistent.

The other consideration here is just how willing we are to make further API changes. I am somewhat inclined to think that we are about to release ZIO 2.0 and we just need to land this ship but you could turn that around and say this is our last chance to make changes and we should do one more thing.

**Comment by robmwalsh** [comment]
@adamgfraser not a huge fan of those names either, even if they are more consistent (in some regards). 

It's been at RC for quite a while. I tend to agree it may be time to just release as is...  If someone would really prefer RTask it's a 1 liner to create another alias. I don't think they're causing too much pain really. I get around my dislike of Task and RIO by not using them. When I have to use them (someone else's code) the compiler stops me doing anything too silly.

Of course on the "one last change" side, renaming a type alias barely even counts as a change (I don't think that even breaks bincompat, since it's all erased to ZIO in the end).

**Comment by domdorn** [comment]
The bigger "issue" I have with `Task` and `RIO` is that they have `Throwable` as the Error type, which is the supertype of `java.lang.Error`s like `OutOfMemoryError`, `StackOverflowError` etc. 

As we've learned in the spartan session about error handling, we should only have errors we can actually handle in the error type. I highly doubt many programs out there do this the right way with a `OutOfMemoryError`..

`Task` and `RIO` are helpful constructs, but they make it way too easy to do the wrong thing. 

IMHO ZIO should make it easy to do the right thing and maybe a little cumbersome to do the wrong thing. 

I'm fine having `UIO` for something that can never fail (although its another thing to remember when you're new to ZIO), but would much appreciate it, if we have something that can fail, that the user at least thinks about "what kind of errors could I expect here" ? A developer coming from Java in a "I don't care"-scenario would probably go for `Exception` instead of `Throwable` as `Throwable` is even a no-go in Java land and `Exception` is the base for anything that can be meaningfully handled.

**Comment by domdorn** [comment]
hm. what if we'd have 
```scala
def attempt[E,A](effect: => A): ZIO[Any, E, A]
def attemptUnsafe[A](effect: => A): ZIO[Any, Throwable, A]
```
?

**Comment by guizmaii** [comment]
> The bigger "issue" I have with Task and RIO is that they have Throwable as the Error type, which is the supertype of java.lang.Errors like OutOfMemoryError, StackOverflowError etc.

> Task and RIO are helpful constructs, but they make it way too easy to do the wrong thing.

The use of `Throwable` was an early mistake in Scala design that we have to deal with today, sadly. 
That being said, as Adam mentioned, these `java.lang.Error` (fatal errors) are not caught by `Task`, `Future`, etc. so they don't allow the user to make such mistake.

> the code bases will be full of effects of Task[A] and a nightmare to support/maintain after some time.

I don't see why then they'd be a nightmare

**Comment by adamgfraser** [comment]
I actually view this the opposite way. It is important that users be able to take incremental steps towards improving their code rather than having to do the "perfect" thing from the beginning. `Task` is a great example of this.

You're right that in most cases I would ultimately like to have domain specific error types in my code unless it is very closely tied to legacy APIs that can throw arbitrary exceptions anywhere.

However, if I am coming from a code base that is using `Future`, or is using another framework that has the error type fixed to `Throwable`, or I'm just learning about ZIO I've got a lot of other problems. I need to understand that workflows are descriptions. I need to learn the ZIO equivalents for things I was doing before. I need to learn new concepts if ZIO allows me to do the same thing but in a different way as before.

In this situation leaving the error type as `Throwable` can be a very sensible strategy of not doing more than you have to initially when you already have to do a lot. So instead of blaming your younger self I would celebrate them for doing a lot of the heavy lifting and allowing you to take the next step now. And you can probably do it more efficiently next time now that you have done it before.

**Comment by luis3m** [comment]
> hm. what if we'd have
> 
> ```scala
> def attempt[E,A](effect: => A): ZIO[Any, E, A]
> ```
> 
> ?

How would you 'catch' the 'E' when evaluating the thunk? You can't.

**Comment by domdorn** [comment]
Thought it was a good thing.. apparently everyone is against it so closing it now.

**Comment by luis3m** [comment]
@domdorn that'd only work if you make `E` a subtype of Throwable which in hindsight seems to be what you were advocating for above. I actually like the idea.
