### ISSUE TITLE
Proposal: rename zio.Duration to zio.ZDuration

### ISSUE THREAD

**Issue by ThijsBroersen** [zio/zio#6998]
With ZIO-2 having both `java.time._` and `zio._` imported gives conflicts on `Duration`-type. As it seems to be just a helper to java.time.Duration I think it makes sense to rename `zio.Duration` to `zio.ZDuration` to prevent import issues, and it saves the hassle of import renamings. 

I am happy to submit a PR when this proposal is accepted.

**Comment by adamgfraser** [comment]
I think with ZIO 2.0 being released the ship has sailed on this.

**Comment by ThijsBroersen** [comment]
Perhaps I should rephrase my question because to me it looks to be a design-flaw. Was it by design to prevent zio-users to have a full import scope on java.time next to zio? I do not see the benefits...

If I am a heavy java.time and zio user I should rename either one all the time?

**Comment by adamgfraser** [comment]
We wanted to use `Duration` because it is the logical name for this concept and wanted it to be available in the `zio` name space without having to do an additional import.

`zio.Duration` is a type alias for for `java.time.Duration` and has a variety of useful constructors so this makes it easy for ZIO users to work with duration and interoperate with Java libraries with just `import zio._` and without having to do `import zio.duration.Duration` or `java.time.Duration`.

I think this was the right decision, though I understand it could create some inconvenience in your case having to hide or rename `java.time.Duration`. We can certainly revisit for ZIO 3 but given binary compatibility I think this is what it is for ZIO 2 and I do think it was the right thing to do.

**Comment by ThijsBroersen** [comment]
pity.. but thanks for your answer @adamgfraser 
I am still happy ZIO embraced java.time 
Will close the issue then.
