### ISSUE TITLE
Test suite not found if class extends ZIOSpecDefault

### ISSUE THREAD

**Issue by aleksandr-vin** [zio/zio#7134]
Writing test suite as class that extends `ZIOSpecDefault` will successfully make the suite non-visible for test runner.

I'd expect it to act same as object, or have an error on compile time.

**Comment by adamgfraser** [comment]
Hi @aleksandr-vin! That's right, tests are runnable applications so just like `App` in Scala `ZIOSpecDefault` needs to be extended in an object to be runnable.

I don't think it would make sense to run classes that extended it (since we wouldn't know that they contained an implementation of `spec`) or to have an error (since many users extend `ZIOSpecDefault` to provide their own custom logic that they then extend in individual test objects).

We could have better documentation of this though.
