### ISSUE TITLE
[ZIO 2] self-referential zio with catchSome and catchSomeCause blows up logging, leaks memory

### ISSUE THREAD

**Issue by codingismy11to7** [zio/zio#7143]
I might be doing something crazy in my code, could definitely be a better way to do things, but this behavior didn't happen with earlier ZIO2 RCs. I've got an effect that is returning an item to operate on. Inside of a `lazy val` effect, i'm calling that effect, processing, and assuming nothing went bad, i'm starting over from the beginning (`*>` to the `lazy val`). I `catchSome` for certain errors and go back to the beginning of the loop and i'm catching interrupts and exiting the loop. In runtime at one point I hit an error, and had _40,000_ log lines from that error. i also feel like this must be using memory to keep track of these stack traces. I've done some stack dumps, and that looks to be the case (tens-to-hundreds of thousands of instances of `OnSuccess` with double that amount of `OnSuccessAndFailure` instances).

I made a fairly succinct repro:

```scala
package x

import zio._

object LotsOfLogs extends ZIOAppDefault {
  def doit(getNext: ZIO[Any, Nothing, Int]): URIO[Any, Unit] = {
    lazy val loop: ZIO[Any, String, Unit] =
      (getNext.flatMap(i => ZIO.fail("it failed").when(i == 5)) *> loop)
        .catchSome { case "it didn't fail" => loop }
        .catchSomeCause { case _: Cause.Interrupt => ZIO.unit }

    loop.tapErrorCause(ZIO.logErrorCause(_)).ignore
  }

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = for {
    ref <- Ref.make(1)
    getNext = ref.getAndUpdate(_ + 1)
    _ <- doit(getNext)
  } yield {}
}
```

which fails after 5 loops and shows 2 lines for every loop

```
timestamp=2022-07-29T05:48:54.212Z level=ERROR thread=#zio-fiber-6 message="" cause="Exception in thread "zio-fiber-6" java.lang.String: it failed
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:8)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:9)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:10)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:9)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:10)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:9)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:10)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:9)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:10)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:9)
	at hyperdl.LotsOfLogs.doit.loop(LotsOfLogs.scala:10)
	at hyperdl.LotsOfLogs.doit(LotsOfLogs.scala:12)
	at hyperdl.LotsOfLogs.run(LotsOfLogs.scala:18)" location=x.LotsOfLogs.doit file=LotsOfLogs.scala line=12
```

I'm processing millions of items, and have been having the jvm crash on me, so wondering if this is why

**Comment by codingismy11to7** [comment]
forgot to mention that if you remove the `catchSomeCause` this doesn't happen. just did a little more experimenting, and commenting out either one will make this not happen, but (for instance) just having two `catchSome`s will cause it to happen (ofc catchSome is a PF and you should never have two, but it will surely happen in the wild)

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!

**Comment by codingismy11to7** [comment]
just fyi i just got this crash and noticed i've seen another in this same spot:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000020213e2d9ac, pid=41996, tid=0x000000000000c6fc
#
# JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 4974 C2 zio.internal.PinchableArray.$plus$plus$eq(Lzio/Chunk;)V (62 bytes) @ 0x0000020213e2d9ac [0x0000020213e2d7a0+0x20c]
```

**Comment by adamgfraser** [comment]
@codingismy11to7 Hi! I took a look at this and I think the issue is actually with this implementation rather than with ZIO.

For recursive workflows to be able to operate with constant memory they must be "effectually tail recursive", which means that the recursive call must be the "last" thing you do in each step.

In your example above, each time we recurse by calling `loop` in the happy path there are two operations (`catchSome` and `catchSomeCause`) that are still on the ZIO stack. ZIO maintains this stack on the heap versus on the JVM stack once it exceeds a specified size so this doesn't cause a stack overflow but those two continuations need to be kept on the stack and take up memory regardless of what we do with the trace and they add up each time. So if we recurse until `i` is a million in the example above we build up two million ZIO continuations which creates a memory leak. 

The same thing is true if there is only a single continuation, you would just build up a stack of one million continuations instead of two million continuations so we leak but more slowly.

The stack trace is just generated lazily from the stack that we already have to maintain so it is more the symptom than the problem. The stack trace just looks shorter when there is a single continuation because we don't keep consecutive stack trace elements from the same line and we have a million continuations from the same line.

So in your example above what you want to do is to rewrite it so that in each step you do your work and then recurse based on it like this:

```scala
import zio._

object Example extends ZIOAppDefault {
  def doit(getNext: ZIO[Any, Nothing, Int]): URIO[Any, Unit] = {
    lazy val loop: ZIO[Any, String, Unit] =
      (getNext.flatMap(i => ZIO.fail("it failed").when(i == 1000000))).foldZIO(
        e => if (e == "it didn't fail") loop else ZIO.refailCause(Cause.fail(e)),
        _ => loop
      )

    loop.tapErrorCause(ZIO.logErrorCause(_)).ignore
  }

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = for {
    ref <- Ref.make(1)
    getNext = ref.getAndUpdate(_ + 1)
    _ <- doit(getNext)
  } yield {}
```

This will now operate in constant space and be much faster.

**Comment by codingismy11to7** [comment]
Thanks for looking at this, I wasn't trying to get you to fix my dumb application, just reporting what I thought was a regression. but what I'm taking away is that this existed in ZIO1 / earlier ZIO2 snapshots, I just didn't see it because my JVM wasn't periodically crashing, and because those versions didn't have the better tracing?

I'm somebody who doesn't write a recursive function unless I can put `@tailrec` over it, and somewhere in my mind I knew that ZIO wasn't magically fixing non-tail recursion but moving it from the stack to the heap...but still- it never really occurred to me that I also need to make ZIO code tail-recursive. I'm wondering how this can be ameliorated, because if I got tripped up I know it's going to happen to others, and my mind is pulling up questionable spots of code from work projects. the only zio linter I know of is the intellij zio plugin; wonder if it would be possible to flag something like this there. probably a daunting task, as is education. just thinking out loud

Is there any difference between `ZIO.refailCause(Cause.fail(e))` and `ZIO.fail(e)`? Looking at the code it seems like the former skips stack tracing. would the latter get me back in the same position of being non-tail-recursive? If so this seems like it's getting into some arcana that's going to cause issues in real code (like, as a non-expert I can recognize that I need to be tail recursive once I have that knowledge, but no way I'm going to know that I also have to use this _other_ method I've never heard of to fail the loop that feels like just a longer way of saying `ZIO.fail`)

Thanks again

Edit: I also think i missed something. Like I said, maybe my code is bad and there's a better way, but somewhere in a stream I'm pulling from that ends, or an STM queue that gets shut down, or something, I'm getting an interrupted signal that I want to swallow to a `ZIO.unit` value to just break out of the loop. it seems like your refactor doesn't do that. is that jsut a matter of replacing `foldZIO` with `foldCause` and matching on the cause? and...not to derail this any further, but in other projects i've tried matching on the cause and got weird results (eg, was trying to catch a `Cause.Fail` of `None` to determine that a zio-http route wasn't matched; my code would never hit until I added `.untraced` to the cause before i matched on it...could be totaly unrelated but it's made me wary of trying to pull apart `Cause`s)

**Comment by adamgfraser** [comment]
Yeah, it is a good question. The concept of being "effectually tail recursive" is definitely one we teach but it is one of the more "advanced" topics.

My overall advice would be if possible to use built in operators instead of using manual recursion, which is probably the same advice a lot of people would give about normal tail recursion (e.g. use `foldLeft` instead of writing your own tail recursive function). We have implemented a set of ZIO operators including `ZIO.iterate` and `ZIO.whileLoop` that will "force you" to do the right thing. Often you can also express recursion in terms of concepts like `Schedule` or `forever` which will also automatically do the right thing for you.

Otherwise the thing to remember is just to make that recursive call the "last" thing that you do. Whether you do `failCause` or `refailCause` in the example above doesn't matter so you don't need to worry about that. If you needed to handle the `Cause` as well you would just replace `foldZIO` with `foldCauseZIO` and then your pattern match would be a little more complex.

I do think you are right that because of the different cases of `Cause` pattern matching on it can be a little low level. I would suggest using operators such as `Cause#isInterrupted` which will handle that logic for you.

Hope this helps!
