### ISSUE TITLE
Remove getOrFailWith

### ISSUE THREAD

**Issue by evis** [zio/zio#7169]
Example of using `getOrFailWith`:

```scala
ZIO.getOrFailWith(new Exception("some error message"))(
  List(1, 2, 3, 6, 7).find(_ == 3))
```

We have to read this code from the end to the beginning. That's confusing.

That's strictly better alternative in the terms of readability:

```scala
ZIO.fromOption(List(1, 2, 3, 6, 7).find(_ == 3))
  .orElseFail(new Exception("some error message"))
```

This way, we can grasp the code easier: first the logic, then the error handling for this logic. Not vice versa =)

**Comment by adamgfraser** [comment]
@evis Hi!

We can't delete operators because we have a binary compatibility guarantee. The most we could do is deprecate it.

This seems somewhat subjective and context dependent. The first snippet uses a single constructor, which some people prefer, whereas the second requires two different operators. The first can also be particularly readable if variables are extracted:

```scala
ZIO.getOrFailWith(noSuchElementException)(option)
```

Here the code reads quite naturally as "get or fail with a no such element exception". This also supports partially applying the constructor to create more specialized variants that fail with a user defined exception which can be helpful if you are doing this in multiple places.

Clearly you have an alternative you like more which is great and you can use that in your own code but I think there are people out there who are also like this so it isn't particularly helpful to take it away from them.

More broadly, we did a ton of effort to simplify the API for ZIO 2.0. Many people were involved in that, everyone got to provide feedback, and while I'm sure some people would have liked to simplify a little more and some people a little less this is where we ended up and I think it is a pretty good place overall. At this point I think we could just use stability in the API and to optimize and let people build on top of ZIO versus deprecating well defined methods because we happen to like writing things another way.
