### ISSUE TITLE
Schedule.fixed is not working with rates less than 1000 events per sec

### ISSUE THREAD

**Issue by Salamahin** [zio/zio#7214]
Looks Schedule.fixed assumes minimum duration of 1ms and milliseconds are used as atomic duration during next run scheduling.
Technically it looks it's possible to use nanosecond as atomic duration, so I'm curious is there any idea of making such strict limit?

**Comment by adamgfraser** [comment]
@Salamahin You're right that it doesn't. I don't think there is any particular but it doesn't seem like there has been a lot of demand for schedules with resolution below one millisecond. Unfortunately I think due to binary compatibility we would need to create a different operator if we wanted to support this.

**Comment by Salamahin** [comment]
Well for me scheduling more than 1k messages per second sounds reasonable. For example in some load-testing suites or similar. I'd say that in many cases rate of 1k msg/sec is very low for modern chips.

On the other hand Im a bit confused with the binary compatibility. See, right now the attempt of scheduling below 1ms would cause an error (see code snippet bellow). Do you expect that there are some ZIO users who relies on such behavior?

```scala
object Test extends ZIOAppDefault {
  val one = ZIO.succeed(1)
// the line below will throw the following 
// java.lang.ArithmeticException: / by zero 
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = one.repeat(Schedule.fixed(Duration.ofNanos(1000))) 
}
```

**Comment by adamgfraser** [comment]
No the issue is that the signature is currently:

```scala
def fixed(interval: Duration): Schedule.WithState[(Option[(Long, Long)], Long), Any, Any, Long]
```

Notice that the type of the state of the internal schedule is exposed in the type signature here. This supports serializing and deserializing schedules in a type safe way but means that changing the state of the schedule, which I think would be necessary to support nanosecond precision, would require changing the type signature, which would be an incompatible change.

Note that there are a variety of other ways you can do what you want, for example `(one *> ZIO.sleep(1000.nanoseconds)).forever` though of course ideally this would work as well.

**Comment by Salamahin** [comment]
Yes, i've missed the signature, thanks.

In general case I don't think that sleeping or delaying is a workaround, because `fixed` tries to enforce rates, in opposite to `spaced`, that basically looks working as on your example

**Comment by pragmaxim** [comment]
Sorry for my newbieness, but why :
```
zio.repeat(Schedule.fixed(30.seconds))
```
leads to : 
```
Found:    zio.Schedule.WithState[(Option[(Long, Long)], Long), Any, Any, Long]
Required: zio.Schedule[Any, Unit, Unit]
```
? I tried all Schedules possible

**Comment by adamgfraser** [comment]
@pragmaxim See below:

```scala
object Example extends ZIOAppDefault {

  val sayHello =
    ZIO.debug("Hello!")

  val run =
    sayHello.repeat(Schedule.fixed(1.seconds))
}
```

**Comment by pragmaxim** [comment]
:facepalm: My bad, `Long/Unit` ... sorry about that ... `(Option[(Long, Long)], Long)` distracted me from looking at the return type. 

I rewrote an app of ~ 10 LOC with Zio without any previous experience and there were just 2-3 strange issues, otherwise everything works like a charm, great job!
