### ISSUE TITLE
Predictable release cycle

### ISSUE THREAD

**Issue by ak0rz** [zio/zio#7216]
Hi,

Thanks for all the fish. :)

It's been a long time from version 2.0.0 has landed, and many changes has been introduced since then into series/2.x branch.

Is there any release cycle policy prefered by ZIO?
If not, maybe it would be helpful to create one? Like, for example, making a small maintenance patch every week or two.

Cheers!

**Comment by adamgfraser** [comment]
@ya-goodfella Hi! We do releases when there have been a sufficient number of changes for a release to make sense. I don't know if it has been a "long time" since June but will probably do another release shortly. 😃

**Comment by ak0rz** [comment]
Well, literally "long time" here refers to the number of changes between https://github.com/zio/zio/compare/v2.0.0...series/2.x :)

It's 173 commits since then and a huge set of differences with 379 files, +16304 -7468 LOC.

But I'm just curious - it there any discussions on providing some release strategy other than "when it's done"? I think for major releases rolling-release strategy is fine. If we encounter some critical problems with fresh release, we may flawlessly downgrade to the previous one and have a predictable fix time for the next release.

**Comment by adamgfraser** [comment]
I don't think this is correct. Since `2.0.0` there have been very changes. There has been a lot of documentation added which is on a separate release schedule but there have been very few changes to the underlying code. I tend to think it makes more sense to do releases when there are changes since there is no need for releases when there are not significant changes and this also lets us release more quickly if necessary based on user demand.

**Comment by adamgfraser** [comment]
Just did a release.

**Comment by guizmaii** [comment]
Thanks @adamgfraser!

Personally, I'd prefer smaller releases that are delivered more often. Especially when it's patch releases like this one that doesn't require any migration effort. 
It's easier to follow what changed and what has been fixed. It's also better when we are blocked by a bug present in the current latest version.

**Comment by adamgfraser** [comment]
@guizmaii Totally! If there is a big fix or feature you need feel free to reach out any time and should be able to do a release in pretty short order.

**Comment by ouertani** [comment]
@adamgfraser @ya-goodfella, I would also recommend that ZIOs community libraries such [ZIO AMQP](https://zio.dev/resources/ecosystem/community/zio-amqp)   or [ZIO Arrow](https://zio.dev/resources/ecosystem/community/zio-arrow) to be aligned with the same version numbering ( at least the major and minor).

**Comment by adamgfraser** [comment]
@ouertani I don't know if that is realistic considering that these projects have their own release cycles. For example ZIO Config is on version 3.0. In addition, community libraries are maintained by authors outside the ZIO organization so we don't have control over their versioning schemes.

I think a more sustainable way to address this is is probably by making it easier to find the latest version of ZIO libraries. The ZIO ecosystem tracker available [here](https://zio-ecosystem.herokuapp.com) is a good way to do this and will be integrated more deeply with the ZIO website in the future. Also versioning should be less important going forward as ZIO 2 versions are now binary compatible with each other.

**Comment by ouertani** [comment]
@adamgfraser Indeed such governance is not easy at all, but will really help to create a more trusted and robust ecosystem, compatibility where all components **tested** to work by default together ala _Spring_.  At least, all official libraries to be aligned. The alignment includes compatibility tests, documentations (updates with new features), one release note, ...

**Comment by adamgfraser** [comment]
@ouertani Definitely agree with the sentiment! 😃

Don't think the particular proposal regarding versioning makes sense because it would make it impossible for one ZIO library to release a new major or minor version until other libraries released one, even though some libraries such as ZIO itself are much more stable and others are evolving much more quickly.

However, we are working on a variety of things as we grow including building out the ZIO website and developing resources like ZIO Pet Clinic to show how everything fits together. Appreciate all of your comments on the documentation in this regard!

Going to close this but appreciate all the feedback and will incorporate as we work to keeping making ZIO better and better.
