### ISSUE TITLE
ZIO.orElseOpt

### ISSUE THREAD

**Issue by Fristi** [zio/zio#7219]
Does this exist already? Couldn't find it

```scala
private implicit class RichZIO[R, E, A](val zio: ZIO[R, E, Option[A]]) {
    def orElseOpt(other: ZIO[R, E, Option[A]]) = zio.flatMap(x => if (x.isDefined) ZIO.succeed(x) else other)
  }

```

**Comment by adamgfraser** [comment]
`left.some.orElse(right.some).unsome`

**Comment by Fristi** [comment]
Would it make sense to add a shortcut for this ? It might be a common thing right?

**Comment by adamgfraser** [comment]
It is a balance.

Any time we add a specialized operator for a `ZIO` with a certain data type inside it there is some convenience of being able to do something with a single operator.

At the same time, there are a very large number of these potential operators, for example you might want to do `orElse` with a `ZIO` with an `Either` inside of it or you might want to do other operations defined on `Option` or `Either` or `Iterable` on `ZIO` values with these data types inside.

In addition, there are already a very large number of operators on `ZIO`. Up to a point this is great because it makes it easier for people to do things but at a certain point it also has a cost that there are so many operators it becomes overwhelming and hard to find things.

The reason we developed operators like `some` and `unsome` or `right` and `unright` that "zoom in" and "zoom out" of nested data types is that they provide a more composable solution to these problems, though clearly more specialized operators would be more concise in certain cases.

I tend to think that we are at the point where there is a pretty high bar for adding new specialized operators for things you can do in a fairly straightforward way at this point and that this isn't common enough to add another specialized operator for.

**Comment by Fristi** [comment]
Yea good points, it's nice to have a minimal set of exposed API 

Type classes could solve the issue of defining the same behavior for the same 'shapes' however the ergonomics are not super good and staying away from that approach is one of the strengths of ZIO :)
