### ISSUE TITLE
Using deterministic generation together with non-deterministic one destroys randomness

### ISSUE THREAD

**Issue by inbrain** [zio/zio#7228]
Verified in zio 1.x (didn't check for 2.x)

Example: 
```scala
import zio.test._
import zio.test.Assertion._

object ExperimentSpec extends DefaultRunnableSpec {
  private val deterministicGen = Gen.fromIterable(List("a", "b", "c", "e", "f"))

  def spec = suite("Experiment")(
    testM("combining deterministic and non deterministic") {
      check(Gen.alphaNumericString, deterministicGen, deterministicGen, deterministicGen, deterministicGen) {
        (str, _, _, _, _) =>
          println(str)
          assert(str)(equalTo(str))

      }
    }
  )
}
```
Running this with default test settings prints the same string over and over. If we provide less amount of deterministic generators or less values for a generator, variability of values generated by non-deterministic ones will increase. 
This behaviour even if intended is extremely confusing and hard to track, because I mistakenly assumed it's fine to have `fromIterable` generators to be combined with others. While it gets better with fewer deterministic generators used in the same `check` block, it's not at all hard to have in a real test suite containing business objects with enum-typed fields to be reduced to just one value being generated for all non-deterministic generators within a test (actually that's how I accidentally stumbled on this behaviour) 
If it's intended or unavoidable, I would (at the very least ) expect it to be noted in scala docs.

**Comment by adamgfraser** [comment]
This is expected behavior. When you combine multiple generators you are basically using `flatMap` to put them together. So the example above is something like:

```scala
for {
  str <- List(Random.alphanumericString.mkString)
  a   <- List("a", "b", "c", "d", "e")
  b   <- List("a", "b", "c", "d", "e")
  c   <- List("a", "b", "c", "d", "e")
  d   <- List("a", "b", "c", "d", "e")
} yield (str, a, b, c, d)
```

So the generator isn't "losing" randomness, it is exhaustively exploring the possible values generated by the finite generators, which is the expected behavior.

To get the behavior I think you want you can just use `Gen.elements` instead of `Gen.fromIterable`, which will create a generator that randomly generates one of the elements instead of exhaustively exploring all of them.

@khajavi Would be good to add something about this in the documentation.

**Comment by inbrain** [comment]
@adamgfraser thank you, got it now, but yes, a hint in documentation would be really nice!
