### ISSUE TITLE
ZIO 2.0 Performance degradation when using provideLayer

### ISSUE THREAD

**Issue by jacobpovar** [zio/zio#7257]
Hi! First of all, thank you for all the hard work your put into making ZIO 2.0 release!

After upgrading my app to ZIO 2.0.1 I noticed much higher CPU usage (about 50% increase).

I'm using ZIO with Quill library, and internally it uses the following pattern - it calls provideLayer to provide DataSource into ZIO[DataSource, E, A] to make it ZIO[Any, E, A], so the dataSource is hidden from other components in the app.

To abstract away from quill, the usage is this:

```
trait InnerService {
  def foo: Task[Int]
}

object InnerService {

  val live = ZLayer.succeed(Live())

  case class Live() extends InnerService {
    override def foo: Task[Int] = ZIO.succeed(42)
  }

  val foo =
    ZIO.serviceWithZIO[InnerService](
      _.foo
    )
}

trait Outservice {
  val bar: Task[Unit]
}

object Outservice {

  val live = ZLayer.fromFunction(Live.apply _)

  case class Live(innerService: InnerService) extends Outservice {
    override val bar: Task[Unit] = {
        InnerService.foo.provideEnvironment(ZEnvironment(innerService))
    }
  }
}

main: 

    (for {
      _ <- ZIO
       
    } yield ())
      .provide(
        Outservice.live,
        InnerService.live,
        OtherService1.live,
        ... // bunch of other services here
      )

  }
}

```

After some profiling I found out that half of the time my app tries to find services in ZIO environment 
<img width="936" alt="Screenshot 2022-08-26 at 09 17 20" src="https://user-images.githubusercontent.com/664640/186835400-9616bdc0-949f-43d5-99ee-a98e998b76a7.png">. 

Each call to provideLayer or provideEnvironment [creates fresh new environment that has in its map all the services from parent environment and empty cache](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala#L1197). After that, when 

```
    ZIO.serviceWithZIO[InnerService](
      _.foo
    )
```

is called, it iterates across the entire map to find the matching instance by tag, since it is not cached is this newly created environment.

<img width="1439" alt="Screenshot 2022-08-26 at 09 22 17" src="https://user-images.githubusercontent.com/664640/186836129-169d662a-2055-4ba6-a8f4-ac3c5411a7a3.png">

This design works great if you have only one env for the entire app, but not when ZEnvironment is created of each call.

I created sample two samples to illustrate the problem: [this code in ZIO 1.0](https://gist.github.com/jacobpovar/bfebac2613cb73067cc3cf026c4a0037) completes in 1 seconds, 
while the [same code in ZIO 2.0](https://gist.github.com/jacobpovar/7a6d1c775c9e4947a4da49851a7f5d42) takes about 10 seconds and the more services your have in the whole app - the slower internal service call becomes.

Is this the expected behaviour? Should the `provide` now be used only on the edge or the app?

**Comment by adamgfraser** [comment]
@jacobpovar Hi! It may be possible to further optimize `ZEnvironment` but this usage is actually an anti-pattern.

Instead of doing this:

```scala
  case class Live(innerService: InnerService) extends Outservice {
    override val bar: Task[Unit] = {
        InnerService.foo.provideEnvironment(ZEnvironment(innerService))
    }
  }
```

You want to do this:

```scala
  case class Live(innerService: InnerService) extends Outservice {
    override val bar: Task[Unit] = {
        innerService.foo
    }
  }
```

There is no need to use the accessor `InnerService.foo` to access an `InnerService` in the environment and then provide it because you just have an `InnerService` sitting there as a constructor parameter!

We recommend against using the first pattern because it has a cost not only in terms of performance of having to access the environment an additional time unnecessarily but also in terms of ergonomics in terms of having to do this additional `provideLayer` everywhere. One of the reasons we removed the default ZIO services from the environment was to avoid the need to do this.

Instead we recommend providing all functionality of an interface as part of operators on that interface and defining higher level services in terms of lower level ones. In a fully idiomatic ZIO application the only time you use accessors is in your main application or in tests. And you don't even do it in your main application if your main application is itself a service.

Hope this helps!

**Comment by jacobpovar** [comment]
Thank you for the clarification
