### ISSUE TITLE
Blocking service do not accept unlimited number of tasks

### ISSUE THREAD

**Issue by Matzz** [zio/zio#7318]
This ticket refer to ZIO 1 but may also be valid for ZIO 2.

From Blocking documentation:
"The Blocking module provides access to a thread pool that can be used for performing blocking operations, such as thread sleeps, synchronous socket/file reads, and so forth. **The contract is that the thread pool will accept unlimited tasks (up to the available memory) and continuously create new threads as necessary.**"

However, the default executor for Blocking service is bounded to 1k threads and `SynchronousQueue` which effectively has 0 capacity:
```scala
  private[blocking] object internal {
    private[blocking] val blockingExecutor0 =
      Executor.fromThreadPoolExecutor(_ => Int.MaxValue) {
        val corePoolSize  = 0
        val maxPoolSize   = 1000
        val keepAliveTime = 60000L
        val timeUnit      = TimeUnit.MILLISECONDS
        val workQueue     = new SynchronousQueue[Runnable]()
        val threadFactory = new NamedThreadFactory("zio-default-blocking", true)

        val threadPool = new ThreadPoolExecutor(
          corePoolSize,
          maxPoolSize,
          keepAliveTime,
          timeUnit,
          workQueue,
          threadFactory
        )

        threadPool
      }
  }
```

This configuration leads to RejectedExecutionException being thrown if we spawn more than 1k blocking concurrent tasks.
I would consider using unbounded number of threads or unbounded workQueue to solve that.

**Comment by adamgfraser** [comment]
I actually think this is a feature rather than a bug. Accepting an unlimited number of tasks sounds great but the reality is that threads are not free and creating a very large number of threads kills application performance. I've seen a lot of cases in production where people use a completely unbounded thread pool and it solves the short term problem but creates performance issues that are much harder to diagnose. Whereas this way you "fail fast" and add something like a `Semaphore` to control the degree of concurrency.

Clearly there is some degree of subjectivity here and you can use your own implementation of the blocking executor with a higher bound or no bound at all but given the above and that this has been the behavior for the life of ZIO I am somewhat disinclined to change the default at this point.

**Comment by Matzz** [comment]
@adamgfraser
I agree that enormous number of threads will lead to a lot of problems. From the other hand, `RejectedExecutionException` is not sth you expect while using ZIO. Especially, when at some point you decide to shift some effect from the default thread pool to blocking. Those kind of errors may manifest very late at software lifecycle (most probably on production or during load tests).  That's why I was considering replacing SynchronousQueue with LinkedBlockingQueue which is used by default pool. Maybe ForkJoin is also an option?
From my point of view, current behaviour should be at least clearly described in documentation and api docs. What's, more it would be nice to have ability to create custom Blocking service in an easy way.  Right now all params are hardcoded, so you need to create exec service on your own. What's worse, `NamedThreadFactory` is private so you need to create your own implementation.

**Comment by adamgfraser** [comment]
@Matzz Will take a look.
