### ISSUE TITLE
define "preferred way of usage" for "context parameters"

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7601]
When I first learned about ZIO's Environment parameter, I thought this was supposed to be the equivalent to the "**Context** and **Dependency Injection**" (CDI) that is known from the JavaEE/JakartaEE world ( https://www.cdi-spec.org/ , https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html ) .

Nowadays, it feels like we use the Environment parameter only when defining layers (**Dependency Injection**) and most of the effects in production code bases have `Any` set as the environment (so no context). 
Also, since logging is now not part of the environment anymore, things like `CorrelationId`/`TraceId` gets stuffed into the (internal) logging `FiberRef`. 

This leaves the question how people are supposed to propagate stuff like a `UserId`, one or multiple `Role`s, `GroupMembership` or in a wider context a `Principal` / `SecurityContext` through the layers of an application. 
- Should we stuff everything in `FiberRefs` when starting the request? 
- Should we "abuse" the logging context? 
- Should we put them into the Environment type? 
- or should we pass it down as function parameters (thereby transforming an effect that could be a `val` to be a `def`)? 

I think the drivers of ZIO, namely @jdegoes and @adamgfraser but also core users like e.g. @adamw should discuss and decide on a best practice here and drive this forward by spreading the word through Zymposiums, Talks, Blog-Posts & enhancing the documention and so on. Maybe we'd even need something similar like the JCP for "big" topics like this, idk.

I think (some) guidance would be good for the community in this regard. Maybe we can also gather some experience from big customers like CapitalOne, Coralogix and so on... I think they surely had this use case and solved it somehow. 

Please let me know what you think.

Thanks,
Dominik

**Comment by adamgfraser** [comment]
@domdorn Hi! The idiomatic usage of the ZIO environment has changed significantly between ZIO 1.0 and ZIO 2.0. While there is some information regarding this, particularly The Three Laws of ZIO Environment (available [here](https://twitter.com/jdegoes/status/1463261876150849547?lang=en) and [here](https://zio.dev/reference/service-pattern/the-three-laws-of-zio-environment/)) I agree that this is an area that could use further clarification.

**Local Capabilities**

The most idiomatic use of the ZIO environment is for:

1. Describing as values workflows that use capabilities that are "local" to a particular context
2. Where tracking the use of this context at the type level is helpful for reasoning about programs

Let's look at `Scope`, which I would say is the most idiomatic usage of the environment in ZIO itself, to see what each of these mean.

The first criteria is that a capability be "local" to a particular context and not shared throughout the entire application. For example, in the case of `Scope` we typically don't just have one scope for our entire application but many smaller scopes, such as the scope for using a particular file. Usages of local context also have an operator that allows locally eliminating this capability, such as the `ZIO.scoped` operator which transforms a `ZIO[R with Scope, E, A]` to a `ZIO[R, E, A]`.

Other potential examples of this would be the `ZState` data type in ZIO, which describes some local use of state and is eliminated by the `ZIO.stateful` operator, a `Transaction` representing the usage of a database transaction, or the context of a particular HTTP request.

Notice that using the environment type allows workflows that require these capabilities to be first class values that compose naturally and can have their own operators for working with them, which would not be possible if we defined them as methods that required us to explicitly pass around these capabilities.

The second criteria is that tracking the usage of this context be helpful for reasoning about programs. We can also use a `FiberRef` value to maintain some local context. However, when we do so, our usage of that context is not reflected at the type level. For example, when we log something it will use a variety of contextual information including the current log level, the current log span, and the current log annotations but none of this is reflected at the type level:

```scala
object ZIO {
  def log(message: => String)(implicit trace: Trace): ZIO[Any, Nothing, Unit]
}
```

Not reflecting this usage of contextual information at the type level can be both an advantage and a disadvantage. The advantage is that it can create a simpler API because we do not clutter up the environment with additional dependencies. The disadvantage is that we can't track at the type level whether we are using contextual information or whether we have provided it.

In the case of logging this is clearly the right trade-off. Logging is a low level concern that we don't want to require us to update our type signatures, and there is essentially no harm in running a ZIO workflow that does logging without providing this log context since we can just log at some default log level without any log spans or annotations.

In contrast, in the case of `Scope` there is tremendous value in reflecting the use of `Scope` at the type level so we know whether a workflow is resourceful and can have operators that reflect at the type level that we have provided a `Scope` to part of our application. Similarly if we have a database transaction reflecting at the type level that some workflow needs to be done as part of a transaction and when we are "executing" a transaction is extremely valuable.

**Business Logic**

The other potential use of the ZIO environment is describing the dependencies of our business logic itself. Normally, we implement higher level services in terms of lower level services using constructor based dependency injection with `ZLayer`.

```scala
trait HighLevelService {
  def doSomething: ZIO[Any, Nothing, Unit]
}

object HighLevelService {
  val live: ZLayer[LowLevelService, Nothing, HighLevelService] =
    ZLayer.fromFunction(HighLevelServiceLive(_))

  final case class HighLevelServiceLive(lowLevelService: LowLevelService) extends HighLevelService {
    def doSomething: ZIO[Any, Nothing, Unit] =
      ??? // implemented in terms of `LowLevelService`
  }
}

trait LowLevelService {
  def doSomethingElse: ZIO[Any, Nothing, Unit]
}

object LowLevelService {
  val live: ZLayer[Any, Nothing, LowLevelService] =
    ???
}
```

This allows us to avoid using `LowLevelService` in the environment and to not "leak" implementation details, since the dependency on `LowLevelService` is an implementation detail of `HighLevelService` that might not even exist if `HighLevelService` is refactored.

However, the question arises then of how we should work with `HighLevelService` in the core of our business logic or the center of the "onion" in the onion architecture.

There are two approaches to this.

One is just that everything is a service:

```scala
sealed trait ApplicationService {
  def run: ZIO[Any, Nothing, Unit]
}

object ApplicationService {
  
  final case class ApplicationServiceLive(highLevelService: HighLevelService) extends ApplicationService {
    val run: ZIO[Any, Nothing, Unit] = ??? // business logic implemented in terms of high level services
  }
}

object Main extends ZIOAppDefault {
  val run =
    ZIO
      .serviceWithZIO[ApplicationService(_.run)
      .provide(
        ApplicationService.live,
        HighLevelSevice.live,
        LowLevelService.live
      )
}
```

This style avoids any usage of the ZIO environment that is not a local capability except for possibly a single time within `ZIOAppDefault`. This way there is no need to implement service accessors, except for potentially writing tests, and there is a certain conceptual regularity that everything is a service.

However, there can be a feeling that defining this final `ApplicationLevelService` is unnecessary and we would like to be able to write our business logic in terms of high level services directly without making it another service.

```scala
object Main extends ZIOAppDefault {

  val myProgramLogic: ZIO[HighLevelService, Nothing, Unit] =
    for {
      _ <- ZIO.serviceWithZIO[HighLevelService](_.doSomething)
      - <- otherLogicHere
    } yield ()

  val run =
    myProgramLogic.provide(
      HighLevelSevice.live,
      LowLevelService.live
    )
}
```

There has been some movement towards the "everything is a service" approach since it avoids the need to implement service accessors but it can be a matter of team style which of these approaches to use. Either way your program is the same except for whether in your business logic you call methods on services directly or use the environment for that.

Hope this helps!

**Comment by adamw** [comment]
I can only second what @adamgfraser wrote. Also to clarify, I'm not involved in the design or development process of ZIO, but I'm rather an external observer, trying to understand the ideas that the ZIO team comes up with and sometimes writing about the results in a blog post.

I've been a long proponent of constructor-based DI (having spent some time working with CDI and its predecessors), as the simplest model and more importantly - one doing its job. ZIO 2.0 definitely goes in this direction, which I'm really happy about, as I wasn't a fan of the approach taken in 1.0.

It should probably come as no surprise that I'd take the first route proposed by Adam, that is treating everything as a service and always using constructors to inject dependencies, which as Adam writes, are an implementation detail of the service. Sometimes there are two layers of services, sometimes more, and if we use different mechanisms for different layers (not in the `ZLayer` sense), we might end up with a weird hybrid. I think that if we'd want an approach to be widely adopted, it needs to have clear rules. Using constructors for DI, reifying these constructors as `ZLayer` values, and using `make` to assemble the object graph I think is simple enough to be followed by a number of ZIO projects. 

Environment is great for local context - scopes, transactions, security context. This does mean that it's not used *that* often, but that's fine - the fact that a feature is there (here: ZIO environment), doesn't mean we have to use it whenever there's a possibility :)

If there's anything missing from the above, is some guidelines as to how libraries should behave. Taking an example from my own back yard, I often see example ZIO code which does use the environment for dependencies. E.g. with an `HttpClient`, you might have `request.get("http://example.org"): ZIO[HttpClient, Exception, Response]` or something similar. This does look succinct and nice, however I'd rather write this as `httpClient.get("..."): ZIO[Any, Exception, Response]`, where `httpClient` is a constructor-injected dependency; or, following the sttp style `sttpBackend.send(basicRequest.get(uri"http://example.org")): ZIO[Any, Exception, Response[...]]`

That said, maybe there should be other rules for libraries to follow, but as far as I'm concerned, I think treating them as any other dependency (even if on an infrastructural level) is the simplest thing to do.

**Comment by adamgfraser** [comment]
Those are called accessors. If we have a service we can make it easier to use with the environment by implementing an accessor like this:

```scala
trait HighLevelService {
  def doSomething: ZIO[Any, Nothing, Unit]
}

object HighLevelService {
  val doSomething: ZIO[HighLevelService, Nothing, Unit] =
    ZIO.serviceWithZIO(_.doSomething)
}
```

In an idiomatic ZIO 2.0 application these accessors are generally only used in two situations.

First, if you are using the style where you access services directly in your business logic, this can support a particularly ergonomic way of doing so.

```scala
object Main extends ZIOAppDefault {
  val run =
    HighLevelService.doSomething.provide(
      HighLevelService.live,
      LowLevelService.live
    )
}
```

Of course you never have to do this. You could instead define your business logic as a service that takes `HighLevelService` as a constructor parameter and use `highLevelService.doSomething` instead.

Second, these accessors can be very useful in writing tests. For example:

```scala
suite("some suite")(
  test("some test") {
    for {
      response <- HttpClient.get(request)
    } yield assertTrue(response == ???)
  },
  test("some other test using the client") {
    ???
  },
  test("yet another test using the client") {
    ???
  }
).provideLayer(testClient)
```

Here `HttpClient.get` accesses a client in the environment and uses it to get the response to a request. `provideLayer` provides a separate copy of a test implementation of the client to each of our tests.

We could manually create a test client in each of our tests and call `get` on it but here the use of the environment seems particularly ergonomic with `provideLayer` automatically taking care of creating a separate instance of the test client for each test.

One way to think about this is as a special case of the point above about it being nice for us to not have to always implement our business logic as a service. The body of each of our tests represents the "business logic" of a miniature application we are testing the behavior of and it is nice to be able to define that logic inline versus having to create a separate service for each of them.

You don't have to use these accessors at all but they can be useful in these two situations. So I think it makes sense for ZIO libraries to provide them and then users can use them if they want.

**Comment by adamw** [comment]
@adamgfraser Thanks for the explanation :) 

I think I don't see any substantial difference between low-level services, high-level services, or infrastructural services / libraries, so I'd just use them the same way. That is, the fact that I'm using an `HttpClient` in my high-level service is an impl detail, and I'd hide it from the users.

I understand the ergonomic arguments in smaller applications / tests, so it's not an easy choice :)

But in the end, I'm not sure if I should bring back ZIO 1.0-style accessors for `SttpBackend` or not.

**Comment by adamgfraser** [comment]
@adamw Well it is your library so you can do whatever you want. :smiley:

But I would encourage library authors to provide these accessors. It is extremely low effort for library authors, basically a couple of one line methods that write themselves. And it can be useful for users to either write tests or to consume your services directly in their business logic.

Also note that there is no difference between high level services, low level services, or infrastructural services / libraries.

Functionality that is going to be consumed by other parts of your code should be modeled as services. Services should be composed with each other using constructor based dependency injection with `ZLayer`. Services should not expose environmental requirements in the service interface other than local capabilities such as `Scope`.

The only question is whether functionality that is not consumed by any other code should be modeled as a service. In other words, should the "root" of the dependency graph itself be a service? Saying that it should be is a perfectly logical position. But saying that it shouldn't be is also perfectly logical, is based on an extremely objective criterion, and can have practical advantages as we have seen in cases such avoiding boilerplate in writing simple applications or writing tests.

So I think while there is value in consistency there is also value in the principle of "don't be preachy" and this is an easy case where you can implement a simple method that makes it easy for users to consume your functionality in the way that makes the most sense for them.

**Comment by 987Nabil** [comment]
@adamgfraser Do you have some real world examples in applications of non-trivial size where the accessor pattern feels good to use?

When we started writing a new app with this style, as it was what we saw in symposiums, we ended up with an app that was not pleasant for the eye.

1. The accessor just feels like another level of indirection. One that is unnecessary, compared with having a service with a dependency.
2. It's more code. The types are getting more complex und the code for the accessor itself.
3. It was hard to understand for new devs. After changing to only dependencies in the service, I got much less questions.

Imho, the accessor pattern whenever used in docs, examples or symposiums should come with a **BIG WARNING** about the trade-offs.

**Comment by adamgfraser** [comment]
@987Nabil I've definitely seen accessors be helpful in very large code bases though as described above their usage is limited to in tests and possibly at the "root" of the dependency graph.

In tests doing something like `PersistenceService.get(user)` can be more ergonomic than doing `ZIO.service[PersistenceService]` and then calling methods on the service directly. I've found that it can also be helpful in minimizing the need for most users to work directly with operators for the environment, which can be one of the more advanced features of ZIO, and in making the service feel like something that just exists that you can call operators on. But your mileage may vary and there is some work to implement the accessors so you have to decide whether that makes sense for you.

The other case where accessors are potentially used, in the "root" of the dependency graph, typically doesn't end up being that much of a difference in large code bases. Almost by definition, in a well structured code base using the service pattern most functionality is pushed into services so it is only this one section of the code where you are wiring the services together that there is essentially a stylistic difference.

I've seen some people like the accessors there because it can support a very ergonomic style where you just call these various accessors. It can also allow you to see in your type signature what services are used by different parts of this code because it shows up in the type signature. In contrast, if you implement this as another service you typically just have all of your dependencies in scope and so don't see at the type level where different services are being used.

I think we have followed these principles of not using accessors in implementing other services in all of our training and educational materials for ZIO 2.0. This leaves the environment free to be used by user defined services but also allows users to avoid working with the environment at all excluding local capabilities if they want to, which sounds like has worked for you.

**Comment by adamw** [comment]
@adamgfraser 

> Well it is your library so you can do whatever you want. 😃

Sure, but I'm trying to follow whatever the "recommended" way of using each library that sttp/tapir is integrating with. It's not always obvious what the recommendations are, though ;)

> The only question is whether functionality that is not consumed by any other code should be modeled as a service. 

That's an interesting aspect - I'll add it to list as to how dependencies can be differentiated - thanks.

**Comment by adamw** [comment]
Btw., @adamgfraser, the above is the cleanest explanation as to when use constructors / layers / environment, I think there's more people which are puzzled by this in addition to me & OP. Even copy-pasting what you wrote here to https://zio.dev/reference/di/ would help a lot I think :)

**Comment by jdegoes** [comment]
cc @khajavi please update documentation based on @adamgfraser's comments.

**Comment by domdorn** [comment]
Thanks @adamgfraser for the explaination about structuring services. I already implement this pattern in my applications, but such a clear explaination is very helpful, especially for new users!
What you explained is basically the "dependency injection" equivalent part of `CDI` .. what's still not clear is the "context" part. 

What kind of data do I mean by context? 
 - CorrelationId
 - UserId
 - SecurityContext ( UserId + Roles / Permissions )
 - RoleMemberships ( list of Roles, e.g. `User`, `Admin`, `Moderator`, ...)

Basically stuff that gets created/initialized (e.g. `CorrelationId` gets created to a new `UUID` when a controllers is invoked by a browser) or resolved (`CorrelationId` gets read from a header when the controller gets called from another service or a consuming component is processing a message from a message queue, `UserId` gets parsed from a JWT-Token) at the outermost layers of the application ( web controllers, queue consumers, etc. ).

I haven't seen a best practice on how to do solve this.. at the moment, my application is always passing these "context parameters" as function parameters (either explicitely in case of `UserId` or implicitely in terms of `CorrelationId`). 
In ZIO 1, we've put the `UserId` and `CorrelationId` into the logging context.. it was kind of a convention that we had `Logging` in every Environment and that these parameters where available e.g. in the repositories storing data or in the outgoing http-clients calling other services (and passing on the `CorrelationId` and `UserId` via headers). 

Now in ZIO 2 the `LoggingContext` is implemented as a `FiberLocal`..  

1) should we put `CorrelationId` and `UserId` as well into a `FiberLocal`? or
2) should our effects be something like `val someEffect: ZIO[CorrerlationId & UserId, ErrorType, A]` ? or 
3) should we keep writing our effects with explicit params as `def someEffect(c: CorrelationId, u: UserId, params...): ZIO[Any, ErrorType, A]` ? or
4) should we put these context parameters as implicits, like `def someEffect(params..)(implicit c: CorrelationId, u: UserId): ZIO[Any, ErrorType, A]` ? 

So its a question on what is the best practice in passing these "context" parameters down from the outermost layer / "web controller" to innermost layers/external systems like
1) the "repository" (where `CorrelationId` and `UserId` are stored as column values in a table or the `UserId` is used to check if a user is allowed to read a certain row from a table) or 
2) to a message queue producer, where these fields are either stored in a header or as part of the message 
3) to a http / grpc client, which uses these fields when talking to other services to establish a log/correlation-trail

**Comment by adamgfraser** [comment]
@domdorn Sure! I tried to address this in my discussion above regarding using the environment for capabilities that are helpful to track at the type level and the logging example but let's go into this in a little more detail.

We have some workflow, `someEffect` that conceptually requires both a `CorrelationId` and a `UserId` to be run. You've helpfully laid our four alternatives. Let's consider them in turn.

**Explicit Parameters**

The simplest way to model this dependency is just as function parameters:

```scala
def someEffect(userId: UserId, correlationId: CorrelationId, ...): ZIO[Any, ErrorType, A] =
  ???
```

This is a fine starting point. Functions that take arguments are about as simple as you can get. However, there are two main issues with this.

First, it can just become a lot of boilerplate. The signature above looks potentially okay on its own, but if it is being called by some other function which in turn is being called by some other function it can become a lot of boilerplate very fast which is why people turn to all of these alternatives. I don't think there is a hard and fast rule for when it gets to be "too much" boilerplate but if you are unsure I think a good practice can be to use explicit parameters until you "feel the pain" and then you can refactor to one of the alternatives discussed below.

The second problem with this approach is that `someEffect` is a method and not a first class value, which can limit our ability to work with it in some cases. But typically the boilerplate is the overwhelming problem that leads people to move away from this approach.

**Implicit Parameters**

The second alternative you highlight is to make these parameters implicit.

```scala
def someEffect(...)(implicit userId: UserId, correlationId: CorrelationId): ZIO[Any, ErrorType, A] =
  ???
```

This addresses the boilerplate problem with explicit parameters by allowing us to pass them implicitly.

I would basically never recommend this solution.

To reason about implicit values in a principled way we want them to be "coherent" which means there is only one implicit value corresponding to any type within our entire program. For example, there is only one `Associative` instance for `String` if we are using functional abstractions, or there is only one `JsonEncoder` instance for `Person`.

If this requirement is not satisfied we get into anti-patterns like an implicit `ExecutionContext`, where changing our imports or moving a block of code can change which thread pool we run on.

By definition, contextual values like this never satisfy this coherence requirement because there are lots of different `CorrelationId` and `UserId` values in our program. We need to pass them around explicitly or implicitly precisely because there are different ones.

So while there are some cases where there might be different alternatives we want to consider this one I think we can rule out.

**Environment and FiberRefs**

The final two alternatives are modeling these contextual values as part of the ZIO Environment or as `FiberRef` values.

If we model both of these requirements as part of the environment our method signature would look like this:

```scala
def someEffect(...): ZIO[UserId & CorrelationId, ErrorType, A] =
  ???
```

If we model them as `FiberRef` values we would define `FiberRef` values that described both the `UserId` and the `CorrelationId`:

```scala
val currentUserId: FiberRef[UserId] = ???
val currentCorrelationId: FiberRef[CorrelationId] = ???

def someEffect(...): ZIO[Any, ErrorType, A] =
  ???
```

Both of these approaches are similar in that they allow us to avoid the boilerplate associated with passing around the `UserId` and the `CorrelationId`, they allow us to treat `someEffect` as a value, and they allow us to locally modify the current value of the `UserId` and `CorrelationId`.

The main difference between these two approaches is that with the ZIO Environment we reflect the fact that `someEffect` needs a `CorrelationId` and a `UserId` in the type signature, whereas when we use a `FiberRef` this requirement is not reflected in the type signature.

Including these requirements in our type signature can be both an advantage and a disadvantage. The advantage is that we make explicit that `someEffect` requires this contextual information, and we cannot even run `someEffect` without providing it. The disadvantage is that we have to include these requirements in the type signatures of all of our workflows, which can "bubble up" through many method signatures and arguably exposes an implementation detail.

So the question I would ask here, going back to my original answer, is whether including these requirements in your type signature is helpful for you to reason about your program. Some related questions you might ask yourself are "would it make sense to run the workflow if a requirement were not provided?" and "is there a sensible default value of this requirement"?

Applying these to the `CorrelationId` and `UserId` I would be tempted to not include the `CorrelationId` in the environment. It may depend what we are doing with it but it seems like the `CorrelationId` is a low level implementation detail associated with logging that we do not need cluttering up our method signatures. There seems to be a very sensible default `CorrelationId` of `None` indicating that there is no `CorrelationId` associated with whatever we are doing and we can still run our program without having a `CorrelationId`, our logs will just not be as helpful as they otherwise would be which we can see and correct.

On the other hand for `UserId` I could easily see coming to the opposite conclusion. If `UserId` is supposed to tell us which user we are supposed to look up in a database or whether we are supposed to be able to look up certain information at all then we may not even be able to run `someEffect` without having a `UserId`. Of course we could just fail at runtime but failing at runtime is much more severe than just logging less precisely and normally we want to use the type system to convert runtime failures to compile time failures. So this seems like it might be a great case for using the ZIO environment.

**Comment by domdorn** [comment]
Thanks @adamgfraser .. so my attempt to sum up your explaination would be: 
1.) For context parameters, that are **of an optional nature**, e.g. the program could run without them or with a sensible default, put them into a `FiberRef`. Examples include `CorrelationId`, `TraceId`, `SpanId`, or other potential useful info that is not strictly required, but sometimes helpful, e.g. 
  - `UserAgent`,
  -  `URL`,
  - `request start time`,
  - `remote ip`, ...

2.) Context parameters that are **strictly required** for the program to function, e.g. because the program is required to do checks on them **SHOULD be put into the environment**. 
  So the type signature of most of the effects in our program changes from `ZIO[Any, E, A]` to e.g. `ZIO[UserId & SecurityContext, E, A]`  or `ZIO[SessionId, E, A]` etc.. 
  Users would most probably then introduce type aliases like `type F[E,A] = ZIO[UserId & SecurityContext & TenantId, E, A]` or `type F[R, E, A] = ZIO[UserId & SecurityContext & TenantId & R, E, A]` 
  

As for my local application, `CorrelationId` would even be a required parameter, as it gets stored with every record in the database and logs get archived in the data lake, so I'd HAVE to put it in the environment. 

If the above summary is correct, I now have a rule of thumb on when to use what which is what I was aiming for.
If the summary is correct, I think it would be great if we could put this also in the documentation and maybe even create a zymposium to spread the word to a wider audience. 

@adamgfraser please confirm if the summary is correct or I got something wrong.

**Comment by domdorn** [comment]
When spinning these rules/ideas further, this basically _could_ mean:

1) `ZLayer` and the `R` in `ZLayer` is for dependency injection (in terms of services, clients, repositories, adapters, ...), we might want to think of renaming `R` to `D`(for Dependency). 
2) `ZIO` and the `R` in `ZIO` is for context injection (in terms of `UserId`, `TenantId`, and so on). We might want to think of renaming `R` to `C`(for context). Providing a `ZIO.context[A]` method (basically a copy of `ZIO.service[A]`) could clarify this even more. 

IMHO this would make things super clear for users on when to use `ZLayer` and `ZIO` and how to implement the above "rule"

Wdyt?

**Comment by adamgfraser** [comment]
@domdorn I would think a little more broadly in terms of whether reflecting a requirement in the type signature is helpful for reasoning about a program than just whether there is a sensible default value, though that is a necessary factor for using a `FiberRef`.

For example, `Scope` could have a sensible default value of an application level scope that is closed at the end of the application, and in fact we do provide such as a `Scope` in `ZIOAppDefault`. But modeling `Scope` as a `FiberRef` would mean that we wouldn't know from the type signature whether a workflow is resourceful, which seems quite useful.
