### ISSUE TITLE
Native build failures are not being treated as failures by SBT / Github Actions

### ISSUE THREAD

**Issue by swoogles** [zio/zio#7671]
Example from the latest run:
https://github.com/zio/zio/actions/runs/3838841200/jobs/6535811993

I don't know how long this has been happening. Will investigate.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/2054940/210622861-ba69e88a-4ce5-42fe-9a68-5f5f324b47cf.png">

**Comment by sideeffffect** [comment]
This is a known issue. Should be fixed in the next Scala Native release (0.5.0?). Relevant tickets are:

 * https://github.com/zio/zio/pull/7031#issuecomment-1284181604
 * https://github.com/scala-native/scala-native/issues/2858
 * https://github.com/scala-native/scala-native/issues/2920

Scala Native PR that solves it
https://github.com/scala-native/scala-native/pull/2949

**Comment by sideeffffect** [comment]
This has been fixed

**Comment by sideeffffect** [comment]
This has been fixed @swoogles @adamgfraser
