### ISSUE TITLE
Gen.fromIterable causes other generators to repeat values

### ISSUE THREAD

**Issue by nigredo-tori** [zio/zio#7709]
This might be the same behavior that was mentioned in https://github.com/zio/zio/issues/5616#issuecomment-925879253, but I don't see an issue covering it.

Given a generator like this:
```scala
val gen = for {
  uuid <- Gen.uuid
  _ <- Gen.fromIterable(Seq(0, 0))
} yield uuid
```
, code like this
```scala
test("with check") {
  check(gen) { x =>
    println(x)
    assertTrue(true)
  }
} @@ samples(2)
```
prints two identical values!

Here's a spec that actually checks what is happening - with `check` inlined:
```scala
import zio.Scope
import zio.test.{Gen, Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

object GenSpec extends ZIOSpecDefault {

  val gen = for {
    uuid <- Gen.uuid
    _ <- Gen.fromIterable(Seq(0, 0))
  } yield uuid

  override def spec: Spec[TestEnvironment with Scope, Any] =
    test("Gen issue") {
      for {
        uuids <- gen.sample.forever.collectSome.take(2).runCollect.map(_.map(_.value))
      } yield assertTrue(uuids.distinct.size == uuids.size)
    }
}
```

**Comment by adamgfraser** [comment]
That is expected behavior. `Gen.fromIterable` creates a deterministic generator that has two elements, in this case `0` and `0`. The composed generator is going to exhaustively explore the space of values that contain the first generator and the values specified in the deterministic generator.

So if your deterministic generator is `Seq(0, 1)` in your example above you will get `(firstUUID, 0)`, `(firstUUID, 1)`, `(secondUUID, 0)`, `(secondUUID, 1)`.

If you want to sample a random value from the collection instead of exhaustively sampling all values you can use `Gen.elements`.

This will produce `(firstUUID, 1)`, `(secondUUID, 0)`, `(thirdUUID, 0)`, `(fourthUUID, 1)` where whether `0` or `1` is samples each time is random.
