### ISSUE TITLE
Metrics: Provide way to access tags & name

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7838]
Hi!

I'm trying to create a unit test for metrics, e.g. a histogram. I'm able to access the `bucket`s of the histogram like this:

```scala
    suite("Tiny Metrics")(
      test("should have 5ms buckets up to 500ms"){
        val m = RTDMetrics.timerTiny("test")
        for {
          value <- m.value
          buckets = value.buckets
        } yield assertTrue(buckets.length == 101) &&
          assertTrue(buckets(0) == (5.0, 0L)) &&
          assertTrue(buckets(1) == (10.0, 0L)) &&
          assertTrue(buckets(99) == (500.0, 0L)) &&
          assertTrue(buckets(100) == (Double.MaxValue, 0L))
      }
    ),
    
    ... 
    
  private[rtd] def timerTiny(
    name: String
  ): Metric[MetricKeyType.Histogram, Duration, MetricState.Histogram] = {
    val chronoUnit = ChronoUnit.MILLIS
    val boundaries = Histogram.Boundaries.linear(5, 5, 100)
    val base       = histogram(name, boundaries).tagged(MetricLabel("time_unit", chronoUnit.toString.toLowerCase()))

    base.contramap[Duration] { (duration: Duration) =>
      duration.toNanos / chronoUnit.getDuration.toNanos
    }
  }
    
```

However, I found no way to access the tags/`MetricLabel` or the `name` of the metric.
How can I access these?

**Comment by adamgfraser** [comment]
@domdorn Metrics don't have a well defined concept of tags or names because metrics can be composites.

If I `zip` together two metrics or I do a `collectAll` on an `Iterable` of `PollingMetric` what is the name of that metric? I can just combine the names in some arbitrary way but that is not very principled.

Similarly each of those underlying metrics can have different tags so I can just combine all the tags into a set but that doesn't really represent anything since none of those underlying metrics may have those tags and they may in fact be inconsistent with each other.

**Comment by 987Nabil** [comment]
@adamgfraser How about an approach that is purely test focused? Something like a test backend for the metrics, where you can inspect immited values and their tags? Something similar to the test logging experience we already have in ZIO.

**Comment by adamgfraser** [comment]
@987Nabil You can already use the `value` operator to retrieve the value of a metric at any point in time.
