### ISSUE TITLE
possible `raceFirst` regression in 2.0.7+

### ISSUE THREAD

**Issue by anovstrup** [zio/zio#7858]
I haven't been able to fully isolate the issue yet, but the following task does not behave as expected when its executed as part of my larger workflow (it prints "A" and "B" but not "C" and does not terminate):

```scala
val task = for {
  _ <- Console.printLine("A").orDie
  _ <- ZIO.never.disconnect raceFirst Console.printLine("B").orDie
  _ <- Console.printLine("C").orDie
} yield ()
```

It works fine in isolation (e.g., `Unsafe.unsafe { implicit unsafe => Runtime.default.unsafe.run(task) }`).  Although I'm not sure what it is about my larger workflow that changes the behavior, I suspect a regression because **the issue does not occur in ZIO 2.0.6 or earlier**.  

The release notes for 2.0.7 mention changes to the semantics of the `race` operations, but those changes do not seem applicable here.  Perhaps they introduced a bug?

**Comment by adamgfraser** [comment]
Thanks for reporting! If you can create a minimized reproducer can definitely take a look!

**Comment by anovstrup** [comment]
@adamgfraser I was never able to come up with a minimized reproducer, but I finally fixed the issue in my real workflow (although I still don't understand the problem).  

My real workflow was more like `(promise.await *> ZIO.interrupt).disconnect raceFirst someEffect`, and this was never terminating after `someEffect` succeeded.

The solution was to write (following an example in the ZIO 2.0.5 source):
```scala
  ZIO.checkInterruptible { status =>
    if (status.isInterruptible) (promise.await *> ZIO.interrupt).disconnect
    else (promise.await *> ZIO.interrupt).uninterruptible.disconnect.interruptible
  } raceFirst someEffect
```

Any idea why this would be necessary?

**Comment by ghostdogpr** [comment]
I am guessing that your code is running in an uninterruptible region. 

This example works fine:
```scala
object TestPierre extends ZIOAppDefault {

  def run =
    for {
      promise   <- Promise.make[Nothing, Int]
      someEffect = ZIO.sleep(3.seconds).as("ok")
      res       <- (promise.await *> ZIO.interrupt).disconnect raceFirst someEffect
      _         <- ZIO.debug(res)
    } yield ()
}
```
But if you wrap the whole thing in `ZIO.uninterruptible`, then the left side of the race is not interrupted when the right finishes. This is expected because it's uninterruptible.

Looking at the history, in 2.0.7 there was a change to restore the original interruptible status when using `disconnect`: https://github.com/zio/zio/pull/7306. This is probably what triggered your issue. In your case you can probably wrap the whole thing in `ZIO.interruptible` or look into why the region is uninterruptible in the first place.

**Comment by anovstrup** [comment]
@ghostdogpr Okay, that makes sense!  It turned out the effect in question was composed into resource acquisition, so `ZIO.acquireAndRelease` made it uninterruptible.
