### ISSUE TITLE
Chunk.empty.toArray throws ClassCastException

### ISSUE THREAD

**Issue by mperucca** [zio/zio#786]
`val a = Chunk.empty.toArray[String]`
gives
`java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;`

I'm not sure why the casting is used in the implementation.

**Comment by jdegoes** [comment]
This will be tricky to fix but I know how.

Casting is used extensively in the implementation to avoid boxing.

**Comment by theAnnie** [comment]
@jdegoes I was looking at this bug and I've found also something like that ```   override final def hashCode: Int = toArray.toSeq.hashCode
 ```. Why there can't we use just .toSeq? Wouldn't be it be bit faster?

**Comment by Jentsch** [comment]
I looked into this issue. The problem is that the JVM enforces to know the type of arrays. In Scala arrays looking like normal generics, but there aren't. This shows in this example:

```scala
$ val ar = Array[String]()
$ ar.asInstanceOf[Array[Product]]
java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to [Lscala.Product;
```

The little `[` ist the representation of the JVM, that this is an array. The JVM is complaining, that `Array[String]` is not an `Array[Product]`, something that the JVM would never do for any other generic type. Replace `Array` with `Vector`, `List` or `Option` in the example and nothing bad happens.

The Scala standard library circumvents this issue by requiring an implicit `ClassTag` for every nearly operation that produces an arrays. (see for example: [ArrayOps](https://www.scala-lang.org/api/current/scala/collection/ArrayOps.html))

For us there is no safe way to create a `ClassTag` from within when the chunk is empty, because the `Empty` object doesn't contain any information about it. `classTagOf` is unimplementable.

I tried tried to throw away the `Empty` object and just using an empty `Arr` to recover the `ClassTag` in `classTagOf`. But this fails than at other points e.g. for `map`:

```scala
$ Chunk(1).filter(_ == 2).map(_.toString).toArray[String]
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
```

Here `map` would require the `ClassTag[String]` to create an empty array of string.

Currently I see to options to fix this issue with empty chunks:
1. add an implicit `ClassTag` to nearly every method of `Chunk` like Scala does
2. use boxing and lose performance on primitive data types (Int, Boolean, etc.)
3. don't allow empty chunks than, than there is always a candidate to reconstruct the `ClassTag`
4. leave as it is and everybody has to be careful while using `toArray`
5. do it like Akka and provide specialised data types for all primitive data types

May be someone more creative than me and finds an other more appealing solution.

**Comment by wi101** [comment]
`Chunk` should work with any type (even case classes) right? 
Because this problem appears with any kind of ` Chunk`  using `Chunk#toArray` 
should we think about a new way to make ClassTags?  cc @iravid

**Comment by wi101** [comment]
if the ` A` is specialized it shouldn't accept ` String` or data types ?  Sorry about my ignorance on this, trying to understand why we should make it possible to accept String ..

**Comment by Jentsch** [comment]
I think the target is to support any type for `A`, but I could be wrong. And `String` is just an example, this issue surfaces for every type for an empty `Chunk`.

(Case class shouldn't be a special for this issue, because for the JVM they are just normal classes. But what happens with things that extend `AnyVal` should be investigated)

**Comment by wi101** [comment]
@Jentsch I found a way to take the define the implicit ClassTag in `toArray`

**Comment by wi101** [comment]
Thanks to @jdegoes 's guidance!
