### ISSUE TITLE
ZStream retry not work on Non-ZIO operations

### ISSUE THREAD

**Issue by liewhite** [zio/zio#7892]
This works well
```scala
ZStream(1, 2, 3)
      .mapZIO(i => ZIO.attempt(throw Exception("fail")))
      .retry(Schedule.exponential(1.second))
      .runDrain
```
But this won't retry 
```scala
ZStream(1, 2, 3)
      .map(_ => throw Exception("xxx"))
      .retry(Schedule.exponential(1.second))
      .runDrain
```

**Comment by adamgfraser** [comment]
@liewhite This is expected behavior. The function in the `map` operator is not expected to throw exceptions, so if it does that exception is translated to a die failure. The `retry` operator only retries expected errors and so does not retry the failed stream in this case. You can use `mapZIO` and `ZIO.attempt` as in the example above or you can recover from the die failure and translate it into a recoverable error using an operator like `catchAllCause`.
