### ISSUE TITLE
Cats Effect: STM & TRef

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#791]
Introduce an effect-polymorphic class atop `STM` and `TRef`, with a default implementation for any Cats Effect data type (Cats IO, Monix Task, etc.).

```scala
package scalaz.zio.interop

trait STM[F[_], +A] {
  ...
}
object STM {
  def succeed[F[_]: ConcurrentEffect, A]: STM[F, A] = ???
  ...
}

trait TRef[F[_], A} { ... }
object TRef { ... }
```

The methods will all delegate to ZIO `STM`, but they will take the `ZIO` effect returned by `STM` methods and lift it into any effect `F[_]` that is suitable equipped.

**Comment by VladKopanev** [comment]
I would like to try this one.

**Comment by VladKopanev** [comment]
I think for convenience we could add ` def mapK[G[_]](f: F ~> G): STM[G, A]` function to all such classes, not only STM  but also Queue, Schedule,  Stream & Sink, etc. Because all concurrency primitives from cats-effect has that, I guess we don't wanna users lost such ability. I can do that in same PR.

**Comment by jdegoes** [comment]
@VladKopanev Yes, that would be fantastic!

**Comment by ghostdogpr** [comment]
Done in #796
