### ISSUE TITLE
assertTrue does not compile with "contains" check

### ISSUE THREAD

**Issue by vasiliy-bout** [zio/zio#7981]
The following test cannot be compiled:
```scala
import zio.Scope
import zio.test.{Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

object ContainsTest extends ZIOSpecDefault{
  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("List.contains") (
      test("should compile") {
        val list = List(1, 2, 3, 4.5)
        assertTrue(list.contains(2))
      }
    )
}
```

The error is:
```
type mismatch;
 found   : zio.test.TestArrow[Seq[Int],Boolean]
 required: zio.test.TestArrow[List[Double],?]
        assertTrue(list.contains(2))
```

It seems that the code is valid and it should compile. For example, if we extract the "contains" check into a variable, then the code compiles (and the test passes if executed):
```scala
import zio.Scope
import zio.test.{Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

object ContainsTest extends ZIOSpecDefault{
  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("List.contains") (
      test("should contain elements") {
        val list = List(1, 2, 3, 4.5)
        val result = list.contains(2)
        assertTrue(result)
      }
    )
}
```

----

Scala version: 2.13.10
ZIO version: 2.0.10

**Comment by adamgfraser** [comment]
This code is doing some kind of strange things.

First it is relying on implicit numeric widening to construct a `List[Double]` from `List(1, 2, 3, 4.5)`.

Then it is trying to call `contains` with `2` which is an `Int`. So at this point `Int` and `Double` are completely unrelated types and the only reason this compiles at all with `contains` extracted is because the `contains` operator in the Scala collections framework is not type safe and it allows you to do nonsensical checks to see whether a collection contains a value that it couldn't possibly contain:

```scala
val numbers: List[Int] = List(42)
numbers.contains("Jane Doe")
```

The implementation of the smart assert macro in ZIO Test is trying to protect against these non-sensical assertions and so won't let this code compile. This may not be ideal in this case because the `Int` `2` and the `Double` `2.0` are equal to each other even though they are unrelated types, but in many other cases this prevents bugs and this reliance on implicit numeric widening is usually considered an anti-pattern.

The original example can easily be fixed by using `list.contains(2.0)` instead of `list.contains(2)`.

**Comment by vasiliy-bout** [comment]
Well, maybe the example is not clearly explains the context... This is just an example of a list with various values of different types that have a common supertype...

Here is another example that better illustrates the context where I face the compilation issue:
```
import SomeLogic.Case1
import zio.Scope
import zio.test.{Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

object ContainsTest extends ZIOSpecDefault{
  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("SomeLogic.doSomeStuff") (
      test("should return Case1") {
        val result = SomeLogic.doSomeStuff()
        val check = result.contains(Case1)
        assertTrue(check)
      },
      test("should compile") {
        val result = SomeLogic.doSomeStuff()
        assertTrue(result.contains(Case1))
      }
    )
}

object SomeLogic {

  sealed trait BaseType

  case object Case1 extends BaseType
  case object Case2 extends BaseType
  case object Case3 extends BaseType

  def doSomeStuff(): List[BaseType] = {
    // do some complex stuff
    List(Case1, Case3)
  }
}
```

In production code we do pattern-matching for the returned values, but in tests I need to check that some specific values are returned in some circumstances.

**Comment by adamgfraser** [comment]
Yes. Not sure if the handling of this by the smart assert macro could be improved but an easy fix is:

```scala
val case1: BaseType =
  Case1

assertTrue(result.contains(case1))
```

**Comment by vasiliy-bout** [comment]
Yes, this fixes compilation. But it is slightly inconvenient to do this thing every time.

Another thing I found is that if we convert the resulting collection to Set using `toSet` method, then the check compiles:
```
assertTrue(result.toSet.contains(Case1))
```

Seemingly, this happens because `SetOps` declares `contains` method as `def contains(elem: A): Boolean` while `Seq` and `List` declare this method as `def contains[A1 >: A](elem: A1): Boolean`.

Hope that this issue can be solved in the future releases.

**Comment by adamgfraser** [comment]
No it is because the smart assertion does not have logic for handling `contains` for collections that are not a subtype of `Seq`.

**Comment by shawjef3** [comment]
I believe I fixed this when I fixed https://github.com/zio/zio/issues/8539.
