### ISSUE TITLE
Develop concurrent weak set that runs on Scala.js, JVM

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#8076]
The concurrent weak set must:

1. Be safe for concurrent addition, removal, and iteration
2. Be weakly consistent for iteration
3. Automatically garbage collect weak references
4. Have performance equal to or better than `Collections.synchronizedSet(Collections.newSetFromMap(new WeakHashMap[A, java.lang.Boolean]()))` for concurrent addition and removal
5. May not use `synchronized` and should instead follow patterns in `ConcurrentHashMap`
6. Must utilize weak references on Scala.js
7. May not be derived from any existing source code, unless that source code is Apache 2 licensed and terms of use and copyright are reproduced appropriately

Should be stored in `zio.internal` package, with a JMH benchmark suite added to `benchmarks` project.

**Comment by andrzejressel** [comment]
So I was looking at this for last few days and while there are a lot of cool looking non blocking data structures they all share the same issue - they don't support multiple items with the same hash and adding it seems to be very hard/impossible due to CAS semantics.

I believe the only thing that is verified and will work here is specialized concurrent skip list map with automatic WeakReference removal. It may be a bit slower than ConcurrentHashMap, but it's fully concurrent - CHM still uses locks while CSL does not require them at all.

Creating structure like that may be also interesting for `scala-native`. From what I've seen they lack a lot of concurrent structures.

I'll see If I can cook something this week.

**Comment by dzikoysk** [comment]
I started 2 days ago porting Spring's `ConcurrentReferenceHashMap` as `ConcurrentWeakHashSet` that seems to match all requirements. I didn't want to claim the issue, because this is my first ever attempt to write Scala at all, but I'd say there are some promising results. I've submitted [draft PR](https://github.com/zio/zio/pull/8093) that presents what I have atm. I need some feedback if it's going into desired direction, I hope it's not a problem.
