### ISSUE TITLE
Add provide and provideSome methods to ZStream

### ISSUE THREAD

**Issue by amelnikov-mylivn** [zio/zio#817]
ZIO type have a method `provide` that allows to convert `ZIO[R,E,A]` type into `ZIO[Any,E,A]`.  

It would be nice to have the same method for `ZStream`, so it can convert `ZStream[R,E,A]` type into `ZStream[Any,E,A]`.

P.S. Also we have `provideSome` method with close semantics which is also super useful.

**Comment by jadireddi** [comment]
@iravid Does this enhancement needed `Tags` approach , inline with `ZIO.scala` or need to be done in different way.

**Comment by iravid** [comment]
From a quick look, I think you could implement this as just another combinator. No need to elaborate the stream structure.

**Comment by jadireddi** [comment]
Sure @iravid . Will try through combinator.

**Comment by runtologist** [comment]
It's doable as a stream combinator. @jadireddi let me know in case you need help.

**Comment by jadireddi** [comment]
Sure @runtologist.. thank you

**Comment by jadireddi** [comment]
@iravid , Below change working as expected. Can you please validate it's correct approach or not.
```
import scalaz.zio.IO.LowerR
  final def provide[R >: LowerR, E, A](stream: ZStream[R, E, A]): Stream[E, A] = stream
```

**Comment by iravid** [comment]
@jadireddi that only appears to work because `IO.LowerR = Any`, so it only compiles for `ZStream[Any, E, A]`. But that isn't very useful because `ZStream[Any, E, A]` requires no environment at all, so nothing to provide.

Take a look at how the other combinators are implemented (e.g. `map`) and try to follow the structure, using `provide` and `provideSome` on the IO values that are used in producing a stream.

**Comment by vasilmkd** [comment]
Any progress on this? I'd like to contribute this.
