### ISSUE TITLE
Random.shuffle not testable with TestRandom.feedInts

### ISSUE THREAD

**Issue by improved-broccoli** [zio/zio#8175]
ZIO version: 1.0.17

Given the [code](https://github.com/zio/zio/blob/v1.0.17/core/shared/src/main/scala/zio/random/package.scala#L186) of `Random.shuffleWith`, I expected that shuffling (with `Random.shuffle`) a list of 2 elements by feeding the RNG with 0 would reverse the list but it does not.
Int feeding works with `Random.nextIntBounded`, but not with `ShuffleWith` while it relies on this method.
Here is an example: https://scastie.scala-lang.org/eFpM2E5cSSu5shbpldby1A

Unless I misunderstood the usage of TestRandom?

**Comment by adamgfraser** [comment]
I don't think this really makes sense. The `feedXYZ` methods let you feed an input of type `XYZ` and provide the guarantee that when you call `getXYZ` next time you will get those values out. So if you do `feedInts(42)` and then `nextInt` you will get `42`.

It does not apply to internal usages of more primitive random number generators in more complex random number generators because this is an implementation detail. So for example right now `shuffleWith` generates random integers internally in determining how to sort a collection. But this algorithm could be changed at any time to use a different type of random value internally or use the same type of random value in a different way.

Similarly we generate random double values as part of generating random normally distributed values but we could use a different algorithm at some point in the future. So any test that expects to feed random values and use that to drive expected values for these operators is by definition wrong.

**Comment by improved-broccoli** [comment]
Thanks for the quick answer, I understand your point. But how are we supposed to make `Random.shuffle` results testable the same way as `Random.next*` methods?
Does it require a new `TestRandom.feedShuffle` or something like that? AFAIK there is no such thing in ZIO test 1.0.17.

**Comment by adamgfraser** [comment]
I'm not sure what you're trying to do but `TestRandom` is deterministic so it will always give the same results for the same set of calls. Do not intend to add any more feed variants.

**Comment by improved-broccoli** [comment]
If I understand correctly, `Random.shuffle` can be tested with `TestRandom.deterministic` and eventually to change the output of shuffle, the initial seed needs to be changed with `TestRandom.setSeed`?

**Comment by adamgfraser** [comment]
`TestRandom` behaves the same way as other pseudorandom number generators so each invocation of an operator both returns a random value and a new random state. So if you perform shuffle twice in a row those two results will be different but you will always get the same results for the same invocation of operations with the same seed.
