### ISSUE TITLE
Gen.collectAll does not support filtered Gen instance

### ISSUE THREAD

**Issue by mbaechler** [zio/zio#8225]
```
    test("collectAll should support filtered Gen instances") {
      val gen = Gen.collectAll(List.fill(10)(Gen.int.filter(_ % 2 == 0)))
      assertZIO(gen.runCollect)(isNonEmpty)
    },
```
This test fails.
Unfortunately, it's how `listOfN` actually works, thus one can't use an arbitrary Gen instance and expect a `listOfN` from it to always work.

**Comment by adamgfraser** [comment]
This is expected behavior. Filtering produces generators that fail by producing no values which are then retried by the test framework. So this test passes:

```scala
test("collectAll should support filtered Gen instances") {
  val gen = Gen.collectAll(List.fill(10)(Gen.int.filter(_ % 2 == 0)))
  check(gen) { list =>
    assert(list)(isNonEmpty)
  }
}
```

Note that filtering is inefficient and you should transform generated values to the expected values instead of filtering them when possible. For example `Gen.int.map(_ * 2)`.
