### ISSUE TITLE
Release Project Loom support & Channel Fiber Runtime

### ISSUE THREAD

**Issue by WtzLAS** [zio/zio#8464]
Java 21 LTS has been out and Project Loom is no longer in preview, but the pull request for Loom seems to be stale for a long time.

Channel Fiber Runtime has landed in the branch `series/2.1.x` since April and no more news for that as well.

So ZIO 2.1 when :(

**Comment by adamgfraser** [comment]
@WtzLAS The PR will be merged when it is ready and we will do a release candidate after that.

**Comment by vishalsurana** [comment]
Now that its been 6 months since this issue we raised, can we get any updates on the same? Is ZIO going to be actively worked on or has Ziverge shifted its focus to Golem? I ask this because there are several other libraries (zio-flow, zio-prelude, zio-schema, etc.) where development seems to have more or less stalled.

**Comment by unoexperto** [comment]
@adamgfraser Could you please share PR link when closed it ?

**Comment by 987Nabil** [comment]
@vishalsurana ZIO, schema and prelude are all actively developed. Independent of what Ziverge does with golem.
@unoexperto loom support is released

**Comment by kyri-petrou** [comment]
@unoexperto  Loom support was added in ZIO [v2.1.0](https://github.com/zio/zio/releases/tag/v2.1.0) back in May. You can configure ZIO's runtime to use virtual threads when bootstrapping the application:

```scala
object FooApp extends ZIOAppDefault {
  override val bootstrap = ZLayer.make(
    Runtime.enableLoomBasedExecutor,
    ??? // Any other bootstrapping layers
  )

  def run = ???
}
```
