### ISSUE TITLE
ZStream.ensuring, finalizer may be deferred to channel executor's close and as a result may cause deadlocks

### ISSUE THREAD

**Issue by eyalfa** [zio/zio#8544]
in this example (made up, real scenario is more complex involving queues), the stream hangs indefinitely.
```
test("ZStream.ensuring oddity ") {
    //this is part of the workaround
    implicit class ForceFold[R, E, A](self : ZStream[R, E, A]) {
      def forceFold : ZStream[R, E, A] = {
        self
          .toChannel
          .map(identity)
          .toStream
      }
    }

    zio
      .Promise.make[Nothing, Any]
      .flatMap{ p =>
        ZStream
          .range(0, 40, 10)
          .ensuring(p.succeed(()))
          //.forceFold  //the workaround
          .merge{
            ZStream.execute(p.await)
          }
          .runCollect
          .map{ collected =>
            zio.test.assertTrue(collected == Chunk.range(0, 40))
          }
      }
  }
```

uncommenting the `.forceFold` line works around the issue. 
I suspect this is related to the way the channel executor collects the finalizers and delay their execution when the stack becomes empty, this combined with the executor's close registered as a finalizer on the downstream channel executor means that the stream can experience deadlocks in scenarios like this (when there's a dependency between the streams) .

cc @adamgfraser

**Comment by adamgfraser** [comment]
@eyalfa This is expected behavior.

The semantics of stream finalizers are that the last finalizers of a stream are deferred to its scope. So when you use `stream.ensuring(promise.succeed(())` the finalizer is deferred to the scope of `stream`.

Furthermore, the semantics of `merge` are that finalizers that are part of the scopes of the `left` and `right` streams become part of the scope of the merged stream. This is necessary for `stream.merge(ZStream.empty)` to be an identity.

If you want to complete the promise immediately when the stream is done you can just add a downstream that completes the promise when the stream is done.
