### ISSUE TITLE
Improve performance of fork/join by one order of magnitude as measured by ForkJoinBenchmark

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#8611]
Fork/join has a relatively high cost when the life of the fiber is short-lived, as shown by ForkJoinBenchmark. 

This ticket is to optimize fork/join so that the benchmark shows roughly a 1 order of magnitude performance, without breaking any tests or altering backward compatibility.

The overall steps involved in solving this problem:

1. Profile using Visual VM, YourKit, or JProfiler. Free licenses are available for the latter due to ZIO's status as an open source project.
2. Identity leading sources for optimization.
3. Optimize, measure, and repeat, starting from step (1).

I have already analyzed this and found there is not a single source of overhead that could improve performance by about 10x. Rather, there are a lot of small things that have to be optimized independently, including:

 * The performance of FiberRefs, as well as core operations on FiberRefs involved in fork/join.
 * The performance of WeakConcurrentBag, which is used for tracking root fibers.
 * The overhead of forking, which involves a message to the mailbox that has its own overhead, and tracking the fiber.
 * The overhead of joining, which involves FiberRefs-related machinery and success/error propagation.
 * Scheduling overhead.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by eyalfa** [comment]
@adamgfraser , I know you took this 😎 but I had a chance o have a look at this and made two findings:

1. notice the benchmark uses the `unsafeRun` utility function which runs the effect on the current thread, this thread is not a `ZScheduler` worker, hence all submits go the to the global queue instead of the per-worker queues.
2. seems like the bottleneck is on the submit rather than the join, I wrote an additional benchmark that demonstrates this (gives very similar number of ~350 ops per second on my laptop):

```
@Benchmark
  def zschedSubmit() : Unit = {
    val runnable : Runnable = () => ()
    val submits = ZIO.executorWith{ executor =>
      ZIO.foreach(range){i =>
          ZIO.succeed{
            executor.asExecutionContext.execute(runnable)
          }
      }
      .fork
      .flatMap(_.await)
    }

    val _ =
      unsafeRun(
        submits
      )
  }
```

notice the fork+await pattern used to make sure the submits run inside a `ZScheduler` worker and utilize the worker specific queue (doesn't make much of a difference as all enqueues are still made to a single queue relying on the workers to distribute the work using the searching mechanism).
