### ISSUE TITLE
STM retry/orElse semantics

### ISSUE THREAD

**Issue by durban** [zio/zio#8696]
This issue is a case of "behaves differently from Haskell", ~~so I'm not even sure this is a bug.~~ (Although the Haskell behavior seems more useful to me.)

Apparently, Haskell's STM retries a transaction if any of the variables read in any branch of an `orElse` change. (See [section 3.4 here](https://cs.uwaterloo.ca/~Brecht/courses/702/Possible-Readings/transactional-memory/composable-mem-trans-ppopp-2005.pdf).) It seems ZSTM doesn't do this: it only retries if the `TRef` read by the RHS/second transaction changes. For example, this program hangs:

```scala
    for {
      ref1 <- TRef.makeCommit(0)
      ref2 <- TRef.makeCommit(0)
      txn1 = ref1.get.flatMap {
        case 0 => STM.retry
        case n => STM.succeed(n)
      } orElse ref2.get.flatMap {
        case 0 => STM.retry
        case n => STM.succeed(n)
      }
      txn2 = ref1.set(1) // if this is `ref2.set(1)`, it doesn't hang
      fib <- txn1.commit.forkDaemon
      _ <- ZIO.sleep(zio.durationInt(1).second)
      _ <- txn2.commit
      r <- fib.join
    } yield ()
```

**Comment by durban** [comment]
Based on [this part](https://zio.dev/reference/stm/stm.md/#composing-alternatives) of the documentation, it probably _should_ work like haskell. And note, that for `orTry` it _does_. So this seems like a bug in `orElse`.

**Comment by jdegoes** [comment]
/bounty $250 for fix and test to accompany it.

**Comment by BijenderKumar1** [comment]
/attempt #8696
I reproduced the issue and found that the changes in the LHS (first branch) for `orElse` do not trigger a retry of the transaction, as pointed out. However, it works correctly with orTry instead of `orElse`. I dived deep into the `ZSTM.scala` file where the `orElse` function is defined. It seems that the issue is with the `prepareResetJournal` function, which resets the journal to empty each time it is invoked, and therefore, any changes in the first branch are not triggering a retry. I will be fixing the issue and raising the PR soon. Thanks!

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvy4pjm20010l709e4imt4zg/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
