### ISSUE TITLE
`You must not use an intersection type` when deriving ZLayer

### ISSUE THREAD

**Issue by felix-hedenstrom** [zio/zio#8877]
Issue occurred in ZIO 2.1.1 and using sttp 3.9.6. Code compiles in ZIO 2.0.22.

When deriving the ZLayer for a implementation I came across the error

```
You must not use an intersection type, yet have provided sttp.capabilities.zio.ZioStreams & sttp.capabilities.WebSockets
```

when trying to compile
```
import zio.ZLayer
import sttp.client3.httpclient.zio.SttpClient

final case class HttpClient(client: SttpClient)

val layer = ZLayer.derive[HttpClient]
```

When looking of the definition of `SttpClient` 
```
type SttpClient = SttpBackend[Task, ZioStreams with WebSockets]
```
it's not obvious to me how the error message is related to the code.

https://scastie.scala-lang.org/GSXj6y15SW2ZS8fTZx6pvA

**Comment by ghostdogpr** [comment]
That case was mentioned in the [release notes](https://github.com/zio/zio/releases/tag/v2.1.0), it is not supported anymore. You have to use either your own alias if you don't need both `ZioStreams & WebSockets` (use `Any` or just one of them). If you need both, make your own trait that extends `SttpBackend[Task, ZioStreams & WebSockets]` so that the environment sees your trait instead.

Note that sttp4 doesn't use this pattern anymore so the problem will eventually disappear.

**Comment by varshith257** [comment]
@ghostdogpr Can I get any guidance on this https://github.com/zio/zio/pull/8808#issuecomment-2120029437  ?
