### ISSUE TITLE
Scala Native CI takes too long to complete, degrading DX

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#8945]
Currently the Scala Native CI takes ~25 minutes to complete (10 minutes longer than the JS CI), which degrades DX as we often need to wait for it to complete so that we can merge in patches / quickfixes. This keeps getting worse (IIRC a few months ago it was taking just under 20 minutes).

Opening this ticket in hopes that someone has any ideas on what we can do to improve this. Or do we wait till we update to Scala Native 0.5 and see if it's improved?

**Comment by varshith257** [comment]
/attempt #8945

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxrlmmb3001gmg0951iop8ey/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by asr2003** [comment]
/attempt #8945

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxrlmmb3001gmg0951iop8ey/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Anshgrover23** [comment]
/attempt #8945

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxrlmmb3001gmg0951iop8ey/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by asr2003** [comment]
@kyri-petrou @jdegoes I have added detailed profiling to both JS and Native CI to understand where the time is spent during the build and tests.

# Comparison of JS and Native Build Times

### Resolving Dependencies
- **JS:** Total time: 12 seconds, Real time: 27.567 seconds
- **Native:** Total time: 13 seconds, Real time: 29.825 seconds

**Observation:** Dependency resolution times are similar between JS and native builds, indicating no significant diff at this phase.

### Compiling
- **JS:** Total time: 145 seconds (2 minutes 25 seconds), Real time: 2 minutes 51.509 seconds
- **Native:** Total time: 155 seconds (2 minutes 35 seconds), Real time: 2 minutes 51.509 seconds

**Observation:** Both JS and native builds spend comparable time compiling with the native build taking slightly longer (10 seconds more)

### Running Tests

- **JS:** Total time: 13 seconds, Real time: 14 minutes 7.403 seconds
- **Native:** Total time: 28 seconds, Real time: 22 minutes 14.318 seconds

**Observation:** The most significant difference is in the test execution phase. Native tests take substantially longer (over 8 minutes more real time) compared to JS tests.

The profiling logs clearly indicates that the native build process involved several additional steps and consumed more time compared to the JS build process. The main contributors to the longer build times for the native CI are:

```
  [info] Linking (8870 ms)
  [info] Checking intermediate code (quick) (2591 ms)
  [info] Discovered 29188 classes and 115409 methods
  [info] Optimizing (debug mode) (25702 ms)
  [info] Generating intermediate code (29907 ms)
  [info] Produced 4 files
  [info] Compiling to native code (16222 ms)
  [info] Linking with [pthread, dl, uv]
  [info] Total (84580 ms)
```
I can see that this extra builds in Native taking the more time as of JS. Idk how it behaved few months ago ~20 min only. Any thoughts on this @kyri-petrou ? 

The culprit here for Native tests for ~25 min is the above extra builds. The only two things I have in my mind to reduce Native tests CI is to upgrade to Native 0.5 and check for any improvement or else to optimize our Native build configuration by parallelization

**Comment by varshith257** [comment]
>The profiling logs clearly indicates that the native build process involved several additional steps and consumed more time compared to the JS build process. 

Yes, I agree with this.

**Comment by varshith257** [comment]
@kyri-petrou Any comments on the @asr2003 analysis. Looks like performed detailed profiling about the Native CI. Can we look after the Scala Native 0.5 PR is merged https://github.com/zio/zio/pull/8840 ?

**Comment by kyri-petrou** [comment]
Thanks for the analysis @asr2003. Unfortunately I don't think we can wait for #8840, because even if it was merged it wouldn't allow for Scala Native to be run in parallel. That would require a rewrite of the Scala Native code to make it compatible with multithreading and it's a whole other monster
