### ISSUE TITLE
Inconsistent behaviour of `provideLayer` pre/post ZIO 2.0.7

### ISSUE THREAD

**Issue by phanhuyn** [zio/zio#8948]
Given the following code snippet, the result return is different between ZIO version 2.0.7+ vs 2.0.6 (and below).

I'm guessing there is some change that causes the ZLayer `counterLayer` to not be shared among the ZIOs in 2.0.7+. However, there is no mention of such changes in the release note of 2.0.7 (https://github.com/zio/zio/releases/tag/v2.0.7). I'm wondering if this behaviour change was intended.

(There is a change in v2.0.7 which is related to ZLayer, though I don't know if that change was the cause: https://github.com/zio/zio/pull/7786/)

```scala
import zio.{ZEnvironment, ZIO, ZIOAppDefault, ZLayer}
import java.util.concurrent.atomic.LongAdder

trait Counter {
  def count: Long
}

object ZIOApp extends ZIOAppDefault {
  val counterLayer: ZLayer[Any, Nothing, Counter] = ZLayer {
    val curCnt = new LongAdder
    ZIO.succeed(
      new Counter {
        override def count: Long = {
          curCnt.increment()
          curCnt.sum()
        }
      }
    )
  }

  def count: ZIO[Counter, Any, Long] = {
     ZIO.environmentWith(_.get.count)
  }

  def countAndPrint(tag: String): ZIO[Counter, Any, Unit] = count.flatMap {
    c => ZIO.logInfo(s"from $tag, count value: $c")
  }

  def countAndPrintForeach(names: List[Int]) = {
    ZIO.foreach(names){
      _ => countAndPrint("countAndPrintForeach").provideLayer(counterLayer)
    }
  }

  override def run = {
    countAndPrintForeach(List.range(1, 5)) 
    // zio 2.0.6: print 1, 2, 3, 4
    // zio 2.0.7: print 1, 1, 1, 1
  }
}
```

build.sbt

```
scalaVersion := "3.2.2"
//lazy val zioVersion = "2.0.7"
lazy val zioVersion = "2.0.6"

libraryDependencies ++= Seq(
  "dev.zio" %% "zio" % zioVersion,
  "dev.zio" %% "zio-test" % zioVersion,
  "dev.zio" %% "zio-test-sbt" % zioVersion,
  "dev.zio" %% "zio-streams" % zioVersion,
  "dev.zio" %% "zio-test-junit" % zioVersion
)
```

**Comment by kyri-petrou** [comment]
Hi @phanhuyn, thanks for reporting. You're correct, #7786 is the one that changed the behaviour. I agree it should have been better documented, although I think the current behaviour is the correct one.

What issues is the new behaviour causing you?

**Comment by phanhuyn** [comment]
> Hi @phanhuyn, thanks for reporting. You're correct, #7786 is the one that changed the behaviour. I agree it should have been better documented, although I think the current behaviour is the correct one.
> 
> What issues is the new behaviour causing you?

Thanks for the quick response @kyri-petrou!

> What issues is the new behaviour causing you

When updating the ZIO version I found that some "stateful" ZLayers no longer works since they are being re-created. Just checking if this was an actual bug.

> I think the current behaviour is the correct one.

Could you please help to share why this current behaviour is the correct one? Instinctively, I though since `counterLayer` is a `val`, when passing it to `provideSome`, the object should be re-used (we're passing a reference, not a constructor). Apology if it's a silly question, I'm quite new to ZIO/Scala.

**Comment by kyri-petrou** [comment]
> Could you please help to share why this current behaviour is the correct one

Because otherwise the ZLayer is not referentially transparent

> I though since counterLayer is a val

Yes, but the parameter to `ZLayer.apply` is by-name. This means that everything passed to it will be recreated. If you're not familiar with "by-name" parameters (and their difference from "by-value" [this post](https://www.baeldung.com/scala/parameters-by-value-by-name) is a good starting point

If you want to achieve the same behaviour, you have 2 options (maybe more, but I'm not _too_ well versed on ZLayers myself)

Option 1 (not recommended, please don't do this as you lose referential transparency!):

```scala
val counterLayer: ZLayer[Any, Nothing, Counter] = {
    val curCnt = new LongAdder // val is outside the constructor
    ZLayer {
      ZIO.succeed(
        new Counter {
          override def count: Long = {
            curCnt.increment()
            curCnt.sum()
          }
        }
      )
    }
  }
```

This way the val is created outside of the ZLayer constructor, so the same instance of the LongAdder is used across all new instances of the ZLayer.

Option 2 (Correct way!): Provide the layer at a higher level / application level

```scala
def countAndPrintForeach(names: List[Int]) =
    ZIO.foreach(names) { _ =>
      countAndPrint("countAndPrintForeach1")
    }.provideLayer(counterLayer) // ideally you should do this in Main!
```

In general, it's recommended to provide layers when bootstrapping the application.

You can also take a look at [this video](https://www.youtube.com/watch?v=wwS19ZNTS_k) for how to "reload" services using ZLayers

**Comment by phanhuyn** [comment]
Thanks @kyri-petrou for the clear explanation. Appreciate it. TIL "by-name" parameter.
