### ISSUE TITLE
Datadog APM doesn't support ZIO 2.1

### ISSUE THREAD

**Issue by guizmaii** [zio/zio#9001]
I noticed that in the DD APM code, they mention that their ZIO integration doesn't work with ZIO 2.1
See https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/zio/zio-2.0/build.gradle#L40-L41

Could be nice if we could update their instrumentation so that it works with the new ZIO versions

Initial implementation was brought by @dmytr and @amarziali.
See:
- https://github.com/DataDog/dd-trace-java/pull/4848
- https://github.com/DataDog/dd-trace-java/pull/6442

**Comment by ghostdogpr** [comment]
Is there any info on what doesn't work? I am using an older version of the datadog agent where it was not disabled, and using ZIO 2.1 in production and it works fine 😄

**Comment by guizmaii** [comment]
> where it was not disabled

What do you mean?

> Is there any info on what doesn't work?

No idea. Maybe @amarziali knows more about this?

**Comment by kyri-petrou** [comment]
@guizmaii maybe open an issue in their repo mentioning you're a ZIO maintainer and if they can provide us with some more info as we don't have access to the linked Jira issue

**Comment by ghostdogpr** [comment]
> > where it was not disabled
> 
> What do you mean?

The code you referenced was introduced in 1.36.0, before that there was not filtering on the zio version so it was enabled even with zio 2.1. I'm using an older agent than 1.36.0 and it works well.

**Comment by dmytr** [comment]
Hi,

As far as I understand, that change doesn't limit ZIO version to which instrumentation is applied. It only limits which ZIO version is used for the "latest version" test. I assume it was introduced because ZIO 2.1 was published for Java 11+ only (as far as I can tell) and DD instrumentation tests that are executed on Java 8 are now broken.

There's nothing wrong with instrumentation itself. With [this change](https://github.com/dmytr/dd-trace-java/commit/995aee9d0a050fb04c57c7736692f6edfab3d70a) tests work. I don't know how to add reusable code in `dd-trace-java` so that common code and tests could be used by both ZIO 2.0 and 2.1 instrumentations :sweat_smile: And I don't have time to figure this out. So I didn't make a PR. But if anyone would like to pick it up - please feel free to do it.

At work we are using ZIO 2.1 with the latest version of DD Java agent (1.37.0) and instrumentation works just fine. The only odd case that I noticed is when trace was not initiated by DD's automatic instrumentation on service entry (e.g. request received by supported HTTP/gRPC server), but it was initiated manually via OpenTracing API. In this case we don't get any spans from automatic instrumentation. But maybe there's just something wrong with our wrapper for OpenTracing tracer.
