### ISSUE TITLE
Async resumption performance is not great

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#9012]
Opening this issue since I don't think there's an easy fix to it, and since I think it's a fairly important aspect in applications that depend highly on async resumption or utilize heavily `ZIO.yieldNow` (which a lot of internal ZIO methods use as well).

<details>
  <summary><h3>Benchmark code (Click to expand)</h3></summary>

```scala
import cats.effect.unsafe.implicits.global
import cats.effect.{IO => CIO}
import org.openjdk.jmh.annotations.{Scope => JScope, _}
import zio.BenchmarkUtil._

import java.util.concurrent.TimeUnit

@State(JScope.Thread)
@BenchmarkMode(Array(Mode.AverageTime))
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Measurement(iterations = 5, timeUnit = TimeUnit.SECONDS, time = 1)
@Warmup(iterations = 5, timeUnit = TimeUnit.SECONDS, time = 1)
@Fork(1)
class AsyncResumptionBenchmark {

  final val size = 1000

  val ints: List[Int] = List.range(0, size)

  @Benchmark
  @OperationsPerInvocation(size)
  def zioAsyncResumptionBenchmark(): Unit = {

    val io = ZIO.foreachDiscard(ints) { _ =>
      ZIO.succeed("foo") *> ZIO.yieldNow *> ZIO.succeed("bar")
    }

    unsafeRun(io)
  }

  @Benchmark
  @OperationsPerInvocation(size)
  def catsAsyncResumptionBenchmark(): Unit = {

    val io = catsForeachDiscard(ints) { _ =>
      CIO("foo") *> CIO.cede *> CIO("bar")
    }

    io.unsafeRunSync()
  }

}
```
</details>

With this benchmark, we get the following results:

```
[info] Benchmark                                              Mode  Cnt    Score    Error  Units
[info] AsyncResumptionBenchmark.catsAsyncResumptionBenchmark  avgt    5  168.198 ±  0.886  ns/op
[info] AsyncResumptionBenchmark.zioAsyncResumptionBenchmark   avgt    5  963.987 ± 52.768  ns/op
```

As we can see, ZIO's `yieldNow` is ~6x slower than cat's effect `cede`. Besides having a much worse performance than the CE counterpart, the average execution time of a single `yieldNow` is close to 1000ns, which can end up adding a significant overhead to applications that heavily utilize it (either directly or indirectly)

**Comment by eyalfa** [comment]
@kyri-petrou I've played with this a bit and made some (potential) progress.
one thing I've noticed is that ZIO will always effectively yield, since work stealing is effectively disabled for few versions now.
what I did was replacing `if (yieldNow.forceAsync || !stealWork(currentDepth))` with `if (yieldNow.forceAsync || shouldYield())` where `shouldYield` delegates to `ZScheduler.shouldYield()` which is currently implemented as:

```
private[zio] def shouldYield() = {
    val worker = ZScheduler.workerOrNull()
    if(null eq worker)
      true
    else {
      if((worker.nextRunnable eq null) && worker.localQueue.isEmpty())
        false //current worker is not stressed
      else {
        //current worker has some pending work, if the scheduler has more messages in the global queue we should yield
        worker.owningScheduler.hasGlobalMessages
      }
    }
  }
```

basic idea was to come up with some indication about the scheduler's load:
1. if the current worker has no pending work, no need to yield
2. otherwise check the global queue, if non empty we should yield. 

I'm pretty sure we can come up with a better indication for #2 as I believe the global queue is rarely empty and on the other hand other fibers may have pending work in their local queues... I guess there's a lot of tuning required here.

applying these changes turned this benchmark's result around:

```Benchmark                                              Mode  Cnt    Score    Error  Units
AsyncResumptionBenchmark.catsAsyncResumptionBenchmark  avgt   15  194.140 ± 50.234  ns/op
AsyncResumptionBenchmark.zioAsyncResumptionBenchmark   avgt   15   73.128 ±  1.591  ns/op```

however I suspect we must add more benchmarks to measure §yield§ behavior under various loads

**Comment by kyri-petrou** [comment]
@eyalfa this is something along the lines that I had in mind, although I think we do need to account for the Scheduler being under stress or even better, being "a bit busy". e.g., in `zio-http` Netty's workers are adding runnables to the global queues. So it's very common to have messages in the global queues intermittently between workers being unparked but that doesn't mean that the Scheduler is stressed.

In addition, this doesn't account for other kinds of async resumption (e.g., `ZIO.async`). If you profile the benchmark in the issue above, you'll see that more than half of the time is spent on recovery from `AsyncJump`. This is because we're throwing an exception which passes multiple `try { ... } catch { ... }` blocks.   Personally I think we should refactor the way that we break from the runloop in cases of async work. I was thinking perhaps we should :
1. substitute `throw AsyncJump` with `return null`
2. add a check at all callsites of `runLoop` along the lines of `if (exit eq null) return null` and propagate the yielding signal more "gracefully".

PS: Take a look at the `ZScheduler#submitOrYield` method, I have a feeling we should be utilizing it in cases that we're yielding

**Comment by eyalfa** [comment]
so u're basically saying I was able to avoid the `AsyncJump` exception tax?
it does make some sense when comparing to the way cats handles `cede`, it reschedules the fiber (usually on the same thread) and 'leaves`, no cleanup necessary. I think this brings up another concern regarding my attempted solution which unlike cats it keeps executing the current fiber instead of actually being 'nice' and enqueuing it at the back of the queue (usually the local one)

**Comment by eyalfa** [comment]
@kyri-petrou I tried eliminating some(most?) of the try/catch effect evaluation goes through.
basically I've commented out the try/catch inside `runLoop itself, this try/catch only handles java interruption but as u wrote the `AsyncJump` has to go through this try/catch pairs throughout the stack, then it is caught in `evaluateEffect`.

long story short, no cigar, benchmark and profiler are unchanged

**Comment by kyri-petrou** [comment]
@eyalfa what about using `return null` instead of using errors for control flow?

**Comment by eyalfa** [comment]
I'm entertaining the though, I suspect it might reduce performance of flatMap/fold and alike

**Comment by eyalfa** [comment]
@kyri-petrou you were spot on 🎯 
the 'nulls approach' works!

```Benchmark                                             Mode  Cnt    Score   Error  Units
AsyncResumptionBenchmark.zioAsyncResumptionBenchmark  avgt   15  228.627 ± 3.139  ns/op
```

my suspicion, JVM's C2 optimizer treated the throwing branch as 'unlikely', effectively generating less efficient code for this case (a hunch, don't really have the means to prove it).
once the throw statement is replaced with a simple boolean variable assignment, the code ends up having two branches, each with its own probability of becoming 'hot' and the throwing branch is all gone...

I think this should optimize the 'real' async case as well since it also used the `AsyncJump` exception to break the loop, well no more 😎 

I still think the yield specific optimization of simply avoiding it if the scheduler can afford it, should still be considered.

I'll open a PR shortly.

**Comment by kyri-petrou** [comment]
> I still think the yield specific optimization of simply avoiding it if the scheduler can afford it, should still be considered.

Agreed!
