### ISSUE TITLE
Unexpected intermittent fiber interruptions from timeout operator

### ISSUE THREAD

**Issue by svroonland** [zio/zio#9288]
This is a minimized version of an issue encountered in a feature branch on zio-kafka. The reproducer below will, after several seconds but not always, intermittently start spewing interrupted exceptions. Removing the `timeout(..).someOrElseZIO(..)` will prevent this from happening, as well as adding a `.fork.flatMap(_.join)`. 

https://scastie.scala-lang.org/8wr2IaZ1QqiYNEfrDFtjqQ

**Comment by kyri-petrou** [comment]
This is interesting; I have a feeling this is likely due to a weird interaction due to calling `timeout` on a fiber that is already interrupted. This would explain why forking resolves the issue, as `timeout` will be called on the child fiber which is not interrupted.

I'll check whether there is something that can be done to prevent this issue

**Comment by kyri-petrou** [comment]
@svroonland after looking into it, my gut feeling was correct. The issue appears to be with `timeout` which works by forking child fibers; one to execute the effect and another that creates a timer. Both of these child fibers are attached to the parent fiber scope, which in this case has already been interrupted and therefore it attempts to interrupt the newly created child fibers. Using `forkDaemon.flatMap(_.join)` works because now the parent fiber is governed by the global scope (due to the `Daemon` part), and therefore we don't attempt to interrupt the child fibers created by `timeout`.

Unfortunately I don't really see an easy solution to fixing the current behavior of `timeout`, and frankly I'm not even entirely sure we should be. Using  `forkDaemon.flatMap(_.join)` is indeed the correct approach, and what's also what's used under the hood in the `disconnect` method.

PS: You could also use `disconnect` instead of `forkDaemon.flatMap(_.join)`

**Comment by svroonland** [comment]
Thanks for looking into it. I ~would~ could be happy with that explanation of the interruption model, were it not for the fact that this happens intermittently. That would mean there is some race condition somewhere.

**Comment by kyri-petrou** [comment]
It's really hard to tell, but the race condition is very likely due to whether the effect completes successfully before or after the interruption signal is propagated to the child fiber (since the interruption of child fibers is done asynchronously)

**Comment by svroonland** [comment]
Still, I would say that anything that runs in a finalizer should not be interrupted from the outside, no matter what kind of forking or scope trickery it does, would you agree? I don't know the fiber model well enough, but it feels like something is inherited that should not be.

**Comment by kyri-petrou** [comment]
@svroonland OK I managed to identify the source of the issue. It seems that when we try to create a new child fiber we're only checking if the parent fiber is interrupted, but not whether we're currently within an uninterruptible region (which what finalizers are).

The solution is pretty much a 1-2 liner change, which is to also check if we're currently in an uninterruptible region and allow the creation of the child fiber in cases that we are within one. However, I want to do some more testing before opening a PR to ensure that this won't create any regressions
