### ISSUE TITLE
Cats Effect interop needs updating in light of inherited interruption status

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#945]
In Cats Effect, interruption status is not inherited, and every "started" fiber starts off as interruptible. In the interop layer, we need to match Cats Effect semantics.

We should also look for other places where semantics have changed to warrant introduction of, e.g. `interruptibleMask`.

**Comment by kaishh** [comment]
My opinion so far, although I'm very open to reconsider, is to consider simply dropping interruptibility inheritance altogether, because:

1. I find the examples not compelling enough, i.e. the example equations already hold with or without presence of inner forks in passed actions - as long as the fiber handles don't leak. Many combinators ensure that fiber handles can't leak, and fibers have no access to and cannot leak their own fiber handles when spawned by such a combinator.
2. It interacts badly with `bracket` and naive uses of `Resource` and `ZManaged` – even if `Concurrent` instance is fixed, monomorphic mixes of cats and ZIO primitives would interact badly in this case.
3. Some combinators change meaning in unexpected ways, e.g. `foreachPar`. Although one could argue that `foreachPar.uninterruptible` now behaves closer to `foreach.uninterruptible` due to uninterruptibility of inner action, in fact it behaves very differently now in another case – uninterruptiblity of inner forks means that sibling workers will NOT be interrupted after one of them fails – error propagation stops working when `foreachPar` is wrapped in `uninterruptible`, this is a very stark difference from `foreach`, where every failure stops the chain, and this behavior does not follow intuitively from `uninterruptible` modifier unless you're highly knowledgeable of internals!

Linking previous gitter discussion here - https://gitter.im/ZIO/Core?at=5cf408bc949a104c36901c42 

/cc @ghostdogpr

**Comment by ghostdogpr** [comment]
To be honest, I have no strong opinion about it. The one that I think is really important is the supervision inheritance: i got bit by the way it works now and i had to comment some `.timeout` so that my code works properly. Didn’t get any case where I needed it on interruptibility.

**Comment by kaishh** [comment]
Re: supervision inheritance, if we remove interruption inheritance, we can't make transitive child fibers visible to root parent's supervision, because then a they'll be able to interrupt 'hidden' fiber handles, e.g. in `foreachPar(...).uninterruptible.fork.interruptChildren` – foreachPar workers will be interrupted by the outermost supervisor, even though that directly contradicts its uninterruptible status.

What we can do however, *I think*, although I'm not sure that'll work, is to inherit a stack of supervisor actions in child fibers, but do not let parent fibers see children of their child fibers – then the above will work correctly – outermost supervisor will try to interrupt `foreachPar`, but it will ignore that, being uninterruptible and its workers will continue – if it was interruptible though, it would interrupt all its children correctly in turn (even if they were spawned by just `fork`, not `foreachPar`).

**Comment by jdegoes** [comment]
As soon as I get a chance, I'll post my thoughts on this and the examples.... until then if someone wants to get out a quick PR to restore Cats Effect behavior by adding `interruptible` around the forks, that'd be awesome just so we can take more time to hammer out details.

**Comment by Fristi** [comment]
🎉

**Comment by kaishh** [comment]
Can we reopen since conversation about interruption inheritance hasn't been concluded yet?

**Comment by Fristi** [comment]
With RC8-4 my problem seems to be solved

**Comment by jdegoes** [comment]
Yes, let's leave this opened for now, will get back on it after my next workshop concludes.

**Comment by adamgfraser** [comment]
Going to close as I believe we have the interop working as well as it can given the differences between the effect systems at this point.
