### ISSUE TITLE
Final Cleanup after publishing to Sonatype using ZIO Org

### ISSUE THREAD

**Issue by softinio** [zio/zio#955]
Once we have published using the `zio` org to sonatype/maven we need to finish off the migration to new org by:

- Updating footer in documentation to point to javadocs.io documentation for zio org as opposed to scalaz (https://github.com/zio/zio/blob/master/website/core/Footer.js#L57)
- setup codecov for repo under zio (or migrate over if possible)
- Make sure zio on scaladex
- Update readme to make sure links to scaladex, codecov, sonatype and others point to the new zio artifacts and pages

**Comment by ghostdogpr** [comment]
We may have to fix Netlify as well, since I manually uploaded the website files for the current version. If the directory structure of the website uploaded by the build is different, we might have to add something like `cd zio` on Netlify side to point to the right subfolder.

Not sure but just wanted to give you heads up.

**Comment by iravid** [comment]
The artifact names have to be updated too - they're still `scalaz-<submodule>`
