### ISSUE TITLE
ZIO port for Rust wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [zio/zio#965]

**Comment by JD557** [comment]
I think that Rust is not "mature enough" to support ZIO/ZIO doesn't really fit into Rust :

- It has no `do` notation and no well defined way to express monads (https://varkor.github.io/blog/2019/03/28/idiomatic-monads-in-rust.html presents a solution, but it seems quite cumbersome)
- It has no variance and no bottom type (that discussion has been going for quite a while: https://github.com/rust-lang/rust/issues/35121), so AFAIK there's no nice way to encode stuff like `ZIO[Any, Nothing, A]`
- AFAIK, there's also no easy way to "make a cake", so the `provide`/`provideSome` operations would be quite awkward.

I'm also not sure if some of the ZIO implementation details, namely [ZManaged](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/ZManaged.scala), make sense in Rust, since you already have the borrow checker.

It might make more sense to write a different effect abstraction that fits rust's model better. After all, a lot of ZIO's defining features (effect rotation, use of variance, cakes...) exist because they fit scala better than the classic IO.

**Comment by kitlangton** [comment]
Great idea! However, I don't believe this is necessarily an issue with ZIO itself 😄

**Comment by blast-hardcheese** [comment]
> @JD557 @kitlangton I'm pretty sure that Rust is mature enough now. I can agree that this isn't the best place for this issue. Where should it go?

Probably just start the project and try to get people onboard, as well as chat with the ZIO folks about ergonomics and edge cases where Scala and Rust differ.

It looks like at least one person has started this work thus far, but it seems abandoned at this point: [jonathanrlouie/env-io](https://github.com/jonathanrlouie/env-io).

This is a great issue as far as SEO goes, even in its (correctly, imho) `Closed` state, it serves a purpose!

**Comment by blast-hardcheese** [comment]
> @MavenRain I'm pretty sure that Rust is mature enough now. I can agree that this isn't the best place for this issue. Where should it go?

Probably just start the project and try to get people onboard, as well as chat with the ZIO folks about ergonomics and edge cases where Scala and Rust differ.

It looks like at least one person has started this work thus far, but it seems abandoned at this point: [jonathanrlouie/env-io](https://github.com/jonathanrlouie/env-io).

This is a great issue as far as SEO goes, even in its (correctly, imho) `Closed` state, it serves a purpose!

**Comment by politrons** [comment]
This was my attempt to have something close to ZIO in Rust

https://github.com/politrons/FunctionalRust/tree/main/rust_io

**Comment by nightscape** [comment]
@politrons you say "was", did you run into any specific issues that made you abandon the approach, or would it just be a matter of going into breadth?

**Comment by bbarker** [comment]
> @politrons you say "was", did you run into any specific issues that made you abandon the approach, or would it just be a matter of going into breadth?

I'm also curious about @politrons experience and thoughts
